In [1]:
import pandas as pd
import numpy as np
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# DISPERSIONES FP

In [2]:
fp_files_1 = glob.glob(r'G:\My Drive\3.-Settlement\1.-Resultado-dispersión\2021\11.-NOVIEMBRE\Dispersión-FP*.xlsx', recursive=False)
fp_files_1

['G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-10-30.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-10-31.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-06.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-07.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-05.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-08.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-01.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-02.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-03.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-04.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-09.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-10.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-11.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-12.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-13.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-14.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-15.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-16.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-17.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-18.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-19.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-20.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-21.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-22.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-23.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-24.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-25.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-26.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-27.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-28.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-29.xlsx',
 'G:\\My Drive\\3.-Settlement\\1.-Resultado-dispersión\\2021\\11.-NOVIEMBRE\\Dispersión-FP 2021-11-30.xlsx']

In [3]:
pagos_2 = pd.concat([pd.read_excel(f,sheet_name='FAST PAYMENTS').assign(file_name=os.path.basename(f)) for f in fp_files_1])
pagos_2['date_file'] = pagos_2["file_name"].str[-15:-4]
pagos_2['date_file']= pd.to_datetime(pagos_2['date_file']) 
pagos_2.sort_values(by=['date_file'],ascending=True,inplace=True)
pagos_2['report_date_local']= pd.to_datetime(pagos_2['report_date_local']) 
pagos_2.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor,file_name,date_file
0,00103b74-5b22-41cb-ab2d-194b3abb79c2,TechInk Food and Services,tonyhernandez13@gmail.com,PCMPHFTMC,2021-10-30,"3,688.29",Pago del día,ASP INTEGRA OPC,Josr Antonio Bravo Hernández,659802020000013503,PAID,"2021-10-30,42644264202110301473283346,40072,90...",09:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30
5105,046a49d6-d861-406f-9948-07ef6b2ac19f,Abarrotes La Ilusión,omar280017@icloud.com,T78CWCPK8,2021-10-30,234.77,Pago del día,ASP INTEGRA OPC,Pablo Omar Rodriguez Rodriguez,659802020000139131,PAID,"2021-10-30,42644264202110301473941711,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30
5104,04045ae1-6f1d-4140-8fb3-19665a4b9003,LA POTOSINA RESTAURANT,la.potosina@hotmail.com,NDJ9JW8KN,2021-10-30,"2,386.98",Pago del día,ASP INTEGRA OPC,Juan Sandoval Perez,659802020000535421,PAID,"2021-10-30,42644264202110301473942158,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30
5103,038f9d7a-4637-4488-9968-bbff6c5b167d,La Pedisima Providencia,emilianonugu@icloud.com,C7JFQXQPP,2021-10-30,70.43,Pago del día,ASP INTEGRA OPC,Emiliano Nunez Guzman,659802020000109611,PAID,"2021-10-30,42644264202110301473942710,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30
5102,0388371d-5da6-4891-bdb1-68b4c6ddb949,ZONATURA,leocon.17_atlas@hotmail.com,ZL8PLJNCJ,2021-10-30,260.64,Pago del día,ASP INTEGRA OPC,Leonardo De Jesus Negrete Contreras,659802020000468352,PAID,"2021-10-30,42644264202110301473943039,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30

In [4]:
pagos_2.shape

(190694, 16)

In [5]:
pagos_2['status'].unique()

array(['PAID', 'ERROR', 'PENDING', 'NEW'], dtype=object)

In [6]:
pagos_2_paid = pagos_2[(pagos_2['status'].isin(['PAID']))]
pagos_2_paid.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor,file_name,date_file
0,00103b74-5b22-41cb-ab2d-194b3abb79c2,TechInk Food and Services,tonyhernandez13@gmail.com,PCMPHFTMC,2021-10-30,"3,688.29",Pago del día,ASP INTEGRA OPC,Josr Antonio Bravo Hernández,659802020000013503,PAID,"2021-10-30,42644264202110301473283346,40072,90...",09:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30
5105,046a49d6-d861-406f-9948-07ef6b2ac19f,Abarrotes La Ilusión,omar280017@icloud.com,T78CWCPK8,2021-10-30,234.77,Pago del día,ASP INTEGRA OPC,Pablo Omar Rodriguez Rodriguez,659802020000139131,PAID,"2021-10-30,42644264202110301473941711,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30
5104,04045ae1-6f1d-4140-8fb3-19665a4b9003,LA POTOSINA RESTAURANT,la.potosina@hotmail.com,NDJ9JW8KN,2021-10-30,"2,386.98",Pago del día,ASP INTEGRA OPC,Juan Sandoval Perez,659802020000535421,PAID,"2021-10-30,42644264202110301473942158,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30
5103,038f9d7a-4637-4488-9968-bbff6c5b167d,La Pedisima Providencia,emilianonugu@icloud.com,C7JFQXQPP,2021-10-30,70.43,Pago del día,ASP INTEGRA OPC,Emiliano Nunez Guzman,659802020000109611,PAID,"2021-10-30,42644264202110301473942710,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30
5102,0388371d-5da6-4891-bdb1-68b4c6ddb949,ZONATURA,leocon.17_atlas@hotmail.com,ZL8PLJNCJ,2021-10-30,260.64,Pago del día,ASP INTEGRA OPC,Leonardo De Jesus Negrete Contreras,659802020000468352,PAID,"2021-10-30,42644264202110301473943039,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30

In [7]:
pagos_2_paid.shape

(188847, 16)

# READING FILES CSV

In [8]:
all_mov_csv = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\EDO CTA BANAMEX\202*\**\TX-NV-P*.csv', recursive=False)

# READING FILES XLSX

In [9]:
all_mov_xlsx = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\EDO CTA BANAMEX\202*\**\TX-NV-P*.xlsx', recursive=False)

# DATA EDO CTA

### CSV

In [10]:
edo_cta_1 = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in all_mov_csv])
edo_cta_1.reset_index(inplace=True)
edo_cta_1.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_13264\2646423125.py:1: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  edo_cta_1 = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in all_mov_csv])

,index,BTID,Account ID,Account Name,Bank Account Number,IBAN,CCY,Account Type,Bank Group,Bank Country,...,Creditor Name,Issuer,file_name,Account User Defined Field,Bank Groups User Defined Field,Bank User Defined Field,BU User Defined Field,Company User Defined Field,Project User Defined Field,Labels
0,0,"13,043,678.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,70047593261,2180700475932617,MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"13,043,679.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,70047593261,2180700475932617,MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"13,043,680.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,70047593261,2180700475932617,MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"13,043,681.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,70047593261,2180700475932617,MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"13,043,682.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,70047593261,2180700475932617,MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
edo_cta_1.shape

(803992, 65)

### XLSX

In [12]:
edo_cta_2 = pd.concat([pd.read_excel(f).assign(file_name=os.path.basename(f)) for f in all_mov_xlsx])
edo_cta_2.reset_index(inplace=True)
edo_cta_2.head()

,index,Instrument Type,Operation Date,Budget Code,Local Code,Bank Reference,Description,Description 1,Credit,Debit,Opening Balance Amount,Closing Balance Amount,file_name
0,0,Merchants,2022-01-27,Merchant Outflow,699,17E9CB49F00BD0BE,4Q4XK32S2FR:INTERBANKENDT:20220127TRID:4Q4XK32...,NaN,0.00,-149.97,"7,674,034.69","7,893,583.67",TX-NV-Payclip_3261_27_Enero_2022.xlsx
1,1,Merchants,2022-01-27,Merchant Outflow,699,17E9CB49E7F10234,YYC39S9RDFR:INTERBANKENDT:20220127TRID:YYC39S9...,NaN,0.00,-90.08,"7,674,034.69","7,893,583.67",TX-NV-Payclip_3261_27_Enero_2022.xlsx
2,2,Merchants,2022-01-27,Merchant Outflow,699,17E9CB49F14CEEA2,2DTHSGCRYFR:INTERBANKENDT:20220127TRID:2DTHSGC...,NaN,0.00,-543.62,"7,674,034.69","7,893,583.67",TX-NV-Payclip_3261_27_Enero_2022.xlsx
3,3,Merchants,2022-01-27,Merchant Outflow,699,17E9CB4A1B391214,Y52PR4S3HFR:INTERBANKENDT:20220127TRID:Y52PR4S...,NaN,0.00,-229.02,"7,674,034.69","7,893,583.67",TX-NV-Payclip_3261_27_Enero_2022.xlsx
4,4,Merchants,2022-01-27,Merchant Outflow,699,17E9CB4A1A842897,23KH82LRWFR:INTERBANKENDT:20220127TRID:23KH82L...,NaN,0.00,"-2,164.18","7,674,034.69","7,893,583.67",TX-NV-Payclip_3261_27_Enero_2022.xlsx

In [13]:
edo_cta_2.shape

(252092, 13)

### CONSOLIDADO

In [14]:
edo_cta = pd.concat([edo_cta_1,edo_cta_2])
edo_cta.head()

,index,BTID,Account ID,Account Name,Bank Account Number,IBAN,CCY,Account Type,Bank Group,Bank Country,...,Creditor Name,Issuer,file_name,Account User Defined Field,Bank Groups User Defined Field,Bank User Defined Field,BU User Defined Field,Company User Defined Field,Project User Defined Field,Labels
0,0,"13,043,678.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,"70,047,593,261.00","2,180,700,475,932,617.00",MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"13,043,679.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,"70,047,593,261.00","2,180,700,475,932,617.00",MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"13,043,680.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,"70,047,593,261.00","2,180,700,475,932,617.00",MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"13,043,681.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,"70,047,593,261.00","2,180,700,475,932,617.00",MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"13,043,682.00",PAYCLIPMX_CITI_MXN_2617,PAYCLIPMX_CITI_MXN_2617,"70,047,593,261.00","2,180,700,475,932,617.00",MXN,Settlement Account,Citibank,MEXICO,...,NaN,NaN,TX-NV-Payclip_3261_Julio_2021.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
edo_cta.shape

(1056084, 65)

In [16]:
edo_cta_all = edo_cta [['Bank Account Number','Operation Date','Value Date','Bank Reference','Description','Debit/Credit Mark',
                       'Credit','Debit','Amount','CCY','Budget Code','Customer Reference','file_name']]
edo_cta_all['Bank Reference'].fillna('blank_spaces',inplace=True)
edo_cta_all.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_13264\2788285558.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edo_cta_all['Bank Reference'].fillna('blank_spaces',inplace=True)

,Bank Account Number,Operation Date,Value Date,Bank Reference,Description,Debit/Credit Mark,Credit,Debit,Amount,CCY,Budget Code,Customer Reference,file_name
0,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A650FB855D8D01,NNB48ZG3RFR:INTERBANKENDT:20210701TRID:NNB48ZG...,D,0.00,-316.22,-316.22,MXN,Merchant Outflow,NNB48ZG3R,TX-NV-Payclip_3261_Julio_2021.csv
1,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A650FDDA628DEE,5Z33TH5QFR:INTERBANKENDT:20210701TRID:5Z33TH5Q...,D,0.00,-306.64,-306.64,MXN,Merchant Outflow,5Z33TH5Q,TX-NV-Payclip_3261_Julio_2021.csv
2,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A650FB85FF4DED,5TNR24SNDFR:INTERBANKENDT:20210701TRID:5TNR24S...,D,0.00,-143.74,-143.74,MXN,Merchant Outflow,5TNR24SND,TX-NV-Payclip_3261_Julio_2021.csv
3,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A650FBEC6A09FD,W2M7J4F6HFR:INTERBANKENDT:20210701TRID:W2M7J4F...,D,0.00,-50.78,-50.78,MXN,Merchant Outflow,W2M7J4F6H,TX-NV-Payclip_3261_Julio_2021.csv
4,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A650FDBEBC25BF,87HDWR4DCFR:INTERBANKENDT:20210701TRID:87HDWR4...,D,0.00,-916.07,-916.07,MXN,Merchant Outflow,87HDWR4DC,TX-NV-Payclip_3261_Julio_2021.csv

In [17]:
edo_cta_all['Budget Code'].unique()

array(['Merchant Outflow', 'Merchant payments rejection',
       'Payclip Funding', 'Bank fees per ME transaction',
       'VAT charged per ME transactions', 'Other revenue', 'Bank fees',
       'VAT Bank fees', 'Intercompany ME Funding', 'Investment intrests',
       'Income TAX', 'Merchant Inflow', 'Profesional Services', 'WhoT',
       'FX Deals', 'Payroll Payments', nan, 'Merchant chargeback',
       'Readers', 'Processor Inflows'], dtype=object)

In [18]:
edo_cta_all_dev = edo_cta_all[(edo_cta_all['Budget Code'].isin(['Merchant payments rejection']))]
edo_cta_all_dev.head()

,Bank Account Number,Operation Date,Value Date,Bank Reference,Description,Debit/Credit Mark,Credit,Debit,Amount,CCY,Budget Code,Customer Reference,file_name
105,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A63FCF2E4F8043,397700718211FR:OPERATION REVERSALENDT:20210701...,C,"28,977.18",0.00,"28,977.18",MXN,Merchant payments rejection,397700718211,TX-NV-Payclip_3261_Julio_2021.csv
883,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A62B345272520E,390780718211FR:OPERATION REVERSALENDT:20210701...,C,"21,081.28",0.00,"21,081.28",MXN,Merchant payments rejection,390780718211,TX-NV-Payclip_3261_Julio_2021.csv
1713,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A650FCE0085DC4,16060718215FR:OPERATION REVERSALENDT:20210701T...,C,"3,567.34",0.00,"3,567.34",MXN,Merchant payments rejection,16060718215,TX-NV-Payclip_3261_Julio_2021.csv
1714,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A650FC8A59EDF7,15150718218FR:OPERATION REVERSALENDT:20210701T...,C,"2,222.82",0.00,"2,222.82",MXN,Merchant payments rejection,15150718218,TX-NV-Payclip_3261_Julio_2021.csv
1715,"70,047,593,261.00",09-Jul-2021,01-Jul-2021,17A5FE9338EC0BD3,888630718115FR:OPERATION REVERSALENDT:20210701...,C,291.31,0.00,291.31,MXN,Merchant payments rejection,888630718115,TX-NV-Payclip_3261_Julio_2021.csv

In [19]:
edo_cta_all_dev.shape

(22841, 13)

# CRUCE DISPERSIONES VS MOVIMIENTOS BANCARIOS

In [20]:
split = pagos_2_paid["CEP"].str.split(",",n=8,expand=True)
split.head()

,0,1,2,3,4,5
0,2021-10-30,42644264202110301473283346,40072,90659,659802020000013503,3688.29
5105,2021-10-30,42644264202110301473941711,40072,90659,659802020000139131,234.77
5104,2021-10-30,42644264202110301473942158,40072,90659,659802020000535421,2386.98
5103,2021-10-30,42644264202110301473942710,40072,90659,659802020000109611,70.43
5102,2021-10-30,42644264202110301473943039,40072,90659,659802020000468352,260.64

In [21]:
pagos_2_paid["Bank Reference"] = split[1]
pagos_2_paid.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_13264\1453815343.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pagos_2_paid["Bank Reference"] = split[1]

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor,file_name,date_file,Bank Reference
0,00103b74-5b22-41cb-ab2d-194b3abb79c2,TechInk Food and Services,tonyhernandez13@gmail.com,PCMPHFTMC,2021-10-30,"3,688.29",Pago del día,ASP INTEGRA OPC,Josr Antonio Bravo Hernández,659802020000013503,PAID,"2021-10-30,42644264202110301473283346,40072,90...",09:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473283346
5105,046a49d6-d861-406f-9948-07ef6b2ac19f,Abarrotes La Ilusión,omar280017@icloud.com,T78CWCPK8,2021-10-30,234.77,Pago del día,ASP INTEGRA OPC,Pablo Omar Rodriguez Rodriguez,659802020000139131,PAID,"2021-10-30,42644264202110301473941711,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473941711
5104,04045ae1-6f1d-4140-8fb3-19665a4b9003,LA POTOSINA RESTAURANT,la.potosina@hotmail.com,NDJ9JW8KN,2021-10-30,"2,386.98",Pago del día,ASP INTEGRA OPC,Juan Sandoval Perez,659802020000535421,PAID,"2021-10-30,42644264202110301473942158,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473942158
5103,038f9d7a-4637-4488-9968-bbff6c5b167d,La Pedisima Providencia,emilianonugu@icloud.com,C7JFQXQPP,2021-10-30,70.43,Pago del día,ASP INTEGRA OPC,Emiliano Nunez Guzman,659802020000109611,PAID,"2021-10-30,42644264202110301473942710,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473942710
5102,0388371d-5da6-4891-bdb1-68b4c6ddb949,ZONATURA,leocon.17_atlas@hotmail.com,ZL8PLJNCJ,2021-10-30,260.64,Pago del día,ASP INTEGRA OPC,Leonardo De Jesus Negrete Contreras,659802020000468352,PAID,"2021-10-30,42644264202110301473943039,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473943039

In [22]:
pagos_2_paid.shape

(188847, 17)

In [23]:
cruce_1 = pagos_2_paid.merge(edo_cta_all_dev[['Bank Reference','Operation Date','Value Date','Description','Credit']],
                             on='Bank Reference',how='left')
cruce_1['Description'].fillna('sin_devolucion',inplace=True)
cruce_1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,...,CEP,Time,Banco_emisor,file_name,date_file,Bank Reference,Operation Date,Value Date,Description,Credit
0,00103b74-5b22-41cb-ab2d-194b3abb79c2,TechInk Food and Services,tonyhernandez13@gmail.com,PCMPHFTMC,2021-10-30,"3,688.29",Pago del día,ASP INTEGRA OPC,Josr Antonio Bravo Hernández,659802020000013503,...,"2021-10-30,42644264202110301473283346,40072,90...",09:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473283346,NaN,NaN,sin_devolucion,NaN
1,046a49d6-d861-406f-9948-07ef6b2ac19f,Abarrotes La Ilusión,omar280017@icloud.com,T78CWCPK8,2021-10-30,234.77,Pago del día,ASP INTEGRA OPC,Pablo Omar Rodriguez Rodriguez,659802020000139131,...,"2021-10-30,42644264202110301473941711,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473941711,NaN,NaN,sin_devolucion,NaN
2,04045ae1-6f1d-4140-8fb3-19665a4b9003,LA POTOSINA RESTAURANT,la.potosina@hotmail.com,NDJ9JW8KN,2021-10-30,"2,386.98",Pago del día,ASP INTEGRA OPC,Juan Sandoval Perez,659802020000535421,...,"2021-10-30,42644264202110301473942158,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473942158,NaN,NaN,sin_devolucion,NaN
3,038f9d7a-4637-4488-9968-bbff6c5b167d,La Pedisima Providencia,emilianonugu@icloud.com,C7JFQXQPP,2021-10-30,70.43,Pago del día,ASP INTEGRA OPC,Emiliano Nunez Guzman,659802020000109611,...,"2021-10-30,42644264202110301473942710,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473942710,NaN,NaN,sin_devolucion,NaN
4,0388371d-5da6-4891-bdb1-68b4c6ddb949,ZONATURA,leocon.17_atlas@hotmail.com,ZL8PLJNCJ,2021-10-30,260.64,Pago del día,ASP INTEGRA OPC,Leonardo De Jesus Negrete Contreras,659802020000468352,...,"2021-10-30,42644264202110301473943039,40072,90...",18:00,BANORTE,Dispersión-FP 2021-10-30.xlsx,2021-10-30,42644264202110301473943039,NaN,NaN,sin_devolucion,NaN

In [24]:
cruce_1.shape

(188907, 21)

In [25]:
cruce_1_final = cruce_1[(cruce_1['Description'] != 'sin_devolucion')]
cruce_1_final.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,...,CEP,Time,Banco_emisor,file_name,date_file,Bank Reference,Operation Date,Value Date,Description,Credit
22327,1a191788-a724-4794-9924-d065f5f0da3f,Maquech JR,restaurantemaquechpurpura@gmail.com,YP6G5P9N3,2021-10-31,"1,796.58",Reprogramación,ASP INTEGRA OPC,Daniel Arod Coronado Delgado,659802020000350761,...,"2021-11-02,17CE3B59DF7C31BA,40002,90659,659802...",20:00,BANAMEX,Dispersión-FP 2021-11-02.xlsx,2021-11-02,17CE3B59DF7C31BA,03-Nov-2021,03-Nov-2021,881920730616FR:OPERATION REVERSALENDT:20211103...,"1,796.58"
27245,cdedba35-308d-4047-ba59-3181161a3603,Abarrotes la bodequita,Antonio.plat@hotmail.com,NQD9DV8KS,2021-11-03,36.41,Pago del día,ASP INTEGRA OPC,Daniel Torres Gonzalez,659802020000514099,...,"2021-11-03,17CE8DC3187C1BC9,40002,90659,659802...",20:00,BANAMEX,Dispersión-FP 2021-11-03.xlsx,2021-11-03,17CE8DC3187C1BC9,03-Nov-2021,03-Nov-2021,938940730713FR:OPERATION REVERSALENDT:20211103...,36.41
31300,cdedba35-308d-4047-ba59-3181161a3603,Abarrotes la bodequita,Antonio.plat@hotmail.com,37FWXYHS3,2021-11-04,300.90,Pago del día,ASP INTEGRA OPC,Daniel Torres Gonzalez,659802020000514099,...,"2021-11-04,17CEC943D6E3AEB2,40002,90659,659802...",14:00,BANAMEX,Dispersión-FP 2021-11-04.xlsx,2021-11-04,17CEC943D6E3AEB2,04-Nov-2021,04-Nov-2021,740730816FR:OPERATION REVERSALENDT:20211104TRI...,300.90
31834,f87b14ea-8769-4c47-b26c-91d572f0dbaa,Kenya Fernanda Ramírez Herrera,chininegrita0@gmail.com,6XS5M8SGF,2021-11-04,"15,331.84",Pago del día,ASP INTEGRA OPC,Kenya Fernanda Ramírez Herrera,659802020000149600,...,"2021-11-04,17CEE02BE02AA06F,40002,90659,659802...",16:00,BANAMEX,Dispersión-FP 2021-11-04.xlsx,2021-11-04,17CEE02BE02AA06F,04-Nov-2021,04-Nov-2021,883910730810FR:OPERATION REVERSALENDT:20211104...,"15,331.84"
34396,cdedba35-308d-4047-ba59-3181161a3603,Abarrotes la bodequita,Antonio.plat@hotmail.com,M8LQ4LY39,2021-11-04,418.75,Pago del día,ASP INTEGRA OPC,Daniel Torres Gonzalez,659802020000514099,...,"2021-11-04,17CEE02B8D7B6EB5,40002,90659,659802...",20:00,BANAMEX,Dispersión-FP 2021-11-04.xlsx,2021-11-04,17CEE02B8D7B6EB5,04-Nov-2021,04-Nov-2021,883080730815FR:OPERATION REVERSALENDT:20211104...,418.75

In [26]:
cruce_1_final.shape

(437, 21)

In [27]:
cruce_1_final['file_name'].unique()

array(['Dispersión-FP 2021-11-02.xlsx', 'Dispersión-FP 2021-11-03.xlsx',
       'Dispersión-FP 2021-11-04.xlsx', 'Dispersión-FP 2021-11-05.xlsx',
       'Dispersión-FP 2021-11-08.xlsx', 'Dispersión-FP 2021-11-09.xlsx',
       'Dispersión-FP 2021-11-10.xlsx', 'Dispersión-FP 2021-11-11.xlsx',
       'Dispersión-FP 2021-11-12.xlsx', 'Dispersión-FP 2021-11-15.xlsx',
       'Dispersión-FP 2021-11-16.xlsx', 'Dispersión-FP 2021-11-17.xlsx',
       'Dispersión-FP 2021-11-18.xlsx', 'Dispersión-FP 2021-11-19.xlsx',
       'Dispersión-FP 2021-11-22.xlsx', 'Dispersión-FP 2021-11-23.xlsx',
       'Dispersión-FP 2021-11-24.xlsx', 'Dispersión-FP 2021-11-25.xlsx',
       'Dispersión-FP 2021-11-26.xlsx', 'Dispersión-FP 2021-11-29.xlsx',
       'Dispersión-FP 2021-11-30.xlsx'], dtype=object)

In [28]:
grouped = cruce_1_final.groupby(cruce_1_final.file_name)

In [29]:
group_1 = grouped.get_group('Dispersión-FP 2021-11-02.xlsx')
group_2 = grouped.get_group('Dispersión-FP 2021-11-03.xlsx')
group_3 = grouped.get_group('Dispersión-FP 2021-11-04.xlsx')
group_4 = grouped.get_group('Dispersión-FP 2021-11-05.xlsx')
group_5 = grouped.get_group('Dispersión-FP 2021-11-08.xlsx')
group_6 = grouped.get_group('Dispersión-FP 2021-11-09.xlsx')
group_7 = grouped.get_group('Dispersión-FP 2021-11-10.xlsx')
group_8 = grouped.get_group('Dispersión-FP 2021-11-11.xlsx')
group_9 = grouped.get_group('Dispersión-FP 2021-11-12.xlsx')
group_10 = grouped.get_group('Dispersión-FP 2021-11-15.xlsx')
group_11 = grouped.get_group('Dispersión-FP 2021-11-16.xlsx')
group_12 = grouped.get_group('Dispersión-FP 2021-11-17.xlsx')
group_13 = grouped.get_group('Dispersión-FP 2021-11-18.xlsx')
group_14 = grouped.get_group('Dispersión-FP 2021-11-19.xlsx')
group_15 = grouped.get_group('Dispersión-FP 2021-11-22.xlsx')
group_16 = grouped.get_group('Dispersión-FP 2021-11-23.xlsx')
group_17 = grouped.get_group('Dispersión-FP 2021-11-24.xlsx')
group_18 = grouped.get_group('Dispersión-FP 2021-11-25.xlsx')
group_19 = grouped.get_group('Dispersión-FP 2021-11-26.xlsx')
group_20 = grouped.get_group('Dispersión-FP 2021-11-29.xlsx')
group_21 = grouped.get_group('Dispersión-FP 2021-11-30.xlsx')
# group_22 = grouped.get_group('Dispersión-FP 2022-03-29.xlsx')
# group_23 = grouped.get_group('Dispersión-FP 2022-03-30.xlsx')
# group_24 = grouped.get_group('Dispersión-FP 2022-03-31.xlsx')

In [30]:
writer = pd.ExcelWriter('DEV EXT CITI NOVIEMBRE 2021.xlsx',
                        engine='xlsxwriter',
                        engine_kwargs={'options': {'encoding':'utf-8'}})
group_1.to_excel(writer, sheet_name='2021.11.02', index=False)
group_2.to_excel(writer, sheet_name='2021.11.03', index=False)
group_3.to_excel(writer, sheet_name='2021.11.04', index=False)
group_4.to_excel(writer, sheet_name='2021.11.05', index=False)
group_5.to_excel(writer, sheet_name='2021.11.08', index=False)
group_6.to_excel(writer, sheet_name='2021.11.09', index=False)
group_7.to_excel(writer, sheet_name='2021.11.10', index=False)
group_8.to_excel(writer, sheet_name='2021.11.11', index=False)
group_9.to_excel(writer, sheet_name='2021.11.12', index=False)
group_10.to_excel(writer, sheet_name='2021.11.15', index=False)
group_11.to_excel(writer, sheet_name='2021.11.16', index=False)
group_12.to_excel(writer, sheet_name='2021.11.17', index=False)
group_13.to_excel(writer, sheet_name='2021.11.18', index=False)
group_14.to_excel(writer, sheet_name='2021.11.19', index=False)
group_15.to_excel(writer, sheet_name='2021.11.22', index=False)
group_16.to_excel(writer, sheet_name='2021.11.23', index=False)
group_17.to_excel(writer, sheet_name='2021.11.24', index=False)
group_18.to_excel(writer, sheet_name='2021.11.25', index=False)
group_19.to_excel(writer, sheet_name='2021.11.26', index=False)
group_20.to_excel(writer, sheet_name='2021.11.29', index=False)
group_21.to_excel(writer, sheet_name='2021.11.30', index=False)
# group_22.to_excel(writer, sheet_name='2022.03.29', index=False)
# group_23.to_excel(writer, sheet_name='2022.03.30', index=False)
# group_24.to_excel(writer, sheet_name='2022.03.31', index=False)
writer.close()