In [1]:
import numpy as np
import pandas as pd
import zipfile
from zipfile import ZipFile
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# SFTP

## HEADERS

In [2]:
name_file=['column_type','affiliation_sftp','merchant_reference','card','settled_amount','commisions','transaction_date',
           'gross_amount','currency','transaction_type','tax','installments_tax','iva_cashback_paid','iva_cashback_charged',
          'cashback_fees_paid','cashback_fees_charged','installments_fees','cashback_amount','number_of_payments',
           'initial_deferment','plan_type','auth_code','unknown.1','eci','interbank_reference','empty.1','unknown.2','empty.2',
          'payworks_reference','card_type','transaction_source','prosa_reference','acquirer_commision','acquirer_tax',
          'unknown.3','unknown.4','unknown.5']
dtypes_file={'interbank_reference':object,'affiliation_sftp':object,'card':object,'number_of_payments':object,
             'initial_deferment':object,'plan_type':object,'auth_code':object,'payworks_reference':object,'eci':object}

In [3]:
use_cols = ['affiliation_sftp','transaction_type','transaction_date','eci','auth_code','interbank_reference',
            'payworks_reference','card','gross_amount','commisions','tax','installments_fees','installments_tax',
            'acquirer_commision','acquirer_tax','card_type','number_of_payments','initial_deferment']

### NOVIEMBRE

In [ ]:
sftp_nov_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\11. NOVIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_nov_1_22

In [ ]:
sftp_nov_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_nov_1_22])
sftp_nov_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_nov_22['date_file'] = sftp_nov_22["file_name"].str[-15:-7]
sftp_nov_22['date_file']= pd.to_datetime(sftp_nov_22['date_file'], format='%d%m%Y').dt.date
sftp_nov_22['date_file']= pd.to_datetime(sftp_nov_22['date_file'])
sftp_nov_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_nov_22['month'] = sftp_nov_22['date_file'].dt.strftime('%B')
sftp_nov_22.head()

In [ ]:
sftp_nov_22.shape

### OCTUBRE

In [ ]:
sftp_oct_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\10. OCTUBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_oct_1_22

In [ ]:
sftp_oct_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_oct_1_22])
sftp_oct_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_oct_22['date_file'] = sftp_oct_22["file_name"].str[-15:-7]
sftp_oct_22['date_file']= pd.to_datetime(sftp_oct_22['date_file'], format='%d%m%Y').dt.date
sftp_oct_22['date_file']= pd.to_datetime(sftp_oct_22['date_file'])
sftp_oct_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_oct_22['month'] = sftp_oct_22['date_file'].dt.strftime('%B')
sftp_oct_22.head()

In [ ]:
sftp_oct_22.shape

### SEPTIEMBRE

In [ ]:
sftp_sep_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\09. SEPTIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_sep_1_22

In [ ]:
sftp_sep_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_sep_1_22])
sftp_sep_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_sep_22['date_file'] = sftp_sep_22["file_name"].str[-15:-7]
sftp_sep_22['date_file']= pd.to_datetime(sftp_sep_22['date_file'], format='%d%m%Y').dt.date
sftp_sep_22['date_file']= pd.to_datetime(sftp_sep_22['date_file'])
sftp_sep_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_sep_22['month'] = sftp_sep_22['date_file'].dt.strftime('%B')
sftp_sep_22.head()

In [ ]:
sftp_sep_22.shape

### AGOSTO

In [ ]:
sftp_aug_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\08. AGOSTO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_aug_1_22

In [ ]:
sftp_aug_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_aug_1_22])
sftp_aug_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_aug_22['date_file'] = sftp_aug_22["file_name"].str[-15:-7]
sftp_aug_22['date_file']= pd.to_datetime(sftp_aug_22['date_file'], format='%d%m%Y').dt.date
sftp_aug_22['date_file']= pd.to_datetime(sftp_aug_22['date_file'])
sftp_aug_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_aug_22['month'] = sftp_aug_22['date_file'].dt.strftime('%B')
sftp_aug_22.head()

In [ ]:
sftp_aug_22.shape

### JULIO

In [ ]:
sftp_jul_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\07. JULIO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_jul_1_22

In [ ]:
sftp_jul_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jul_1_22])
sftp_jul_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jul_22['date_file'] = sftp_jul_22["file_name"].str[-15:-7]
sftp_jul_22['date_file']= pd.to_datetime(sftp_jul_22['date_file'], format='%d%m%Y').dt.date
sftp_jul_22['date_file']= pd.to_datetime(sftp_jul_22['date_file'])
sftp_jul_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jul_22['month'] = sftp_jul_22['date_file'].dt.strftime('%B')
sftp_jul_22.head()

In [ ]:
sftp_jul_22.shape

### JUNIO

In [4]:
sftp_jun_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\06. JUNIO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_jun_1_22

['G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\01062022\\PAYCLIP_Settlement_01062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\02062022\\PAYCLIP_Settlement_02062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\03062022\\PAYCLIP_Settlement_03062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\04062022\\PAYCLIP_Settlement_04062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\07062022\\PAYCLIP_Settlement_07062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\08062022\\PAYCLIP_Settlement_08062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\09062022\\PAYCLIP_Settlement_09062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\09062022\\PAYCLIP_Settlement_10062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\10062022\\PAYCLIP_Settlement_10062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\11062022\\PAYCLIP_Settlement_11062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\14062022\\PAYCLIP_Settlement_14062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\15062022\\PAYCLIP_Settlement_15062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\16062022\\PAYCLIP_Settlement_16062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\17062022\\PAYCLIP_Settlement_17062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\18062022\\PAYCLIP_Settlement_18062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\21062022\\PAYCLIP_Settlement_21062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\22062022\\PAYCLIP_Settlement_22062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\23062022\\PAYCLIP_Settlement_23062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\24062022\\PAYCLIP_Settlement_24062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\25062022\\PAYCLIP_Settlement_25062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\28062022\\PAYCLIP_Settlement_28062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\29062022\\PAYCLIP_Settlement_29062022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\06. JUNIO\\30062022\\PAYCLIP_Settlement_30062022_V1.csv']

In [5]:
sftp_jun_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jun_1_22])
sftp_jun_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jun_22['date_file'] = sftp_jun_22["file_name"].str[-15:-7]
sftp_jun_22['date_file']= pd.to_datetime(sftp_jun_22['date_file'], format='%d%m%Y').dt.date
sftp_jun_22['date_file']= pd.to_datetime(sftp_jun_22['date_file'])
sftp_jun_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jun_22['month'] = sftp_jun_22['date_file'].dt.strftime('%B')
sftp_jun_22.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-256832543,298313,3105221,20220531,BANORTE,20220531,"3,105,221.00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_01062022_V1.csv,2022-06-01,June
198880,07927517,5349261366,-26,20220530,2000,SETTLED,-4,0.00,0.00,00,...,906430,75445502150502279275179,480704729775,NaN,D,-26.00,-4.00,PAYCLIP_Settlement_01062022_V1.csv,2022-06-01,June
198879,07927517,5579209180,-663,20220530,51000,SETTLED,-106,0.00,0.00,00,...,854975,75445502150657479275179,544836188526,NaN,D,-663.00,-106.00,PAYCLIP_Settlement_01062022_V1.csv,2022-06-01,June
198878,07927517,4152313846,-183,20220530,14100,SETTLED,-29,0.00,0.00,00,...,971504,74518992150983479275177,051809270236,NaN,D,-183.00,-29.00,PAYCLIP_Settlement_01062022_V1.csv,2022-06-01,June
198877,07927517,4772913056,-74,20220530,4000,SETTLED,-12,0.00,0.00,00,...,971164,74518992150207579275170,549812079287,NaN,C,-74.00,-12.00,PAYCLIP_Settlement_01062022_V1.csv,2022-06-01,June

In [6]:
sftp_jun_22.shape

(10266365, 21)

### MAYO

In [7]:
sftp_may_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\05. MAYO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_may_1_22

['G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\03052022\\PAYCLIP_Settlement_03052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\04052022\\PAYCLIP_Settlement_04052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\05052022\\PAYCLIP_Settlement_05052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\06052022\\PAYCLIP_Settlement_06052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\07052022\\PAYCLIP_Settlement_07052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\10052022\\PAYCLIP_Settlement_10052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\11052022\\PAYCLIP_Settlement_11052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\12052022\\PAYCLIP_Settlement_12052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\13052022\\PAYCLIP_Settlement_13052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\14052022\\PAYCLIP_Settlement_14052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\17052022\\PAYCLIP_Settlement_17052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\18052022\\PAYCLIP_Settlement_18052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\19052022\\PAYCLIP_Settlement_19052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\20052022\\PAYCLIP_Settlement_20052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\21052022\\PAYCLIP_Settlement_21052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\24052022\\PAYCLIP_Settlement_24052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\25052022\\PAYCLIP_Settlement_25052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\26052022\\PAYCLIP_Settlement_26052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\27052022\\PAYCLIP_Settlement_27052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\28052022\\PAYCLIP_Settlement_28052022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\05. MAYO\\31052022\\PAYCLIP_Settlement_31052022_V1.csv']

In [8]:
sftp_may_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_may_1_22])
sftp_may_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_may_22['date_file'] = sftp_may_22["file_name"].str[-15:-7]
sftp_may_22['date_file']= pd.to_datetime(sftp_may_22['date_file'], format='%d%m%Y').dt.date
sftp_may_22['date_file']= pd.to_datetime(sftp_may_22['date_file'])
sftp_may_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_may_22['month'] = sftp_may_22['date_file'].dt.strftime('%B')
sftp_may_22.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-957497671,1190276,205221,20220502,BANORTE,20220502,"205,221.00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May
793521,07927517,4524216067,-359,20220429,19400,SETTLED,-57,0.00,0.00,00,...,363508,74518992119006779275174,152533118533,NaN,C,-359.00,-57.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May
793520,07927517,4152313426,-91,20220429,7000,SETTLED,-15,0.00,0.00,00,...,810696,74518992119236479275170,872135522338,NaN,D,-91.00,-15.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May
793519,07927517,4213166137,-182,20220429,14000,SETTLED,-29,0.00,0.00,00,...,010267,74518992119907079275170,316163233041,NaN,D,-182.00,-29.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May
793518,07927517,4152313836,-234,20220429,18000,SETTLED,-37,0.00,0.00,00,...,810383,74518992119622879275177,510926664159,NaN,D,-234.00,-37.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May

In [9]:
sftp_may_22.shape

(10704022, 21)

### ABRIL

In [ ]:
sftp_apr_1_22 = sorted(glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\04. ABRIL\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_apr_1_22

In [ ]:
sftp_apr_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_apr_1_22])
sftp_apr_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_apr_22['date_file'] = sftp_apr_22["file_name"].str[-15:-7]
sftp_apr_22['date_file']= pd.to_datetime(sftp_apr_22['date_file'], format='%d%m%Y').dt.date
sftp_apr_22['date_file']= pd.to_datetime(sftp_apr_22['date_file'])
sftp_apr_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_apr_22['month'] = sftp_apr_22['date_file'].dt.strftime('%B')
sftp_apr_22.head()

In [ ]:
sftp_apr_22.shape

### MARZO

In [ ]:
sftp_mar_1_22 = sorted(glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\03. MARZO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_mar_1_22

In [ ]:
sftp_mar_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_mar_1_22])
sftp_mar_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_mar_22['date_file'] = sftp_mar_22["file_name"].str[-15:-7]
sftp_mar_22['date_file']= pd.to_datetime(sftp_mar_22['date_file'], format='%d%m%Y').dt.date
sftp_mar_22['date_file']= pd.to_datetime(sftp_mar_22['date_file'])
sftp_mar_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_mar_22['month'] = sftp_mar_22['date_file'].dt.strftime('%B')
sftp_mar_22.head()

In [ ]:
sftp_mar_22.shape

### FEBRERO 2022

In [ ]:
sftp_feb_1_22 = sorted(glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\02. FEBRERO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_feb_1_22

In [ ]:
sftp_feb_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_feb_1_22])
sftp_feb_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_feb_22['date_file'] = sftp_feb_22["file_name"].str[-15:-7]
sftp_feb_22['date_file']= pd.to_datetime(sftp_feb_22['date_file'], format='%d%m%Y').dt.date
sftp_feb_22['date_file']= pd.to_datetime(sftp_feb_22['date_file'])
sftp_feb_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_feb_22['month'] = sftp_feb_22['date_file'].dt.strftime('%B')
sftp_feb_22.head()

In [ ]:
sftp_feb_22.shape

### ENERO 2022

In [ ]:
sftp_jan_1_22 = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\01. ENERO\**\PAYCLIP_Settlement*.csv', recursive=False)
sftp_jan_1_22

In [ ]:
sftp_jan_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jan_1_22])
sftp_jan_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jan_22['date_file'] = sftp_jan_22["file_name"].str[-15:-7]
sftp_jan_22['date_file']= pd.to_datetime(sftp_jan_22['date_file'], format='%d%m%Y').dt.date
sftp_jan_22['date_file']= pd.to_datetime(sftp_jan_22['date_file'])
sftp_jan_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jan_22['month'] = sftp_jan_22['date_file'].dt.strftime('%B')
sftp_jan_22.head()

In [ ]:
sftp_jan_22.shape

### DICIEMBRE 2021

In [ ]:
sftp_dec_1_21 = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2021 SFTP Banorte\12. DICIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False)
sftp_dec_1_21

In [ ]:
sftp_dec_21 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_dec_1_21])
sftp_dec_21.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_dec_21['date_file'] = sftp_dec_21["file_name"].str[-15:-7]
sftp_dec_21['date_file']= pd.to_datetime(sftp_dec_21['date_file'], format='%d%m%Y').dt.date
sftp_dec_21['date_file']= pd.to_datetime(sftp_dec_21['date_file'])
sftp_dec_21.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_dec_21['month'] = sftp_dec_21['date_file'].dt.strftime('%B')
sftp_dec_21.head()

In [ ]:
sftp_dec_21.shape

### NOVIEMBRE 2021

In [ ]:
sftp_nov_1_21 = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2021 SFTP Banorte\11. NOVIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False)
sftp_nov_1_21

In [ ]:
sftp_nov_21 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_nov_1_21])
sftp_nov_21.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_nov_21['date_file'] = sftp_nov_21["file_name"].str[-15:-7]
sftp_nov_21['date_file']= pd.to_datetime(sftp_nov_21['date_file'], format='%d%m%Y').dt.date
sftp_nov_21['date_file']= pd.to_datetime(sftp_nov_21['date_file'])
sftp_nov_21.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_nov_21['month'] = sftp_nov_21['date_file'].dt.strftime('%B')
sftp_nov_21.head()

In [ ]:
sftp_nov_21.shape

# ALL SFTP

In [10]:
sftp = pd.concat([sftp_may_22,sftp_jun_22])
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-957497671,1190276,205221,20220502,BANORTE,20220502,"205,221.00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May
793521,07927517,4524216067,-359,20220429,19400,SETTLED,-57,0.00,0.00,00,...,363508,74518992119006779275174,152533118533,NaN,C,-359.00,-57.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May
793520,07927517,4152313426,-91,20220429,7000,SETTLED,-15,0.00,0.00,00,...,810696,74518992119236479275170,872135522338,NaN,D,-91.00,-15.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May
793519,07927517,4213166137,-182,20220429,14000,SETTLED,-29,0.00,0.00,00,...,010267,74518992119907079275170,316163233041,NaN,D,-182.00,-29.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May
793518,07927517,4152313836,-234,20220429,18000,SETTLED,-37,0.00,0.00,00,...,810383,74518992119622879275177,510926664159,NaN,D,-234.00,-37.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May

In [11]:
sftp.shape

(20970387, 21)

In [12]:
sftp_fecha_deposito = sftp[(sftp['transaction_type'] == 'BANORTE')]
sftp_fecha_deposito = sftp_fecha_deposito[['date_file', 'gross_amount']]
sftp_fecha_deposito.rename(columns ={'gross_amount': 'deposit_date'},inplace=True)
sftp_fecha_deposito.head()

   date_file  deposit_date
0 2022-05-03      20220502
0 2022-05-04      20220503
0 2022-05-05      20220504
0 2022-05-06      20220505
0 2022-05-07      20220506

In [13]:
sftp = sftp[(sftp['transaction_type'] != 'BANORTE')]
sftp = sftp.merge(sftp_fecha_deposito[['date_file', 'deposit_date']],on='date_file',how='left')

In [14]:
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month,deposit_date
0,07927517,4524216067,-359,20220429,19400,SETTLED,-57,0.00,0.00,00,...,74518992119006779275174,152533118533,NaN,C,-359.00,-57.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,20220502
1,07927517,4152313426,-91,20220429,7000,SETTLED,-15,0.00,0.00,00,...,74518992119236479275170,872135522338,NaN,D,-91.00,-15.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,20220502
2,07927517,4213166137,-182,20220429,14000,SETTLED,-29,0.00,0.00,00,...,74518992119907079275170,316163233041,NaN,D,-182.00,-29.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,20220502
3,07927517,4152313836,-234,20220429,18000,SETTLED,-37,0.00,0.00,00,...,74518992119622879275177,510926664159,NaN,D,-234.00,-37.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,20220502
4,07927517,4915664451,-538,20220429,41400,SETTLED,-86,0.00,0.00,00,...,74518992119337179275179,202934838045,NaN,D,-538.00,-86.00,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,20220502

In [15]:
sftp['transaction_type'].unique()

array(['SETTLED', 'REFUNDED', 'CHARGE_BACK'], dtype=object)

In [16]:
sftp['transaction_date'] = pd.to_datetime(sftp['transaction_date'], format='%Y%m%d').dt.date
sftp['deposit_date'] = pd.to_datetime(sftp['deposit_date'], format='%Y%m%d').dt.date

In [17]:
sftp['transaction_date'] = pd.to_datetime(sftp['transaction_date'])
sftp['deposit_date'] = pd.to_datetime(sftp['deposit_date'])

In [18]:
sftp['gross_amount'] = sftp['gross_amount']/100
sftp['commisions'] = sftp['commisions']/100
sftp['tax'] = sftp['tax']/100
sftp['installments_fees'] = sftp['installments_fees']/100
sftp['installments_tax'] = sftp['installments_tax']/100
sftp['acquirer_commision'] = sftp['acquirer_commision']/100
sftp['acquirer_tax'] = sftp['acquirer_tax']/100
sftp.loc[sftp['transaction_type'] != 'SETTLED', 'gross_amount'] = sftp['gross_amount']*-1
sftp['LAST2_SFTP'] = sftp['card'].str[-2:].astype(str)
sftp['BIN_SFTP'] = sftp['card'].str[:6].astype(str)
sftp['INDEX_TOTAL'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['INDEX_TOTAL_XPAY'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['order_id_xpay'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['INDEX_COD_AUTH'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['codigo_autorizacion'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['order_id'].fillna('NO EXISTE EN SFTP',inplace=True)
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
0,07927517,4524216067,-3.59,2022-04-29,194.00,SETTLED,-0.57,0.00,0.00,00,...,-0.57,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,67,452421,452421_67_152533118533_194.0,452421_67_nan_194.0,452421_67_363508_194.0
1,07927517,4152313426,-0.91,2022-04-29,70.00,SETTLED,-0.15,0.00,0.00,00,...,-0.15,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,26,415231,415231_26_872135522338_70.0,415231_26_nan_70.0,415231_26_810696_70.0
2,07927517,4213166137,-1.82,2022-04-29,140.00,SETTLED,-0.29,0.00,0.00,00,...,-0.29,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,37,421316,421316_37_316163233041_140.0,421316_37_nan_140.0,421316_37_010267_140.0
3,07927517,4152313836,-2.34,2022-04-29,180.00,SETTLED,-0.37,0.00,0.00,00,...,-0.37,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,36,415231,415231_36_510926664159_180.0,415231_36_nan_180.0,415231_36_810383_180.0
4,07927517,4915664451,-5.38,2022-04-29,414.00,SETTLED,-0.86,0.00,0.00,00,...,-0.86,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,51,491566,491566_51_202934838045_414.0,491566_51_nan_414.0,491566_51_000646_414.0

In [19]:
sftp.shape

(21568063, 27)

In [20]:
sftp['affiliation_sftp'].fillna('NULL',inplace=True)

In [21]:
match_range = sftp[(sftp['affiliation_sftp'] == '07927517')]
match_range.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
0,07927517,4524216067,-3.59,2022-04-29,194.00,SETTLED,-0.57,0.00,0.00,00,...,-0.57,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,67,452421,452421_67_152533118533_194.0,452421_67_nan_194.0,452421_67_363508_194.0
1,07927517,4152313426,-0.91,2022-04-29,70.00,SETTLED,-0.15,0.00,0.00,00,...,-0.15,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,26,415231,415231_26_872135522338_70.0,415231_26_nan_70.0,415231_26_810696_70.0
2,07927517,4213166137,-1.82,2022-04-29,140.00,SETTLED,-0.29,0.00,0.00,00,...,-0.29,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,37,421316,421316_37_316163233041_140.0,421316_37_nan_140.0,421316_37_010267_140.0
3,07927517,4152313836,-2.34,2022-04-29,180.00,SETTLED,-0.37,0.00,0.00,00,...,-0.37,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,36,415231,415231_36_510926664159_180.0,415231_36_nan_180.0,415231_36_810383_180.0
4,07927517,4915664451,-5.38,2022-04-29,414.00,SETTLED,-0.86,0.00,0.00,00,...,-0.86,PAYCLIP_Settlement_03052022_V1.csv,2022-05-03,May,2022-05-02,51,491566,491566_51_202934838045_414.0,491566_51_nan_414.0,491566_51_000646_414.0

In [22]:
match_range.shape

(7800761, 27)

In [23]:
start_date = '2022-05-09'
final_date = '2022-05-09'

In [24]:
match_range_2 = match_range[(match_range['deposit_date'] >= start_date) & (match_range['deposit_date'] <= final_date)]
match_range_2.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
2441018,07927517,4152313596,-2.82,2022-05-06,217.00,SETTLED,-0.45,0.00,0.00,00,...,-0.45,PAYCLIP_Settlement_10052022_V1.csv,2022-05-10,May,2022-05-09,96,415231,415231_96_530668135537_217.0,415231_96_nan_217.0,415231_96_847418_217.0
2441019,07927517,5470467019,-1.98,2022-05-06,107.00,SETTLED,-0.32,0.00,0.00,00,...,-0.32,PAYCLIP_Settlement_10052022_V1.csv,2022-05-10,May,2022-05-09,19,547046,547046_19_486497136524_107.0,547046_19_nan_107.0,547046_19_073429_107.0
2441020,07927517,4213166118,-3.50,2022-05-06,269.00,SETTLED,-0.56,0.00,0.00,00,...,-0.56,PAYCLIP_Settlement_10052022_V1.csv,2022-05-10,May,2022-05-09,18,421316,421316_18_473766712926_269.0,421316_18_nan_269.0,421316_18_086462_269.0
2441021,07927517,4152313465,-2.74,2022-05-06,211.00,SETTLED,-0.44,0.00,0.00,00,...,-0.44,PAYCLIP_Settlement_10052022_V1.csv,2022-05-10,May,2022-05-09,65,415231,415231_65_079276364858_211.0,415231_65_nan_211.0,415231_65_846922_211.0
2441022,07927517,5579100232,-1.59,2022-05-06,122.00,SETTLED,-0.25,0.00,0.00,00,...,-0.25,PAYCLIP_Settlement_10052022_V1.csv,2022-05-10,May,2022-05-09,32,557910,557910_32_985200689137_122.0,557910_32_nan_122.0,557910_32_071647_122.0

In [25]:
match_range_2.shape

(432511, 27)

In [26]:
match_range_2.to_excel('afiliacion_07927517_20220509.xlsx',index=False)