In [1]:
import pandas as pd
import numpy as np
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# FECHA PERIODO CONTABLE

In [2]:
start_date = '2022-01-01'
finish_date = '2022-01-31'

# READING FILES

### EPA

In [3]:
mov_ban_epa = glob.glob(r'G:\My Drive\Settlement\PROVISIONES\2022\01. ENERO\MOVIMIENTOS BANCARIOS AMEX\EPA*.csv',
                            recursive=False)
mov_ban_epa

['G:\\My Drive\\Settlement\\PROVISIONES\\2022\\01. ENERO\\MOVIMIENTOS BANCARIOS AMEX\\EPA-Resultados_de_la_búsqueda_de_transacciones02022022_101334.csv']

### GRRCN

In [4]:
mov_ban_grrcn = glob.glob(r'G:\My Drive\Settlement\PROVISIONES\2022\01. ENERO\MOVIMIENTOS BANCARIOS AMEX\GRRCN*.csv',
                            recursive=False)
mov_ban_grrcn

['G:\\My Drive\\Settlement\\PROVISIONES\\2022\\01. ENERO\\MOVIMIENTOS BANCARIOS AMEX\\GRRCN-Resultados_de_la_búsqueda_de_transacciones02022022_100953.csv',
 'G:\\My Drive\\Settlement\\PROVISIONES\\2022\\01. ENERO\\MOVIMIENTOS BANCARIOS AMEX\\GRRCN-Resultados_de_la_búsqueda_de_transacciones02022022_100930.csv',
 'G:\\My Drive\\Settlement\\PROVISIONES\\2022\\01. ENERO\\MOVIMIENTOS BANCARIOS AMEX\\GRRCN-Resultados_de_la_búsqueda_de_transacciones02022022_100826.csv',
 'G:\\My Drive\\Settlement\\PROVISIONES\\2022\\01. ENERO\\MOVIMIENTOS BANCARIOS AMEX\\GRRCN-Resultados_de_la_búsqueda_de_transacciones02022022_100736.csv',
 'G:\\My Drive\\Settlement\\PROVISIONES\\2022\\01. ENERO\\MOVIMIENTOS BANCARIOS AMEX\\GRRCN-Resultados_de_la_búsqueda_de_transacciones02022022_100646.csv']

# CUENTA POR COBRAR AGREGADOR

In [5]:
cxc_agg = pd.concat([pd.read_csv(f,skiprows=9,parse_dates=['Fecha de la transacción','Fecha de pago'],dayfirst=True)
                         .assign(file_name=os.path.basename(f)) for f in mov_ban_epa])
cxc_agg['Fecha de la transacción']= pd.to_datetime(cxc_agg['Fecha de la transacción'])
cxc_agg['Fecha de pago']= pd.to_datetime(cxc_agg['Fecha de pago'])
cxc_agg.sort_values(by=['Fecha de la transacción'],inplace=True)
cxc_agg.head()

,Fecha de la transacción,Fecha de pago,Número de afiliación del que envía,Monto del cargo,Número de sucursal que envía,Número de tarjetahabiente,Tipo de ajuste,Número de referencia del cargo,Tipo de autorización,Código de aprobación,Tipo,Número de terminal,file_name
0,2022-01-25,2022-01-26,9351789434,880.00,nan,376702XXXXX4004,nan,S6KNCHLFAJA3,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...
26,2022-01-25,2022-01-27,9351789434,393.30,nan,376718XXXXX2007,nan,5E8MSKGYKQ3F,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...
25,2022-01-25,2022-01-27,9351789434,"1,000.00",nan,376718XXXXX8030,nan,CEIV80LQV7XI,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...
24,2022-01-25,2022-01-27,9351789434,"1,908.00",nan,376702XXXXX2003,nan,BBS4CZH1E2CF,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...
23,2022-01-25,2022-01-27,9351789434,"1,000.00",nan,376701XXXXX2008,nan,QEWBWEL4OL5F,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...

In [6]:
cxc_agg.shape

(169, 13)

In [7]:
cxc_agg_final = cxc_agg[((cxc_agg['Fecha de pago'] > finish_date) & (cxc_agg['Fecha de la transacción'] <= finish_date))]
cxc_agg_final.head()

,Fecha de la transacción,Fecha de pago,Número de afiliación del que envía,Monto del cargo,Número de sucursal que envía,Número de tarjetahabiente,Tipo de ajuste,Número de referencia del cargo,Tipo de autorización,Código de aprobación,Tipo,Número de terminal,file_name
86,2022-01-28,2022-02-01,9351789434,230.00,nan,370785XXXXX4007,nan,NV27SJAGZ7VT,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...
93,2022-01-28,2022-02-01,9351789434,"1,827.00",nan,371777XXXXX1002,nan,LDSD6HX062J6,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...
92,2022-01-28,2022-02-01,9351789434,60.00,nan,376679XXXXX1024,nan,A8WX4YTUUZEH,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...
90,2022-01-28,2022-02-01,9351789434,"1,720.58",nan,376680XXXXX1007,nan,KDKSXXJGGH1O,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...
89,2022-01-28,2022-02-01,9351789434,"1,040.00",nan,371772XXXXX1011,nan,DJ7XVAYRPHXX,Y,nan,Sale,nan,EPA-Resultados_de_la_búsqueda_de_transacciones...

In [8]:
cxc_agg_final.shape

(72, 13)

# CUENTA POR COBRAR OPTBLUE

In [9]:
cxc_opt = pd.concat([pd.read_csv(f,skiprows=9,parse_dates=['Fecha de la transacción','Fecha de pago'],dayfirst=True)
                         .assign(file_name=os.path.basename(f)) for f in mov_ban_grrcn])
cxc_opt['Fecha de la transacción']= pd.to_datetime(cxc_opt['Fecha de la transacción'])
cxc_opt['Fecha de pago']= pd.to_datetime(cxc_opt['Fecha de pago'])
cxc_opt.sort_values(by=['Fecha de la transacción'],inplace=True)
cxc_opt.head()

,Fecha de la transacción,Fecha de pago,Número de afiliación del que envía,Monto del cargo,Número de sucursal que envía,Número de tarjetahabiente,Tipo de ajuste,Número de referencia del cargo,Tipo de autorización,Código de aprobación,Tipo,Número de terminal,file_name
7030,2022-01-25,2022-01-26,8138464128,200.00,nan,377238XXXXX4001,nan,00YWGUZ2OXKW,Y,nan,Sale,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...
828,2022-01-25,2022-01-26,8138464136,352.00,nan,371774XXXXX1014,nan,ET9YUAHZXEYN,Y,nan,Sale,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...
827,2022-01-25,2022-01-26,8138464136,463.00,nan,376663XXXXX3028,nan,G2LFFCMMVSYW,Y,nan,Sale,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...
826,2022-01-25,2022-01-26,8138464136,124.20,nan,370789XXXXX1006,nan,9MRDM7GCIO1J,Y,nan,Sale,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...
825,2022-01-25,2022-01-26,8138464136,726.00,nan,374908XXXXX4006,nan,YXC1UD7VZAKZ,Y,nan,Sale,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...

In [10]:
cxc_opt.shape

(41874, 13)

In [11]:
cxc_opt_final = cxc_opt[((cxc_opt['Fecha de pago'] > finish_date) & (cxc_opt['Fecha de la transacción'] <= finish_date))]
cxc_opt_final.head()

,Fecha de la transacción,Fecha de pago,Número de afiliación del que envía,Monto del cargo,Número de sucursal que envía,Número de tarjetahabiente,Tipo de ajuste,Número de referencia del cargo,Tipo de autorización,Código de aprobación,Tipo,Número de terminal,file_name
5319,2022-01-26,2022-02-02,8138464144,"(15,800.00)",nan,376689XXXXX6001,nan,HD7EQLZ83K5R,Y,nan,Credit,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...
4583,2022-01-28,2022-02-02,8138464227,"(40,000.00)",nan,373969XXXXX2000,nan,ASTACWNEG6GN,Y,nan,Credit,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...
1055,2022-01-31,2022-02-01,8138464227,500.00,nan,376718XXXXX2002,nan,BNEOCQQTZU9M,Y,nan,Sale,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...
1056,2022-01-31,2022-02-01,8138464227,"20,068.83",nan,376675XXXXX4000,nan,1MNCJVNXKHO6,Y,nan,Sale,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...
1057,2022-01-31,2022-02-01,8138464227,"1,740.00",nan,376670XXXXX3006,nan,NZL3I65DAXXZ,Y,nan,Sale,nan,GRRCN-Resultados_de_la_búsqueda_de_transaccion...

In [12]:
cxc_opt_final.shape

(3835, 13)

# EXCEL FINAL

In [13]:
writer = pd.ExcelWriter('CXC AMEX ENERO 2022.xlsx', engine='xlsxwriter', options={'encoding':'utf-8'})   
cxc_agg_final.to_excel(writer, sheet_name='AGREGADOR',index=False)
cxc_opt_final.to_excel(writer, sheet_name='OPTBLUE',index=False)
writer.save()
writer.close()