In [1]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

## READING FILES

In [2]:
excel_name = 'Dispersión-20220823.xlsx'
date_respuesta = '2022-08-23'
date_respuesta = pd.to_datetime(date_respuesta)

In [3]:
names_resp = ['report_id','status','report_date_local','amount','disbursement_batch_id','merchant_id','bank_account_number',
             'bank_name','bank_account_owner_name','execution_date','aplication_date','disbursement_tracking_key',
             'error_description','reference_number','cep']

In [4]:
disp = pd.read_csv(r'G:\.shortcut-targets-by-id\1Oe28Mf9uSidMamjllDen2gkNnC59eSUr\3.-Settlement\5.-HISTORICO FILES PAGOS\01. TRADICIONAL\2022\08. AUGUST\SANT 2022-08-23.csv')
rs1 = pd.read_excel(r'C:\Users\Cristian.Aparicio\Documents\DISPERSIONES\2022\08. AGOSTO\Respuesta-SANT 2022-08-23.xlsx',
                    sheet_name='Report',names=names_resp,
                    converters={'bank_account_number':str,'disbursement_tracking_key':str,'report_id':str})
bin1 = pd.read_csv(r'C:\Users\Cristian.Aparicio\Documents\DISPERSIONES\Catalogo_Bancos.csv'
                  ,dtype={'BIN':object,'Clave de la institución':object,'Nombre de la institución':object})

C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

# BIN

In [5]:
bin1.head()

   BIN Clave de la institución Nombre de la institución
0  138                   40138              ABC CAPITAL
1  102                   40102            ACCENDO BANCO
2  133                   40133                 ACTINVER
3  062                   40062                   AFIRME
4  638                   90638                    AKALA

In [6]:
bin1.shape

(90, 3)

# ARCHIVO RESPUESTA

In [7]:
rs1['Date_respuesta'] = date_respuesta
rs1['BIN'] = rs1['bank_account_number'].str[:3]
rs1.rename(columns ={'bank_account_number':'CLABE'}, inplace=True)
rs1['Metodo de dispersion'] = 'SANTANDER'
rs1.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,aplication_date,disbursement_tracking_key,error_description,reference_number,cep,Date_respuesta,BIN,Metodo de dispersion
0,TT5899MSH,PAID,2022-08-23T00:00,"5,653.62",eeb3b711-4ac2-4245-b2c9-980a40557d38,789e3e85-5fe8-41dd-ac03-9af6014dd9dd,002180700433258663,"Banco Nacional de MÃ©xico, S.A.",Maria del Rocio Duarte Aguirre,2022-08-23T13:09:50,2022-08-23T08:07:18,2022082340014 HDH0001420224870,NaN,338729,"2022-08-23,2022082340014 HDH0001420224870,4001...",2022-08-23,002,SANTANDER
1,JN7493JY4,PAID,2022-08-23T00:00,4.79,eeb3b711-4ac2-4245-b2c9-980a40557d38,dcf51273-55ff-49df-af22-2286605324d5,012456015691079750,"BBVA Bancomer, S.A.",Jose De Jesus Mojica Rodrguez,2022-08-23T13:14:12,2022-08-23T08:12:42,2022082340014 HDH0001420487250,NaN,371095,"2022-08-23,2022082340014 HDH0001420487250,4001...",2022-08-23,012,SANTANDER
2,J9T9MCL3X,PAID,2022-08-23T00:00,192.60,eeb3b711-4ac2-4245-b2c9-980a40557d38,522ea0a4-0a91-426a-819f-7374320e51c9,127180013315020086,"Banco Azteca, S.A.",Hector Galvan Hernandez,2022-08-23T13:08:11,2022-08-23T08:07:18,2022082340014 HDH0001419891920,NaN,326477,"2022-08-23,2022082340014 HDH0001419891920,4001...",2022-08-23,127,SANTANDER
3,W5YK2YDLM,PAID,2022-08-23T00:00,"3,449.36",eeb3b711-4ac2-4245-b2c9-980a40557d38,4b1fbe48-524f-49aa-aee9-38f7ca88ecb4,002375034170661780,"Banco Nacional de México, S.A.",Santos Gloria Joya Rubio,2022-08-23T13:07:52,2022-08-23T08:07:18,2022082340014 HDH0001419850510,NaN,324164,"2022-08-23,2022082340014 HDH0001419850510,4001...",2022-08-23,002,SANTANDER
4,PN7BXRJ6W,PAID,2022-08-23T00:00,349.76,eeb3b711-4ac2-4245-b2c9-980a40557d38,cd3f18ca-c688-4990-99cc-a6e555d8494b,002040701757130328,"Banco Nacional de México, S.A.",Midori Shiba Cosio,2022-08-23T13:13:31,2022-08-23T08:12:42,2022082340014 HDH0001420348320,NaN,365960,"2022-08-23,2022082340014 HDH0001420348320,4001...",2022-08-23,002,SANTANDER

In [8]:
rs1.shape

(82221, 18)

In [9]:
rs1['report_id'] = rs1['report_id'].str.strip()

In [10]:
rs2 = rs1.merge(bin1[['BIN','Clave de la institución','Nombre de la institución']] ,on='BIN', how='left')
rs2['Banco emisor'] = '40014'
rs2['Banco_emisor'] = 'SANTANDER'
rs2['Comision'] = ''
rs2['LINEA CEP'] = (rs2['Date_respuesta'].astype(str).replace(' ', '',regex=True)+','
                    +rs2['disbursement_tracking_key'].astype(str)+','
                    +rs2['Banco emisor'].astype(str).replace(' ', '',regex=True)+','
                    +rs2['Clave de la institución'].astype(str).replace(' ', '',regex=True)+','
                    +rs2['CLABE'].astype(str).replace(' ', '',regex=True)+','
                    +rs2['amount'].astype(str).replace(' ', '',regex=True))
rs2.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,...,cep,Date_respuesta,BIN,Metodo de dispersion,Clave de la institución,Nombre de la institución,Banco emisor,Banco_emisor,Comision,LINEA CEP
0,TT5899MSH,PAID,2022-08-23T00:00,"5,653.62",eeb3b711-4ac2-4245-b2c9-980a40557d38,789e3e85-5fe8-41dd-ac03-9af6014dd9dd,002180700433258663,"Banco Nacional de MÃ©xico, S.A.",Maria del Rocio Duarte Aguirre,2022-08-23T13:09:50,...,"2022-08-23,2022082340014 HDH0001420224870,4001...",2022-08-23,002,SANTANDER,40002,BANAMEX,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001420224870,4001..."
1,JN7493JY4,PAID,2022-08-23T00:00,4.79,eeb3b711-4ac2-4245-b2c9-980a40557d38,dcf51273-55ff-49df-af22-2286605324d5,012456015691079750,"BBVA Bancomer, S.A.",Jose De Jesus Mojica Rodrguez,2022-08-23T13:14:12,...,"2022-08-23,2022082340014 HDH0001420487250,4001...",2022-08-23,012,SANTANDER,40012,BBVA BANCOMER,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001420487250,4001..."
2,J9T9MCL3X,PAID,2022-08-23T00:00,192.60,eeb3b711-4ac2-4245-b2c9-980a40557d38,522ea0a4-0a91-426a-819f-7374320e51c9,127180013315020086,"Banco Azteca, S.A.",Hector Galvan Hernandez,2022-08-23T13:08:11,...,"2022-08-23,2022082340014 HDH0001419891920,4001...",2022-08-23,127,SANTANDER,40127,AZTECA,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001419891920,4001..."
3,W5YK2YDLM,PAID,2022-08-23T00:00,"3,449.36",eeb3b711-4ac2-4245-b2c9-980a40557d38,4b1fbe48-524f-49aa-aee9-38f7ca88ecb4,002375034170661780,"Banco Nacional de México, S.A.",Santos Gloria Joya Rubio,2022-08-23T13:07:52,...,"2022-08-23,2022082340014 HDH0001419850510,4001...",2022-08-23,002,SANTANDER,40002,BANAMEX,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001419850510,4001..."
4,PN7BXRJ6W,PAID,2022-08-23T00:00,349.76,eeb3b711-4ac2-4245-b2c9-980a40557d38,cd3f18ca-c688-4990-99cc-a6e555d8494b,002040701757130328,"Banco Nacional de México, S.A.",Midori Shiba Cosio,2022-08-23T13:13:31,...,"2022-08-23,2022082340014 HDH0001420348320,4001...",2022-08-23,002,SANTANDER,40002,BANAMEX,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001420348320,4001..."

In [11]:
rs2.shape

(82221, 24)

# ARCHIVO DISPERSION

In [12]:
disp['date_disbursement'] = date_respuesta
disp['report_id'] = disp['report_id'].str.strip()
disp['report_date_local'] = pd.to_datetime(disp['report_date_local'])

In [13]:
disp.loc[disp['report_date_local'] == date_respuesta, 'tipo'] = 'Pago del día'
disp.loc[disp['report_date_local'] != date_respuesta, 'tipo'] = 'Reprogramación'
disp.drop(['bank_name','bank_account_number','status','swap','payment_date_local'],axis=1,inplace=True)
disp.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,bank_account_owner_name,batch_created_date,disbursement_method,date_disbursement,tipo
0,DAILY,0000d758-84b4-4cb0-a165-4f0d3c44864d,MAHARISHI PANTJALI SA DE CV,maharishiclip@gmail.com,PYBYG4S8S,2022-08-23,610.33,MAHARISHI PANTJALI S.A. DE C.V.,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día
1,DAILY,0000e953-6b2c-44d0-a798-9dac1abf24ea,Super Kandy,yanellysegovia18@gmail.com,8PF859N38,2022-08-23,998.45,Ana Yanelly Puente Gutierrez,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día
2,DAILY,00016126-0052-402d-ba8a-95e5e1a1c673,Seguridad Industrial OM,jocabetolan@gmail.com,ZGG995FCC,2022-08-23,"2,217.37",CYNTHIA JOCABET OLAN RODRIGUEZ,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día
3,DAILY,00023bd5-6149-4ef9-95be-edb61d22588d,LAS PEKES,alebarradas1@hotmail.com,QQWZ7XGFR,2022-08-23,258.25,Virginia Alejandra Barradas Prez,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día
4,DAILY,0003bb43-38fc-4893-bf1c-d287f8b41fd4,Burgetto,lh1162921@gmail.com,6NCWSWDV4,2022-08-23,809.71,Elia Gabriela Sandoval Tassinari,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día

In [14]:
disp.shape

(82221, 12)

In [15]:
disp_2 = disp.merge(rs2[['report_id','status','Nombre de la institución','CLABE','LINEA CEP','Banco_emisor']]
                    ,on='report_id', how='left')
disp_2.loc[disp_2['status'] != 'PAID', 'status'] = 'ERROR'
disp_2.sort_values(by=['status'])
disp_2.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,bank_account_owner_name,batch_created_date,disbursement_method,date_disbursement,tipo,status,Nombre de la institución,CLABE,LINEA CEP,Banco_emisor
0,DAILY,0000d758-84b4-4cb0-a165-4f0d3c44864d,MAHARISHI PANTJALI SA DE CV,maharishiclip@gmail.com,PYBYG4S8S,2022-08-23,610.33,MAHARISHI PANTJALI S.A. DE C.V.,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día,PAID,BANREGIO,058375000003160831,"2022-08-23,2022082340014 HDH0001419962540,4001...",SANTANDER
1,DAILY,0000e953-6b2c-44d0-a798-9dac1abf24ea,Super Kandy,yanellysegovia18@gmail.com,8PF859N38,2022-08-23,998.45,Ana Yanelly Puente Gutierrez,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día,PAID,BANAMEX,002580701334955664,"2022-08-23,2022082340014 HDH0001419962440,4001...",SANTANDER
2,DAILY,00016126-0052-402d-ba8a-95e5e1a1c673,Seguridad Industrial OM,jocabetolan@gmail.com,ZGG995FCC,2022-08-23,"2,217.37",CYNTHIA JOCABET OLAN RODRIGUEZ,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día,PAID,BANAMEX,002045701331339825,"2022-08-23,2022082340014 HDH0001419962480,4001...",SANTANDER
3,DAILY,00023bd5-6149-4ef9-95be-edb61d22588d,LAS PEKES,alebarradas1@hotmail.com,QQWZ7XGFR,2022-08-23,258.25,Virginia Alejandra Barradas Prez,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día,PAID,BANCOPPEL,137463103868892825,"2022-08-23,2022082340014 HDH0001419962580,4001...",SANTANDER
4,DAILY,0003bb43-38fc-4893-bf1c-d287f8b41fd4,Burgetto,lh1162921@gmail.com,6NCWSWDV4,2022-08-23,809.71,Elia Gabriela Sandoval Tassinari,2022-08-23 08:03:24,SANTANDER,2022-08-23,Pago del día,PAID,BBVA BANCOMER,012730015122265937,"2022-08-23,2022082340014 HDH0001419962490,4001...",SANTANDER

In [16]:
disp_2.loc[disp_2['Nombre de la institución'] == 'SANTANDER', 'LINEA CEP'] = 'COMPROBANTE MISMO BANCO SANTANDER'
disp_2.loc[disp_2['status'] == 'ERROR', 'LINEA CEP'] = ''
disp_2.loc[disp_2['status'] == 'ERROR', 'Banco_emisor'] = ''

In [17]:
for col in disp_2.columns: 
    print(col)

type
merchant_id
merchant_name
user_email
report_id
report_date_local
amount
bank_account_owner_name
batch_created_date
disbursement_method
date_disbursement
tipo
status
Nombre de la institución
CLABE
LINEA CEP
Banco_emisor

In [18]:
disp_final = disp_2[['type','merchant_id','merchant_name','user_email','report_id','report_date_local','amount','tipo'
                    ,'Nombre de la institución','bank_account_owner_name','CLABE','status','LINEA CEP','Banco_emisor']]
disp_final.rename(columns ={'Nombre de la institución':'bank','amount':'total_due'}, inplace=True)
disp_final.sort_values(by=['status'], ascending=True, inplace=True)
disp_final.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_14320\1936322415.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.rename(columns ={'Nombre de la institución':'bank','amount':'total_due'}, inplace=True)
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_14320\1936322415.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.sort_values(by=['status'], ascending=True, inplace=True)

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,bank_account_owner_name,CLABE,status,LINEA CEP,Banco_emisor
66710,DAILY,cf842c28-eee3-43ae-9f9a-694c82ba1ba4,Artesanias Y Articulos De Playa,jaime_rb31@hotmail.com,CGQDLX425,2022-08-23,939.08,Pago del día,SANTANDER,Jaime Roman Bousieguez,014744605746307086,ERROR,,
57057,DAILY,b1aed04f-2450-46a2-8b35-f8bf86e499d6,Grupo AMI Angeles,gpe_gago79@hotmail.com,4HTCC9FXS,2022-08-23,"1,097.18",Pago del día,BANORTE/IXE,Guadalupe Garca Gomez,072010011473269142,ERROR,,
11089,DAILY,22bb083a-331e-4c5e-9440-98abddd927c3,Abarrotes claudia,abarrotesclaudia28@gmail.com,CFW559WHT,2022-08-23,186.16,Pago del día,BBVA BANCOMER,Norma Aracely Camacho Nuncio,012580015927751045,ERROR,,
43375,DAILY,86df6ed2-37d6-4db8-aa11-3309cf2c0f05,Limoncito,karelygat@gmail.com,PPK7H863X,2022-08-23,335.38,Pago del día,BBVA BANCOMER,Jess Missael Guardado Alvarado,012190015402793044,ERROR,,
81552,DAILY,fdfb116c-0a62-4d91-9993-2916a47bf227,Sb Lash,shaday002@icloud.com,B74FD8WTZ,2022-08-23,"1,066.44",Pago del día,BANREGIO,Shasta Lorena de la Cerda Lopez,058597000023174410,ERROR,,

In [19]:
disp_final.shape

(82221, 14)

# ERROR

In [20]:
error = disp_final[(disp_final['status'] != 'PAID')]
error.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,bank_account_owner_name,CLABE,status,LINEA CEP,Banco_emisor
66710,DAILY,cf842c28-eee3-43ae-9f9a-694c82ba1ba4,Artesanias Y Articulos De Playa,jaime_rb31@hotmail.com,CGQDLX425,2022-08-23,939.08,Pago del día,SANTANDER,Jaime Roman Bousieguez,014744605746307086,ERROR,,
57057,DAILY,b1aed04f-2450-46a2-8b35-f8bf86e499d6,Grupo AMI Angeles,gpe_gago79@hotmail.com,4HTCC9FXS,2022-08-23,"1,097.18",Pago del día,BANORTE/IXE,Guadalupe Garca Gomez,072010011473269142,ERROR,,
11089,DAILY,22bb083a-331e-4c5e-9440-98abddd927c3,Abarrotes claudia,abarrotesclaudia28@gmail.com,CFW559WHT,2022-08-23,186.16,Pago del día,BBVA BANCOMER,Norma Aracely Camacho Nuncio,012580015927751045,ERROR,,
43375,DAILY,86df6ed2-37d6-4db8-aa11-3309cf2c0f05,Limoncito,karelygat@gmail.com,PPK7H863X,2022-08-23,335.38,Pago del día,BBVA BANCOMER,Jess Missael Guardado Alvarado,012190015402793044,ERROR,,
81552,DAILY,fdfb116c-0a62-4d91-9993-2916a47bf227,Sb Lash,shaday002@icloud.com,B74FD8WTZ,2022-08-23,"1,066.44",Pago del día,BANREGIO,Shasta Lorena de la Cerda Lopez,058597000023174410,ERROR,,

In [21]:
error.shape

(402, 14)

In [22]:
error.drop(['bank_account_owner_name','CLABE','status','LINEA CEP','Banco_emisor'],axis=1,inplace=True)

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_14320\1215281788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  error.drop(['bank_account_owner_name','CLABE','status','LINEA CEP','Banco_emisor'],axis=1,inplace=True)

In [23]:
error.loc[error['bank'] == 'SANTANDER', 'Check'] = 'SPEI DEVUELTO MISMO BANCO'
error.loc[error['bank'] != 'SANTANDER', 'Check'] = 'SPEI DEVUELTO'

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_14320\2883469485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  error.loc[error['bank'] == 'SANTANDER', 'Check'] = 'SPEI DEVUELTO MISMO BANCO'

In [24]:
error_final = error.merge(rs2[['report_id','error_description']] ,on='report_id', how='left')
error_final.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,Check,error_description
0,DAILY,cf842c28-eee3-43ae-9f9a-694c82ba1ba4,Artesanias Y Articulos De Playa,jaime_rb31@hotmail.com,CGQDLX425,2022-08-23,939.08,Pago del día,SANTANDER,SPEI DEVUELTO MISMO BANCO,P6
1,DAILY,b1aed04f-2450-46a2-8b35-f8bf86e499d6,Grupo AMI Angeles,gpe_gago79@hotmail.com,4HTCC9FXS,2022-08-23,"1,097.18",Pago del día,BANORTE/IXE,SPEI DEVUELTO,DN
2,DAILY,22bb083a-331e-4c5e-9440-98abddd927c3,Abarrotes claudia,abarrotesclaudia28@gmail.com,CFW559WHT,2022-08-23,186.16,Pago del día,BBVA BANCOMER,SPEI DEVUELTO,DM
3,DAILY,86df6ed2-37d6-4db8-aa11-3309cf2c0f05,Limoncito,karelygat@gmail.com,PPK7H863X,2022-08-23,335.38,Pago del día,BBVA BANCOMER,SPEI DEVUELTO,DM
4,DAILY,fdfb116c-0a62-4d91-9993-2916a47bf227,Sb Lash,shaday002@icloud.com,B74FD8WTZ,2022-08-23,"1,066.44",Pago del día,BANREGIO,SPEI DEVUELTO,DA

In [25]:
error_final.shape

(402, 11)

# ARCHIVOS FINALES

### ARCHIVO DISPERSION

In [26]:
writer = pd.ExcelWriter(excel_name, engine='xlsxwriter', engine_kwargs={'options': {'encoding':'utf-8'}})
disp_final.to_excel(writer, sheet_name='Swap del día',index=False)
error_final.to_excel(writer, sheet_name='ERROR',index=False)
writer.close()

### ARCHIVO RESPUESTA

In [27]:
rs2.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,...,cep,Date_respuesta,BIN,Metodo de dispersion,Clave de la institución,Nombre de la institución,Banco emisor,Banco_emisor,Comision,LINEA CEP
0,TT5899MSH,PAID,2022-08-23T00:00,"5,653.62",eeb3b711-4ac2-4245-b2c9-980a40557d38,789e3e85-5fe8-41dd-ac03-9af6014dd9dd,002180700433258663,"Banco Nacional de MÃ©xico, S.A.",Maria del Rocio Duarte Aguirre,2022-08-23T13:09:50,...,"2022-08-23,2022082340014 HDH0001420224870,4001...",2022-08-23,002,SANTANDER,40002,BANAMEX,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001420224870,4001..."
1,JN7493JY4,PAID,2022-08-23T00:00,4.79,eeb3b711-4ac2-4245-b2c9-980a40557d38,dcf51273-55ff-49df-af22-2286605324d5,012456015691079750,"BBVA Bancomer, S.A.",Jose De Jesus Mojica Rodrguez,2022-08-23T13:14:12,...,"2022-08-23,2022082340014 HDH0001420487250,4001...",2022-08-23,012,SANTANDER,40012,BBVA BANCOMER,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001420487250,4001..."
2,J9T9MCL3X,PAID,2022-08-23T00:00,192.60,eeb3b711-4ac2-4245-b2c9-980a40557d38,522ea0a4-0a91-426a-819f-7374320e51c9,127180013315020086,"Banco Azteca, S.A.",Hector Galvan Hernandez,2022-08-23T13:08:11,...,"2022-08-23,2022082340014 HDH0001419891920,4001...",2022-08-23,127,SANTANDER,40127,AZTECA,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001419891920,4001..."
3,W5YK2YDLM,PAID,2022-08-23T00:00,"3,449.36",eeb3b711-4ac2-4245-b2c9-980a40557d38,4b1fbe48-524f-49aa-aee9-38f7ca88ecb4,002375034170661780,"Banco Nacional de México, S.A.",Santos Gloria Joya Rubio,2022-08-23T13:07:52,...,"2022-08-23,2022082340014 HDH0001419850510,4001...",2022-08-23,002,SANTANDER,40002,BANAMEX,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001419850510,4001..."
4,PN7BXRJ6W,PAID,2022-08-23T00:00,349.76,eeb3b711-4ac2-4245-b2c9-980a40557d38,cd3f18ca-c688-4990-99cc-a6e555d8494b,002040701757130328,"Banco Nacional de México, S.A.",Midori Shiba Cosio,2022-08-23T13:13:31,...,"2022-08-23,2022082340014 HDH0001420348320,4001...",2022-08-23,002,SANTANDER,40002,BANAMEX,40014,SANTANDER,,"2022-08-23,2022082340014 HDH0001420348320,4001..."

In [28]:
rs_final = rs2[['disbursement_tracking_key','bank_account_owner_name','report_id','CLABE',
                'Nombre de la institución','amount','Comision','status','error_description','Date_respuesta',
                'Metodo de dispersion']]
rs_final.rename(columns = {'disbursement_tracking_key':'Rastreo CEP'
                           ,'bank_account_owner_name':'Nombre','CLABE':'Cuenta'
                           ,'Nombre de la institución':'Banco','amount':'Importe','status':'Estatus'
                           ,'error_description':'Mensaje'}, inplace=True)
rs_final['Cuenta'] = "'"+rs_final['Cuenta']
rs_final.sort_values(by=['Estatus'], ascending=True, inplace=True)
rs_final.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_14320\828709770.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rs_final.rename(columns = {'disbursement_tracking_key':'Rastreo CEP'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_14320\828709770.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rs_final['Cuenta'] = "'"+rs_final['Cuenta']
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_14320\828709770.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rs_final.sort_values(by=['Estatus'], ascending=True, inplace=True)

,Rastreo CEP,Nombre,report_id,Cuenta,Banco,Importe,Comision,Estatus,Mensaje,Date_respuesta,Metodo de dispersion
38473,2022082340014 HDH0001420176780,JANNELY SARAHI LOPEZ OBESO,LW25NQ83V,'012730015192380648,BBVA BANCOMER,"2,654.32",,ERROR,DM,2022-08-23,SANTANDER
8208,2022082340014 HDH0001420208730,Ana Karen Ortega Nunez,WGXH3XQQ5,'012180015593249022,BBVA BANCOMER,"1,471.18",,ERROR,DM,2022-08-23,SANTANDER
60526,2022082340014 HDH0001420436090,Alondra Figueroa Huerta,8PSQXX24B,'012180029393733494,BBVA BANCOMER,"1,835.28",,ERROR,DA,2022-08-23,SANTANDER
10002,2022082340014 HDH0001420503560,Rebeca Vidal Terron,8NBD72FPD,'130877001047848903,COMPARTAMOS,1.20,,ERROR,DI,2022-08-23,SANTANDER
4285,2022082340014 HDH0001420070680,Iris Zoraina Alvarez Delgado,335NK72HX,'012818015197476369,BBVA BANCOMER,536.62,,ERROR,DM,2022-08-23,SANTANDER

In [29]:
rs_final.shape

(82221, 11)

In [30]:
rs_final.to_csv(r'G:\.shortcut-targets-by-id\1Oe28Mf9uSidMamjllDen2gkNnC59eSUr\3.-Settlement\Respuestas Swap\2022\08. Agosto 2022\Respuesta 2022-08-23.csv',index=False)