In [1]:
import numpy as np
import pandas as pd
import zipfile
from zipfile import ZipFile
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# SFTP

## HEADERS

In [2]:
name_file=['column_type','affiliation_sftp','merchant_reference','card','settled_amount','commisions','transaction_date',
           'gross_amount','currency','transaction_type','tax','installments_tax','iva_cashback_paid','iva_cashback_charged',
          'cashback_fees_paid','cashback_fees_charged','installments_fees','cashback_amount','number_of_payments',
           'initial_deferment','plan_type','auth_code','unknown.1','eci','interbank_reference','empty.1','unknown.2','empty.2',
          'payworks_reference','card_type','transaction_source','prosa_reference','acquirer_commision','acquirer_tax',
          'unknown.3','unknown.4','unknown.5']
dtypes_file={'interbank_reference':object,'affiliation_sftp':object,'card':object,'number_of_payments':object,
             'initial_deferment':object,'plan_type':object,'auth_code':object,'payworks_reference':object,'eci':object}

In [3]:
use_cols = ['affiliation_sftp','transaction_type','transaction_date','eci','auth_code','interbank_reference',
            'payworks_reference','card','gross_amount','commisions','tax','installments_fees','installments_tax',
            'acquirer_commision','acquirer_tax','card_type','number_of_payments','initial_deferment']

### DICIEMBRE

In [ ]:
sftp_dec_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\12. DICIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_dec_1_22

In [ ]:
sftp_dec_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_dec_1_22])
sftp_dec_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_dec_22['date_file'] = sftp_dec_22["file_name"].str[-15:-7]
sftp_dec_22['date_file']= pd.to_datetime(sftp_dec_22['date_file'], format='%d%m%Y').dt.date
sftp_dec_22['date_file']= pd.to_datetime(sftp_dec_22['date_file'])
sftp_dec_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_dec_22['month'] = sftp_dec_22['date_file'].dt.strftime('%B')
sftp_dec_22.head()

In [ ]:
sftp_dec_22.shape

### NOVIEMBRE

In [4]:
sftp_nov_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\11. NOVIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_nov_1_22

['G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\01112022\\PAYCLIP_Settlement_01112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\02112022\\PAYCLIP_Settlement_02112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\04112022\\PAYCLIP_Settlement_04112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\05112022\\PAYCLIP_Settlement_05112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\08112022\\PAYCLIP_Settlement_08112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\09112022\\PAYCLIP_Settlement_09112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\10112022\\PAYCLIP_Settlement_10112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\11112022\\PAYCLIP_Settlement_11112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\12112022\\PAYCLIP_Settlement_12112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\15112022\\PAYCLIP_Settlement_15112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\16112022\\PAYCLIP_Settlement_16112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\17112022\\PAYCLIP_Settlement_17112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\18112022\\PAYCLIP_Settlement_18112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\19112022\\PAYCLIP_Settlement_19112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\23112022\\PAYCLIP_Settlement_23112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\24112022\\PAYCLIP_Settlement_24112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\25112022\\PAYCLIP_Settlement_25112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\26112022\\PAYCLIP_Settlement_26112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\29112022\\PAYCLIP_Settlement_29112022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\11. NOVIEMBRE\\30112022\\PAYCLIP_Settlement_30112022_V1.csv']

In [5]:
sftp_nov_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_nov_1_22])
sftp_nov_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_nov_22['date_file'] = sftp_nov_22["file_name"].str[-15:-7]
sftp_nov_22['date_file']= pd.to_datetime(sftp_nov_22['date_file'], format='%d%m%Y').dt.date
sftp_nov_22['date_file']= pd.to_datetime(sftp_nov_22['date_file'])
sftp_nov_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_nov_22['month'] = sftp_nov_22['date_file'].dt.strftime('%B')
sftp_nov_22.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-1160366795,1418279,3110221,20221031,BANORTE,20221031,"3,110,221.00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_01112022_V1.csv,2022-11-01,November
945524,07927517,4772103038,-1151,20221028,62200,SETTLED,-184,0.00,0.00,00,...,117241,74518992301906779275173,497437309090,NaN,C,"-1,151.00",-184.00,PAYCLIP_Settlement_01112022_V1.csv,2022-11-01,November
945523,07927517,5532530063,-37,20221028,2000,SETTLED,-6,0.00,0.00,00,...,091353,75445502301079179275177,570173638145,NaN,C,-37.00,-6.00,PAYCLIP_Settlement_01112022_V1.csv,2022-11-01,November
945522,07927517,5491380201,-492,20221028,26600,SETTLED,-79,0.00,0.00,00,...,678415,75445502301033979275176,223573145307,NaN,C,-492.00,-79.00,PAYCLIP_Settlement_01112022_V1.csv,2022-11-01,November
945521,07927517,4910897052,-247,20221028,19000,SETTLED,-40,0.00,0.00,00,...,010744,74518992301099379275171,223853786870,NaN,D,-247.00,-40.00,PAYCLIP_Settlement_01112022_V1.csv,2022-11-01,November

In [6]:
sftp_nov_22.shape

(13112446, 21)

### OCTUBRE

In [7]:
sftp_oct_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\10. OCTUBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_oct_1_22

['G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\01102022\\PAYCLIP_Settlement_01102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\04102022\\PAYCLIP_Settlement_04102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\05102022\\PAYCLIP_Settlement_05102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\06102022\\PAYCLIP_Settlement_06102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\07102022\\PAYCLIP_Settlement_07102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\08102022\\PAYCLIP_Settlement_08102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\11102022\\PAYCLIP_Settlement_11102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\12102022\\PAYCLIP_Settlement_12102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\13102022\\PAYCLIP_Settlement_13102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\14102022\\PAYCLIP_Settlement_14102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\15102022\\PAYCLIP_Settlement_15102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\18102022\\PAYCLIP_Settlement_18102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\19102022\\PAYCLIP_Settlement_19102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\20102022\\PAYCLIP_Settlement_20102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\21102022\\PAYCLIP_Settlement_21102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\22102022\\PAYCLIP_Settlement_22102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\25102022\\PAYCLIP_Settlement_25102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\26102022\\PAYCLIP_Settlement_26102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\27102022\\PAYCLIP_Settlement_27102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\28102022\\PAYCLIP_Settlement_28102022_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2022 SFTP Banorte\\10. OCTUBRE\\29102022\\PAYCLIP_Settlement_29102022_V1.csv']

In [8]:
sftp_oct_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_oct_1_22])
sftp_oct_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_oct_22['date_file'] = sftp_oct_22["file_name"].str[-15:-7]
sftp_oct_22['date_file']= pd.to_datetime(sftp_oct_22['date_file'], format='%d%m%Y').dt.date
sftp_oct_22['date_file']= pd.to_datetime(sftp_oct_22['date_file'])
sftp_oct_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_oct_22['month'] = sftp_oct_22['date_file'].dt.strftime('%B')
sftp_oct_22.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-347116226,410334,3009221,20220930,BANORTE,20220930,"3,009,221.00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October
273562,07927517,4027665074,-247,20220929,19000,SETTLED,-40,0.00,0.00,00,...,370750,74518992272408579275177,553743879819,NaN,D,-247.00,-40.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October
273561,07927517,4152313826,-69,20220929,5300,SETTLED,-11,0.00,0.00,00,...,443828,74518992272638879275176,058146201172,NaN,D,-69.00,-11.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October
273560,07927517,5192030085,-244,20220929,13200,SETTLED,-39,0.00,0.00,00,...,430693,75445502272207879275172,415800511373,NaN,C,-244.00,-39.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October
273559,07927517,5579079046,-52,20220929,4000,SETTLED,-8,0.00,0.00,00,...,004702,75445502272528679275173,252660087696,NaN,D,-52.00,-8.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October

In [9]:
sftp_oct_22.shape

(11435626, 21)

### SEPTIEMBRE

In [ ]:
sftp_sep_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\09. SEPTIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_sep_1_22

In [ ]:
sftp_sep_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_sep_1_22])
sftp_sep_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_sep_22['date_file'] = sftp_sep_22["file_name"].str[-15:-7]
sftp_sep_22['date_file']= pd.to_datetime(sftp_sep_22['date_file'], format='%d%m%Y').dt.date
sftp_sep_22['date_file']= pd.to_datetime(sftp_sep_22['date_file'])
sftp_sep_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_sep_22['month'] = sftp_sep_22['date_file'].dt.strftime('%B')
sftp_sep_22.head()

In [ ]:
sftp_sep_22.shape

### AGOSTO

In [ ]:
sftp_aug_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\08. AGOSTO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_aug_1_22

In [ ]:
sftp_aug_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_aug_1_22])
sftp_aug_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_aug_22['date_file'] = sftp_aug_22["file_name"].str[-15:-7]
sftp_aug_22['date_file']= pd.to_datetime(sftp_aug_22['date_file'], format='%d%m%Y').dt.date
sftp_aug_22['date_file']= pd.to_datetime(sftp_aug_22['date_file'])
sftp_aug_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_aug_22['month'] = sftp_aug_22['date_file'].dt.strftime('%B')
sftp_aug_22.head()

In [ ]:
sftp_aug_22.shape

### JULIO

In [ ]:
sftp_jul_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\07. JULIO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_jul_1_22

In [ ]:
sftp_jul_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jul_1_22])
sftp_jul_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jul_22['date_file'] = sftp_jul_22["file_name"].str[-15:-7]
sftp_jul_22['date_file']= pd.to_datetime(sftp_jul_22['date_file'], format='%d%m%Y').dt.date
sftp_jul_22['date_file']= pd.to_datetime(sftp_jul_22['date_file'])
sftp_jul_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jul_22['month'] = sftp_jul_22['date_file'].dt.strftime('%B')
sftp_jul_22.head()

In [ ]:
sftp_jul_22.shape

### JUNIO

In [ ]:
sftp_jun_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\06. JUNIO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_jun_1_22

In [ ]:
sftp_jun_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jun_1_22])
sftp_jun_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jun_22['date_file'] = sftp_jun_22["file_name"].str[-15:-7]
sftp_jun_22['date_file']= pd.to_datetime(sftp_jun_22['date_file'], format='%d%m%Y').dt.date
sftp_jun_22['date_file']= pd.to_datetime(sftp_jun_22['date_file'])
sftp_jun_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jun_22['month'] = sftp_jun_22['date_file'].dt.strftime('%B')
sftp_jun_22.head()

In [ ]:
sftp_jun_22.shape

### MAYO

In [ ]:
sftp_may_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\05. MAYO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_may_1_22

In [ ]:
sftp_may_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_may_1_22])
sftp_may_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_may_22['date_file'] = sftp_may_22["file_name"].str[-15:-7]
sftp_may_22['date_file']= pd.to_datetime(sftp_may_22['date_file'], format='%d%m%Y').dt.date
sftp_may_22['date_file']= pd.to_datetime(sftp_may_22['date_file'])
sftp_may_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_may_22['month'] = sftp_may_22['date_file'].dt.strftime('%B')
sftp_may_22.head()

In [ ]:
sftp_may_22.shape

### ABRIL

In [ ]:
sftp_apr_1_22 = sorted(glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\04. ABRIL\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_apr_1_22

In [ ]:
sftp_apr_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_apr_1_22])
sftp_apr_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_apr_22['date_file'] = sftp_apr_22["file_name"].str[-15:-7]
sftp_apr_22['date_file']= pd.to_datetime(sftp_apr_22['date_file'], format='%d%m%Y').dt.date
sftp_apr_22['date_file']= pd.to_datetime(sftp_apr_22['date_file'])
sftp_apr_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_apr_22['month'] = sftp_apr_22['date_file'].dt.strftime('%B')
sftp_apr_22.head()

In [ ]:
sftp_apr_22.shape

### MARZO

In [ ]:
sftp_mar_1_22 = sorted(glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\03. MARZO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_mar_1_22

In [ ]:
sftp_mar_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_mar_1_22])
sftp_mar_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_mar_22['date_file'] = sftp_mar_22["file_name"].str[-15:-7]
sftp_mar_22['date_file']= pd.to_datetime(sftp_mar_22['date_file'], format='%d%m%Y').dt.date
sftp_mar_22['date_file']= pd.to_datetime(sftp_mar_22['date_file'])
sftp_mar_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_mar_22['month'] = sftp_mar_22['date_file'].dt.strftime('%B')
sftp_mar_22.head()

In [ ]:
sftp_mar_22.shape

### FEBRERO 2022

In [ ]:
sftp_feb_1_22 = sorted(glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\02. FEBRERO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_feb_1_22

In [ ]:
sftp_feb_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_feb_1_22])
sftp_feb_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_feb_22['date_file'] = sftp_feb_22["file_name"].str[-15:-7]
sftp_feb_22['date_file']= pd.to_datetime(sftp_feb_22['date_file'], format='%d%m%Y').dt.date
sftp_feb_22['date_file']= pd.to_datetime(sftp_feb_22['date_file'])
sftp_feb_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_feb_22['month'] = sftp_feb_22['date_file'].dt.strftime('%B')
sftp_feb_22.head()

In [ ]:
sftp_feb_22.shape

### ENERO 2022

In [ ]:
sftp_jan_1_22 = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\01. ENERO\**\PAYCLIP_Settlement*.csv', recursive=False)
sftp_jan_1_22

In [ ]:
sftp_jan_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jan_1_22])
sftp_jan_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jan_22['date_file'] = sftp_jan_22["file_name"].str[-15:-7]
sftp_jan_22['date_file']= pd.to_datetime(sftp_jan_22['date_file'], format='%d%m%Y').dt.date
sftp_jan_22['date_file']= pd.to_datetime(sftp_jan_22['date_file'])
sftp_jan_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jan_22['month'] = sftp_jan_22['date_file'].dt.strftime('%B')
sftp_jan_22.head()

In [ ]:
sftp_jan_22.shape

### DICIEMBRE 2021

In [ ]:
sftp_dec_1_21 = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2021 SFTP Banorte\12. DICIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False)
sftp_dec_1_21

In [ ]:
sftp_dec_21 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_dec_1_21])
sftp_dec_21.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_dec_21['date_file'] = sftp_dec_21["file_name"].str[-15:-7]
sftp_dec_21['date_file']= pd.to_datetime(sftp_dec_21['date_file'], format='%d%m%Y').dt.date
sftp_dec_21['date_file']= pd.to_datetime(sftp_dec_21['date_file'])
sftp_dec_21.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_dec_21['month'] = sftp_dec_21['date_file'].dt.strftime('%B')
sftp_dec_21.head()

In [ ]:
sftp_dec_21.shape

### NOVIEMBRE 2021

In [ ]:
sftp_nov_1_21 = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2021 SFTP Banorte\11. NOVIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False)
sftp_nov_1_21

In [ ]:
sftp_nov_21 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_nov_1_21])
sftp_nov_21.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_nov_21['date_file'] = sftp_nov_21["file_name"].str[-15:-7]
sftp_nov_21['date_file']= pd.to_datetime(sftp_nov_21['date_file'], format='%d%m%Y').dt.date
sftp_nov_21['date_file']= pd.to_datetime(sftp_nov_21['date_file'])
sftp_nov_21.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_nov_21['month'] = sftp_nov_21['date_file'].dt.strftime('%B')
sftp_nov_21.head()

In [ ]:
sftp_nov_21.shape

# ALL SFTP

In [10]:
sftp = pd.concat([sftp_oct_22,sftp_nov_22])
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-347116226,410334,3009221,20220930,BANORTE,20220930,"3,009,221.00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October
273562,07927517,4027665074,-247,20220929,19000,SETTLED,-40,0.00,0.00,00,...,370750,74518992272408579275177,553743879819,NaN,D,-247.00,-40.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October
273561,07927517,4152313826,-69,20220929,5300,SETTLED,-11,0.00,0.00,00,...,443828,74518992272638879275176,058146201172,NaN,D,-69.00,-11.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October
273560,07927517,5192030085,-244,20220929,13200,SETTLED,-39,0.00,0.00,00,...,430693,75445502272207879275172,415800511373,NaN,C,-244.00,-39.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October
273559,07927517,5579079046,-52,20220929,4000,SETTLED,-8,0.00,0.00,00,...,004702,75445502272528679275173,252660087696,NaN,D,-52.00,-8.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October

In [11]:
sftp.shape

(24548072, 21)

In [12]:
sftp_fecha_deposito = sftp[(sftp['transaction_type'] == 'BANORTE')]
sftp_fecha_deposito = sftp_fecha_deposito[['date_file', 'gross_amount']]
sftp_fecha_deposito.rename(columns ={'gross_amount': 'deposit_date'},inplace=True)
sftp_fecha_deposito.head()

   date_file  deposit_date
0 2022-10-01      20220930
0 2022-10-04      20221003
0 2022-10-05      20221004
0 2022-10-06      20221005
0 2022-10-07      20221006

In [13]:
sftp = sftp[(sftp['transaction_type'] != 'BANORTE')]
sftp = sftp.merge(sftp_fecha_deposito[['date_file', 'deposit_date']],on='date_file',how='left')

In [14]:
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month,deposit_date
0,07927517,4027665074,-247,20220929,19000,SETTLED,-40,0.00,0.00,00,...,74518992272408579275177,553743879819,NaN,D,-247.00,-40.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,20220930
1,07927517,4152313826,-69,20220929,5300,SETTLED,-11,0.00,0.00,00,...,74518992272638879275176,058146201172,NaN,D,-69.00,-11.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,20220930
2,07927517,5192030085,-244,20220929,13200,SETTLED,-39,0.00,0.00,00,...,75445502272207879275172,415800511373,NaN,C,-244.00,-39.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,20220930
3,07927517,5579079046,-52,20220929,4000,SETTLED,-8,0.00,0.00,00,...,75445502272528679275173,252660087696,NaN,D,-52.00,-8.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,20220930
4,07927517,5349261349,-1300,20220929,100000,SETTLED,-208,0.00,0.00,00,...,75445502272386379275179,967820103687,NaN,D,"-1,300.00",-208.00,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,20220930

In [15]:
sftp['transaction_type'].unique()

array(['SETTLED', 'REFUNDED', 'CHARGE_BACK'], dtype=object)

In [16]:
sftp['transaction_date'] = pd.to_datetime(sftp['transaction_date'], format='%Y%m%d').dt.date
sftp['deposit_date'] = pd.to_datetime(sftp['deposit_date'], format='%Y%m%d').dt.date

In [17]:
sftp['transaction_date'] = pd.to_datetime(sftp['transaction_date'])
sftp['deposit_date'] = pd.to_datetime(sftp['deposit_date'])

In [18]:
sftp['gross_amount'] = sftp['gross_amount']/100
sftp['commisions'] = sftp['commisions']/100
sftp['tax'] = sftp['tax']/100
sftp['installments_fees'] = sftp['installments_fees']/100
sftp['installments_tax'] = sftp['installments_tax']/100
sftp['acquirer_commision'] = sftp['acquirer_commision']/100
sftp['acquirer_tax'] = sftp['acquirer_tax']/100
sftp.loc[sftp['transaction_type'] != 'SETTLED', 'gross_amount'] = sftp['gross_amount']*-1
sftp['LAST2_SFTP'] = sftp['card'].str[-2:].astype(str)
sftp['BIN_SFTP'] = sftp['card'].str[:6].astype(str)
sftp['INDEX_TOTAL'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['INDEX_TOTAL_XPAY'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['order_id_xpay'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['INDEX_COD_AUTH'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['codigo_autorizacion'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['order_id'].fillna('NO EXISTE EN SFTP',inplace=True)
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
0,07927517,4027665074,-2.47,2022-09-29,190.00,SETTLED,-0.40,0.00,0.00,00,...,-0.40,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,2022-09-30,74,402766,402766_74_553743879819_190.0,402766_74_nan_190.0,402766_74_370750_190.0
1,07927517,4152313826,-0.69,2022-09-29,53.00,SETTLED,-0.11,0.00,0.00,00,...,-0.11,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,2022-09-30,26,415231,415231_26_058146201172_53.0,415231_26_nan_53.0,415231_26_443828_53.0
2,07927517,5192030085,-2.44,2022-09-29,132.00,SETTLED,-0.39,0.00,0.00,00,...,-0.39,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,2022-09-30,85,519203,519203_85_415800511373_132.0,519203_85_nan_132.0,519203_85_430693_132.0
3,07927517,5579079046,-0.52,2022-09-29,40.00,SETTLED,-0.08,0.00,0.00,00,...,-0.08,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,2022-09-30,46,557907,557907_46_252660087696_40.0,557907_46_nan_40.0,557907_46_004702_40.0
4,07927517,5349261349,-13.00,2022-09-29,"1,000.00",SETTLED,-2.08,0.00,0.00,00,...,-2.08,PAYCLIP_Settlement_01102022_V1.csv,2022-10-01,October,2022-09-30,49,534926,534926_49_967820103687_1000.0,534926_49_nan_1000.0,534926_49_467709_1000.0

In [19]:
sftp.shape

(24548031, 27)

In [20]:
sftp['affiliation_sftp'].fillna('NULL',inplace=True)

# DATA POR AFILIACION

In [ ]:
sftp_por_afiliacion = sftp.loc[sftp['affiliation_sftp'].isin(['08380402'])]
sftp_por_afiliacion.head()

In [ ]:
sftp_por_afiliacion.shape

In [ ]:
sftp_por_afiliacion['affiliation_sftp'].unique()

In [ ]:
sftp_por_afiliacion.to_excel('MIT.xlsx',index=False)

# CHECKS

### QUERIES DB

In [21]:
ticket_zendesk = pd.read_csv('DISPUTAS BNTE 2023.03.13.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object
                                                  ,'last4':object,'order_id':object})
ticket_zendesk.columns = ticket_zendesk.columns.str.strip().str.lower()
ticket_zendesk['order_id_xpay'] = ticket_zendesk['order_id'] 
ticket_zendesk['INDEX_TOTAL'] = (ticket_zendesk['bin'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['last4'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['amount'].astype(str).replace(' ', '',regex=True))
ticket_zendesk['INDEX_TOTAL_XPAY'] = (ticket_zendesk['bin'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['last4'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['amount'].astype(str).replace(' ', '',regex=True))
ticket_zendesk.head()

,merchant_id,uuid,transaction_id,order_id,affiliation,affiliation_type,sub_affiliation,mcc,date_transaction,created_at,...,status_code,msi,device_id,clip_reader,status_msg,issuer,brand,order_id_xpay,INDEX_TOTAL,INDEX_TOTAL_XPAY
0,7a7215a8-f170-4925-82cd-6684620f2b09,0ae41d77-784a-4678-ba42-f4d7ede6a517,a9cbd44b-f839-45c2-9c46-9c4d8dac8557,000827275844,8380402,ECOMMERCE,0,5965,2022-10-13,2022-10-14 03:41:45,...,1,0,80010001,Clip Classic,Paid,BAJIO,VISA,000827275844,421003_8497_000827275844_7000.0,421003_8497_000827275844_7000.0
1,b7e16087-d9f4-4c85-954a-b24a1647d0c7,eeca8c69-0942-4173-9172-8f569bc02d27,e976c317-9245-4d6a-9eda-9ee7fc4a4332,527700286928,7927496,CARD_PRESENT,1723825,8021,2022-11-07,2022-11-07 20:41:37,...,3,0,A36884000409F85FFE0906EB1C,Clip Plus 2,Approved. Received and Discarded AI Cancel.,NU BN SERVICIOS MEXICO,MASTERCARD,527700286928,526777_9347_527700286928_630.0,526777_9347_527700286928_630.0
2,db92e68a-1acb-4738-a299-59205688e6f8,3bcb8a81-01ff-421b-a709-71706871b2a5,cdb8c840-eb53-473b-8df4-3702518b0b59,108182248360,7927515,CARD_PRESENT,1233083,5912,2022-12-03,2022-12-03 21:33:23,...,3,0,N500W132393,Clip Total,Approved. Received and Discarded AI Cancel.,NU BN SERVICIOS MEXICO,MASTERCARD,108182248360,526777_0404_108182248360_268.0,526777_0404_108182248360_268.0
3,b69d36ec-9b1d-4b59-9875-f452a56e2c0a,357ea3fe-882f-4cdf-bb0d-83eff6bf9660,fe8777a9-8d86-4fc2-8659-3fcbe69761ea,407906785912,7927517,CARD_PRESENT,1935256,5814,2023-02-22,2023-02-23 03:09:39,...,-3,0,N500W4L2821,Clip Total,Declined,BANCOPPEL,VISA,407906785912,426807_7217_407906785912_284.0,426807_7217_407906785912_284.0
4,a5b2fd28-4316-42bd-955f-bb93ad1f7542,75a8c5ee-2db7-4da5-bb30-b6b3f1783eb8,4f8f3b32-a375-4b29-a39d-e9f3c38d7711,000210047488,8380402,ECOMMERCE,0,5651,2023-02-26,2023-02-26 19:14:01,...,-6,0,80010001,Clip Classic,Cancel Error,BANREGIO,VISA,000210047488,474175_8914_000210047488_670.0,474175_8914_000210047488_670.0

In [22]:
ticket_zendesk.shape

(5, 27)

In [23]:
ticket_zendesk.columns

Index(['merchant_id', 'uuid', 'transaction_id', 'order_id', 'affiliation',
       'affiliation_type', 'sub_affiliation', 'mcc', 'date_transaction',
       'created_at', 'updated_at', 'psp', 'amount', 'clave_autorizacion',
       'bin', 'receipt_no', 'last4', 'status_code', 'msi', 'device_id',
       'clip_reader', 'status_msg', 'issuer', 'brand', 'order_id_xpay',
       'INDEX_TOTAL', 'INDEX_TOTAL_XPAY'],
      dtype='object')

### FILES DE AUDITORIA

In [ ]:
ticket_zendesk = pd.read_excel('AUDITORIA_DICIEMBRE_TXN_2021.xlsx',converters={'TRANSACTION_AMOUNT':float,'CLAVE_AUTORIZACION': str,
                                                                                'BIN':str,'LAST4':str,'ORDER_ID':str})
ticket_zendesk.columns = ticket_zendesk.columns.str.strip().str.lower() 
ticket_zendesk['INDEX_TOTAL'] = (ticket_zendesk['bin'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['last4'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['transaction_amount'].astype(str).replace(' ', '',regex=True))
ticket_zendesk['INDEX_TOTAL_XPAY'] = (ticket_zendesk['bin'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['last4'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['transaction_amount'].astype(str).replace(' ', '',regex=True))
ticket_zendesk.head()

In [ ]:
ticket_zendesk.shape

## EXTRACCIÓN DE ORDER_ID

In [24]:
ticket_zendesk['psp'].unique()

array(['MIT-3DS', 'PROSA'], dtype=object)

In [25]:
ticket_zendesk['status_code'].unique()

array([ 1,  3, -3, -6], dtype=int64)

In [26]:
ticket_zendesk['order_id_busqueda'] = "'"+ticket_zendesk['order_id'].replace(' ', '',regex=True)+"',"
print (ticket_zendesk['order_id_busqueda'].to_string(index=False))

'000827275844',
'527700286928',
'108182248360',
'407906785912',
'000210047488',

# IMPORTANTE: REVISAR A QUE PSP CORRESPONDE EL ORDER ID (PROSA O XPAY)

In [27]:
# select columns by name
check_txn = sftp[(sftp['order_id'].isin([
'000827275844',
'527700286928',
'108182248360',
'407906785912',
'000210047488'])) | (sftp['order_id_xpay'].isin([
'000827275844',
'527700286928',
'108182248360',
'407906785912',
'000210047488']))]
# check_txn = sftp[sftp['ECI'].isin(['74518990297102774892283'])]
# check_txn = sftp[sftp['order_id'] == '082566136893']
# check_txn = sftp[sftp['order_id_xpay'].isin(['223432604325'])]
# check_txn = sftp[(sftp.order_id == ('470520706509')) | (sftp.order_id ==('684089225828'))]
# check_txn = sftp[(sftp.CONCAT_2 == ('4388-2460.0')) | (sftp.CONCAT_2 == ('4388--2460.0'))]
# check_txn = sftp[(sftp.CONCAT_3 == ('314771-2718-295.0')) | (sftp.CONCAT_3 == ('314771-2718--295.0'))]
# check_txn = sftp[(sftp['LAST4'] == '7206')]
# check_txn.sort_values(by=['order_id','Fecha txn'],inplace=True)
check_txn.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
5583064,08380402,4210030097,-94.50,2022-10-13,"7,000.00",SETTLED,-15.12,0.00,0.00,00,...,-15.12,PAYCLIP_Settlement_15102022_V1.csv,2022-10-15,October,2022-10-14,97,421003,421003_97_000827275844_7000.0,421003_97_nan_7000.0,421003_97_023699_7000.0
15929253,07927496,5267770047,-11.66,2022-11-07,630.00,SETTLED,-1.87,0.00,0.00,00,...,-1.87,PAYCLIP_Settlement_09112022_V1.csv,2022-11-09,November,2022-11-08,47,526777,526777_47_527700286928_630.0,526777_47_nan_630.0,526777_47_219818_630.0

In [28]:
check_txn.shape

(2, 27)

In [29]:
# check_txn.to_excel('eci.xlsx')

In [30]:
# writer = pd.ExcelWriter('EXAMPLE_SFTP(2).xlsx', engine='openpyxl', options={'encoding':'utf-8'})
# check_txn.to_excel(writer, sheet_name='MATCH TXN 1', index=False)
# ticket_zendesk.to_excel(writer, sheet_name='TICKET', index=False)
# writer.save()
# writer.close()

# MATCH DEPENDIENDO DEL PSP (INDEX_TOTAL O INDEX_TOTAL_XPAY)

In [31]:
match = ticket_zendesk.merge(check_txn[['order_id','affiliation_sftp','transaction_date','transaction_type','INDEX_TOTAL',
                                        'order_id_xpay','codigo_autorizacion','deposit_date','gross_amount']],on='order_id',how='left')
match_2 = ticket_zendesk.merge(check_txn[['order_id_xpay','affiliation_sftp','transaction_date','transaction_type','order_id',
                                          'INDEX_TOTAL_XPAY','codigo_autorizacion','deposit_date','gross_amount']],on='order_id_xpay',
                               how='left')
# match = check_txn.merge(ticket_zendesk[['order_id','ISSUER','BRAND']],on='order_id',how='left')
# match['transaction_id'].fillna('NO MATCH',inplace=True)
# match['status_code'].fillna('NO MATCH',inplace=True)
# match['status_msg'].fillna('NO MATCH',inplace=True)

In [32]:
match.head()

,merchant_id,uuid,transaction_id,order_id,affiliation,affiliation_type,sub_affiliation,mcc,date_transaction,created_at,...,INDEX_TOTAL_XPAY,order_id_busqueda,affiliation_sftp,transaction_date,transaction_type,INDEX_TOTAL_y,order_id_xpay_y,codigo_autorizacion,deposit_date,gross_amount
0,7a7215a8-f170-4925-82cd-6684620f2b09,0ae41d77-784a-4678-ba42-f4d7ede6a517,a9cbd44b-f839-45c2-9c46-9c4d8dac8557,000827275844,8380402,ECOMMERCE,0,5965,2022-10-13,2022-10-14 03:41:45,...,421003_8497_000827275844_7000.0,"'000827275844',",08380402,2022-10-13,SETTLED,421003_97_000827275844_7000.0,NaN,023699,2022-10-14,"7,000.00"
1,b7e16087-d9f4-4c85-954a-b24a1647d0c7,eeca8c69-0942-4173-9172-8f569bc02d27,e976c317-9245-4d6a-9eda-9ee7fc4a4332,527700286928,7927496,CARD_PRESENT,1723825,8021,2022-11-07,2022-11-07 20:41:37,...,526777_9347_527700286928_630.0,"'527700286928',",07927496,2022-11-07,SETTLED,526777_47_527700286928_630.0,NaN,219818,2022-11-08,630.00
2,db92e68a-1acb-4738-a299-59205688e6f8,3bcb8a81-01ff-421b-a709-71706871b2a5,cdb8c840-eb53-473b-8df4-3702518b0b59,108182248360,7927515,CARD_PRESENT,1233083,5912,2022-12-03,2022-12-03 21:33:23,...,526777_0404_108182248360_268.0,"'108182248360',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN
3,b69d36ec-9b1d-4b59-9875-f452a56e2c0a,357ea3fe-882f-4cdf-bb0d-83eff6bf9660,fe8777a9-8d86-4fc2-8659-3fcbe69761ea,407906785912,7927517,CARD_PRESENT,1935256,5814,2023-02-22,2023-02-23 03:09:39,...,426807_7217_407906785912_284.0,"'407906785912',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN
4,a5b2fd28-4316-42bd-955f-bb93ad1f7542,75a8c5ee-2db7-4da5-bb30-b6b3f1783eb8,4f8f3b32-a375-4b29-a39d-e9f3c38d7711,000210047488,8380402,ECOMMERCE,0,5651,2023-02-26,2023-02-26 19:14:01,...,474175_8914_000210047488_670.0,"'000210047488',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN

In [33]:
match_2.head()

,merchant_id,uuid,transaction_id,order_id_x,affiliation,affiliation_type,sub_affiliation,mcc,date_transaction,created_at,...,INDEX_TOTAL_XPAY_x,order_id_busqueda,affiliation_sftp,transaction_date,transaction_type,order_id_y,INDEX_TOTAL_XPAY_y,codigo_autorizacion,deposit_date,gross_amount
0,7a7215a8-f170-4925-82cd-6684620f2b09,0ae41d77-784a-4678-ba42-f4d7ede6a517,a9cbd44b-f839-45c2-9c46-9c4d8dac8557,000827275844,8380402,ECOMMERCE,0,5965,2022-10-13,2022-10-14 03:41:45,...,421003_8497_000827275844_7000.0,"'000827275844',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN
1,b7e16087-d9f4-4c85-954a-b24a1647d0c7,eeca8c69-0942-4173-9172-8f569bc02d27,e976c317-9245-4d6a-9eda-9ee7fc4a4332,527700286928,7927496,CARD_PRESENT,1723825,8021,2022-11-07,2022-11-07 20:41:37,...,526777_9347_527700286928_630.0,"'527700286928',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN
2,db92e68a-1acb-4738-a299-59205688e6f8,3bcb8a81-01ff-421b-a709-71706871b2a5,cdb8c840-eb53-473b-8df4-3702518b0b59,108182248360,7927515,CARD_PRESENT,1233083,5912,2022-12-03,2022-12-03 21:33:23,...,526777_0404_108182248360_268.0,"'108182248360',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN
3,b69d36ec-9b1d-4b59-9875-f452a56e2c0a,357ea3fe-882f-4cdf-bb0d-83eff6bf9660,fe8777a9-8d86-4fc2-8659-3fcbe69761ea,407906785912,7927517,CARD_PRESENT,1935256,5814,2023-02-22,2023-02-23 03:09:39,...,426807_7217_407906785912_284.0,"'407906785912',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN
4,a5b2fd28-4316-42bd-955f-bb93ad1f7542,75a8c5ee-2db7-4da5-bb30-b6b3f1783eb8,4f8f3b32-a375-4b29-a39d-e9f3c38d7711,000210047488,8380402,ECOMMERCE,0,5651,2023-02-26,2023-02-26 19:14:01,...,474175_8914_000210047488_670.0,"'000210047488',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN

In [34]:
match.shape

(5, 36)

In [35]:
match_2.shape

(5, 36)

In [36]:
match_final = match[['merchant_id','transaction_id','status_code','order_id','order_id_xpay_x','codigo_autorizacion',
                     'affiliation_sftp','transaction_date','transaction_type','deposit_date','gross_amount']]

In [37]:
match_final_2 = match_2[['merchant_id','transaction_id','status_code','order_id_x','order_id_xpay','codigo_autorizacion',
                     'affiliation_sftp','transaction_date','transaction_type','deposit_date','gross_amount']]

In [38]:
writer = pd.ExcelWriter('DATA FINAL DISPUTAS BNTE 2023.03.13-1.xlsx',
                        engine='xlsxwriter',
                        engine_kwargs={'options': {'encoding':'utf-8'}})
match_final.to_excel(writer, sheet_name='MATCH_FINAL', index=False)
match_final_2.to_excel(writer, sheet_name='MATCH_FINAL_2', index=False)
match.to_excel(writer, sheet_name='MATCH', index=False)
match_2.to_excel(writer, sheet_name='MATCH_2', index=False)
writer.close()