In [1]:
import pandas as pd
import numpy as np
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# DISPERSIONES FP

In [2]:
fp_files_1 = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\07. JULIO\ARCHIVO DISPERSIONES FP\Dispersión-FP*.xlsx', recursive=False)
fp_files_1

['C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-01.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-02.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-03.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-04.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-05.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-06.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-07.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-08.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-09.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-10.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-11.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-12.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\07. JULIO\\ARCHIVO DISPERSIONES FP\\Dispersión-FP 2022-07-13.xlsx']

In [3]:
pagos_2 = pd.concat([pd.read_excel(f,sheet_name='FAST PAYMENTS').assign(file_name=os.path.basename(f)) for f in fp_files_1])
pagos_2['date_file'] = pagos_2["file_name"].str[-15:-4]
pagos_2['date_file']= pd.to_datetime(pagos_2['date_file']) 
pagos_2.sort_values(by=['date_file'],ascending=True,inplace=True)
pagos_2['report_date_local']= pd.to_datetime(pagos_2['report_date_local']) 
pagos_2.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor,file_name,date_file
0,INSTANT,899c66ea-5865-487a-bdd1-b64a6f0141c3,Stero Boutique,steroboutiquemxli@outlook.com,N4P3RJ77S,2022-06-17,"3,084.58",Reprogramación,BBVA BANCOMER,Luis Humberto Rodriguez Armenta,12180015897982315,ERROR,NaN,09:00,SANTANDER,Dispersión-FP 2022-07-01.xlsx,2022-07-01
3751,INSTANT,2222c2fc-4efd-4c4f-8709-db80db4885ce,Las Mejores,rufis.716@gmail.com,FLP4DMV3W,2022-07-01,"1,571.51",Pago del día,ASP INTEGRA OPC,Guadalupe Monserrat Garcia Castro,659802020000458317,PAID,"2022-07-01,181BC1B32DCC05EC,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01
3750,INSTANT,21de0a58-362a-4d50-8fac-77260e6423ce,Six Chavarria,david_30ag90@hotmail.com,JH3XHQ8P5,2022-07-01,14.37,Pago del día,ASP INTEGRA OPC,David Diego Hilario,659802020000177478,PAID,"2022-07-01,181BC1B3221699FE,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01
3749,INSTANT,21d752cd-acd5-47ac-929e-284a4c0e2dcd,Don regio cortes,lalotamez5@gmail.com,QSJNHG984,2022-07-01,762.58,Pago del día,ASP INTEGRA OPC,Gerardo Tamez Garza,659802020000494672,PAID,"2022-07-01,181BC1B3A5D362B8,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01
3748,INSTANT,2192f095-9279-49aa-8929-29e63c4d9aee,Centro Holistiko,jozfort.ju@gmail.com,DDLFH2FKK,2022-07-01,"1,274.46",Pago del día,ASP INTEGRA OPC,Jose Fortino Juarez Carmona,659802020000500744,PAID,"2022-07-01,181BC1B3357BCCD0,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01

In [4]:
pagos_2.shape

(62730, 17)

In [5]:
pagos_2['status'].unique()

array(['ERROR', 'PAID', 'NEW'], dtype=object)

In [6]:
pagos_2_paid = pagos_2[(pagos_2['status'].isin(['PAID']))]
pagos_2_paid.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor,file_name,date_file
3751,INSTANT,2222c2fc-4efd-4c4f-8709-db80db4885ce,Las Mejores,rufis.716@gmail.com,FLP4DMV3W,2022-07-01,"1,571.51",Pago del día,ASP INTEGRA OPC,Guadalupe Monserrat Garcia Castro,659802020000458317,PAID,"2022-07-01,181BC1B32DCC05EC,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01
3750,INSTANT,21de0a58-362a-4d50-8fac-77260e6423ce,Six Chavarria,david_30ag90@hotmail.com,JH3XHQ8P5,2022-07-01,14.37,Pago del día,ASP INTEGRA OPC,David Diego Hilario,659802020000177478,PAID,"2022-07-01,181BC1B3221699FE,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01
3749,INSTANT,21d752cd-acd5-47ac-929e-284a4c0e2dcd,Don regio cortes,lalotamez5@gmail.com,QSJNHG984,2022-07-01,762.58,Pago del día,ASP INTEGRA OPC,Gerardo Tamez Garza,659802020000494672,PAID,"2022-07-01,181BC1B3A5D362B8,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01
3748,INSTANT,2192f095-9279-49aa-8929-29e63c4d9aee,Centro Holistiko,jozfort.ju@gmail.com,DDLFH2FKK,2022-07-01,"1,274.46",Pago del día,ASP INTEGRA OPC,Jose Fortino Juarez Carmona,659802020000500744,PAID,"2022-07-01,181BC1B3357BCCD0,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01
3747,INSTANT,218216f4-7d79-410b-8064-dd74f5fb6a83,Abarrotes ABNER,zurc_93@hotmail.com,VZ9RVTTGX,2022-07-01,40.57,Pago del día,ASP INTEGRA OPC,Abner Cruz Rodriguez,659802020000048536,PAID,"2022-07-01,181BC1B3506ACDA3,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01

In [7]:
pagos_2_paid.shape

(61382, 17)

# READING FILES CSV

In [8]:
# all_mov_csv = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\EDO CTA BANAMEX\202*\**\TX-NV-P*.csv', recursive=False)

# READING FILES XLSX

In [9]:
all_mov_xlsx = glob.glob(r'G:\My Drive\2.-CONCILIACIONES Y POLIZA\EDO CTA BANAMEX\2022\**\TX-NV-P*.xlsx', recursive=False)
all_mov_xlsx

['G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_21_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_01_Abril_04_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_05_Abril_06_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_07_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_08_Abril_10_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_11_Abrill_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_12_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_13_Abril_17_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_18_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_19_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_20_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_22_Abril_24_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_25_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_26_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_27_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_29_Abril_01_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\04. ABRIL\\TX-NV-Payclip_3261_28_Abril_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\01. ENERO\\TX-NV-Payclip_3261_27_Enero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\01. ENERO\\TX-NV-Payclip_3261_28_Enero_30_Enero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\01. ENERO\\TX-NV-Payclip_3261_31_Enero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_01_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_02_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_03_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_04_Febrero_07_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_08_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_09_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_10_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_11_Febrero_13_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_14_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_15_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_16_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_17_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_18_Febrero_20_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_21_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_22_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_23_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_24_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_25_Febero_27_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\02. FEBRERO\\TX-NV-Payclip_3261_28_Febrero_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_01_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_02_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_03_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_04_Marzo_06_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_07_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_08_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_09_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_10_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_11_Marzo_13_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_14_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\03. MARZO\\TX-NV-Payclip_3261_15_Marzo_31_Marzo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\05. MAYO\\TX-NV-Payclip_3261_02_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\05. MAYO\\TX-NV-Payclip_3261_03_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\05. MAYO\\TX-NV-Payclip_3261_04_Mayo_05_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\05. MAYO\\TX-NV-Payclip_3261_05_Mayo_10_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\05. MAYO\\TX-NV-Payclip_3261_11_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\05. MAYO\\TX-NV-Payclip_3261_12_Mayo_22_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\05. MAYO\\TX-NV-Payclip_3261_23_Mayo_24_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\05. MAYO\\TX-NV-Payclip_3261_25_Mayo_2022.xlsx',
 'G:\\My Drive\\2.-CONCILIACIONES Y POLIZA\\EDO CTA BANAMEX\\2022\\07. JULIO\\TX-NV-Payclip_3261_01_Julio_13_Julio_2022.xlsx']

# DATA EDO CTA

### CSV

In [10]:
# edo_cta_1 = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in all_mov_csv])
# edo_cta_1.reset_index(inplace=True)
# edo_cta_1.head()

In [11]:
# edo_cta_1.shape

### XLSX

In [12]:
edo_cta_2 = pd.concat([pd.read_excel(f).assign(file_name=os.path.basename(f)) for f in all_mov_xlsx])
edo_cta_2.reset_index(inplace=True)
edo_cta_2.head()

,index,Instrument Type,Operation Date,Budget Code,Local Code,Bank Reference,Description,Description 1,Credit,Debit,Opening Balance Amount,Closing Balance Amount,file_name,Bank Account Number,Bank Group,Description Local Code,Value Date,Amount,Instrument Code,BTID
0,0,Merchants,2022-04-21,Merchant Outflow,699,1804EF7CF92ABC7D,TDY956Q5WFR:INTERBANKENDT:20220421TRID:TDY956Q...,NaN,0.00,-157.63,"2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,1,Merchants,2022-04-21,Merchant Outflow,699,1804EF7CFEDFA64F,9Y35Y6NM8FR:INTERBANKENDT:20220421TRID:9Y35Y6N...,NaN,0.00,-199.31,"2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2,2,Merchants,2022-04-21,Merchant Outflow,699,1804EF7D035A60FB,9N4YX4GH8FR:INTERBANKENDT:20220421TRID:9N4YX4G...,NaN,0.00,-100.62,"2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,3,Merchants,2022-04-21,Merchant Outflow,699,1804EF7DE993C6BC,8JK8QVV75FR:INTERBANKENDT:20220421TRID:8JK8QVV...,NaN,0.00,-948.66,"2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,4,Merchants,2022-04-21,Merchant Outflow,699,1804EF7DEA4B8BF9,77D64BXNYFR:INTERBANKENDT:20220421TRID:77D64BX...,NaN,0.00,"-1,149.89","2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [13]:
edo_cta_2.shape

(417312, 20)

### CONSOLIDADO

In [14]:
edo_cta = pd.concat([edo_cta_2])
edo_cta.head()

,index,Instrument Type,Operation Date,Budget Code,Local Code,Bank Reference,Description,Description 1,Credit,Debit,Opening Balance Amount,Closing Balance Amount,file_name,Bank Account Number,Bank Group,Description Local Code,Value Date,Amount,Instrument Code,BTID
0,0,Merchants,2022-04-21,Merchant Outflow,699,1804EF7CF92ABC7D,TDY956Q5WFR:INTERBANKENDT:20220421TRID:TDY956Q...,NaN,0.00,-157.63,"2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,1,Merchants,2022-04-21,Merchant Outflow,699,1804EF7CFEDFA64F,9Y35Y6NM8FR:INTERBANKENDT:20220421TRID:9Y35Y6N...,NaN,0.00,-199.31,"2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2,2,Merchants,2022-04-21,Merchant Outflow,699,1804EF7D035A60FB,9N4YX4GH8FR:INTERBANKENDT:20220421TRID:9N4YX4G...,NaN,0.00,-100.62,"2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,3,Merchants,2022-04-21,Merchant Outflow,699,1804EF7DE993C6BC,8JK8QVV75FR:INTERBANKENDT:20220421TRID:8JK8QVV...,NaN,0.00,-948.66,"2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,4,Merchants,2022-04-21,Merchant Outflow,699,1804EF7DEA4B8BF9,77D64BXNYFR:INTERBANKENDT:20220421TRID:77D64BX...,NaN,0.00,"-1,149.89","2,469,138.91","6,677,381.02",TX-NV-Payclip_3261_21_Abril_2022.xlsx,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [15]:
edo_cta.shape

(417312, 20)

In [16]:
edo_cta_all = edo_cta [['Bank Account Number','Operation Date','Value Date','Bank Reference','Description',
                       'Credit','Debit','Amount','Budget Code','file_name']]
edo_cta_all['Bank Reference'].fillna('blank_spaces',inplace=True)
edo_cta_all.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15552\1106876473.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edo_cta_all['Bank Reference'].fillna('blank_spaces',inplace=True)

,Bank Account Number,Operation Date,Value Date,Bank Reference,Description,Credit,Debit,Amount,Budget Code,file_name
0,NaN,2022-04-21,NaT,1804EF7CF92ABC7D,TDY956Q5WFR:INTERBANKENDT:20220421TRID:TDY956Q...,0.00,-157.63,NaN,Merchant Outflow,TX-NV-Payclip_3261_21_Abril_2022.xlsx
1,NaN,2022-04-21,NaT,1804EF7CFEDFA64F,9Y35Y6NM8FR:INTERBANKENDT:20220421TRID:9Y35Y6N...,0.00,-199.31,NaN,Merchant Outflow,TX-NV-Payclip_3261_21_Abril_2022.xlsx
2,NaN,2022-04-21,NaT,1804EF7D035A60FB,9N4YX4GH8FR:INTERBANKENDT:20220421TRID:9N4YX4G...,0.00,-100.62,NaN,Merchant Outflow,TX-NV-Payclip_3261_21_Abril_2022.xlsx
3,NaN,2022-04-21,NaT,1804EF7DE993C6BC,8JK8QVV75FR:INTERBANKENDT:20220421TRID:8JK8QVV...,0.00,-948.66,NaN,Merchant Outflow,TX-NV-Payclip_3261_21_Abril_2022.xlsx
4,NaN,2022-04-21,NaT,1804EF7DEA4B8BF9,77D64BXNYFR:INTERBANKENDT:20220421TRID:77D64BX...,0.00,"-1,149.89",NaN,Merchant Outflow,TX-NV-Payclip_3261_21_Abril_2022.xlsx

In [17]:
edo_cta_all['Budget Code'].unique()

array(['Merchant Outflow', 'Merchant payments rejection', 'Other revenue',
       'Payclip Funding', 'Bank fees per ME transaction',
       'VAT charged per ME transactions', nan, 'Bank fees',
       "Bank fees per TPV'S transactions",
       "VAT Bank fees per TPV's transactions", 'Profesional Services',
       'WhoT', 'FX Deals', 'Payroll Payments', 'Merchant Inflow',
       'Merchant chargeback', 'VAT Bank fees', 'Investment intrests',
       'Income TAX', 'Readers', 'Intercompany ME Funding',
       'Processor Inflows', 'Bank fees per ME transactions',
       'VAT Bank fees per ME transactions'], dtype=object)

In [18]:
edo_cta_all_dev = edo_cta_all[(edo_cta_all['Budget Code'].isin(['Merchant payments rejection']))]
edo_cta_all_dev.head()

,Bank Account Number,Operation Date,Value Date,Bank Reference,Description,Credit,Debit,Amount,Budget Code,file_name
77,NaN,2022-04-21,NaT,1804EF79A8F0D1DE,230070711121FR:OPERATION REVERSALENDT:20220421...,273.93,0.00,NaN,Merchant payments rejection,TX-NV-Payclip_3261_21_Abril_2022.xlsx
78,NaN,2022-04-21,NaT,1804EF7E8146F52C,238010711125FR:OPERATION REVERSALENDT:20220421...,179.19,0.00,NaN,Merchant payments rejection,TX-NV-Payclip_3261_21_Abril_2022.xlsx
79,NaN,2022-04-21,NaT,1804EF7E83881C0D,238030711123FR:OPERATION REVERSALENDT:20220421...,"1,964.39",0.00,NaN,Merchant payments rejection,TX-NV-Payclip_3261_21_Abril_2022.xlsx
366,NaN,2022-04-21,NaT,1804EF7E1BB642CB,236780711126FR:OPERATION REVERSALENDT:20220421...,92.95,0.00,NaN,Merchant payments rejection,TX-NV-Payclip_3261_21_Abril_2022.xlsx
367,NaN,2022-04-21,NaT,1804EF7CC6502782,232710711124FR:OPERATION REVERSALENDT:20220421...,458.03,0.00,NaN,Merchant payments rejection,TX-NV-Payclip_3261_21_Abril_2022.xlsx

In [19]:
edo_cta_all_dev.shape

(6395, 10)

# CRUCE DISPERSIONES VS MOVIMIENTOS BANCARIOS

In [20]:
split = pagos_2_paid["CEP"].str.split(",",n=8,expand=True)
split.head()

               0                 1      2      3                   4        5
3751  2022-07-01  181BC1B32DCC05EC  40002  90659  659802020000458317  1571.51
3750  2022-07-01  181BC1B3221699FE  40002  90659  659802020000177478    14.37
3749  2022-07-01  181BC1B3A5D362B8  40002  90659  659802020000494672   762.58
3748  2022-07-01  181BC1B3357BCCD0  40002  90659  659802020000500744  1274.46
3747  2022-07-01  181BC1B3506ACDA3  40002  90659  659802020000048536    40.57

In [21]:
pagos_2_paid["Bank Reference"] = split[1]
pagos_2_paid.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15552\1453815343.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pagos_2_paid["Bank Reference"] = split[1]

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor,file_name,date_file,Bank Reference
3751,INSTANT,2222c2fc-4efd-4c4f-8709-db80db4885ce,Las Mejores,rufis.716@gmail.com,FLP4DMV3W,2022-07-01,"1,571.51",Pago del día,ASP INTEGRA OPC,Guadalupe Monserrat Garcia Castro,659802020000458317,PAID,"2022-07-01,181BC1B32DCC05EC,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B32DCC05EC
3750,INSTANT,21de0a58-362a-4d50-8fac-77260e6423ce,Six Chavarria,david_30ag90@hotmail.com,JH3XHQ8P5,2022-07-01,14.37,Pago del día,ASP INTEGRA OPC,David Diego Hilario,659802020000177478,PAID,"2022-07-01,181BC1B3221699FE,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B3221699FE
3749,INSTANT,21d752cd-acd5-47ac-929e-284a4c0e2dcd,Don regio cortes,lalotamez5@gmail.com,QSJNHG984,2022-07-01,762.58,Pago del día,ASP INTEGRA OPC,Gerardo Tamez Garza,659802020000494672,PAID,"2022-07-01,181BC1B3A5D362B8,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B3A5D362B8
3748,INSTANT,2192f095-9279-49aa-8929-29e63c4d9aee,Centro Holistiko,jozfort.ju@gmail.com,DDLFH2FKK,2022-07-01,"1,274.46",Pago del día,ASP INTEGRA OPC,Jose Fortino Juarez Carmona,659802020000500744,PAID,"2022-07-01,181BC1B3357BCCD0,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B3357BCCD0
3747,INSTANT,218216f4-7d79-410b-8064-dd74f5fb6a83,Abarrotes ABNER,zurc_93@hotmail.com,VZ9RVTTGX,2022-07-01,40.57,Pago del día,ASP INTEGRA OPC,Abner Cruz Rodriguez,659802020000048536,PAID,"2022-07-01,181BC1B3506ACDA3,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B3506ACDA3

In [22]:
pagos_2_paid.shape

(61382, 18)

In [23]:
cruce_1 = pagos_2_paid.merge(edo_cta_all_dev[['Bank Reference','Operation Date','Value Date','Description','Credit']],
                             on='Bank Reference',how='left')
cruce_1['Description'].fillna('sin_devolucion',inplace=True)
cruce_1.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,...,CEP,Time,Banco_emisor,file_name,date_file,Bank Reference,Operation Date,Value Date,Description,Credit
0,INSTANT,2222c2fc-4efd-4c4f-8709-db80db4885ce,Las Mejores,rufis.716@gmail.com,FLP4DMV3W,2022-07-01,"1,571.51",Pago del día,ASP INTEGRA OPC,Guadalupe Monserrat Garcia Castro,...,"2022-07-01,181BC1B32DCC05EC,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B32DCC05EC,NaT,NaT,sin_devolucion,NaN
1,INSTANT,21de0a58-362a-4d50-8fac-77260e6423ce,Six Chavarria,david_30ag90@hotmail.com,JH3XHQ8P5,2022-07-01,14.37,Pago del día,ASP INTEGRA OPC,David Diego Hilario,...,"2022-07-01,181BC1B3221699FE,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B3221699FE,NaT,NaT,sin_devolucion,NaN
2,INSTANT,21d752cd-acd5-47ac-929e-284a4c0e2dcd,Don regio cortes,lalotamez5@gmail.com,QSJNHG984,2022-07-01,762.58,Pago del día,ASP INTEGRA OPC,Gerardo Tamez Garza,...,"2022-07-01,181BC1B3A5D362B8,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B3A5D362B8,NaT,NaT,sin_devolucion,NaN
3,INSTANT,2192f095-9279-49aa-8929-29e63c4d9aee,Centro Holistiko,jozfort.ju@gmail.com,DDLFH2FKK,2022-07-01,"1,274.46",Pago del día,ASP INTEGRA OPC,Jose Fortino Juarez Carmona,...,"2022-07-01,181BC1B3357BCCD0,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B3357BCCD0,NaT,NaT,sin_devolucion,NaN
4,INSTANT,218216f4-7d79-410b-8064-dd74f5fb6a83,Abarrotes ABNER,zurc_93@hotmail.com,VZ9RVTTGX,2022-07-01,40.57,Pago del día,ASP INTEGRA OPC,Abner Cruz Rodriguez,...,"2022-07-01,181BC1B3506ACDA3,40002,90659,659802...",18:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC1B3506ACDA3,NaT,NaT,sin_devolucion,NaN

In [24]:
cruce_1.shape

(61382, 22)

In [25]:
cruce_1_final = cruce_1[(cruce_1['Description'] != 'sin_devolucion')]
cruce_1_final.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,...,CEP,Time,Banco_emisor,file_name,date_file,Bank Reference,Operation Date,Value Date,Description,Credit
2638,INSTANT,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,TBV3PT4JG,2022-05-22,767.55,Reprogramación,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,...,"2022-07-01,181BC9B4231B9623,40002,90659,659802...",20:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC9B4231B9623,2022-07-01,NaT,925850718224FR:OPERATION REVERSALENDT:20220701...,767.55
2641,INSTANT,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,4XKYPN5P8,2022-05-21,26.83,Reprogramación,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,...,"2022-07-01,181BC9B33EFE0E89,40002,90659,659802...",20:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC9B33EFE0E89,2022-07-01,NaT,923550718227FR:OPERATION REVERSALENDT:20220701...,26.83
2651,INSTANT,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,938TN57DC,2022-05-16,376.59,Reprogramación,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,...,"2022-07-01,181BC9B30EBA1BD1,40002,90659,659802...",20:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC9B30EBA1BD1,2022-07-01,NaT,922930718223FR:OPERATION REVERSALENDT:20220701...,376.59
2680,INSTANT,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,ZVZKMDNT2,2022-04-24,45.04,Reprogramación,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,...,"2022-07-01,181BC9B34C8E4C0F,40002,90659,659802...",20:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC9B34C8E4C0F,2022-07-01,NaT,923740718223FR:OPERATION REVERSALENDT:20220701...,45.04
2689,INSTANT,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,X8ZS6QDK5,2022-04-22,124.57,Reprogramación,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,...,"2022-07-01,181BC9B352F5DAED,40002,90659,659802...",20:00,BANAMEX,Dispersión-FP 2022-07-01.xlsx,2022-07-01,181BC9B352F5DAED,2022-07-01,NaT,923870718220FR:OPERATION REVERSALENDT:20220701...,124.57

In [26]:
cruce_1_final.shape

(42, 22)

In [29]:
sorted(cruce_1_final['file_name'].unique())

['Dispersión-FP 2022-07-01.xlsx',
 'Dispersión-FP 2022-07-04.xlsx',
 'Dispersión-FP 2022-07-05.xlsx',
 'Dispersión-FP 2022-07-06.xlsx',
 'Dispersión-FP 2022-07-07.xlsx',
 'Dispersión-FP 2022-07-08.xlsx',
 'Dispersión-FP 2022-07-12.xlsx',
 'Dispersión-FP 2022-07-13.xlsx']

In [30]:
grouped = cruce_1_final.groupby(cruce_1_final.file_name)

In [31]:
group_1 = grouped.get_group('Dispersión-FP 2022-07-01.xlsx')
group_2 = grouped.get_group('Dispersión-FP 2022-07-04.xlsx')
group_3 = grouped.get_group('Dispersión-FP 2022-07-05.xlsx')
group_4 = grouped.get_group('Dispersión-FP 2022-07-06.xlsx')
group_5 = grouped.get_group('Dispersión-FP 2022-07-07.xlsx')
group_6 = grouped.get_group('Dispersión-FP 2022-07-08.xlsx')
group_7 = grouped.get_group('Dispersión-FP 2022-07-12.xlsx')
group_8 = grouped.get_group('Dispersión-FP 2022-07-13.xlsx')
# group_9 = grouped.get_group('Dispersión-FP 2022-05-20.xlsx')
# group_10 = grouped.get_group('Dispersión-FP 2022-04-19.xlsx')
# group_11 = grouped.get_group('Dispersión-FP 2022-04-20.xlsx')
# group_12 = grouped.get_group('Dispersión-FP 2022-04-21.xlsx')
# group_13 = grouped.get_group('Dispersión-FP 2022-04-22.xlsx')
# group_14 = grouped.get_group('Dispersión-FP 2022-04-25.xlsx')
# group_15 = grouped.get_group('Dispersión-FP 2022-04-26.xlsx')
# group_16 = grouped.get_group('Dispersión-FP 2022-04-27.xlsx')
# group_17 = grouped.get_group('Dispersión-FP 2022-03-23.xlsx')
# group_18 = grouped.get_group('Dispersión-FP 2022-03-24.xlsx')
# group_19 = grouped.get_group('Dispersión-FP 2022-03-25.xlsx')
# group_20 = grouped.get_group('Dispersión-FP 2022-03-27.xlsx')
# group_21 = grouped.get_group('Dispersión-FP 2022-03-28.xlsx')
# group_22 = grouped.get_group('Dispersión-FP 2022-03-29.xlsx')
# group_23 = grouped.get_group('Dispersión-FP 2022-03-30.xlsx')
# group_24 = grouped.get_group('Dispersión-FP 2022-03-31.xlsx')

In [32]:
writer = pd.ExcelWriter('DEV EXT CITI JULIO 2022.xlsx',
                        engine='xlsxwriter',
                        engine_kwargs={'options': {'encoding':'utf-8'}})
group_1.to_excel(writer, sheet_name='2022.07.01', index=False)
group_2.to_excel(writer, sheet_name='2022.07.04', index=False)
group_3.to_excel(writer, sheet_name='2022.07.05', index=False)
group_4.to_excel(writer, sheet_name='2022.07.06', index=False)
group_5.to_excel(writer, sheet_name='2022.07.07', index=False)
group_6.to_excel(writer, sheet_name='2022.07.08', index=False)
group_7.to_excel(writer, sheet_name='2022.07.12', index=False)
group_8.to_excel(writer, sheet_name='2022.07.13', index=False)
# group_9.to_excel(writer, sheet_name='2022.05.20', index=False)
# group_10.to_excel(writer, sheet_name='2022.04.19', index=False)
# group_11.to_excel(writer, sheet_name='2022.04.20', index=False)
# group_12.to_excel(writer, sheet_name='2022.04.21', index=False)
# group_13.to_excel(writer, sheet_name='2022.04.22', index=False)
# group_14.to_excel(writer, sheet_name='2022.04.25', index=False)
# group_15.to_excel(writer, sheet_name='2022.04.26', index=False)
# group_16.to_excel(writer, sheet_name='2022.04.27', index=False)
# group_17.to_excel(writer, sheet_name='2022.03.23', index=False)
# group_18.to_excel(writer, sheet_name='2022.03.24', index=False)
# group_19.to_excel(writer, sheet_name='2022.03.25', index=False)
# group_20.to_excel(writer, sheet_name='2022.03.27', index=False)
# group_21.to_excel(writer, sheet_name='2022.03.28', index=False)
# group_22.to_excel(writer, sheet_name='2022.03.29', index=False)
# group_23.to_excel(writer, sheet_name='2022.03.30', index=False)
# group_24.to_excel(writer, sheet_name='2022.03.31', index=False)
writer.close()