In [1]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook
import glob
import os
from datetime import datetime
pd.options.display.float_format = '{:,.2f}'.format

# READING FILES

In [2]:
date_respuesta = '2022-06-26'
date_respuesta = pd.to_datetime(date_respuesta)

## RESPUESTAS FP

In [3]:
names_resp = ['report_id','status','report_date_local','amount','disbursement_batch_id','merchant_id','bank_account_number',
             'bank_name','bank_account_owner_name','execution_date','aplication_date','disbursement_tracking_key',
             'error_description','reference_number','cep']

In [4]:
rs = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\06. JUNIO\Respuesta-FP-BNTE*.xlsx', recursive=False)
rs

['C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\06. JUNIO\\Respuesta-FP-BNTE-1 2022-06-26.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\06. JUNIO\\Respuesta-FP-BNTE-2 2022-06-26.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\06. JUNIO\\Respuesta-FP-BNTE-3 2022-06-26.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\06. JUNIO\\Respuesta-FP-BNTE-4 2022-06-26.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\06. JUNIO\\Respuesta-FP-BNTE-5 2022-06-26.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\06. JUNIO\\Respuesta-FP-BNTE-6 2022-06-26.xlsx']

In [5]:
rs_concat = pd.concat([pd.read_excel(f,sheet_name='Report',names=names_resp,
                                     converters={'bank_account_number':str,'disbursement_tracking_key':str,'report_id':str})
                       .assign(file_name=os.path.basename(f)) for f in rs])
rs_concat.loc[rs_concat['file_name'].str.contains('BNTE-1'), 'Time_rs'] = '09:00'
rs_concat.loc[rs_concat['file_name'].str.contains('BNTE-2'), 'Time_rs'] = '11:00'
rs_concat.loc[rs_concat['file_name'].str.contains('BNTE-3'), 'Time_rs'] = '14:00'
rs_concat.loc[rs_concat['file_name'].str.contains('BNTE-4'), 'Time_rs'] = '16:00'
rs_concat.loc[rs_concat['file_name'].str.contains('BNTE-5'), 'Time_rs'] = '18:00'
rs_concat.loc[rs_concat['file_name'].str.contains('BNTE-6'), 'Time_rs'] = '20:00'
rs_concat['INDEX'] = (rs_concat['report_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +rs_concat['Time_rs'].astype(str).replace(' ', '',regex=True))
rs_concat.head()

C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,bank_account_number,bank_name,bank_account_owner_name,execution_date,aplication_date,disbursement_tracking_key,error_description,reference_number,cep,file_name,Time_rs,INDEX
0,29WLLJ2D3,PAID,2022-06-26T00:00,191.65,598ad6ee-5740-496d-b778-0561617f8d5d,0018261c-b847-4346-9f11-e3f2bdc6df80,659802020000043654,"Opciones Empresariales del Noreste, S.A. de C....",Ismael Lopez Herrera,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777585898,NaN,300001,"2022-06-26,42644264202206261777585898,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,29WLLJ2D3_09:00
1,N3V3KQNJS,PAID,2022-06-26T00:00,996.58,598ad6ee-5740-496d-b778-0561617f8d5d,00d6a6e0-3374-4a17-910d-586e503543ea,659802020000162328,"Opciones Empresariales del Noreste, S.A. de C....",Jesus Daniel Icedo Paredes,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777586536,NaN,300002,"2022-06-26,42644264202206261777586536,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,N3V3KQNJS_09:00
2,CCQQXFRKK,PAID,2022-06-26T00:00,316.22,598ad6ee-5740-496d-b778-0561617f8d5d,00fa58c6-207a-4587-853f-5fa53c181cf9,659802020000416265,"Opciones Empresariales del Noreste, S.A. de C....",Victor Manuel Castro Flores,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777586107,NaN,300003,"2022-06-26,42644264202206261777586107,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,CCQQXFRKK_09:00
3,YGPDXJ3XM,PAID,2022-06-26T00:00,"1,095.36",598ad6ee-5740-496d-b778-0561617f8d5d,01054eec-e90e-42a8-9471-3fb1711cbbc1,659802020000300038,"Opciones Empresariales del Noreste, S.A. de C....",Miguel Hernandez Ramirez,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777586739,NaN,300004,"2022-06-26,42644264202206261777586739,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,YGPDXJ3XM_09:00
4,TJBL7SLXQ,PAID,2022-06-26T00:00,141.26,598ad6ee-5740-496d-b778-0561617f8d5d,011385dc-0001-484e-ad6e-0b156669975e,659802020000058102,"Opciones Empresariales del Noreste, S.A. de C....",Andrea Rodriguez Zamora,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777586320,NaN,300005,"2022-06-26,42644264202206261777586320,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,TJBL7SLXQ_09:00

In [6]:
rs_concat.shape

(4106, 18)

In [7]:
duplicates = rs_concat[rs_concat.duplicated(['report_id'] , keep=False)]
duplicates.head()

Empty DataFrame
Columns: [report_id, status, report_date_local, amount, disbursement_batch_id, merchant_id, bank_account_number, bank_name, bank_account_owner_name, execution_date, aplication_date, disbursement_tracking_key, error_description, reference_number, cep, file_name, Time_rs, INDEX]
Index: []

In [8]:
duplicates.shape

(0, 18)

## QUERY PAYMENTS

In [9]:
query = pd.read_csv(r'G:\My Drive\3.-Settlement\5.-HISTORICO FILES PAGOS\02. FAST PAYMENTS\2022\06. JUNIO\FP-BNTE 2022-06-26.csv')
query['batch_created_date'] = pd.to_datetime(query['batch_created_date'])
query.set_index('batch_created_date',inplace=True)
query.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap
batch_created_date,,,,,,,,,,,,,
2022-06-26 09:45:19,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,29WLLJ2D3,2022-06-26 00:00:00,191.65,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:06:52,Ismael Lopez Herrera,'659802020000043654,BANORTE,"Ismael Lopez Herrera,,191.65,65980202000004365..."
2022-06-26 20:45:25,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,PFCH66XRS,2022-06-26 00:00:00,153.32,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 21:12:15,Ismael Lopez Herrera,'659802020000043654,BANORTE,"Ismael Lopez Herrera,,153.32,65980202000004365..."
2022-06-26 11:55:44,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,PP7HSPVPZ,2022-06-26 00:00:00,143.74,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 12:16:59,Ismael Lopez Herrera,'659802020000043654,BANORTE,"Ismael Lopez Herrera,,143.74,65980202000004365..."
2022-06-26 18:25:16,003e3797-50f2-45d4-94f9-c211dc599854,El Pollo TOM,rpalomares.celulares@gmail.com,HZ6QLZ9FR,2022-06-26 00:00:00,210.81,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 18:47:02,Ricardo Enrique Palomares Garcia,'659802020000047838,BANORTE,"Ricardo Enrique Palomares Garcia,,210.81,65980..."
2022-06-26 20:45:25,00817ad9-b94b-4dd9-bec6-26d2b38d9e4d,Pasteles De Luna,jezrrel_89@hotmail.com,ZP9WPX26S,2022-06-26 00:00:00,292.26,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 21:12:19,Ivan Jezrrel Luna Daza,'659802020000289528,BANORTE,"Ivan Jezrrel Luna Daza,,292.26,659802020000289..."

In [10]:
query.shape

(4106, 13)

In [11]:
hour1 = query.between_time('08:00','10:59')
hour1['Time'] = '09:00'
hour2 = query.between_time('11:00','13:59')
hour2['Time'] = '11:00'
hour3 = query.between_time('14:00','15:59')
hour3['Time'] = '14:00'
hour4 = query.between_time('16:00','17:59')
hour4['Time'] = '16:00'
hour5 = query.between_time('18:00','19:59')
hour5['Time'] = '18:00'
hour6 = query.between_time('20:00','23:59')
hour6['Time'] = '20:00'

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1214382282.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour1['Time'] = '09:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1214382282.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour2['Time'] = '11:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1214382282.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour3['Time'] = '14:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1214382282.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour4['Time'] = '16:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1214382282.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour5['Time'] = '18:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1214382282.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour6['Time'] = '20:00'

In [12]:
disp1 = pd.concat([hour1,hour2,hour3,hour4,hour5,hour6])
disp1['INDEX'] = (disp1['report_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +disp1['Time'].astype(str).replace(' ', '',regex=True))
disp1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX
batch_created_date,,,,,,,,,,,,,,,
2022-06-26 09:45:19,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,29WLLJ2D3,2022-06-26 00:00:00,191.65,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:06:52,Ismael Lopez Herrera,'659802020000043654,BANORTE,"Ismael Lopez Herrera,,191.65,65980202000004365...",09:00,29WLLJ2D3_09:00
2022-06-26 09:45:19,00d6a6e0-3374-4a17-910d-586e503543ea,Green-Go Mini Market,jesusicedo3@gmail.com,N3V3KQNJS,2022-06-26 00:00:00,996.58,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:06:58,Jesus Daniel Icedo Paredes,'659802020000162328,BANORTE,"Jesus Daniel Icedo Paredes,,996.58,65980202000...",09:00,N3V3KQNJS_09:00
2022-06-26 09:45:19,00fa58c6-207a-4587-853f-5fa53c181cf9,Transportes Viko,victorcastro488@gmail.com,CCQQXFRKK,2022-06-26 00:00:00,316.22,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:03,Victor Manuel Castro Flores,'659802020000416265,BANORTE,"Victor Manuel Castro Flores,,316.22,6598020200...",09:00,CCQQXFRKK_09:00
2022-06-26 09:45:19,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,YGPDXJ3XM,2022-06-26 00:00:00,"1,095.36",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:08,Miguel Hernandez Ramirez,'659802020000300038,BANORTE,"Miguel Hernandez Ramirez,,1095.36,659802020000...",09:00,YGPDXJ3XM_09:00
2022-06-26 09:45:19,011385dc-0001-484e-ad6e-0b156669975e,PEPPES PIZZA,psaso7@gmail.com,TJBL7SLXQ,2022-06-26 00:00:00,141.26,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:13,Andrea Rodriguez Zamora,'659802020000058102,BANORTE,"Andrea Rodriguez Zamora,,141.26,65980202000005...",09:00,TJBL7SLXQ_09:00

In [13]:
disp1.shape

(4106, 15)

In [14]:
duplicates_query = disp1[disp1.duplicated(['report_id'] , keep=False)]
duplicates_query.head()

Empty DataFrame
Columns: [merchant_id, merchant_name, user_email, report_id, report_date_local, amount, status, bank_name, payment_date_local, bank_account_owner_name, bank_account_number, disbursement_method, swap, Time, INDEX]
Index: []

In [15]:
duplicates_query.shape

(0, 15)

## BIN

In [16]:
bin1 = pd.read_csv(r'C:\Users\Cristian.Aparicio\Documents\DISPERSIONES\Catalogo_Bancos.csv'
                  ,dtype={'BIN':str,'Clave de la institución':str,'Nombre de la institución':str})

In [17]:
bin1.head()

   BIN Clave de la institución Nombre de la institución
0  138                   40138              ABC CAPITAL
1  102                   40102            ACCENDO BANCO
2  133                   40133                 ACTINVER
3  062                   40062                   AFIRME
4  638                   90638                    AKALA

In [18]:
bin1.shape

(90, 3)

# ARCHIVO RESPUESTA

In [19]:
rs_concat['Date_respuesta'] = date_respuesta
rs_concat.rename(columns ={'bank_account_number':'CLABE'}, inplace=True)
rs_concat['BIN'] = rs_concat['CLABE'].str[:3].replace(' ', '',regex=True)
rs_concat.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,aplication_date,disbursement_tracking_key,error_description,reference_number,cep,file_name,Time_rs,INDEX,Date_respuesta,BIN
0,29WLLJ2D3,PAID,2022-06-26T00:00,191.65,598ad6ee-5740-496d-b778-0561617f8d5d,0018261c-b847-4346-9f11-e3f2bdc6df80,659802020000043654,"Opciones Empresariales del Noreste, S.A. de C....",Ismael Lopez Herrera,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777585898,NaN,300001,"2022-06-26,42644264202206261777585898,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,29WLLJ2D3_09:00,2022-06-26,659
1,N3V3KQNJS,PAID,2022-06-26T00:00,996.58,598ad6ee-5740-496d-b778-0561617f8d5d,00d6a6e0-3374-4a17-910d-586e503543ea,659802020000162328,"Opciones Empresariales del Noreste, S.A. de C....",Jesus Daniel Icedo Paredes,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777586536,NaN,300002,"2022-06-26,42644264202206261777586536,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,N3V3KQNJS_09:00,2022-06-26,659
2,CCQQXFRKK,PAID,2022-06-26T00:00,316.22,598ad6ee-5740-496d-b778-0561617f8d5d,00fa58c6-207a-4587-853f-5fa53c181cf9,659802020000416265,"Opciones Empresariales del Noreste, S.A. de C....",Victor Manuel Castro Flores,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777586107,NaN,300003,"2022-06-26,42644264202206261777586107,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,CCQQXFRKK_09:00,2022-06-26,659
3,YGPDXJ3XM,PAID,2022-06-26T00:00,"1,095.36",598ad6ee-5740-496d-b778-0561617f8d5d,01054eec-e90e-42a8-9471-3fb1711cbbc1,659802020000300038,"Opciones Empresariales del Noreste, S.A. de C....",Miguel Hernandez Ramirez,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777586739,NaN,300004,"2022-06-26,42644264202206261777586739,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,YGPDXJ3XM_09:00,2022-06-26,659
4,TJBL7SLXQ,PAID,2022-06-26T00:00,141.26,598ad6ee-5740-496d-b778-0561617f8d5d,011385dc-0001-484e-ad6e-0b156669975e,659802020000058102,"Opciones Empresariales del Noreste, S.A. de C....",Andrea Rodriguez Zamora,2022-06-26T00:00,2022-06-26T09:45:20,42644264202206261777586320,NaN,300005,"2022-06-26,42644264202206261777586320,40072,90...",Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,TJBL7SLXQ_09:00,2022-06-26,659

In [20]:
rs_concat.shape

(4106, 20)

In [21]:
rs_concat_2 = rs_concat.merge(bin1[['BIN','Clave de la institución','Nombre de la institución']] ,on='BIN', how='left')
rs_concat_2['Banco emisor'] = '40072'
rs_concat_2['Banco_emisor'] = 'BANORTE'
rs_concat_2['LINEA CEP'] = (rs_concat_2['Date_respuesta'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['disbursement_tracking_key'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['Banco emisor'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['Clave de la institución'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['CLABE'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['amount'].astype(str).replace(' ', '',regex=True))
rs_concat_2.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,...,file_name,Time_rs,INDEX,Date_respuesta,BIN,Clave de la institución,Nombre de la institución,Banco emisor,Banco_emisor,LINEA CEP
0,29WLLJ2D3,PAID,2022-06-26T00:00,191.65,598ad6ee-5740-496d-b778-0561617f8d5d,0018261c-b847-4346-9f11-e3f2bdc6df80,659802020000043654,"Opciones Empresariales del Noreste, S.A. de C....",Ismael Lopez Herrera,2022-06-26T00:00,...,Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,29WLLJ2D3_09:00,2022-06-26,659,90659,ASP INTEGRA OPC,40072,BANORTE,"2022-06-26,42644264202206261777585898,40072,90..."
1,N3V3KQNJS,PAID,2022-06-26T00:00,996.58,598ad6ee-5740-496d-b778-0561617f8d5d,00d6a6e0-3374-4a17-910d-586e503543ea,659802020000162328,"Opciones Empresariales del Noreste, S.A. de C....",Jesus Daniel Icedo Paredes,2022-06-26T00:00,...,Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,N3V3KQNJS_09:00,2022-06-26,659,90659,ASP INTEGRA OPC,40072,BANORTE,"2022-06-26,42644264202206261777586536,40072,90..."
2,CCQQXFRKK,PAID,2022-06-26T00:00,316.22,598ad6ee-5740-496d-b778-0561617f8d5d,00fa58c6-207a-4587-853f-5fa53c181cf9,659802020000416265,"Opciones Empresariales del Noreste, S.A. de C....",Victor Manuel Castro Flores,2022-06-26T00:00,...,Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,CCQQXFRKK_09:00,2022-06-26,659,90659,ASP INTEGRA OPC,40072,BANORTE,"2022-06-26,42644264202206261777586107,40072,90..."
3,YGPDXJ3XM,PAID,2022-06-26T00:00,"1,095.36",598ad6ee-5740-496d-b778-0561617f8d5d,01054eec-e90e-42a8-9471-3fb1711cbbc1,659802020000300038,"Opciones Empresariales del Noreste, S.A. de C....",Miguel Hernandez Ramirez,2022-06-26T00:00,...,Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,YGPDXJ3XM_09:00,2022-06-26,659,90659,ASP INTEGRA OPC,40072,BANORTE,"2022-06-26,42644264202206261777586739,40072,90..."
4,TJBL7SLXQ,PAID,2022-06-26T00:00,141.26,598ad6ee-5740-496d-b778-0561617f8d5d,011385dc-0001-484e-ad6e-0b156669975e,659802020000058102,"Opciones Empresariales del Noreste, S.A. de C....",Andrea Rodriguez Zamora,2022-06-26T00:00,...,Respuesta-FP-BNTE-1 2022-06-26.xlsx,09:00,TJBL7SLXQ_09:00,2022-06-26,659,90659,ASP INTEGRA OPC,40072,BANORTE,"2022-06-26,42644264202206261777586320,40072,90..."

In [22]:
rs_concat_2.shape

(4106, 25)

# ARCHIVO DISPERSION

In [23]:
disp1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX
batch_created_date,,,,,,,,,,,,,,,
2022-06-26 09:45:19,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,29WLLJ2D3,2022-06-26 00:00:00,191.65,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:06:52,Ismael Lopez Herrera,'659802020000043654,BANORTE,"Ismael Lopez Herrera,,191.65,65980202000004365...",09:00,29WLLJ2D3_09:00
2022-06-26 09:45:19,00d6a6e0-3374-4a17-910d-586e503543ea,Green-Go Mini Market,jesusicedo3@gmail.com,N3V3KQNJS,2022-06-26 00:00:00,996.58,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:06:58,Jesus Daniel Icedo Paredes,'659802020000162328,BANORTE,"Jesus Daniel Icedo Paredes,,996.58,65980202000...",09:00,N3V3KQNJS_09:00
2022-06-26 09:45:19,00fa58c6-207a-4587-853f-5fa53c181cf9,Transportes Viko,victorcastro488@gmail.com,CCQQXFRKK,2022-06-26 00:00:00,316.22,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:03,Victor Manuel Castro Flores,'659802020000416265,BANORTE,"Victor Manuel Castro Flores,,316.22,6598020200...",09:00,CCQQXFRKK_09:00
2022-06-26 09:45:19,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,YGPDXJ3XM,2022-06-26 00:00:00,"1,095.36",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:08,Miguel Hernandez Ramirez,'659802020000300038,BANORTE,"Miguel Hernandez Ramirez,,1095.36,659802020000...",09:00,YGPDXJ3XM_09:00
2022-06-26 09:45:19,011385dc-0001-484e-ad6e-0b156669975e,PEPPES PIZZA,psaso7@gmail.com,TJBL7SLXQ,2022-06-26 00:00:00,141.26,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:13,Andrea Rodriguez Zamora,'659802020000058102,BANORTE,"Andrea Rodriguez Zamora,,141.26,65980202000005...",09:00,TJBL7SLXQ_09:00

In [24]:
disp1['report_date_local'] = pd.to_datetime(disp1['report_date_local'])

In [25]:
split = disp1["swap"].str.split(",",n=7,expand=True)
split.head()

,0,1,2,3,4
batch_created_date,,,,,
2022-06-26 09:45:19,Ismael Lopez Herrera,,191.65,659802020000043654,CLIP-29WLLJ2D3
2022-06-26 09:45:19,Jesus Daniel Icedo Paredes,,996.58,659802020000162328,CLIP-N3V3KQNJS
2022-06-26 09:45:19,Victor Manuel Castro Flores,,316.22,659802020000416265,CLIP-CCQQXFRKK
2022-06-26 09:45:19,Miguel Hernandez Ramirez,,1095.36,659802020000300038,CLIP-YGPDXJ3XM
2022-06-26 09:45:19,Andrea Rodriguez Zamora,,141.26,659802020000058102,CLIP-TJBL7SLXQ

In [26]:
disp1["swap"] = split[0] 
disp1["CLABE"] = split[3]

In [27]:
disp1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX,CLABE
batch_created_date,,,,,,,,,,,,,,,,
2022-06-26 09:45:19,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,29WLLJ2D3,2022-06-26,191.65,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:06:52,Ismael Lopez Herrera,'659802020000043654,BANORTE,Ismael Lopez Herrera,09:00,29WLLJ2D3_09:00,659802020000043654
2022-06-26 09:45:19,00d6a6e0-3374-4a17-910d-586e503543ea,Green-Go Mini Market,jesusicedo3@gmail.com,N3V3KQNJS,2022-06-26,996.58,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:06:58,Jesus Daniel Icedo Paredes,'659802020000162328,BANORTE,Jesus Daniel Icedo Paredes,09:00,N3V3KQNJS_09:00,659802020000162328
2022-06-26 09:45:19,00fa58c6-207a-4587-853f-5fa53c181cf9,Transportes Viko,victorcastro488@gmail.com,CCQQXFRKK,2022-06-26,316.22,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:03,Victor Manuel Castro Flores,'659802020000416265,BANORTE,Victor Manuel Castro Flores,09:00,CCQQXFRKK_09:00,659802020000416265
2022-06-26 09:45:19,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,YGPDXJ3XM,2022-06-26,"1,095.36",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:08,Miguel Hernandez Ramirez,'659802020000300038,BANORTE,Miguel Hernandez Ramirez,09:00,YGPDXJ3XM_09:00,659802020000300038
2022-06-26 09:45:19,011385dc-0001-484e-ad6e-0b156669975e,PEPPES PIZZA,psaso7@gmail.com,TJBL7SLXQ,2022-06-26,141.26,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-06-26 10:07:13,Andrea Rodriguez Zamora,'659802020000058102,BANORTE,Andrea Rodriguez Zamora,09:00,TJBL7SLXQ_09:00,659802020000058102

In [28]:
disp1.loc[disp1['report_date_local'] == date_respuesta, 'tipo'] = 'Pago del día'
disp1.loc[disp1['report_date_local'] != date_respuesta, 'tipo'] = 'Reprogramación'
disp1.drop(['bank_name','CLABE','status'],axis=1,inplace=True)
disp1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX,tipo
batch_created_date,,,,,,,,,,,,,,
2022-06-26 09:45:19,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,29WLLJ2D3,2022-06-26,191.65,2022-06-26 10:06:52,Ismael Lopez Herrera,'659802020000043654,BANORTE,Ismael Lopez Herrera,09:00,29WLLJ2D3_09:00,Pago del día
2022-06-26 09:45:19,00d6a6e0-3374-4a17-910d-586e503543ea,Green-Go Mini Market,jesusicedo3@gmail.com,N3V3KQNJS,2022-06-26,996.58,2022-06-26 10:06:58,Jesus Daniel Icedo Paredes,'659802020000162328,BANORTE,Jesus Daniel Icedo Paredes,09:00,N3V3KQNJS_09:00,Pago del día
2022-06-26 09:45:19,00fa58c6-207a-4587-853f-5fa53c181cf9,Transportes Viko,victorcastro488@gmail.com,CCQQXFRKK,2022-06-26,316.22,2022-06-26 10:07:03,Victor Manuel Castro Flores,'659802020000416265,BANORTE,Victor Manuel Castro Flores,09:00,CCQQXFRKK_09:00,Pago del día
2022-06-26 09:45:19,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,YGPDXJ3XM,2022-06-26,"1,095.36",2022-06-26 10:07:08,Miguel Hernandez Ramirez,'659802020000300038,BANORTE,Miguel Hernandez Ramirez,09:00,YGPDXJ3XM_09:00,Pago del día
2022-06-26 09:45:19,011385dc-0001-484e-ad6e-0b156669975e,PEPPES PIZZA,psaso7@gmail.com,TJBL7SLXQ,2022-06-26,141.26,2022-06-26 10:07:13,Andrea Rodriguez Zamora,'659802020000058102,BANORTE,Andrea Rodriguez Zamora,09:00,TJBL7SLXQ_09:00,Pago del día

In [29]:
disp_2 = disp1.merge(rs_concat_2[['INDEX','status','Nombre de la institución','CLABE','LINEA CEP','Time_rs','Banco_emisor']]
                     ,on='INDEX', how='left')
disp_2.sort_values(by=['status'])
disp_2["Time"].fillna('NO TIME',inplace=True)
disp_2.loc[disp_2['Time'] == 'NO TIME', 'status'] = 'ERROR'
disp_2.loc[(disp_2['LINEA CEP'].str.contains('nan')) & (['Nombre de la institución'] == 'BANORTE/IXE'), 'status'] = 'ERROR'
# disp_2.loc[pd.notnull(disp_2['error_description']), 'status'] = 'ERROR'
disp_2.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX,tipo,status,Nombre de la institución,CLABE,LINEA CEP,Time_rs,Banco_emisor
0,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,29WLLJ2D3,2022-06-26,191.65,2022-06-26 10:06:52,Ismael Lopez Herrera,'659802020000043654,BANORTE,Ismael Lopez Herrera,09:00,29WLLJ2D3_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000043654,"2022-06-26,42644264202206261777585898,40072,90...",09:00,BANORTE
1,00d6a6e0-3374-4a17-910d-586e503543ea,Green-Go Mini Market,jesusicedo3@gmail.com,N3V3KQNJS,2022-06-26,996.58,2022-06-26 10:06:58,Jesus Daniel Icedo Paredes,'659802020000162328,BANORTE,Jesus Daniel Icedo Paredes,09:00,N3V3KQNJS_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000162328,"2022-06-26,42644264202206261777586536,40072,90...",09:00,BANORTE
2,00fa58c6-207a-4587-853f-5fa53c181cf9,Transportes Viko,victorcastro488@gmail.com,CCQQXFRKK,2022-06-26,316.22,2022-06-26 10:07:03,Victor Manuel Castro Flores,'659802020000416265,BANORTE,Victor Manuel Castro Flores,09:00,CCQQXFRKK_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000416265,"2022-06-26,42644264202206261777586107,40072,90...",09:00,BANORTE
3,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,YGPDXJ3XM,2022-06-26,"1,095.36",2022-06-26 10:07:08,Miguel Hernandez Ramirez,'659802020000300038,BANORTE,Miguel Hernandez Ramirez,09:00,YGPDXJ3XM_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000300038,"2022-06-26,42644264202206261777586739,40072,90...",09:00,BANORTE
4,011385dc-0001-484e-ad6e-0b156669975e,PEPPES PIZZA,psaso7@gmail.com,TJBL7SLXQ,2022-06-26,141.26,2022-06-26 10:07:13,Andrea Rodriguez Zamora,'659802020000058102,BANORTE,Andrea Rodriguez Zamora,09:00,TJBL7SLXQ_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000058102,"2022-06-26,42644264202206261777586320,40072,90...",09:00,BANORTE

In [30]:
disp_2.loc[disp_2['Nombre de la institución'] == 'BANORTE/IXE', 'LINEA CEP'] = 'COMPROBANTE MISMO BANCO BANORTE'
disp_2.loc[disp_2['status'] == 'ERROR', 'LINEA CEP'] = ''

In [31]:
for col in disp_2.columns: 
    print(col)

merchant_id
merchant_name
user_email
report_id
report_date_local
amount
payment_date_local
bank_account_owner_name
bank_account_number
disbursement_method
swap
Time
INDEX
tipo
status
Nombre de la institución
CLABE
LINEA CEP
Time_rs
Banco_emisor

In [32]:
disp_final = disp_2[['merchant_id','merchant_name','user_email','report_id','report_date_local','amount','tipo'
                    ,'Nombre de la institución','swap','CLABE','status','LINEA CEP','Time','Banco_emisor']]
disp_final.rename(columns ={'Nombre de la institución':'bank','amount':'total_due','LINEA CEP':'CEP'}, inplace=True)
disp_final.sort_values(by=['status','Time'], ascending=True, inplace=True)
disp_final.drop_duplicates(subset =['report_id','Time'], keep ='first', inplace=True)
disp_final.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1713376454.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.rename(columns ={'Nombre de la institución':'bank','amount':'total_due','LINEA CEP':'CEP'}, inplace=True)
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1713376454.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.sort_values(by=['status','Time'], ascending=True, inplace=True)
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1713376454.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.drop_duplicates(subset =['report_id','Time'], keep ='first', inplace=True)

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor
28,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,X46LWNDH2,2022-06-26,263.13,Pago del día,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,659802020000003995,ERROR,,09:00,BANORTE
90,14c65f6b-370d-4f86-85a2-f0cd67dfb2d0,El gallo Negro,yoyo_yoyis@hotmail.com,KD7VYBMDM,2022-06-26,143.74,Pago del día,ASP INTEGRA OPC,Yael Rodrigo Gutierrez Serrano,659802020000403090,ERROR,,09:00,BANORTE
120,1bae3a1d-1c49-442c-97d9-8aeac2e70f15,Aba Ponch,gusscass@yahoo.com.mx,37GTC473P,2022-06-26,277.90,Pago del día,ASP INTEGRA OPC,Gustavo Natalio Cassielles Arce,659802020000145675,ERROR,,09:00,BANORTE
150,26e27833-5769-49ef-9a62-2509f663a8b2,Alos Accesories,afernanadezpalma@gmail.com,RRRWFF6YB,2022-06-26,177.27,Pago del día,ASP INTEGRA OPC,Alondra Fernandez Palma,659802020000054575,ERROR,,09:00,BANORTE
157,285e47e8-3f34-400e-91e9-4715f587eddc,Abarrotes Morales,guillermomorales_3@hotmail.com,YRWGYM4KV,2022-06-26,521.11,Pago del día,ASP INTEGRA OPC,Edwin ivan Morales Samaniego,659802020000243315,ERROR,,09:00,BANORTE

In [33]:
disp_final.shape

(4106, 14)

# ERROR

In [34]:
error = disp_final[(disp_final['status'] != 'PAID')]
error.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor
28,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,X46LWNDH2,2022-06-26,263.13,Pago del día,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,659802020000003995,ERROR,,09:00,BANORTE
90,14c65f6b-370d-4f86-85a2-f0cd67dfb2d0,El gallo Negro,yoyo_yoyis@hotmail.com,KD7VYBMDM,2022-06-26,143.74,Pago del día,ASP INTEGRA OPC,Yael Rodrigo Gutierrez Serrano,659802020000403090,ERROR,,09:00,BANORTE
120,1bae3a1d-1c49-442c-97d9-8aeac2e70f15,Aba Ponch,gusscass@yahoo.com.mx,37GTC473P,2022-06-26,277.90,Pago del día,ASP INTEGRA OPC,Gustavo Natalio Cassielles Arce,659802020000145675,ERROR,,09:00,BANORTE
150,26e27833-5769-49ef-9a62-2509f663a8b2,Alos Accesories,afernanadezpalma@gmail.com,RRRWFF6YB,2022-06-26,177.27,Pago del día,ASP INTEGRA OPC,Alondra Fernandez Palma,659802020000054575,ERROR,,09:00,BANORTE
157,285e47e8-3f34-400e-91e9-4715f587eddc,Abarrotes Morales,guillermomorales_3@hotmail.com,YRWGYM4KV,2022-06-26,521.11,Pago del día,ASP INTEGRA OPC,Edwin ivan Morales Samaniego,659802020000243315,ERROR,,09:00,BANORTE

In [35]:
error.shape

(188, 14)

In [36]:
error.drop(['swap','CLABE','status','CEP','Banco_emisor'],axis=1,inplace=True)

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\3363876278.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  error.drop(['swap','CLABE','status','CEP','Banco_emisor'],axis=1,inplace=True)

In [37]:
error_final = error
error_final.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,Time
28,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,X46LWNDH2,2022-06-26,263.13,Pago del día,ASP INTEGRA OPC,09:00
90,14c65f6b-370d-4f86-85a2-f0cd67dfb2d0,El gallo Negro,yoyo_yoyis@hotmail.com,KD7VYBMDM,2022-06-26,143.74,Pago del día,ASP INTEGRA OPC,09:00
120,1bae3a1d-1c49-442c-97d9-8aeac2e70f15,Aba Ponch,gusscass@yahoo.com.mx,37GTC473P,2022-06-26,277.90,Pago del día,ASP INTEGRA OPC,09:00
150,26e27833-5769-49ef-9a62-2509f663a8b2,Alos Accesories,afernanadezpalma@gmail.com,RRRWFF6YB,2022-06-26,177.27,Pago del día,ASP INTEGRA OPC,09:00
157,285e47e8-3f34-400e-91e9-4715f587eddc,Abarrotes Morales,guillermomorales_3@hotmail.com,YRWGYM4KV,2022-06-26,521.11,Pago del día,ASP INTEGRA OPC,09:00

In [38]:
error.loc[error['bank'] == 'BANORTE/IXE', 'Check'] = 'SPEI DEVUELTO MISMO BANCO'
error.loc[error['bank'] != 'BANORTE/IXE', 'Check'] = 'SPEI DEVUELTO'

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_11300\1112414736.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  error.loc[error['bank'] == 'BANORTE/IXE', 'Check'] = 'SPEI DEVUELTO MISMO BANCO'

In [39]:
error.shape

(188, 10)

In [40]:
error_final = error.merge(rs_concat_2[['report_id','error_description']],on='report_id',how='left')
error_final.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,Time,Check,error_description
0,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,X46LWNDH2,2022-06-26,263.13,Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,DEV.SPEIEXCEDE EL LNMITE DE AB
1,14c65f6b-370d-4f86-85a2-f0cd67dfb2d0,El gallo Negro,yoyo_yoyis@hotmail.com,KD7VYBMDM,2022-06-26,143.74,Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,DEV.SPEIEXCEDE EL LNMITE DE AB
2,1bae3a1d-1c49-442c-97d9-8aeac2e70f15,Aba Ponch,gusscass@yahoo.com.mx,37GTC473P,2022-06-26,277.90,Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,DEV.SPEIEXCEDE EL LNMITE DE AB
3,26e27833-5769-49ef-9a62-2509f663a8b2,Alos Accesories,afernanadezpalma@gmail.com,RRRWFF6YB,2022-06-26,177.27,Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,DEV.SPEIEXCEDE EL LNMITE DE AB
4,285e47e8-3f34-400e-91e9-4715f587eddc,Abarrotes Morales,guillermomorales_3@hotmail.com,YRWGYM4KV,2022-06-26,521.11,Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,DEV.SPEIEXCEDE EL LNMITE DE AB

In [41]:
error_final.shape

(188, 11)

# ARCHIVOS FINALES

### ARCHIVO DISPERSION

In [42]:
writer = pd.ExcelWriter(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\06. JUNIO\ARCHIVO DISPERSIONES FP\BNTE\Dispersión-FP-BNTE 2022-06-26.xlsx',
                        engine='xlsxwriter', engine_kwargs={'options': {'encoding':'utf-8'}})
disp_final.to_excel(writer, sheet_name='FAST PAYMENTS',index=False)
error_final.to_excel(writer, sheet_name='ERROR',index=False)
writer.close()

### ARCHIVO DISPERSIÓN - TODO POR BNTE

In [43]:
writer = pd.ExcelWriter(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\06. JUNIO\ARCHIVO DISPERSIONES FP\Dispersión-FP 2022-06-26.xlsx',
                        engine='xlsxwriter', engine_kwargs={'options': {'encoding':'utf-8'}})
disp_final.to_excel(writer, sheet_name='FAST PAYMENTS',index=False)
error_final.to_excel(writer, sheet_name='ERROR',index=False)
writer.close()

### ARCHIVO RESPUESTA

In [44]:
rs_concat.to_csv(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\06. JUNIO\ARCHIVO RESPUESTAS FINALES\Respuesta-FP-BNTE 2022-06-26.csv',index=False)

In [ ]:
# book = load_workbook('Dispersión-FP 2020-07-20.xlsx')
# writer = pd.ExcelWriter('Dispersión-FP 2020-07-20.xlsx', engine='openpyxl', options={'encoding':'utf-8'})
# writer.book = book
# match_final.to_excel(writer, sheet_name='FP-2 2020-07-20', index=False)
# writer.save()
# writer.close()