In [1]:
import pandas as pd
import numpy as np
import openpyxl
from openpyxl import load_workbook
import xlsxwriter
import glob
import os
from datetime import datetime
pd.options.display.float_format = '{:,.2f}'.format

# READING FILES

In [2]:
date_respuesta = '2022-05-16'
date_respuesta = pd.to_datetime(date_respuesta)

## RESPUESTAS FP

In [3]:
names_resp = ['report_id','status','report_date_local','amount','disbursement_batch_id','merchant_id','bank_account_number',
             'bank_name','bank_account_owner_name','execution_date','aplication_date','disbursement_tracking_key',
             'error_description','reference_number','cep']

In [4]:
rs = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\05. MAYO\Respuesta-FP-CITI*.xlsx', recursive=False)
rs

['C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\05. MAYO\\Respuesta-FP-CITI-1 2022-05-16.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\05. MAYO\\Respuesta-FP-CITI-2 2022-05-16.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\05. MAYO\\Respuesta-FP-CITI-3 2022-05-16.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\05. MAYO\\Respuesta-FP-CITI-4 2022-05-16.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\05. MAYO\\Respuesta-FP-CITI-5 2022-05-16.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\FAST PAYMENTS\\2022\\05. MAYO\\Respuesta-FP-CITI-6 2022-05-16.xlsx']

In [5]:
rs_concat = pd.concat([pd.read_excel(f,sheet_name='Report',names=names_resp,
                                     converters={'bank_account_number':str,'disbursement_tracking_key':str,'report_id':str})
                       .assign(file_name=os.path.basename(f)) for f in rs])
rs_concat.loc[rs_concat['file_name'].str.contains('CITI-1'), 'Time_rs'] = '09:00'
rs_concat.loc[rs_concat['file_name'].str.contains('CITI-2'), 'Time_rs'] = '11:00'
rs_concat.loc[rs_concat['file_name'].str.contains('CITI-3'), 'Time_rs'] = '14:00'
rs_concat.loc[rs_concat['file_name'].str.contains('CITI-4'), 'Time_rs'] = '16:00'
rs_concat.loc[rs_concat['file_name'].str.contains('CITI-5'), 'Time_rs'] = '18:00'
rs_concat.loc[rs_concat['file_name'].str.contains('CITI-6'), 'Time_rs'] = '20:00'
rs_concat['INDEX'] = (rs_concat['report_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +rs_concat['Time_rs'].astype(str).replace(' ', '',regex=True))
rs_concat.head()

C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,bank_account_number,bank_name,bank_account_owner_name,execution_date,aplication_date,disbursement_tracking_key,error_description,reference_number,cep,file_name,Time_rs,INDEX
0,747LYKL4C,PAID,2022-05-16T00:00,"2,395.60",d07893bc-7789-43a3-8205-a74f46e78003,00094c06-2b54-4569-9314-00c3c213297c,659802020000471271,"Opciones Empresariales del Noreste, S.A. de C....",Guadalupe Carmen Villa Vazquez,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5AB73A85493,NaN,300001,"2022-05-16,180CD5AB73A85493,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,747LYKL4C_09:00
1,N7GMWSNJB,PAID,2022-05-16T00:00,364.13,d07893bc-7789-43a3-8205-a74f46e78003,0018261c-b847-4346-9f11-e3f2bdc6df80,659802020000043654,"Opciones Empresariales del Noreste, S.A. de C....",Ismael Lopez Herrera,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5AB73D43FF6,NaN,300002,"2022-05-16,180CD5AB73D43FF6,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,N7GMWSNJB_09:00
2,S49HJVPJJ,PAID,2022-05-16T00:00,30.67,d07893bc-7789-43a3-8205-a74f46e78003,0079b7bd-0713-4cf9-9b37-992cbbba9c1e,659802020000524814,"Opciones Empresariales del Noreste, S.A. de C....",Zaida Sarai Aguirre Hernandez,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5ABBCD6EE75,NaN,300003,"2022-05-16,180CD5ABBCD6EE75,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,S49HJVPJJ_09:00
3,VH5G2Z755,PAID,2022-05-16T00:00,142.79,d07893bc-7789-43a3-8205-a74f46e78003,01054eec-e90e-42a8-9471-3fb1711cbbc1,659802020000300038,"Opciones Empresariales del Noreste, S.A. de C....",Miguel Hernandez Ramirez,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5ABA9F430B1,NaN,300004,"2022-05-16,180CD5ABA9F430B1,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,VH5G2Z755_09:00
4,FXY83F7PY,PAID,2022-05-16T00:00,206.98,d07893bc-7789-43a3-8205-a74f46e78003,018ea728-1b9e-43ef-bc47-1de244528643,659802020000112941,"Opciones Empresariales del Noreste, S.A. de C....",Mario ivan Flores Hernandez,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5AB7A42CA70,NaN,300005,"2022-05-16,180CD5AB7A42CA70,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,FXY83F7PY_09:00

In [6]:
rs_concat.shape

(4588, 18)

In [7]:
rs_concat.columns

Index(['report_id', 'status', 'report_date_local', 'amount',
       'disbursement_batch_id', 'merchant_id', 'bank_account_number',
       'bank_name', 'bank_account_owner_name', 'execution_date',
       'aplication_date', 'disbursement_tracking_key', 'error_description',
       'reference_number', 'cep', 'file_name', 'Time_rs', 'INDEX'],
      dtype='object')

In [8]:
duplicates = rs_concat[rs_concat.duplicated(['report_id'] , keep=False)]
duplicates.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,bank_account_number,bank_name,bank_account_owner_name,execution_date,aplication_date,disbursement_tracking_key,error_description,reference_number,cep,file_name,Time_rs,INDEX
316,ZKFS3RFKC,PAID,2022-05-16T00:00,"8,624.16",d07893bc-7789-43a3-8205-a74f46e78003,55b390cf-f5bd-4cab-a142-b1ea68a08e20,659802020000329873,"Opciones Empresariales del Noreste, S.A. de C....",Roselino Rodriguez Estrada,2022-05-16T14:45:07,2022-05-16T09:45:05,180CEBFF74AFEE51,/21/CB Return Exceeds the limit of credits all...,300317,"2022-05-16,180CEBFF74AFEE51,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,ZKFS3RFKC_09:00
279,ZKFS3RFKC,PAID,2022-05-16T00:00,"8,624.16",c3b6431a-a05a-44ad-b495-0430ba32adf3,55b390cf-f5bd-4cab-a142-b1ea68a08e20,127126013337406134,"Banco Azteca, S.A.",Roselino Rodriguez Estrada,2022-05-16T21:15:48,2022-05-16T16:15:46,180CEBFF74AFEE51,/21/CB Return Exceeds the limit of credits all...,600280,"2022-05-16,180CEBFF74AFEE51,40002,40127,127126...",Respuesta-FP-CITI-4 2022-05-16.xlsx,16:00,ZKFS3RFKC_16:00

In [9]:
duplicates.shape

(2, 18)

## QUERY PAYMENTS

In [10]:
query = pd.read_csv(r'G:\My Drive\3.-Settlement\5.-HISTORICO FILES PAGOS\02. FAST PAYMENTS\2022\05. MAYO\FP-CITI 2022-05-16.csv')
query['batch_created_date'] = pd.to_datetime(query['batch_created_date'])
query.set_index('batch_created_date',inplace=True)
query.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap
batch_created_date,,,,,,,,,,,,,
2022-05-16 09:45:04,00094c06-2b54-4569-9314-00c3c213297c,5antas Alitas Dgo,lacosa0012@gmail.com,747LYKL4C,2022-05-16 00:00:00,"2,395.60",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Guadalupe Carmen Villa Vazquez,'659802020000471271,CITI,"Guadalupe Carmen Villa Vazquez,,2395.60,659802..."
2022-05-16 09:45:04,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,N7GMWSNJB,2022-05-16 00:00:00,364.13,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:23,Ismael Lopez Herrera,'659802020000043654,CITI,"Ismael Lopez Herrera,,364.13,65980202000004365..."
2022-05-16 16:15:46,004441ca-4367-4c31-946d-bb862e448df4,Megci,csalazargue@yahoo.com.mx,3SKJZ4VZQ,2022-05-16 00:00:00,"2,395.60",ERROR,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 16:33:05,Claudia Pilar SALAZAR Guerrero,'659802020000057187,CITI,"Claudia Pilar SALAZAR Guerrero,,2395.60,659802..."
2022-05-16 20:45:39,004441ca-4367-4c31-946d-bb862e448df4,Megci,csalazargue@yahoo.com.mx,BV8ZNSXBM,2022-05-16 00:00:00,"2,874.72",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 20:52:25,Claudia Pilar SALAZAR Guerrero,'659802020000057187,CITI,"Claudia Pilar SALAZAR Guerrero,,2874.72,659802..."
2022-05-16 18:25:49,004441ca-4367-4c31-946d-bb862e448df4,Megci,csalazargue@yahoo.com.mx,FJZTV5SZJ,2022-05-16 00:00:00,479.12,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 18:32:22,Claudia Pilar SALAZAR Guerrero,'659802020000057187,CITI,"Claudia Pilar SALAZAR Guerrero,,479.12,6598020..."

In [11]:
query.shape

(4588, 13)

In [12]:
hour1 = query.between_time('08:00','10:59')
hour1['Time'] = '09:00'
hour2 = query.between_time('11:00','13:59')
hour2['Time'] = '11:00'
hour3 = query.between_time('14:00','15:59')
hour3['Time'] = '14:00'
hour4 = query.between_time('16:00','17:59')
hour4['Time'] = '16:00'
hour5 = query.between_time('18:00','19:59')
hour5['Time'] = '18:00'
hour6 = query.between_time('20:00','23:59')
hour6['Time'] = '20:00'

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1214382282.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour1['Time'] = '09:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1214382282.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour2['Time'] = '11:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1214382282.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour3['Time'] = '14:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1214382282.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour4['Time'] = '16:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1214382282.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour5['Time'] = '18:00'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1214382282.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hour6['Time'] = '20:00'

In [13]:
disp1 = pd.concat([hour1,hour2,hour3,hour4,hour5,hour6])
disp1['INDEX'] = (disp1['report_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +disp1['Time'].astype(str).replace(' ', '',regex=True))
disp1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX
batch_created_date,,,,,,,,,,,,,,,
2022-05-16 09:45:04,00094c06-2b54-4569-9314-00c3c213297c,5antas Alitas Dgo,lacosa0012@gmail.com,747LYKL4C,2022-05-16 00:00:00,"2,395.60",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Guadalupe Carmen Villa Vazquez,'659802020000471271,CITI,"Guadalupe Carmen Villa Vazquez,,2395.60,659802...",09:00,747LYKL4C_09:00
2022-05-16 09:45:04,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,N7GMWSNJB,2022-05-16 00:00:00,364.13,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:23,Ismael Lopez Herrera,'659802020000043654,CITI,"Ismael Lopez Herrera,,364.13,65980202000004365...",09:00,N7GMWSNJB_09:00
2022-05-16 09:45:04,0079b7bd-0713-4cf9-9b37-992cbbba9c1e,Zaida Sarai,zaida.sarai.aguirre.hernandez@gmail.com,S49HJVPJJ,2022-05-16 00:00:00,30.67,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Zaida Sarai Aguirre Hernandez,'659802020000524814,CITI,"Zaida Sarai Aguirre Hernandez,,30.67,659802020...",09:00,S49HJVPJJ_09:00
2022-05-16 09:45:04,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,VH5G2Z755,2022-05-16 00:00:00,142.79,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Miguel Hernandez Ramirez,'659802020000300038,CITI,"Miguel Hernandez Ramirez,,142.79,6598020200003...",09:00,VH5G2Z755_09:00
2022-05-16 09:45:04,018ea728-1b9e-43ef-bc47-1de244528643,Abarrotes Cris,plasmakoarcade69@gmail.com,FXY83F7PY,2022-05-16 00:00:00,206.98,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:24,Mario ivan Flores Hernandez,'659802020000112941,CITI,"Mario ivan Flores Hernandez,,206.98,6598020200...",09:00,FXY83F7PY_09:00

In [14]:
disp1.shape

(4588, 15)

## BIN

In [15]:
bin1 = pd.read_csv(r'C:\Users\Cristian.Aparicio\Documents\DISPERSIONES\Catalogo_Bancos.csv'
                  ,dtype={'BIN':str,'Clave de la institución':str,'Nombre de la institución':str})

In [16]:
bin1.head()

   BIN Clave de la institución Nombre de la institución
0  138                   40138              ABC CAPITAL
1  102                   40102            ACCENDO BANCO
2  133                   40133                 ACTINVER
3  062                   40062                   AFIRME
4  638                   90638                    AKALA

In [17]:
bin1.shape

(89, 3)

# ARCHIVO RESPUESTA

In [18]:
rs_concat['Date_respuesta'] = date_respuesta
rs_concat.rename(columns ={'bank_account_number':'CLABE'}, inplace=True)
rs_concat['BIN'] = rs_concat['CLABE'].str[:3].replace(' ', '',regex=True)
rs_concat.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,aplication_date,disbursement_tracking_key,error_description,reference_number,cep,file_name,Time_rs,INDEX,Date_respuesta,BIN
0,747LYKL4C,PAID,2022-05-16T00:00,"2,395.60",d07893bc-7789-43a3-8205-a74f46e78003,00094c06-2b54-4569-9314-00c3c213297c,659802020000471271,"Opciones Empresariales del Noreste, S.A. de C....",Guadalupe Carmen Villa Vazquez,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5AB73A85493,NaN,300001,"2022-05-16,180CD5AB73A85493,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,747LYKL4C_09:00,2022-05-16,659
1,N7GMWSNJB,PAID,2022-05-16T00:00,364.13,d07893bc-7789-43a3-8205-a74f46e78003,0018261c-b847-4346-9f11-e3f2bdc6df80,659802020000043654,"Opciones Empresariales del Noreste, S.A. de C....",Ismael Lopez Herrera,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5AB73D43FF6,NaN,300002,"2022-05-16,180CD5AB73D43FF6,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,N7GMWSNJB_09:00,2022-05-16,659
2,S49HJVPJJ,PAID,2022-05-16T00:00,30.67,d07893bc-7789-43a3-8205-a74f46e78003,0079b7bd-0713-4cf9-9b37-992cbbba9c1e,659802020000524814,"Opciones Empresariales del Noreste, S.A. de C....",Zaida Sarai Aguirre Hernandez,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5ABBCD6EE75,NaN,300003,"2022-05-16,180CD5ABBCD6EE75,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,S49HJVPJJ_09:00,2022-05-16,659
3,VH5G2Z755,PAID,2022-05-16T00:00,142.79,d07893bc-7789-43a3-8205-a74f46e78003,01054eec-e90e-42a8-9471-3fb1711cbbc1,659802020000300038,"Opciones Empresariales del Noreste, S.A. de C....",Miguel Hernandez Ramirez,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5ABA9F430B1,NaN,300004,"2022-05-16,180CD5ABA9F430B1,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,VH5G2Z755_09:00,2022-05-16,659
4,FXY83F7PY,PAID,2022-05-16T00:00,206.98,d07893bc-7789-43a3-8205-a74f46e78003,018ea728-1b9e-43ef-bc47-1de244528643,659802020000112941,"Opciones Empresariales del Noreste, S.A. de C....",Mario ivan Flores Hernandez,2022-05-16T14:45:04,2022-05-16T09:45:05,180CD5AB7A42CA70,NaN,300005,"2022-05-16,180CD5AB7A42CA70,40002,90659,659802...",Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,FXY83F7PY_09:00,2022-05-16,659

In [19]:
rs_concat.shape

(4588, 20)

In [20]:
rs_concat_2 = rs_concat.merge(bin1[['BIN','Clave de la institución','Nombre de la institución']] ,on='BIN', how='left')
rs_concat_2['Banco emisor'] = '40002'
rs_concat_2['Banco_emisor'] = 'BANAMEX'
rs_concat_2['LINEA CEP'] = (rs_concat_2['Date_respuesta'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['disbursement_tracking_key'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['Banco emisor'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['Clave de la institución'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['CLABE'].astype(str).replace(' ', '',regex=True)+','
                            +rs_concat_2['amount'].astype(str).replace(' ', '',regex=True))
rs_concat_2.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,...,file_name,Time_rs,INDEX,Date_respuesta,BIN,Clave de la institución,Nombre de la institución,Banco emisor,Banco_emisor,LINEA CEP
0,747LYKL4C,PAID,2022-05-16T00:00,"2,395.60",d07893bc-7789-43a3-8205-a74f46e78003,00094c06-2b54-4569-9314-00c3c213297c,659802020000471271,"Opciones Empresariales del Noreste, S.A. de C....",Guadalupe Carmen Villa Vazquez,2022-05-16T14:45:04,...,Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,747LYKL4C_09:00,2022-05-16,659,90659,ASP INTEGRA OPC,40002,BANAMEX,"2022-05-16,180CD5AB73A85493,40002,90659,659802..."
1,N7GMWSNJB,PAID,2022-05-16T00:00,364.13,d07893bc-7789-43a3-8205-a74f46e78003,0018261c-b847-4346-9f11-e3f2bdc6df80,659802020000043654,"Opciones Empresariales del Noreste, S.A. de C....",Ismael Lopez Herrera,2022-05-16T14:45:04,...,Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,N7GMWSNJB_09:00,2022-05-16,659,90659,ASP INTEGRA OPC,40002,BANAMEX,"2022-05-16,180CD5AB73D43FF6,40002,90659,659802..."
2,S49HJVPJJ,PAID,2022-05-16T00:00,30.67,d07893bc-7789-43a3-8205-a74f46e78003,0079b7bd-0713-4cf9-9b37-992cbbba9c1e,659802020000524814,"Opciones Empresariales del Noreste, S.A. de C....",Zaida Sarai Aguirre Hernandez,2022-05-16T14:45:04,...,Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,S49HJVPJJ_09:00,2022-05-16,659,90659,ASP INTEGRA OPC,40002,BANAMEX,"2022-05-16,180CD5ABBCD6EE75,40002,90659,659802..."
3,VH5G2Z755,PAID,2022-05-16T00:00,142.79,d07893bc-7789-43a3-8205-a74f46e78003,01054eec-e90e-42a8-9471-3fb1711cbbc1,659802020000300038,"Opciones Empresariales del Noreste, S.A. de C....",Miguel Hernandez Ramirez,2022-05-16T14:45:04,...,Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,VH5G2Z755_09:00,2022-05-16,659,90659,ASP INTEGRA OPC,40002,BANAMEX,"2022-05-16,180CD5ABA9F430B1,40002,90659,659802..."
4,FXY83F7PY,PAID,2022-05-16T00:00,206.98,d07893bc-7789-43a3-8205-a74f46e78003,018ea728-1b9e-43ef-bc47-1de244528643,659802020000112941,"Opciones Empresariales del Noreste, S.A. de C....",Mario ivan Flores Hernandez,2022-05-16T14:45:04,...,Respuesta-FP-CITI-1 2022-05-16.xlsx,09:00,FXY83F7PY_09:00,2022-05-16,659,90659,ASP INTEGRA OPC,40002,BANAMEX,"2022-05-16,180CD5AB7A42CA70,40002,90659,659802..."

In [21]:
rs_concat_2.shape

(4588, 25)

# ARCHIVO DISPERSION

In [22]:
disp1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX
batch_created_date,,,,,,,,,,,,,,,
2022-05-16 09:45:04,00094c06-2b54-4569-9314-00c3c213297c,5antas Alitas Dgo,lacosa0012@gmail.com,747LYKL4C,2022-05-16 00:00:00,"2,395.60",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Guadalupe Carmen Villa Vazquez,'659802020000471271,CITI,"Guadalupe Carmen Villa Vazquez,,2395.60,659802...",09:00,747LYKL4C_09:00
2022-05-16 09:45:04,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,N7GMWSNJB,2022-05-16 00:00:00,364.13,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:23,Ismael Lopez Herrera,'659802020000043654,CITI,"Ismael Lopez Herrera,,364.13,65980202000004365...",09:00,N7GMWSNJB_09:00
2022-05-16 09:45:04,0079b7bd-0713-4cf9-9b37-992cbbba9c1e,Zaida Sarai,zaida.sarai.aguirre.hernandez@gmail.com,S49HJVPJJ,2022-05-16 00:00:00,30.67,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Zaida Sarai Aguirre Hernandez,'659802020000524814,CITI,"Zaida Sarai Aguirre Hernandez,,30.67,659802020...",09:00,S49HJVPJJ_09:00
2022-05-16 09:45:04,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,VH5G2Z755,2022-05-16 00:00:00,142.79,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Miguel Hernandez Ramirez,'659802020000300038,CITI,"Miguel Hernandez Ramirez,,142.79,6598020200003...",09:00,VH5G2Z755_09:00
2022-05-16 09:45:04,018ea728-1b9e-43ef-bc47-1de244528643,Abarrotes Cris,plasmakoarcade69@gmail.com,FXY83F7PY,2022-05-16 00:00:00,206.98,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:24,Mario ivan Flores Hernandez,'659802020000112941,CITI,"Mario ivan Flores Hernandez,,206.98,6598020200...",09:00,FXY83F7PY_09:00

In [23]:
disp1['report_date_local'] = pd.to_datetime(disp1['report_date_local'])

In [24]:
split = disp1["swap"].str.split(",",n=7,expand=True)
split.head()

,0,1,2,3,4
batch_created_date,,,,,
2022-05-16 09:45:04,Guadalupe Carmen Villa Vazquez,,2395.60,659802020000471271,CLIP-747LYKL4C
2022-05-16 09:45:04,Ismael Lopez Herrera,,364.13,659802020000043654,CLIP-N7GMWSNJB
2022-05-16 09:45:04,Zaida Sarai Aguirre Hernandez,,30.67,659802020000524814,CLIP-S49HJVPJJ
2022-05-16 09:45:04,Miguel Hernandez Ramirez,,142.79,659802020000300038,CLIP-VH5G2Z755
2022-05-16 09:45:04,Mario ivan Flores Hernandez,,206.98,659802020000112941,CLIP-FXY83F7PY

In [25]:
disp1["swap"] = split[0] 
disp1["CLABE"] = split[3]

In [26]:
disp1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX,CLABE
batch_created_date,,,,,,,,,,,,,,,,
2022-05-16 09:45:04,00094c06-2b54-4569-9314-00c3c213297c,5antas Alitas Dgo,lacosa0012@gmail.com,747LYKL4C,2022-05-16,"2,395.60",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Guadalupe Carmen Villa Vazquez,'659802020000471271,CITI,Guadalupe Carmen Villa Vazquez,09:00,747LYKL4C_09:00,659802020000471271
2022-05-16 09:45:04,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,N7GMWSNJB,2022-05-16,364.13,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:23,Ismael Lopez Herrera,'659802020000043654,CITI,Ismael Lopez Herrera,09:00,N7GMWSNJB_09:00,659802020000043654
2022-05-16 09:45:04,0079b7bd-0713-4cf9-9b37-992cbbba9c1e,Zaida Sarai,zaida.sarai.aguirre.hernandez@gmail.com,S49HJVPJJ,2022-05-16,30.67,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Zaida Sarai Aguirre Hernandez,'659802020000524814,CITI,Zaida Sarai Aguirre Hernandez,09:00,S49HJVPJJ_09:00,659802020000524814
2022-05-16 09:45:04,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,VH5G2Z755,2022-05-16,142.79,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:25,Miguel Hernandez Ramirez,'659802020000300038,CITI,Miguel Hernandez Ramirez,09:00,VH5G2Z755_09:00,659802020000300038
2022-05-16 09:45:04,018ea728-1b9e-43ef-bc47-1de244528643,Abarrotes Cris,plasmakoarcade69@gmail.com,FXY83F7PY,2022-05-16,206.98,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2022-05-16 09:52:24,Mario ivan Flores Hernandez,'659802020000112941,CITI,Mario ivan Flores Hernandez,09:00,FXY83F7PY_09:00,659802020000112941

In [27]:
disp1.loc[disp1['report_date_local'] == date_respuesta, 'tipo'] = 'Pago del día'
disp1.loc[disp1['report_date_local'] != date_respuesta, 'tipo'] = 'Reprogramación'
disp1.drop(['bank_name','CLABE','status'],axis=1,inplace=True)
disp1.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX,tipo
batch_created_date,,,,,,,,,,,,,,
2022-05-16 09:45:04,00094c06-2b54-4569-9314-00c3c213297c,5antas Alitas Dgo,lacosa0012@gmail.com,747LYKL4C,2022-05-16,"2,395.60",2022-05-16 09:52:25,Guadalupe Carmen Villa Vazquez,'659802020000471271,CITI,Guadalupe Carmen Villa Vazquez,09:00,747LYKL4C_09:00,Pago del día
2022-05-16 09:45:04,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,N7GMWSNJB,2022-05-16,364.13,2022-05-16 09:52:23,Ismael Lopez Herrera,'659802020000043654,CITI,Ismael Lopez Herrera,09:00,N7GMWSNJB_09:00,Pago del día
2022-05-16 09:45:04,0079b7bd-0713-4cf9-9b37-992cbbba9c1e,Zaida Sarai,zaida.sarai.aguirre.hernandez@gmail.com,S49HJVPJJ,2022-05-16,30.67,2022-05-16 09:52:25,Zaida Sarai Aguirre Hernandez,'659802020000524814,CITI,Zaida Sarai Aguirre Hernandez,09:00,S49HJVPJJ_09:00,Pago del día
2022-05-16 09:45:04,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,VH5G2Z755,2022-05-16,142.79,2022-05-16 09:52:25,Miguel Hernandez Ramirez,'659802020000300038,CITI,Miguel Hernandez Ramirez,09:00,VH5G2Z755_09:00,Pago del día
2022-05-16 09:45:04,018ea728-1b9e-43ef-bc47-1de244528643,Abarrotes Cris,plasmakoarcade69@gmail.com,FXY83F7PY,2022-05-16,206.98,2022-05-16 09:52:24,Mario ivan Flores Hernandez,'659802020000112941,CITI,Mario ivan Flores Hernandez,09:00,FXY83F7PY_09:00,Pago del día

In [28]:
disp_2 = disp1.merge(rs_concat_2[['report_id','status','Nombre de la institución','CLABE','LINEA CEP','Time_rs','Banco_emisor']]
                     ,on='report_id', how='left')
disp_2.sort_values(by=['status'])
disp_2["Time"].fillna('NO TIME',inplace=True)
disp_2.loc[disp_2['Time'] == 'NO TIME', 'status'] = 'ERROR'
disp_2.loc[(disp_2['LINEA CEP'].str.contains('nan')) & (['Nombre de la institución'] == 'BANAMEX'), 'status'] = 'ERROR'
# disp_2.loc[pd.notnull(disp_2['error_description']), 'status'] = 'ERROR'
disp_2.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,amount,payment_date_local,bank_account_owner_name,bank_account_number,disbursement_method,swap,Time,INDEX,tipo,status,Nombre de la institución,CLABE,LINEA CEP,Time_rs,Banco_emisor
0,00094c06-2b54-4569-9314-00c3c213297c,5antas Alitas Dgo,lacosa0012@gmail.com,747LYKL4C,2022-05-16,"2,395.60",2022-05-16 09:52:25,Guadalupe Carmen Villa Vazquez,'659802020000471271,CITI,Guadalupe Carmen Villa Vazquez,09:00,747LYKL4C_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000471271,"2022-05-16,180CD5AB73A85493,40002,90659,659802...",09:00,BANAMEX
1,0018261c-b847-4346-9f11-e3f2bdc6df80,Taqueria El Aguila,ismael200884@gmail.com,N7GMWSNJB,2022-05-16,364.13,2022-05-16 09:52:23,Ismael Lopez Herrera,'659802020000043654,CITI,Ismael Lopez Herrera,09:00,N7GMWSNJB_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000043654,"2022-05-16,180CD5AB73D43FF6,40002,90659,659802...",09:00,BANAMEX
2,0079b7bd-0713-4cf9-9b37-992cbbba9c1e,Zaida Sarai,zaida.sarai.aguirre.hernandez@gmail.com,S49HJVPJJ,2022-05-16,30.67,2022-05-16 09:52:25,Zaida Sarai Aguirre Hernandez,'659802020000524814,CITI,Zaida Sarai Aguirre Hernandez,09:00,S49HJVPJJ_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000524814,"2022-05-16,180CD5ABBCD6EE75,40002,90659,659802...",09:00,BANAMEX
3,01054eec-e90e-42a8-9471-3fb1711cbbc1,Abarrotes La Perla De Magon,laperlademagon2021@hotmail.com,VH5G2Z755,2022-05-16,142.79,2022-05-16 09:52:25,Miguel Hernandez Ramirez,'659802020000300038,CITI,Miguel Hernandez Ramirez,09:00,VH5G2Z755_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000300038,"2022-05-16,180CD5ABA9F430B1,40002,90659,659802...",09:00,BANAMEX
4,018ea728-1b9e-43ef-bc47-1de244528643,Abarrotes Cris,plasmakoarcade69@gmail.com,FXY83F7PY,2022-05-16,206.98,2022-05-16 09:52:24,Mario ivan Flores Hernandez,'659802020000112941,CITI,Mario ivan Flores Hernandez,09:00,FXY83F7PY_09:00,Pago del día,PAID,ASP INTEGRA OPC,659802020000112941,"2022-05-16,180CD5AB7A42CA70,40002,90659,659802...",09:00,BANAMEX

In [29]:
disp_2.loc[disp_2['Nombre de la institución'] == 'BANAMEX', 'LINEA CEP'] = 'COMPROBANTE MISMO BANCO BANAMEX'
disp_2.loc[disp_2['status'] == 'ERROR', 'LINEA CEP'] = ''

In [30]:
for col in disp_2.columns: 
    print(col)

merchant_id
merchant_name
user_email
report_id
report_date_local
amount
payment_date_local
bank_account_owner_name
bank_account_number
disbursement_method
swap
Time
INDEX
tipo
status
Nombre de la institución
CLABE
LINEA CEP
Time_rs
Banco_emisor

In [31]:
disp_final = disp_2[['merchant_id','merchant_name','user_email','report_id','report_date_local','amount','tipo'
                    ,'Nombre de la institución','swap','CLABE','status','LINEA CEP','Time','Banco_emisor']]
disp_final.rename(columns ={'Nombre de la institución':'bank','amount':'total_due','LINEA CEP':'CEP'}, inplace=True)
disp_final.sort_values(by=['status','Time'], ascending=True, inplace=True)
disp_final.drop_duplicates(subset =['report_id','Time'], keep ='first', inplace=True)
disp_final.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1713376454.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.rename(columns ={'Nombre de la institución':'bank','amount':'total_due','LINEA CEP':'CEP'}, inplace=True)
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1713376454.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.sort_values(by=['status','Time'], ascending=True, inplace=True)
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\1713376454.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.drop_duplicates(subset =['report_id','Time'], keep ='first', inplace=True)

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor
31,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,938TN57DC,2022-05-16,376.59,Pago del día,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,659802020000003995,ERROR,,09:00,BANAMEX
313,54b6d102-672f-4ab8-a56d-c2255259b4b6,MARA CONCEPT STORE,xio_lq@hotmail.com,2Q48FZMHC,2022-05-16,186.86,Pago del día,ASP INTEGRA OPC,Zulma Xiomara Lopez Quevedo,659802020000482121,ERROR,,09:00,BANAMEX
400,6e066b8c-135f-4959-b163-9fcbfc542f6b,Modelorama GONZÁLEZ,Lacatesca.oficial@gmail.com,ZBVLSN79P,2022-05-16,967.19,Pago del día,ASP INTEGRA OPC,Luis Armando Montelongo Flores,659802020000117726,ERROR,,09:00,BANAMEX
473,81c1483b-df15-4c1b-8d46-952dd08c3164,Taqueria Los Piratas #2,Jorgeheredia8enero@hotmail.com,FDJY8LPZM,2022-05-16,"1,768.92",Pago del día,ASP INTEGRA OPC,Jorge Alberto Heredia Alvarado,659802020000497226,ERROR,,09:00,BANAMEX
754,cb8d211b-a878-41c1-bae0-a0a08a0be599,Mini super la raquelita,axellongo31@gmail.com,RWK2PXDVG,2022-05-16,"1,198.76",Pago del día,ASP INTEGRA OPC,Axel Morales Orozco,659802020000010917,ERROR,,09:00,BANAMEX

In [32]:
disp_final.shape

(4588, 14)

# ERROR

In [33]:
error = disp_final[(disp_final['status'] != 'PAID')]
error.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,swap,CLABE,status,CEP,Time,Banco_emisor
31,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,938TN57DC,2022-05-16,376.59,Pago del día,ASP INTEGRA OPC,Jose De Jesus Reyes Rivera,659802020000003995,ERROR,,09:00,BANAMEX
313,54b6d102-672f-4ab8-a56d-c2255259b4b6,MARA CONCEPT STORE,xio_lq@hotmail.com,2Q48FZMHC,2022-05-16,186.86,Pago del día,ASP INTEGRA OPC,Zulma Xiomara Lopez Quevedo,659802020000482121,ERROR,,09:00,BANAMEX
400,6e066b8c-135f-4959-b163-9fcbfc542f6b,Modelorama GONZÁLEZ,Lacatesca.oficial@gmail.com,ZBVLSN79P,2022-05-16,967.19,Pago del día,ASP INTEGRA OPC,Luis Armando Montelongo Flores,659802020000117726,ERROR,,09:00,BANAMEX
473,81c1483b-df15-4c1b-8d46-952dd08c3164,Taqueria Los Piratas #2,Jorgeheredia8enero@hotmail.com,FDJY8LPZM,2022-05-16,"1,768.92",Pago del día,ASP INTEGRA OPC,Jorge Alberto Heredia Alvarado,659802020000497226,ERROR,,09:00,BANAMEX
754,cb8d211b-a878-41c1-bae0-a0a08a0be599,Mini super la raquelita,axellongo31@gmail.com,RWK2PXDVG,2022-05-16,"1,198.76",Pago del día,ASP INTEGRA OPC,Axel Morales Orozco,659802020000010917,ERROR,,09:00,BANAMEX

In [34]:
error.shape

(35, 14)

In [35]:
error.drop(['swap','CLABE','status','CEP','Banco_emisor'],axis=1,inplace=True)

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\3363876278.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  error.drop(['swap','CLABE','status','CEP','Banco_emisor'],axis=1,inplace=True)

In [36]:
error_final = error
error_final.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,Time
31,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,938TN57DC,2022-05-16,376.59,Pago del día,ASP INTEGRA OPC,09:00
313,54b6d102-672f-4ab8-a56d-c2255259b4b6,MARA CONCEPT STORE,xio_lq@hotmail.com,2Q48FZMHC,2022-05-16,186.86,Pago del día,ASP INTEGRA OPC,09:00
400,6e066b8c-135f-4959-b163-9fcbfc542f6b,Modelorama GONZÁLEZ,Lacatesca.oficial@gmail.com,ZBVLSN79P,2022-05-16,967.19,Pago del día,ASP INTEGRA OPC,09:00
473,81c1483b-df15-4c1b-8d46-952dd08c3164,Taqueria Los Piratas #2,Jorgeheredia8enero@hotmail.com,FDJY8LPZM,2022-05-16,"1,768.92",Pago del día,ASP INTEGRA OPC,09:00
754,cb8d211b-a878-41c1-bae0-a0a08a0be599,Mini super la raquelita,axellongo31@gmail.com,RWK2PXDVG,2022-05-16,"1,198.76",Pago del día,ASP INTEGRA OPC,09:00

In [37]:
error.loc[error['bank'] == 'BANAMEX', 'Check'] = 'SPEI DEVUELTO MISMO BANCO'
error.loc[error['bank'] != 'BANAMEX', 'Check'] = 'SPEI DEVUELTO'

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_17804\2969446146.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  error.loc[error['bank'] == 'BANAMEX', 'Check'] = 'SPEI DEVUELTO MISMO BANCO'

In [38]:
error.shape

(35, 10)

In [39]:
error_final = error.merge(rs_concat_2[['report_id','error_description']],on='report_id',how='left')
error_final.head()

,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,Time,Check,error_description
0,06e0a5e4-a369-43fd-829c-9d52041f2292,Carniceria Reyes,joseriverareyes1@hotmail.com,938TN57DC,2022-05-16,376.59,Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,/21/CB Return Exceeds the limit of credits all...
1,54b6d102-672f-4ab8-a56d-c2255259b4b6,MARA CONCEPT STORE,xio_lq@hotmail.com,2Q48FZMHC,2022-05-16,186.86,Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,/21/CB Return Exceeds the limit of credits all...
2,6e066b8c-135f-4959-b163-9fcbfc542f6b,Modelorama GONZÁLEZ,Lacatesca.oficial@gmail.com,ZBVLSN79P,2022-05-16,967.19,Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,/21/CB Return Exceeds the limit of credits all...
3,81c1483b-df15-4c1b-8d46-952dd08c3164,Taqueria Los Piratas #2,Jorgeheredia8enero@hotmail.com,FDJY8LPZM,2022-05-16,"1,768.92",Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,/21/CB Return Exceeds the limit of credits all...
4,cb8d211b-a878-41c1-bae0-a0a08a0be599,Mini super la raquelita,axellongo31@gmail.com,RWK2PXDVG,2022-05-16,"1,198.76",Pago del día,ASP INTEGRA OPC,09:00,SPEI DEVUELTO,/21/CB Return Exceeds the limit of credits all...

In [40]:
error_final.shape

(35, 11)

# ARCHIVOS FINALES

### ARCHIVO DISPERSION

In [42]:
writer = pd.ExcelWriter(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\05. MAYO\ARCHIVO DISPERSIONES FP\CITI\Dispersión-FP-CITI 2022-05-16.xlsx',
                        engine='xlsxwriter', engine_kwargs={'options': {'encoding':'utf-8'}})
disp_final.to_excel(writer, sheet_name='FAST PAYMENTS',index=False)
error_final.to_excel(writer, sheet_name='ERROR',index=False)
writer.close()

### ARCHIVO DISPERSIÓN - TODO POR CITI

In [43]:
writer = pd.ExcelWriter(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\05. MAYO\ARCHIVO DISPERSIONES FP\Dispersión-FP 2022-05-16.xlsx',
                        engine='xlsxwriter', engine_kwargs={'options': {'encoding':'utf-8'}})
disp_final.to_excel(writer, sheet_name='FAST PAYMENTS',index=False)
error_final.to_excel(writer, sheet_name='ERROR',index=False)
writer.close()

### ARCHIVO RESPUESTA

In [44]:
rs_concat.to_csv(r'C:\Users\Cristian.Aparicio\Documents\FAST PAYMENTS\2022\05. MAYO\ARCHIVO RESPUESTAS FINALES\Respuesta-FP-CITI 2022-05-16.csv',index=False)

In [ ]:
# book = load_workbook('Dispersión-FP 2020-07-20.xlsx')
# writer = pd.ExcelWriter('Dispersión-FP 2020-07-20.xlsx', engine='openpyxl', options={'encoding':'utf-8'})
# writer.book = book
# match_final.to_excel(writer, sheet_name='FP-2 2020-07-20', index=False)
# writer.save()
# writer.close()