In [1]:
import numpy as np
import pandas as pd
import zipfile
from zipfile import ZipFile
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# SFTP

## HEADERS

In [2]:
name_file=['column_type','affiliation_sftp','merchant_reference','card','settled_amount','commisions','transaction_date',
           'gross_amount','currency','transaction_type','tax','installments_tax','iva_cashback_paid','iva_cashback_charged',
          'cashback_fees_paid','cashback_fees_charged','installments_fees','cashback_amount','number_of_payments',
           'initial_deferment','plan_type','auth_code','unknown.1','eci','interbank_reference','empty.1','unknown.2','empty.2',
          'payworks_reference','card_type','transaction_source','prosa_reference','acquirer_commision','acquirer_tax',
          'unknown.3','unknown.4','unknown.5']
dtypes_file={'interbank_reference':object,'affiliation_sftp':object,'card':object,'number_of_payments':object,
             'initial_deferment':object,'plan_type':object,'auth_code':object,'payworks_reference':object,'eci':object}

In [3]:
use_cols = ['affiliation_sftp','transaction_type','transaction_date','eci','auth_code','interbank_reference',
            'payworks_reference','card','gross_amount','commisions','tax','installments_fees','installments_tax',
            'acquirer_commision','acquirer_tax','card_type','number_of_payments','initial_deferment']

### SEPTIEMBRE 2023

In [4]:
sftp_sep_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\09. SEPTIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_sep_1_23

['G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\09. SEPTIEMBRE\\01092023\\PAYCLIP_Settlement_01092023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\09. SEPTIEMBRE\\02092023\\PAYCLIP_Settlement_02092023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\09. SEPTIEMBRE\\05092023\\PAYCLIP_Settlement_05092023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\09. SEPTIEMBRE\\06092023\\PAYCLIP_Settlement_06092023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\09. SEPTIEMBRE\\07092023\\PAYCLIP_Settlement_07092023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\09. SEPTIEMBRE\\08092023\\PAYCLIP_Settlement_08092023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\09. SEPTIEMBRE\\09092023\\PAYCLIP_Settlement_09092023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\09. SEPTIEMBRE\\12092023\\PAYCLIP_Settlement_12092023_V1.csv']

In [5]:
sftp_sep_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_sep_1_23])
sftp_sep_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_sep_23['date_file'] = sftp_sep_23["file_name"].str[-15:-7]
sftp_sep_23['date_file']= pd.to_datetime(sftp_sep_23['date_file'], format='%d%m%Y').dt.date
sftp_sep_23['date_file']= pd.to_datetime(sftp_sep_23['date_file'])
sftp_sep_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_sep_23['month'] = sftp_sep_23['date_file'].dt.strftime('%B')
sftp_sep_23.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-320088939,470573,3108231,20230831,BANORTE,20230831,3108231,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_01092023_V1.csv,2023-09-01,September
313722,07927517,4217470025,-25,20230830,2090,SETTLED,-4,0,0.00,00,...,099120,74518993242725079275174,472751306706,NaN,D,-25.00,-4.00,PAYCLIP_Settlement_01092023_V1.csv,2023-09-01,September
313721,07927517,4152313857,-18,20230830,1500,SETTLED,-3,0,0.00,00,...,809444,74518993242232979275172,619976426691,NaN,D,-18.00,-3.00,PAYCLIP_Settlement_01092023_V1.csv,2023-09-01,September
313720,07927517,5267770883,-934,20230830,50500,SETTLED,-149,0,0.00,00,...,904949,75445503242184379275173,817410984389,NaN,C,-934.00,-149.00,PAYCLIP_Settlement_01092023_V1.csv,2023-09-01,September
313719,07927517,5579070040,-437,20230830,35800,SETTLED,-70,0,0.00,00,...,072475,75445503242388879275175,132869017960,NaN,D,-437.00,-70.00,PAYCLIP_Settlement_01092023_V1.csv,2023-09-01,September

In [6]:
sftp_sep_23.shape

(6034768, 21)

### AGOSTO 2023

In [7]:
sftp_aug_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\08. AGOSTO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_aug_1_23

['G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\01082023\\PAYCLIP_Settlement_01082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\02082023\\PAYCLIP_Settlement_02082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\03082023\\PAYCLIP_Settlement_03082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\04082023\\PAYCLIP_Settlement_04082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\05082023\\PAYCLIP_Settlement_05082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\08082023\\PAYCLIP_Settlement_08082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\09082023\\PAYCLIP_Settlement_09082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\10082023\\PAYCLIP_Settlement_10082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\11082023\\PAYCLIP_Settlement_11082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\12082023\\PAYCLIP_Settlement_12082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\15082023\\PAYCLIP_Settlement_15082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\16082023\\PAYCLIP_Settlement_16082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\17082023\\PAYCLIP_Settlement_17082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\18082023\\PAYCLIP_Settlement_18082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\19082023\\PAYCLIP_Settlement_19082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\22082023\\PAYCLIP_Settlement_22082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\23082023\\PAYCLIP_Settlement_23082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\24082023\\PAYCLIP_Settlement_24082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\25082023\\PAYCLIP_Settlement_25082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\26082023\\PAYCLIP_Settlement_26082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\29082023\\PAYCLIP_Settlement_29082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\30082023\\PAYCLIP_Settlement_30082023_V1.csv',
 'G:\\.shortcut-targets-by-id\\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\\2.-CONCILIACIONES Y POLIZA\\SFTP BANORTE\\2023 SFTP Banorte\\08. AGOSTO\\31082023\\PAYCLIP_Settlement_31082023_V1.csv']

In [8]:
sftp_aug_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_aug_1_23])
sftp_aug_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_aug_23['date_file'] = sftp_aug_23["file_name"].str[-15:-7]
sftp_aug_23['date_file']= pd.to_datetime(sftp_aug_23['date_file'], format='%d%m%Y').dt.date
sftp_aug_23['date_file']= pd.to_datetime(sftp_aug_23['date_file'])
sftp_aug_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_aug_23['month'] = sftp_aug_23['date_file'].dt.strftime('%B')
sftp_aug_23.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-1040317733,1535033,3107231,20230731,BANORTE,20230731,3107231,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August
1023361,07927517,4152313482,-342,20230728,28000,SETTLED,-55,0,0.00,00,...,680023,74518993209440579275176,909149323632,NaN,D,-342.00,-55.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August
1023360,07927517,4152313986,-403,20230728,33000,SETTLED,-64,0,0.00,00,...,680002,74518993209829079275175,160563947080,NaN,D,-403.00,-64.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August
1023359,07927517,4152314152,-791,20230728,64800,SETTLED,-127,0,0.00,00,...,679667,74518993209144979275170,897350076086,NaN,D,-791.00,-127.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August
1023358,07927517,5579070026,-1251,20230728,102500,SETTLED,-200,0,0.00,00,...,085574,75445503209033579275171,501647141594,NaN,D,"-1,251.00",-200.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August

In [9]:
sftp_aug_23.shape

(15527546, 21)

### JULIO 2023

In [ ]:
sftp_jul_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\07. JULIO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_jul_1_23

In [ ]:
sftp_jul_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jul_1_23])
sftp_jul_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jul_23['date_file'] = sftp_jul_23["file_name"].str[-15:-7]
sftp_jul_23['date_file']= pd.to_datetime(sftp_jul_23['date_file'], format='%d%m%Y').dt.date
sftp_jul_23['date_file']= pd.to_datetime(sftp_jul_23['date_file'])
sftp_jul_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jul_23['month'] = sftp_jul_23['date_file'].dt.strftime('%B')
sftp_jul_23.head()

In [ ]:
sftp_jul_23.shape

### JUNIO 2023

In [ ]:
sftp_jun_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\06. JUNIO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_jun_1_23

In [ ]:
sftp_jun_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jun_1_23])
sftp_jun_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jun_23['date_file'] = sftp_jun_23["file_name"].str[-15:-7]
sftp_jun_23['date_file']= pd.to_datetime(sftp_jun_23['date_file'], format='%d%m%Y').dt.date
sftp_jun_23['date_file']= pd.to_datetime(sftp_jun_23['date_file'])
sftp_jun_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jun_23['month'] = sftp_jun_23['date_file'].dt.strftime('%B')
sftp_jun_23.head()

In [ ]:
sftp_jun_23.shape

### MAYO 2023

In [ ]:
sftp_may_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\05. MAYO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_may_1_23

In [ ]:
sftp_may_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_may_1_23])
sftp_may_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_may_23['date_file'] = sftp_may_23["file_name"].str[-15:-7]
sftp_may_23['date_file']= pd.to_datetime(sftp_may_23['date_file'], format='%d%m%Y').dt.date
sftp_may_23['date_file']= pd.to_datetime(sftp_may_23['date_file'])
sftp_may_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_may_23['month'] = sftp_may_23['date_file'].dt.strftime('%B')
sftp_may_23.head()

In [ ]:
sftp_may_23.shape

### ABRIL 2023

In [ ]:
sftp_apr_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\04. ABRIL\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_apr_1_23

In [ ]:
sftp_apr_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_apr_1_23])
sftp_apr_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_apr_23['date_file'] = sftp_apr_23["file_name"].str[-15:-7]
sftp_apr_23['date_file']= pd.to_datetime(sftp_apr_23['date_file'], format='%d%m%Y').dt.date
sftp_apr_23['date_file']= pd.to_datetime(sftp_apr_23['date_file'])
sftp_apr_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_apr_23['month'] = sftp_apr_23['date_file'].dt.strftime('%B')
sftp_apr_23.head()

In [ ]:
sftp_apr_23.shape

### MARZO 2023

In [ ]:
sftp_mar_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\03. MARZO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_mar_1_23

In [ ]:
sftp_mar_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_mar_1_23])
sftp_mar_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_mar_23['date_file'] = sftp_mar_23["file_name"].str[-15:-7]
sftp_mar_23['date_file']= pd.to_datetime(sftp_mar_23['date_file'], format='%d%m%Y').dt.date
sftp_mar_23['date_file']= pd.to_datetime(sftp_mar_23['date_file'])
sftp_mar_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_mar_23['month'] = sftp_mar_23['date_file'].dt.strftime('%B')
sftp_mar_23.head()

In [ ]:
sftp_mar_23.shape

### FEBRERO 2023

In [ ]:
sftp_feb_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\02. FEBRERO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_feb_1_23

In [ ]:
sftp_feb_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_feb_1_23])
sftp_feb_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_feb_23['date_file'] = sftp_feb_23["file_name"].str[-15:-7]
sftp_feb_23['date_file']= pd.to_datetime(sftp_feb_23['date_file'], format='%d%m%Y').dt.date
sftp_feb_23['date_file']= pd.to_datetime(sftp_feb_23['date_file'])
sftp_feb_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_feb_23['month'] = sftp_feb_23['date_file'].dt.strftime('%B')
sftp_feb_23.head()

In [ ]:
sftp_feb_23.shape

### ENERO 2023

In [ ]:
sftp_jan_1_23 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2023 SFTP Banorte\01. ENERO\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_jan_1_23

In [ ]:
sftp_jan_23 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_jan_1_23])
sftp_jan_23.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_jan_23['date_file'] = sftp_jan_23["file_name"].str[-15:-7]
sftp_jan_23['date_file']= pd.to_datetime(sftp_jan_23['date_file'], format='%d%m%Y').dt.date
sftp_jan_23['date_file']= pd.to_datetime(sftp_jan_23['date_file'])
sftp_jan_23.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_jan_23['month'] = sftp_jan_23['date_file'].dt.strftime('%B')
sftp_jan_23.head()

In [ ]:
sftp_jan_23.shape

### DICIEMBRE 2022

In [ ]:
sftp_dec_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\12. DICIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_dec_1_22

In [ ]:
sftp_dec_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_dec_1_22])
sftp_dec_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_dec_22['date_file'] = sftp_dec_22["file_name"].str[-15:-7]
sftp_dec_22['date_file']= pd.to_datetime(sftp_dec_22['date_file'], format='%d%m%Y').dt.date
sftp_dec_22['date_file']= pd.to_datetime(sftp_dec_22['date_file'])
sftp_dec_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_dec_22['month'] = sftp_dec_22['date_file'].dt.strftime('%B')
sftp_dec_22.head()

In [ ]:
sftp_dec_22.shape

### NOVIEMBRE 2022

In [ ]:
sftp_nov_1_22 = sorted(glob.glob(r'G:\.shortcut-targets-by-id\1dIw3KdQWk6HAGd7cIi1VZsIyka0tkfYi\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2022 SFTP Banorte\11. NOVIEMBRE\**\PAYCLIP_Settlement*.csv', recursive=False))
sftp_nov_1_22

In [ ]:
sftp_nov_22 = pd.concat([pd.read_csv(f,names=name_file,dtype=dtypes_file,usecols=use_cols)
                         .assign(file_name=os.path.basename(f)) for f in sftp_nov_1_22])
sftp_nov_22.rename(columns ={'interbank_reference':'order_id','auth_code':'codigo_autorizacion',
                             'payworks_reference':'order_id_xpay'}, inplace=True)
sftp_nov_22['date_file'] = sftp_nov_22["file_name"].str[-15:-7]
sftp_nov_22['date_file']= pd.to_datetime(sftp_nov_22['date_file'], format='%d%m%Y').dt.date
sftp_nov_22['date_file']= pd.to_datetime(sftp_nov_22['date_file'])
sftp_nov_22.sort_values(by=['date_file'],ascending=True,inplace=True)
sftp_nov_22['month'] = sftp_nov_22['date_file'].dt.strftime('%B')
sftp_nov_22.head()

In [ ]:
sftp_nov_22.shape

# ALL SFTP

In [10]:
sftp = pd.concat([sftp_aug_23,sftp_sep_23])
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,codigo_autorizacion,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month
0,MXN,-1040317733,1535033,3107231,20230731,BANORTE,20230731,3107231,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August
1023361,07927517,4152313482,-342,20230728,28000,SETTLED,-55,0,0.00,00,...,680023,74518993209440579275176,909149323632,NaN,D,-342.00,-55.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August
1023360,07927517,4152313986,-403,20230728,33000,SETTLED,-64,0,0.00,00,...,680002,74518993209829079275175,160563947080,NaN,D,-403.00,-64.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August
1023359,07927517,4152314152,-791,20230728,64800,SETTLED,-127,0,0.00,00,...,679667,74518993209144979275170,897350076086,NaN,D,-791.00,-127.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August
1023358,07927517,5579070026,-1251,20230728,102500,SETTLED,-200,0,0.00,00,...,085574,75445503209033579275171,501647141594,NaN,D,"-1,251.00",-200.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August

In [11]:
sftp.shape

(21562314, 21)

In [12]:
sftp_fecha_deposito = sftp[(sftp['transaction_type'] == 'BANORTE')]
sftp_fecha_deposito = sftp_fecha_deposito[['date_file', 'gross_amount']]
sftp_fecha_deposito.rename(columns ={'gross_amount': 'deposit_date'},inplace=True)
sftp_fecha_deposito.head()

   date_file  deposit_date
0 2023-08-01      20230731
0 2023-08-02      20230801
0 2023-08-03      20230802
0 2023-08-04      20230803
0 2023-08-05      20230804

In [13]:
sftp = sftp[(sftp['transaction_type'] != 'BANORTE')]
sftp = sftp.merge(sftp_fecha_deposito[['date_file', 'deposit_date']],on='date_file',how='left')

In [14]:
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,eci,order_id,order_id_xpay,card_type,acquirer_commision,acquirer_tax,file_name,date_file,month,deposit_date
0,07927517,4152313482,-342,20230728,28000,SETTLED,-55,0,0.00,00,...,74518993209440579275176,909149323632,NaN,D,-342.00,-55.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,20230731
1,07927517,4152313986,-403,20230728,33000,SETTLED,-64,0,0.00,00,...,74518993209829079275175,160563947080,NaN,D,-403.00,-64.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,20230731
2,07927517,4152314152,-791,20230728,64800,SETTLED,-127,0,0.00,00,...,74518993209144979275170,897350076086,NaN,D,-791.00,-127.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,20230731
3,07927517,5579070026,-1251,20230728,102500,SETTLED,-200,0,0.00,00,...,75445503209033579275171,501647141594,NaN,D,"-1,251.00",-200.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,20230731
4,07927517,5204164891,-803,20230728,65800,SETTLED,-128,0,0.00,00,...,75445503209282379275176,139629771522,NaN,D,-803.00,-128.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,20230731

In [15]:
sftp['transaction_type'].unique()

array(['SETTLED', 'REFUNDED', 'CHARGE_BACK'], dtype=object)

In [16]:
sftp['transaction_date'] = pd.to_datetime(sftp['transaction_date'], format='%Y%m%d').dt.date
sftp['deposit_date'] = pd.to_datetime(sftp['deposit_date'], format='%Y%m%d').dt.date

In [17]:
sftp['transaction_date'] = pd.to_datetime(sftp['transaction_date'])
sftp['deposit_date'] = pd.to_datetime(sftp['deposit_date'])

In [18]:
sftp['gross_amount'] = sftp['gross_amount']/100
sftp['commisions'] = sftp['commisions']/100
sftp['tax'] = sftp['tax']/100
sftp['installments_fees'] = sftp['installments_fees']/100
sftp['installments_tax'] = sftp['installments_tax']/100
sftp['acquirer_commision'] = sftp['acquirer_commision']/100
sftp['acquirer_tax'] = sftp['acquirer_tax']/100
sftp.loc[sftp['transaction_type'] != 'SETTLED', 'gross_amount'] = sftp['gross_amount']*-1
sftp['LAST2_SFTP'] = sftp['card'].str[-2:].astype(str)
sftp['BIN_SFTP'] = sftp['card'].str[:6].astype(str)
sftp['INDEX_TOTAL'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['INDEX_TOTAL_XPAY'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['order_id_xpay'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['INDEX_COD_AUTH'] = (sftp['BIN_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['LAST2_SFTP'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['codigo_autorizacion'].astype(str).replace(' ', '',regex=True)+'_'
                       +sftp['gross_amount'].astype(str).replace(' ', '',regex=True))
sftp['order_id'].fillna('NO EXISTE EN SFTP',inplace=True)
sftp.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
0,07927517,4152313482,-3.42,2023-07-28,280.00,SETTLED,-0.55,0.00,0.00,00,...,-0.55,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,82,415231,415231_82_909149323632_280.0,415231_82_nan_280.0,415231_82_680023_280.0
1,07927517,4152313986,-4.03,2023-07-28,330.00,SETTLED,-0.64,0.00,0.00,00,...,-0.64,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,86,415231,415231_86_160563947080_330.0,415231_86_nan_330.0,415231_86_680002_330.0
2,07927517,4152314152,-7.91,2023-07-28,648.00,SETTLED,-1.27,0.00,0.00,00,...,-1.27,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,52,415231,415231_52_897350076086_648.0,415231_52_nan_648.0,415231_52_679667_648.0
3,07927517,5579070026,-12.51,2023-07-28,"1,025.00",SETTLED,-2.00,0.00,0.00,00,...,-2.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,26,557907,557907_26_501647141594_1025.0,557907_26_nan_1025.0,557907_26_085574_1025.0
4,07927517,5204164891,-8.03,2023-07-28,658.00,SETTLED,-1.28,0.00,0.00,00,...,-1.28,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,91,520416,520416_91_139629771522_658.0,520416_91_nan_658.0,520416_91_024060_658.0

In [19]:
sftp.shape

(21562283, 27)

In [20]:
sftp['affiliation_sftp'].fillna('NULL',inplace=True)

# DATA POR AFILIACION

In [21]:
sftp_por_afiliacion = sftp.loc[sftp['affiliation_sftp'].isin(['07927517'])]
sftp_por_afiliacion.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
0,07927517,4152313482,-3.42,2023-07-28,280.00,SETTLED,-0.55,0.00,0.00,00,...,-0.55,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,82,415231,415231_82_909149323632_280.0,415231_82_nan_280.0,415231_82_680023_280.0
1,07927517,4152313986,-4.03,2023-07-28,330.00,SETTLED,-0.64,0.00,0.00,00,...,-0.64,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,86,415231,415231_86_160563947080_330.0,415231_86_nan_330.0,415231_86_680002_330.0
2,07927517,4152314152,-7.91,2023-07-28,648.00,SETTLED,-1.27,0.00,0.00,00,...,-1.27,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,52,415231,415231_52_897350076086_648.0,415231_52_nan_648.0,415231_52_679667_648.0
3,07927517,5579070026,-12.51,2023-07-28,"1,025.00",SETTLED,-2.00,0.00,0.00,00,...,-2.00,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,26,557907,557907_26_501647141594_1025.0,557907_26_nan_1025.0,557907_26_085574_1025.0
4,07927517,5204164891,-8.03,2023-07-28,658.00,SETTLED,-1.28,0.00,0.00,00,...,-1.28,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,91,520416,520416_91_139629771522_658.0,520416_91_nan_658.0,520416_91_024060_658.0

In [22]:
sftp_por_afiliacion.shape

(7706157, 27)

In [23]:
sftp_por_afiliacion['affiliation_sftp'].unique()

array(['07927517'], dtype=object)

In [24]:
sftp_por_cod_auth = sftp_por_afiliacion.loc[sftp_por_afiliacion['codigo_autorizacion'].isin(['007060'])]
sftp_por_cod_auth.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
167801,07927517,4931720082,-8.85,2023-07-28,478.50,SETTLED,-1.42,0.00,0.00,00,...,-1.42,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,82,493172,493172_82_779444361069_478.5,493172_82_nan_478.5,493172_82_007060_478.5
395780,07927517,4772913024,-3.66,2023-07-30,198.00,SETTLED,-0.59,0.00,0.00,00,...,-0.59,PAYCLIP_Settlement_01082023_V1.csv,2023-08-01,August,2023-07-31,24,477291,477291_24_450285032619_198.0,477291_24_nan_198.0,477291_24_007060_198.0
1577116,07927517,4213166104,-4.03,2023-07-31,330.00,SETTLED,-0.64,0.00,0.00,00,...,-0.64,PAYCLIP_Settlement_02082023_V1.csv,2023-08-02,August,2023-08-01,04,421316,421316_04_831018532466_330.0,421316_04_nan_330.0,421316_04_007060_330.0
1736685,07927517,4152314007,-6.17,2023-07-31,506.00,SETTLED,-0.99,0.00,0.00,00,...,-0.99,PAYCLIP_Settlement_02082023_V1.csv,2023-08-02,August,2023-08-01,07,415231,415231_07_783740835372_506.0,415231_07_nan_506.0,415231_07_007060_506.0
2155884,07927517,4931730046,-1.30,2023-08-01,70.00,SETTLED,-0.21,0.00,0.00,00,...,-0.21,PAYCLIP_Settlement_03082023_V1.csv,2023-08-03,August,2023-08-02,46,493173,493173_46_660035772324_70.0,493173_46_nan_70.0,493173_46_007060_70.0

In [25]:
sftp_por_cod_auth.shape

(44, 27)

In [26]:
sftp_por_cod_auth.to_excel('DATA FINAL AFILIACION DISPUTAS BNTE 2023.09.12.xlsx',index=False)

# CHECKS

### QUERIES DB

In [28]:
ticket_zendesk = pd.read_csv('DISPUTAS BNTE 2023.09.12.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object
                                                  ,'last4':object,'order_id':object})
# ticket_zendesk = pd.read_csv('DISPUTAS BNTE 2023.09.11.csv',dtype={'AMOUNT':float,'CLAVE_AUTORIZACION':object,'BIN':object
#                                                   ,'LAST4':object,'ORDER_ID':object})
ticket_zendesk.columns = ticket_zendesk.columns.str.strip().str.lower()
ticket_zendesk['order_id_xpay'] = ticket_zendesk['order_id'] 
ticket_zendesk['INDEX_TOTAL'] = (ticket_zendesk['bin'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['last4'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['amount'].astype(str).replace(' ', '',regex=True))
ticket_zendesk['INDEX_TOTAL_XPAY'] = (ticket_zendesk['bin'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['last4'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['amount'].astype(str).replace(' ', '',regex=True))
ticket_zendesk.head()

,merchant_id,uuid,transaction_id,order_id,affiliation,affiliation_type,sub_affiliation,mcc,date_transaction,created_at,...,status_code,msi,device_id,clip_reader,status_msg,issuer,brand,order_id_xpay,INDEX_TOTAL,INDEX_TOTAL_XPAY
0,c46967ba-4cfe-4cba-8a85-baaba3208064,0b1e249b-63bc-4da0-8fb5-eff1fccd68c9,fd16fb1c-b1f8-475b-8ef3-a2f27e3ade60,912010942285,7927496,CARD_PRESENT,2298284,7399,2023-08-01,2023-08-02 00:00:30,...,-5,6,P5220316004823,Clip Classic,Error. Cancel requested on pending payment.,BBVA,VISA,912010942285,477291_1781_912010942285_2500.0,477291_1781_912010942285_2500.0
1,4c7c4833-f8a9-474d-be9a-a5054be060d5,02ccceb6-3082-4a29-9f6c-f82b45f6fe0b,32b0391e-9fe7-4969-9d59-c8f7ac70e41d,000594079858,8380402,ECOMMERCE,0,5651,2023-08-15,2023-08-15 19:27:53,...,-3,0,80010001,Clip Classic,Declined,NU MEXICO FINANCIERA,MASTERCARD,000594079858,526777_8590_000594079858_400.0,526777_8590_000594079858_400.0
2,b90c1f9f-7edd-433f-8f0f-8787c04fd709,8a4c7bdf-7009-4aba-8ed0-cdb098aa2659,077fc653-913d-4cc2-9749-73ed0450966a,276920009906,7927517,CARD_PRESENT,253836,5812,2023-08-25,2023-08-25 22:28:24,...,-3,0,N500W4C9114,Clip Total,Reserved for private use or Over daily limit *,BANORTE,VISA,276920009906,491566_5652_276920009906_300.0,491566_5652_276920009906_300.0

In [29]:
ticket_zendesk.shape

(3, 27)

In [30]:
ticket_zendesk.columns

Index(['merchant_id', 'uuid', 'transaction_id', 'order_id', 'affiliation',
       'affiliation_type', 'sub_affiliation', 'mcc', 'date_transaction',
       'created_at', 'updated_at', 'psp', 'amount', 'clave_autorizacion',
       'bin', 'receipt_no', 'last4', 'status_code', 'msi', 'device_id',
       'clip_reader', 'status_msg', 'issuer', 'brand', 'order_id_xpay',
       'INDEX_TOTAL', 'INDEX_TOTAL_XPAY'],
      dtype='object')

### FILES DE AUDITORIA

In [ ]:
ticket_zendesk = pd.read_excel('AUDITORIA_DICIEMBRE_TXN_2021.xlsx',converters={'TRANSACTION_AMOUNT':float,'CLAVE_AUTORIZACION': str,
                                                                                'BIN':str,'LAST4':str,'ORDER_ID':str})
ticket_zendesk.columns = ticket_zendesk.columns.str.strip().str.lower() 
ticket_zendesk['INDEX_TOTAL'] = (ticket_zendesk['bin'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['last4'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['transaction_amount'].astype(str).replace(' ', '',regex=True))
ticket_zendesk['INDEX_TOTAL_XPAY'] = (ticket_zendesk['bin'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['last4'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['order_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +ticket_zendesk['transaction_amount'].astype(str).replace(' ', '',regex=True))
ticket_zendesk.head()

In [ ]:
ticket_zendesk.shape

## EXTRACCIÓN DE ORDER_ID

In [31]:
ticket_zendesk['psp'].unique()

array(['PROSA', 'MIT-3DS'], dtype=object)

In [32]:
ticket_zendesk['status_code'].unique()

array([-5, -3], dtype=int64)

In [33]:
ticket_zendesk['order_id_busqueda'] = "'"+ticket_zendesk['order_id'].replace(' ', '',regex=True)+"',"
print (ticket_zendesk['order_id_busqueda'].to_string(index=False))

'912010942285',
'000594079858',
'276920009906',

# IMPORTANTE: REVISAR A QUE PSP CORRESPONDE EL ORDER ID (PROSA O XPAY)

In [34]:
# select columns by name
check_txn = sftp[(sftp['order_id'].isin([
'740476428489'
])) | (sftp['order_id_xpay'].isin([
'740476428489'
]))]
# check_txn = sftp[sftp['eci'].isin(['75445503214043979274966'])]
# check_txn = sftp[sftp['order_id'] == '082566136893']
# check_txn = sftp[sftp['order_id_xpay'].isin(['223432604325'])]
# check_txn = sftp[(sftp.order_id == ('470520706509')) | (sftp.order_id ==('684089225828'))]
# check_txn = sftp[(sftp.CONCAT_2 == ('4388-2460.0')) | (sftp.CONCAT_2 == ('4388--2460.0'))]
# check_txn = sftp[(sftp.CONCAT_3 == ('314771-2718-295.0')) | (sftp.CONCAT_3 == ('314771-2718--295.0'))]
# check_txn = sftp[(sftp['LAST4'] == '7206')]
# check_txn.sort_values(by=['order_id','Fecha txn'],inplace=True)
check_txn.head()

,affiliation_sftp,card,commisions,transaction_date,gross_amount,transaction_type,tax,installments_tax,installments_fees,number_of_payments,...,acquirer_tax,file_name,date_file,month,deposit_date,LAST2_SFTP,BIN_SFTP,INDEX_TOTAL,INDEX_TOTAL_XPAY,INDEX_COD_AUTH
2254143,07927496,4772913081,-46.25,2023-08-01,"2,500.00",SETTLED,-7.40,0.00,0.00,06,...,-7.40,PAYCLIP_Settlement_03082023_V1.csv,2023-08-03,August,2023-08-02,81,477291,477291_81_912010942285_2500.0,477291_81_nan_2500.0,477291_81_335165_2500.0
8606197,08380402,5267771890,-7.40,2023-08-15,400.00,SETTLED,-1.18,0.00,0.00,00,...,-1.18,PAYCLIP_Settlement_17082023_V1.csv,2023-08-17,August,2023-08-16,90,526777,526777_90_000594079858_400.0,526777_90_nan_400.0,526777_90_504023_400.0

In [35]:
# check_txn.shape

In [36]:
# check_txn.to_excel('eci_2023.08.18.xlsx')

In [37]:
# writer = pd.ExcelWriter('EXAMPLE_SFTP(2).xlsx', engine='openpyxl', options={'encoding':'utf-8'})
# check_txn.to_excel(writer, sheet_name='MATCH TXN 1', index=False)
# ticket_zendesk.to_excel(writer, sheet_name='TICKET', index=False)
# writer.save()
# writer.close()

# MATCH DEPENDIENDO DEL PSP (INDEX_TOTAL O INDEX_TOTAL_XPAY)

In [38]:
match = ticket_zendesk.merge(check_txn[['order_id','affiliation_sftp','transaction_date','transaction_type','INDEX_TOTAL',
                                        'order_id_xpay','codigo_autorizacion','deposit_date','gross_amount']],on='order_id',how='left')
match_2 = ticket_zendesk.merge(check_txn[['order_id_xpay','affiliation_sftp','transaction_date','transaction_type','order_id',
                                          'INDEX_TOTAL_XPAY','codigo_autorizacion','deposit_date','gross_amount']],on='order_id_xpay',
                               how='left')
# match = check_txn.merge(ticket_zendesk[['order_id','ISSUER','BRAND']],on='order_id',how='left')
# match['transaction_id'].fillna('NO MATCH',inplace=True)
# match['status_code'].fillna('NO MATCH',inplace=True)
# match['status_msg'].fillna('NO MATCH',inplace=True)

In [39]:
match.head()

,merchant_id,uuid,transaction_id,order_id,affiliation,affiliation_type,sub_affiliation,mcc,date_transaction,created_at,...,INDEX_TOTAL_XPAY,order_id_busqueda,affiliation_sftp,transaction_date,transaction_type,INDEX_TOTAL_y,order_id_xpay_y,codigo_autorizacion,deposit_date,gross_amount
0,c46967ba-4cfe-4cba-8a85-baaba3208064,0b1e249b-63bc-4da0-8fb5-eff1fccd68c9,fd16fb1c-b1f8-475b-8ef3-a2f27e3ade60,912010942285,7927496,CARD_PRESENT,2298284,7399,2023-08-01,2023-08-02 00:00:30,...,477291_1781_912010942285_2500.0,"'912010942285',",07927496,2023-08-01,SETTLED,477291_81_912010942285_2500.0,NaN,335165,2023-08-02,"2,500.00"
1,4c7c4833-f8a9-474d-be9a-a5054be060d5,02ccceb6-3082-4a29-9f6c-f82b45f6fe0b,32b0391e-9fe7-4969-9d59-c8f7ac70e41d,000594079858,8380402,ECOMMERCE,0,5651,2023-08-15,2023-08-15 19:27:53,...,526777_8590_000594079858_400.0,"'000594079858',",08380402,2023-08-15,SETTLED,526777_90_000594079858_400.0,NaN,504023,2023-08-16,400.00
2,b90c1f9f-7edd-433f-8f0f-8787c04fd709,8a4c7bdf-7009-4aba-8ed0-cdb098aa2659,077fc653-913d-4cc2-9749-73ed0450966a,276920009906,7927517,CARD_PRESENT,253836,5812,2023-08-25,2023-08-25 22:28:24,...,491566_5652_276920009906_300.0,"'276920009906',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN

In [40]:
match_2.head()

,merchant_id,uuid,transaction_id,order_id_x,affiliation,affiliation_type,sub_affiliation,mcc,date_transaction,created_at,...,INDEX_TOTAL_XPAY_x,order_id_busqueda,affiliation_sftp,transaction_date,transaction_type,order_id_y,INDEX_TOTAL_XPAY_y,codigo_autorizacion,deposit_date,gross_amount
0,c46967ba-4cfe-4cba-8a85-baaba3208064,0b1e249b-63bc-4da0-8fb5-eff1fccd68c9,fd16fb1c-b1f8-475b-8ef3-a2f27e3ade60,912010942285,7927496,CARD_PRESENT,2298284,7399,2023-08-01,2023-08-02 00:00:30,...,477291_1781_912010942285_2500.0,"'912010942285',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN
1,4c7c4833-f8a9-474d-be9a-a5054be060d5,02ccceb6-3082-4a29-9f6c-f82b45f6fe0b,32b0391e-9fe7-4969-9d59-c8f7ac70e41d,000594079858,8380402,ECOMMERCE,0,5651,2023-08-15,2023-08-15 19:27:53,...,526777_8590_000594079858_400.0,"'000594079858',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN
2,b90c1f9f-7edd-433f-8f0f-8787c04fd709,8a4c7bdf-7009-4aba-8ed0-cdb098aa2659,077fc653-913d-4cc2-9749-73ed0450966a,276920009906,7927517,CARD_PRESENT,253836,5812,2023-08-25,2023-08-25 22:28:24,...,491566_5652_276920009906_300.0,"'276920009906',",NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN

In [41]:
match.shape

(3, 36)

In [42]:
match_2.shape

(3, 36)

In [43]:
match_final = match[['merchant_id','transaction_id','status_code','order_id','order_id_xpay_x','codigo_autorizacion',
                     'affiliation_sftp','transaction_date','transaction_type','deposit_date','gross_amount']]

In [44]:
match_final_2 = match_2[['merchant_id','transaction_id','status_code','order_id_x','order_id_xpay','codigo_autorizacion',
                     'affiliation_sftp','transaction_date','transaction_type','deposit_date','gross_amount']]

In [45]:
writer = pd.ExcelWriter('DATA FINAL DISPUTAS BNTE 2023.09.12.xlsx',
                        engine='xlsxwriter',
                        engine_kwargs={'options': {'encoding':'utf-8'}})
match_final.to_excel(writer, sheet_name='MATCH_FINAL', index=False)
match_final_2.to_excel(writer, sheet_name='MATCH_FINAL_2', index=False)
match.to_excel(writer, sheet_name='MATCH', index=False)
match_2.to_excel(writer, sheet_name='MATCH_2', index=False)
writer.close()