In [1]:
import pandas as pd
import numpy as np
import openpyxl
from openpyxl import load_workbook
import xlsxwriter
import glob
import os
from datetime import datetime
pd.options.display.float_format = '{:,.2f}'.format

## READING FILES

In [2]:
excel_name = 'Dispersi√≥n-20240131.xlsx'
date_respuesta = '2024-01-31'
date_respuesta = pd.to_datetime(date_respuesta)

In [3]:
names_resp = ['report_id','status','report_date_local','amount','disbursement_batch_id','merchant_id','bank_account_number',
             'bank_name','bank_account_owner_name','execution_date','aplication_date','disbursement_tracking_key',
             'error_description','reference_number','cep']

In [4]:
rs = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\DISPERSIONES\2024\01. ENERO\Respuesta*.xlsx', recursive=False)
rs

['C:\\Users\\Cristian.Aparicio\\Documents\\DISPERSIONES\\2024\\01. ENERO\\Respuesta-BNTE-trad-3 2024-01-31.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\DISPERSIONES\\2024\\01. ENERO\\Respuesta-SANT-trad-1 2024-01-31.xlsx',
 'C:\\Users\\Cristian.Aparicio\\Documents\\DISPERSIONES\\2024\\01. ENERO\\Respuesta-SANT-trad-2 2024-01-31.xlsx']

In [5]:
rs1 = pd.concat([pd.read_excel(f,sheet_name='Report',names=names_resp,
                                     converters={'bank_account_number':str,'disbursement_tracking_key':str,'report_id':str})
                       .assign(file_name=os.path.basename(f)) for f in rs])
rs1.loc[rs1['file_name'].str.contains('trad-1'), 'Batch_time'] = '01. First_batch'
rs1.loc[rs1['file_name'].str.contains('trad-2'), 'Batch_time'] = '02. Second_batch'
rs1.loc[rs1['file_name'].str.contains('trad-3'), 'Batch_time'] = '03. Third_batch'
rs1.loc[rs1['file_name'].str.contains('CITI'), "Banco_emisor"] = 'BANAMEX'
rs1.loc[rs1['file_name'].str.contains('BNTE'), "Banco_emisor"] = 'BANORTE'
rs1.loc[rs1['file_name'].str.contains('SANT'), "Banco_emisor"] = 'SANTANDER'
rs1.loc[rs1['Banco_emisor'] == 'BANAMEX', "Banco emisor"] = '40002'
rs1.loc[rs1['Banco_emisor'] == 'BANORTE', "Banco emisor"] = '40072'
rs1.loc[rs1['Banco_emisor'] == 'SANTANDER', "Banco emisor"] = '40014'
rs1['INDEX'] = (rs1['report_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +rs1['Batch_time'].astype(str).replace(' ', '',regex=True))
rs1.head()

C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Cristian.Aparicio\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,bank_account_number,bank_name,bank_account_owner_name,execution_date,aplication_date,disbursement_tracking_key,error_description,reference_number,cep,file_name,Batch_time,Banco_emisor,Banco emisor,INDEX
0,AHN3VLNX6,PAID,2024-01-31T19:45:57,324.85,b9fc2374-c741-4f4b-a06d-da3935b1a99b,00bf0fb9-405a-4b41-9ace-14dfe8e0b471,127456013890994028,AZTECA,Omar Polo Ochoa,2024-01-31T00:00,2024-01-31T14:00:17,42644264202401312821502472,NaN,800001,"2024-01-31,42644264202401312821502472,40072,40...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AHN3VLNX6_03.Third_batch
1,ASSKDM3KS,PAID,2024-01-31T19:46:08,711.39,b9fc2374-c741-4f4b-a06d-da3935b1a99b,0194010b-f10f-48fd-9b19-5fb77fea13ea,659802020000196080,"Opciones Empresariales del Noreste, S.A. de C....",Alan Orlando Gonzalez Rodriguez,2024-01-31T00:00,2024-01-31T14:00:17,42644264202401312821503249,NaN,800002,"2024-01-31,42644264202401312821503249,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,ASSKDM3KS_03.Third_batch
2,ASC8GPZ5Q,PAID,2024-01-31T19:45:52,"1,500.61",b9fc2374-c741-4f4b-a06d-da3935b1a99b,019d425c-787f-4b39-99bd-e6641505ee39,659802020000267294,"Opciones Empresariales del Noreste, S.A. de C....",Jose Guadalupe Herrera Acosta,2024-01-31T00:00,2024-01-31T14:00:17,42644264202401312821502734,NaN,800003,"2024-01-31,42644264202401312821502734,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,ASC8GPZ5Q_03.Third_batch
3,AMHFXR2F7,PAID,2024-01-31T19:45:57,179.19,b9fc2374-c741-4f4b-a06d-da3935b1a99b,023aeb3b-712b-4472-a8c6-17a42db36c6f,659802020000208334,"Opciones Empresariales del Noreste, S.A. de C....",Alejandro Ponce Estrada,2024-01-31T00:00,2024-01-31T14:00:17,42644264202401312821503435,NaN,800004,"2024-01-31,42644264202401312821503435,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AMHFXR2F7_03.Third_batch
4,A9TNVMKB3,PAID,2024-01-31T19:45:48,"1,002.80",b9fc2374-c741-4f4b-a06d-da3935b1a99b,04bc1b25-2e2c-4389-a017-d6a39cc67204,012760001859288342,"BBVA Bancomer, S.A.",Tersesita Rivas,2024-01-31T00:00,2024-01-31T14:00:17,42644264202401312821502874,NaN,800005,"2024-01-31,42644264202401312821502874,40072,40...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,A9TNVMKB3_03.Third_batch

In [6]:
rs1.shape

(102262, 20)

In [7]:
rs1.columns

Index(['report_id', 'status', 'report_date_local', 'amount',
       'disbursement_batch_id', 'merchant_id', 'bank_account_number',
       'bank_name', 'bank_account_owner_name', 'execution_date',
       'aplication_date', 'disbursement_tracking_key', 'error_description',
       'reference_number', 'cep', 'file_name', 'Batch_time', 'Banco_emisor',
       'Banco emisor', 'INDEX'],
      dtype='object')

In [8]:
duplicates = rs1[rs1.duplicated(['report_id'] , keep=False)]
duplicates.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,bank_account_number,bank_name,bank_account_owner_name,execution_date,aplication_date,disbursement_tracking_key,error_description,reference_number,cep,file_name,Batch_time,Banco_emisor,Banco emisor,INDEX
45,AVYNKPC25,PAID,2024-01-31T12:05:51,"8,771.74",b9fc2374-c741-4f4b-a06d-da3935b1a99b,1e152d56-2596-4bc9-ba40-9fb369a80d0c,012180015030584088,"BBVA Bancomer, S.A.",Jessica Lira Ramirez,2024-01-31T00:00,2024-01-31T14:00:17,18D62146FD6EA3C8,DEVOLUCION(20): Excede el limite de saldo auto...,800046,"2024-01-31,18D62146FD6EA3C8,40072,40012,012180...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AVYNKPC25_03.Third_batch
123,AKWDCKLD4,ERROR,2024-01-31T12:06:43,"13,894.48",b9fc2374-c741-4f4b-a06d-da3935b1a99b,4eba4eaa-d60b-4767-9172-e3eccef6b8e9,012180015038517170,"BBVA Bancomer, S.A.",Elmer Leonardo Alegria Marin,2024-01-31T00:00,2024-01-31T14:00:17,18D621498E2BFC49,DEV.SPEIEXCEDE EL LNMITE DE SA,800124,"2024-01-31,18D621498E2BFC49,40072,40012,012180...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AKWDCKLD4_03.Third_batch
126,AQ6GDWPXK,ERROR,2024-01-31T12:06:05,"2,874.72",b9fc2374-c741-4f4b-a06d-da3935b1a99b,508eb9c4-bc60-4127-bb93-17257bc81648,044180001015110213,"Scotiabank Inverlat, S.A.",Indira Cecilia Herrera Hernandez,2024-01-31T00:00,2024-01-31T14:00:17,20240131400140HDH0001455423910,DEV.SPEITIPO DE CUENTA NO CORR,800127,"2024-01-31,20240131400140HDH0001455423910,4007...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AQ6GDWPXK_03.Third_batch
127,AYXBTFTRG,PAID,2024-01-31T12:05:59,"31,665.11",b9fc2374-c741-4f4b-a06d-da3935b1a99b,50948e58-9fda-4aa5-bc2e-62105b355a2f,002180701222412871,"Banco Nacional de M√©xico, S.A.",Mar√≠a Esther jastrow candas,2024-01-31T00:00,2024-01-31T14:00:17,42644264202401312821502853,W5,800128,"2024-01-31,42644264202401312821502853,40072,40...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AYXBTFTRG_03.Third_batch
252,AN8TSBS4V,ERROR,2024-01-31T12:06:19,"2,055.92",b9fc2374-c741-4f4b-a06d-da3935b1a99b,9e4d4034-418c-44a6-9cfb-e2c84c2bfd84,137180290034921826,BANCOPPEL,Paola Canche,2024-01-31T00:00,2024-01-31T14:00:17,20240131400140HDH0001454726370,DEV.SPEIEXCEDE EL LNMITE DE AB,800253,"2024-01-31,20240131400140HDH0001454726370,4007...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AN8TSBS4V_03.Third_batch

In [9]:
duplicates.shape

(12, 20)

# QUERY

In [10]:
query_files = glob.glob(r'G:\.shortcut-targets-by-id\1Oe28Mf9uSidMamjllDen2gkNnC59eSUr\3.-Settlement\5.-HISTORICO FILES PAGOS\01. TRADICIONAL\2024\01. JANUARY\*.csv', recursive=False)
query_files

['G:\\.shortcut-targets-by-id\\1Oe28Mf9uSidMamjllDen2gkNnC59eSUr\\3.-Settlement\\5.-HISTORICO FILES PAGOS\\01. TRADICIONAL\\2024\\01. JANUARY\\BNTE-3 2024-01-31.csv',
 'G:\\.shortcut-targets-by-id\\1Oe28Mf9uSidMamjllDen2gkNnC59eSUr\\3.-Settlement\\5.-HISTORICO FILES PAGOS\\01. TRADICIONAL\\2024\\01. JANUARY\\SANT-2 2024-01-31.csv',
 'G:\\.shortcut-targets-by-id\\1Oe28Mf9uSidMamjllDen2gkNnC59eSUr\\3.-Settlement\\5.-HISTORICO FILES PAGOS\\01. TRADICIONAL\\2024\\01. JANUARY\\SANT-1 2024-01-31.csv']

In [11]:
disp = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in query_files])
disp.columns = disp.columns.str.strip().str.lower() 
disp['batch_created_date'] = pd.to_datetime(disp['batch_created_date']).dt.tz_localize(None)
disp['payment_date_local'] = pd.to_datetime(disp['payment_date_local']).dt.tz_localize(None)
disp.loc[disp['file_name'].str.contains('BNTE-1'), 'Batch_time'] = '01. First_batch'
disp.loc[disp['file_name'].str.contains('BNTE-2'), 'Batch_time'] = '02. Second_batch'
disp.loc[disp['file_name'].str.contains('BNTE-3'), 'Batch_time'] = '03. Third_batch'
disp.loc[disp['file_name'].str.contains('SANT-1'), 'Batch_time'] = '01. First_batch'
disp.loc[disp['file_name'].str.contains('SANT-2'), 'Batch_time'] = '02. Second_batch'
disp.loc[disp['file_name'].str.contains('SANT-3'), 'Batch_time'] = '03. Third_batch'
disp.loc[disp['type'].isnull(), 'type'] = 'LEDGER_TRAD'
disp['INDEX'] = (disp['report_id'].astype(str).replace(' ', '',regex=True)+'_'
                       +disp['Batch_time'].astype(str).replace(' ', '',regex=True))
disp.head()

,type,merchant_id,merchant_token,merchant_name,user_email,report_id,report_date_local,amount,status,bank_name,payment_date_local,bank_account_owner_name,bank_account_number,batch_created_date,disbursement_method,swap,file_name,Batch_time,INDEX
0,LEDGER_TRAD,00bf0fb9-405a-4b41-9ace-14dfe8e0b471,NaN,NaN,NaN,AHN3VLNX6,2024-01-31,324.85,PAID,AZTECA,2024-01-31 14:22:17,Omar Polo Ochoa,'127456013890994028,2024-01-31 14:00:16,BANORTE,"Omar Polo Ochoa,,324.85,127456013890994028,CLI...",BNTE-3 2024-01-31.csv,03. Third_batch,AHN3VLNX6_03.Third_batch
1,LEDGER_TRAD,0194010b-f10f-48fd-9b19-5fb77fea13ea,NaN,NaN,NaN,ASSKDM3KS,2024-01-31,711.39,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2024-01-31 14:22:18,Alan Orlando Gonzalez Rodriguez,'659802020000196080,2024-01-31 14:00:16,BANORTE,"Alan Orlando Gonzalez Rodriguez,,711.39,659802...",BNTE-3 2024-01-31.csv,03. Third_batch,ASSKDM3KS_03.Third_batch
2,LEDGER_TRAD,019d425c-787f-4b39-99bd-e6641505ee39,NaN,NaN,NaN,ASC8GPZ5Q,2024-01-31,"1,500.61",PAID,"Opciones Empresariales del Noreste, S.A. de C....",2024-01-31 14:22:19,Jose Guadalupe Herrera Acosta,'659802020000267294,2024-01-31 14:00:16,BANORTE,"Jose Guadalupe Herrera Acosta,,1500.61,6598020...",BNTE-3 2024-01-31.csv,03. Third_batch,ASC8GPZ5Q_03.Third_batch
3,LEDGER_TRAD,023aeb3b-712b-4472-a8c6-17a42db36c6f,NaN,NaN,NaN,AMHFXR2F7,2024-01-31,179.19,PAID,"Opciones Empresariales del Noreste, S.A. de C....",2024-01-31 14:22:20,Alejandro Ponce Estrada,'659802020000208334,2024-01-31 14:00:16,BANORTE,"Alejandro Ponce Estrada,,179.19,65980202000020...",BNTE-3 2024-01-31.csv,03. Third_batch,AMHFXR2F7_03.Third_batch
4,LEDGER_TRAD,04bc1b25-2e2c-4389-a017-d6a39cc67204,NaN,NaN,NaN,A9TNVMKB3,2024-01-31,"1,002.80",PAID,"BBVA Bancomer, S.A.",2024-01-31 14:22:25,Tersesita Rivas,'012760001859288342,2024-01-31 14:00:17,BANORTE,"Tersesita Rivas ,,1002.8,012760001859288342,CL...",BNTE-3 2024-01-31.csv,03. Third_batch,A9TNVMKB3_03.Third_batch

In [12]:
disp.shape

(102262, 19)

In [13]:
disp['type'].unique()

array(['LEDGER_TRAD', 'INSTANT', 'DAILY'], dtype=object)

# BIN

In [14]:
bin1 = pd.read_csv(r'C:\Users\Cristian.Aparicio\Documents\DISPERSIONES\Catalogo_Bancos.csv'
                  ,dtype={'BIN':object,'Clave de la instituci√≥n':object,'Nombre de la instituci√≥n':object})

In [15]:
bin1.head()

   BIN Clave de la instituci√≥n Nombre de la instituci√≥n
0  138                   40138              ABC CAPITAL
1  102                   40102            ACCENDO BANCO
2  133                   40133                 ACTINVER
3  062                   40062                   AFIRME
4  638                   90638                    AKALA

In [16]:
bin1.shape

(94, 3)

# ARCHIVO RESPUESTA

In [17]:
rs1['Date_respuesta'] = date_respuesta
rs1['BIN'] = rs1['bank_account_number'].str[:3]
rs1.rename(columns ={'bank_account_number':'CLABE'}, inplace=True)
rs1.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,...,error_description,reference_number,cep,file_name,Batch_time,Banco_emisor,Banco emisor,INDEX,Date_respuesta,BIN
0,AHN3VLNX6,PAID,2024-01-31T19:45:57,324.85,b9fc2374-c741-4f4b-a06d-da3935b1a99b,00bf0fb9-405a-4b41-9ace-14dfe8e0b471,127456013890994028,AZTECA,Omar Polo Ochoa,2024-01-31T00:00,...,NaN,800001,"2024-01-31,42644264202401312821502472,40072,40...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AHN3VLNX6_03.Third_batch,2024-01-31,127
1,ASSKDM3KS,PAID,2024-01-31T19:46:08,711.39,b9fc2374-c741-4f4b-a06d-da3935b1a99b,0194010b-f10f-48fd-9b19-5fb77fea13ea,659802020000196080,"Opciones Empresariales del Noreste, S.A. de C....",Alan Orlando Gonzalez Rodriguez,2024-01-31T00:00,...,NaN,800002,"2024-01-31,42644264202401312821503249,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,ASSKDM3KS_03.Third_batch,2024-01-31,659
2,ASC8GPZ5Q,PAID,2024-01-31T19:45:52,"1,500.61",b9fc2374-c741-4f4b-a06d-da3935b1a99b,019d425c-787f-4b39-99bd-e6641505ee39,659802020000267294,"Opciones Empresariales del Noreste, S.A. de C....",Jose Guadalupe Herrera Acosta,2024-01-31T00:00,...,NaN,800003,"2024-01-31,42644264202401312821502734,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,ASC8GPZ5Q_03.Third_batch,2024-01-31,659
3,AMHFXR2F7,PAID,2024-01-31T19:45:57,179.19,b9fc2374-c741-4f4b-a06d-da3935b1a99b,023aeb3b-712b-4472-a8c6-17a42db36c6f,659802020000208334,"Opciones Empresariales del Noreste, S.A. de C....",Alejandro Ponce Estrada,2024-01-31T00:00,...,NaN,800004,"2024-01-31,42644264202401312821503435,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AMHFXR2F7_03.Third_batch,2024-01-31,659
4,A9TNVMKB3,PAID,2024-01-31T19:45:48,"1,002.80",b9fc2374-c741-4f4b-a06d-da3935b1a99b,04bc1b25-2e2c-4389-a017-d6a39cc67204,012760001859288342,"BBVA Bancomer, S.A.",Tersesita Rivas,2024-01-31T00:00,...,NaN,800005,"2024-01-31,42644264202401312821502874,40072,40...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,A9TNVMKB3_03.Third_batch,2024-01-31,012

In [18]:
rs1.shape

(102262, 22)

In [19]:
rs1['report_id'] = rs1['report_id'].str.strip()

In [20]:
rs2 = rs1.merge(bin1[['BIN','Clave de la instituci√≥n','Nombre de la instituci√≥n']] ,on='BIN', how='left')
rs2['Comision'] = ''
rs2['LINEA CEP'] = (rs2['Date_respuesta'].astype(str).replace(' ', '',regex=True)+','
                    +rs2['disbursement_tracking_key'].astype(str)+','
                    +rs2['Banco emisor'].astype(str).replace(' ', '',regex=True)+','
                    +rs2['Clave de la instituci√≥n'].astype(str).replace(' ', '',regex=True)+','
                    +rs2['CLABE'].astype(str).replace(' ', '',regex=True)+','
                    +rs2['amount'].astype(str).replace(' ', '',regex=True))
rs2['Metodo de dispersion'] = rs2['Banco_emisor']
rs2.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,...,Banco_emisor,Banco emisor,INDEX,Date_respuesta,BIN,Clave de la instituci√≥n,Nombre de la instituci√≥n,Comision,LINEA CEP,Metodo de dispersion
0,AHN3VLNX6,PAID,2024-01-31T19:45:57,324.85,b9fc2374-c741-4f4b-a06d-da3935b1a99b,00bf0fb9-405a-4b41-9ace-14dfe8e0b471,127456013890994028,AZTECA,Omar Polo Ochoa,2024-01-31T00:00,...,BANORTE,40072,AHN3VLNX6_03.Third_batch,2024-01-31,127,40127,AZTECA,,"2024-01-31,42644264202401312821502472,40072,40...",BANORTE
1,ASSKDM3KS,PAID,2024-01-31T19:46:08,711.39,b9fc2374-c741-4f4b-a06d-da3935b1a99b,0194010b-f10f-48fd-9b19-5fb77fea13ea,659802020000196080,"Opciones Empresariales del Noreste, S.A. de C....",Alan Orlando Gonzalez Rodriguez,2024-01-31T00:00,...,BANORTE,40072,ASSKDM3KS_03.Third_batch,2024-01-31,659,90659,ASP INTEGRA OPC,,"2024-01-31,42644264202401312821503249,40072,90...",BANORTE
2,ASC8GPZ5Q,PAID,2024-01-31T19:45:52,"1,500.61",b9fc2374-c741-4f4b-a06d-da3935b1a99b,019d425c-787f-4b39-99bd-e6641505ee39,659802020000267294,"Opciones Empresariales del Noreste, S.A. de C....",Jose Guadalupe Herrera Acosta,2024-01-31T00:00,...,BANORTE,40072,ASC8GPZ5Q_03.Third_batch,2024-01-31,659,90659,ASP INTEGRA OPC,,"2024-01-31,42644264202401312821502734,40072,90...",BANORTE
3,AMHFXR2F7,PAID,2024-01-31T19:45:57,179.19,b9fc2374-c741-4f4b-a06d-da3935b1a99b,023aeb3b-712b-4472-a8c6-17a42db36c6f,659802020000208334,"Opciones Empresariales del Noreste, S.A. de C....",Alejandro Ponce Estrada,2024-01-31T00:00,...,BANORTE,40072,AMHFXR2F7_03.Third_batch,2024-01-31,659,90659,ASP INTEGRA OPC,,"2024-01-31,42644264202401312821503435,40072,90...",BANORTE
4,A9TNVMKB3,PAID,2024-01-31T19:45:48,"1,002.80",b9fc2374-c741-4f4b-a06d-da3935b1a99b,04bc1b25-2e2c-4389-a017-d6a39cc67204,012760001859288342,"BBVA Bancomer, S.A.",Tersesita Rivas,2024-01-31T00:00,...,BANORTE,40072,A9TNVMKB3_03.Third_batch,2024-01-31,012,40012,BBVA BANCOMER,,"2024-01-31,42644264202401312821502874,40072,40...",BANORTE

In [21]:
rs2.shape

(102262, 27)

# ARCHIVO DISPERSION

In [22]:
disp['date_disbursement'] = date_respuesta
disp['report_id'] = disp['report_id'].str.strip()
disp['report_date_local'] = pd.to_datetime(disp['report_date_local'])

In [23]:
disp.loc[disp['report_date_local'] == date_respuesta, 'tipo'] = 'Pago del d√≠a'
disp.loc[disp['report_date_local'] != date_respuesta, 'tipo'] = 'Reprogramaci√≥n'
disp.drop(['bank_name','bank_account_number','status','swap','payment_date_local'],axis=1,inplace=True)
disp.head()

,type,merchant_id,merchant_token,merchant_name,user_email,report_id,report_date_local,amount,bank_account_owner_name,batch_created_date,disbursement_method,file_name,Batch_time,INDEX,date_disbursement,tipo
0,LEDGER_TRAD,00bf0fb9-405a-4b41-9ace-14dfe8e0b471,NaN,NaN,NaN,AHN3VLNX6,2024-01-31,324.85,Omar Polo Ochoa,2024-01-31 14:00:16,BANORTE,BNTE-3 2024-01-31.csv,03. Third_batch,AHN3VLNX6_03.Third_batch,2024-01-31,Pago del d√≠a
1,LEDGER_TRAD,0194010b-f10f-48fd-9b19-5fb77fea13ea,NaN,NaN,NaN,ASSKDM3KS,2024-01-31,711.39,Alan Orlando Gonzalez Rodriguez,2024-01-31 14:00:16,BANORTE,BNTE-3 2024-01-31.csv,03. Third_batch,ASSKDM3KS_03.Third_batch,2024-01-31,Pago del d√≠a
2,LEDGER_TRAD,019d425c-787f-4b39-99bd-e6641505ee39,NaN,NaN,NaN,ASC8GPZ5Q,2024-01-31,"1,500.61",Jose Guadalupe Herrera Acosta,2024-01-31 14:00:16,BANORTE,BNTE-3 2024-01-31.csv,03. Third_batch,ASC8GPZ5Q_03.Third_batch,2024-01-31,Pago del d√≠a
3,LEDGER_TRAD,023aeb3b-712b-4472-a8c6-17a42db36c6f,NaN,NaN,NaN,AMHFXR2F7,2024-01-31,179.19,Alejandro Ponce Estrada,2024-01-31 14:00:16,BANORTE,BNTE-3 2024-01-31.csv,03. Third_batch,AMHFXR2F7_03.Third_batch,2024-01-31,Pago del d√≠a
4,LEDGER_TRAD,04bc1b25-2e2c-4389-a017-d6a39cc67204,NaN,NaN,NaN,A9TNVMKB3,2024-01-31,"1,002.80",Tersesita Rivas,2024-01-31 14:00:17,BANORTE,BNTE-3 2024-01-31.csv,03. Third_batch,A9TNVMKB3_03.Third_batch,2024-01-31,Pago del d√≠a

In [24]:
disp.shape

(102262, 16)

In [25]:
disp_2 = disp.merge(rs2[['INDEX','status','Nombre de la instituci√≥n','CLABE','LINEA CEP','Banco_emisor']]
                    ,on='INDEX', how='left')
disp_2.loc[disp_2['status'] != 'PAID', 'status'] = 'ERROR'
disp_2.sort_values(by=['status'])
disp_2.head()

,type,merchant_id,merchant_token,merchant_name,user_email,report_id,report_date_local,amount,bank_account_owner_name,batch_created_date,...,file_name,Batch_time,INDEX,date_disbursement,tipo,status,Nombre de la instituci√≥n,CLABE,LINEA CEP,Banco_emisor
0,LEDGER_TRAD,00bf0fb9-405a-4b41-9ace-14dfe8e0b471,NaN,NaN,NaN,AHN3VLNX6,2024-01-31,324.85,Omar Polo Ochoa,2024-01-31 14:00:16,...,BNTE-3 2024-01-31.csv,03. Third_batch,AHN3VLNX6_03.Third_batch,2024-01-31,Pago del d√≠a,PAID,AZTECA,127456013890994028,"2024-01-31,42644264202401312821502472,40072,40...",BANORTE
1,LEDGER_TRAD,0194010b-f10f-48fd-9b19-5fb77fea13ea,NaN,NaN,NaN,ASSKDM3KS,2024-01-31,711.39,Alan Orlando Gonzalez Rodriguez,2024-01-31 14:00:16,...,BNTE-3 2024-01-31.csv,03. Third_batch,ASSKDM3KS_03.Third_batch,2024-01-31,Pago del d√≠a,PAID,ASP INTEGRA OPC,659802020000196080,"2024-01-31,42644264202401312821503249,40072,90...",BANORTE
2,LEDGER_TRAD,019d425c-787f-4b39-99bd-e6641505ee39,NaN,NaN,NaN,ASC8GPZ5Q,2024-01-31,"1,500.61",Jose Guadalupe Herrera Acosta,2024-01-31 14:00:16,...,BNTE-3 2024-01-31.csv,03. Third_batch,ASC8GPZ5Q_03.Third_batch,2024-01-31,Pago del d√≠a,PAID,ASP INTEGRA OPC,659802020000267294,"2024-01-31,42644264202401312821502734,40072,90...",BANORTE
3,LEDGER_TRAD,023aeb3b-712b-4472-a8c6-17a42db36c6f,NaN,NaN,NaN,AMHFXR2F7,2024-01-31,179.19,Alejandro Ponce Estrada,2024-01-31 14:00:16,...,BNTE-3 2024-01-31.csv,03. Third_batch,AMHFXR2F7_03.Third_batch,2024-01-31,Pago del d√≠a,PAID,ASP INTEGRA OPC,659802020000208334,"2024-01-31,42644264202401312821503435,40072,90...",BANORTE
4,LEDGER_TRAD,04bc1b25-2e2c-4389-a017-d6a39cc67204,NaN,NaN,NaN,A9TNVMKB3,2024-01-31,"1,002.80",Tersesita Rivas,2024-01-31 14:00:17,...,BNTE-3 2024-01-31.csv,03. Third_batch,A9TNVMKB3_03.Third_batch,2024-01-31,Pago del d√≠a,PAID,BBVA BANCOMER,012760001859288342,"2024-01-31,42644264202401312821502874,40072,40...",BANORTE

In [26]:
disp_2.loc[((disp_2['Banco_emisor'] == 'BANAMEX') &
            (disp_2['Nombre de la instituci√≥n'] == 'BANAMEX')), 'LINEA CEP'] = 'COMPROBANTE MISMO BANCO BANAMEX'
disp_2.loc[((disp_2['Banco_emisor'] == 'SANTANDER') &
            (disp_2['Nombre de la instituci√≥n'] == 'SANTANDER')), 'LINEA CEP'] = 'COMPROBANTE MISMO BANCO SANTANDER'
disp_2.loc[((disp_2['Banco_emisor'] == 'BANORTE') &
            (disp_2['Nombre de la instituci√≥n'] == 'BANORTE/IXE')), 'LINEA CEP'] = 'COMPROBANTE MISMO BANCO BANORTE'
disp_2.loc[disp_2['status'] == 'ERROR', 'LINEA CEP'] = ''

In [27]:
for col in disp_2.columns: 
    print(col)

type
merchant_id
merchant_token
merchant_name
user_email
report_id
report_date_local
amount
bank_account_owner_name
batch_created_date
disbursement_method
file_name
Batch_time
INDEX
date_disbursement
tipo
status
Nombre de la instituci√≥n
CLABE
LINEA CEP
Banco_emisor

In [28]:
disp_final = disp_2[['type','merchant_id','merchant_name','user_email','report_id','report_date_local','amount','tipo'
                    ,'Nombre de la instituci√≥n','bank_account_owner_name','CLABE','status','LINEA CEP','Batch_time',
                     'Banco_emisor','INDEX']]
disp_final.rename(columns ={'Nombre de la instituci√≥n':'bank','amount':'total_due'}, inplace=True)
disp_final.sort_values(by=['status','Batch_time'], ascending=True, inplace=True)
disp_final.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_7372\1166564361.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.rename(columns ={'Nombre de la instituci√≥n':'bank','amount':'total_due'}, inplace=True)
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_7372\1166564361.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.sort_values(by=['status','Batch_time'], ascending=True, inplace=True)

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,bank_account_owner_name,CLABE,status,LINEA CEP,Batch_time,Banco_emisor,INDEX
7472,LEDGER_TRAD,000d47e7-e6b8-4203-ae19-97a624c9db75,NaN,NaN,ANPW9J7DH,2024-01-31,183.02,Pago del d√≠a,HSBC,Mar√≠a Luisa Valentina Morales Guertero,021542700880577574,ERROR,,01. First_batch,SANTANDER,ANPW9J7DH_01.First_batch
7724,LEDGER_TRAD,00b50496-05b3-4c3d-966b-113684729202,NaN,NaN,AY4PHK4LV,2024-01-31,"1,437.36",Pago del d√≠a,BBVA BANCOMER,Vania De Los Angeles Silva,012180015514200260,ERROR,,01. First_batch,SANTANDER,AY4PHK4LV_01.First_batch
7792,LEDGER_TRAD,00e3612a-a210-4218-90c6-f7f9239ed419,NaN,NaN,A24XPXZ2N,2024-01-31,867.20,Pago del d√≠a,BBVA BANCOMER,Claudia Margarita Ibarra Madera,012180015427320813,ERROR,,01. First_batch,SANTANDER,A24XPXZ2N_01.First_batch
7795,LEDGER_TRAD,00e46871-5e8f-4c8c-8194-cd7c05e02d64,NaN,NaN,AW73WDP3Q,2024-01-31,332.51,Pago del d√≠a,BBVA BANCOMER,Nancy Maria Magdalena Zepeda Arias,012180015232689493,ERROR,,01. First_batch,SANTANDER,AW73WDP3Q_01.First_batch
7886,LEDGER_TRAD,012c539f-c3e7-47e0-8f0a-17d8c3c5ad85,NaN,NaN,AYDYM4JS3,2024-01-31,622.86,Pago del d√≠a,BANREGIO,Enrique Villafuerte,058597000021452105,ERROR,,01. First_batch,SANTANDER,AYDYM4JS3_01.First_batch

In [29]:
disp_final.shape

(102262, 16)

# ERROR

In [30]:
error = disp_final[(disp_final['status'] != 'PAID')]
error.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,bank_account_owner_name,CLABE,status,LINEA CEP,Batch_time,Banco_emisor,INDEX
7472,LEDGER_TRAD,000d47e7-e6b8-4203-ae19-97a624c9db75,NaN,NaN,ANPW9J7DH,2024-01-31,183.02,Pago del d√≠a,HSBC,Mar√≠a Luisa Valentina Morales Guertero,021542700880577574,ERROR,,01. First_batch,SANTANDER,ANPW9J7DH_01.First_batch
7724,LEDGER_TRAD,00b50496-05b3-4c3d-966b-113684729202,NaN,NaN,AY4PHK4LV,2024-01-31,"1,437.36",Pago del d√≠a,BBVA BANCOMER,Vania De Los Angeles Silva,012180015514200260,ERROR,,01. First_batch,SANTANDER,AY4PHK4LV_01.First_batch
7792,LEDGER_TRAD,00e3612a-a210-4218-90c6-f7f9239ed419,NaN,NaN,A24XPXZ2N,2024-01-31,867.20,Pago del d√≠a,BBVA BANCOMER,Claudia Margarita Ibarra Madera,012180015427320813,ERROR,,01. First_batch,SANTANDER,A24XPXZ2N_01.First_batch
7795,LEDGER_TRAD,00e46871-5e8f-4c8c-8194-cd7c05e02d64,NaN,NaN,AW73WDP3Q,2024-01-31,332.51,Pago del d√≠a,BBVA BANCOMER,Nancy Maria Magdalena Zepeda Arias,012180015232689493,ERROR,,01. First_batch,SANTANDER,AW73WDP3Q_01.First_batch
7886,LEDGER_TRAD,012c539f-c3e7-47e0-8f0a-17d8c3c5ad85,NaN,NaN,AYDYM4JS3,2024-01-31,622.86,Pago del d√≠a,BANREGIO,Enrique Villafuerte,058597000021452105,ERROR,,01. First_batch,SANTANDER,AYDYM4JS3_01.First_batch

In [31]:
error.shape

(613, 16)

In [32]:
error.drop(['bank_account_owner_name','CLABE','status','LINEA CEP','Banco_emisor'],axis=1,inplace=True)

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_7372\1215281788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  error.drop(['bank_account_owner_name','CLABE','status','LINEA CEP','Banco_emisor'],axis=1,inplace=True)

In [33]:
error.loc[((error['bank'] == 'BANORTE/IXE') | (error['bank'] == 'SANTANDER')), 'Check'] = 'SPEI DEVUELTO MISMO BANCO'
error.loc[((error['bank'] != 'BANORTE/IXE') |(error['bank'] != 'SANTANDER')), 'Check'] = 'SPEI DEVUELTO'

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_7372\3372586593.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  error.loc[((error['bank'] == 'BANORTE/IXE') | (error['bank'] == 'SANTANDER')), 'Check'] = 'SPEI DEVUELTO MISMO BANCO'

In [34]:
error_final = error
error_final.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,Batch_time,INDEX,Check
7472,LEDGER_TRAD,000d47e7-e6b8-4203-ae19-97a624c9db75,NaN,NaN,ANPW9J7DH,2024-01-31,183.02,Pago del d√≠a,HSBC,01. First_batch,ANPW9J7DH_01.First_batch,SPEI DEVUELTO
7724,LEDGER_TRAD,00b50496-05b3-4c3d-966b-113684729202,NaN,NaN,AY4PHK4LV,2024-01-31,"1,437.36",Pago del d√≠a,BBVA BANCOMER,01. First_batch,AY4PHK4LV_01.First_batch,SPEI DEVUELTO
7792,LEDGER_TRAD,00e3612a-a210-4218-90c6-f7f9239ed419,NaN,NaN,A24XPXZ2N,2024-01-31,867.20,Pago del d√≠a,BBVA BANCOMER,01. First_batch,A24XPXZ2N_01.First_batch,SPEI DEVUELTO
7795,LEDGER_TRAD,00e46871-5e8f-4c8c-8194-cd7c05e02d64,NaN,NaN,AW73WDP3Q,2024-01-31,332.51,Pago del d√≠a,BBVA BANCOMER,01. First_batch,AW73WDP3Q_01.First_batch,SPEI DEVUELTO
7886,LEDGER_TRAD,012c539f-c3e7-47e0-8f0a-17d8c3c5ad85,NaN,NaN,AYDYM4JS3,2024-01-31,622.86,Pago del d√≠a,BANREGIO,01. First_batch,AYDYM4JS3_01.First_batch,SPEI DEVUELTO

In [35]:
error_final = error.merge(rs2[['INDEX','error_description']] ,on='INDEX', how='left')
error_final.sort_values(by=['Batch_time'], ascending=True, inplace=True)
error_final.head()

,type,merchant_id,merchant_name,user_email,report_id,report_date_local,total_due,tipo,bank,Batch_time,INDEX,Check,error_description
0,LEDGER_TRAD,000d47e7-e6b8-4203-ae19-97a624c9db75,NaN,NaN,ANPW9J7DH,2024-01-31,183.02,Pago del d√≠a,HSBC,01. First_batch,ANPW9J7DH_01.First_batch,SPEI DEVUELTO,DEVOLUCION(03): Cuenta cancelada 021542...
365,LEDGER_TRAD,a8b8c944-cb3f-4737-a62d-2dfc32854486,NaN,NaN,AV4JXN9J2,2024-01-31,948.66,Pago del d√≠a,BBVA BANCOMER,01. First_batch,AV4JXN9J2_01.First_batch,SPEI DEVUELTO,/21/CB Return Exceeds authorized account balan...
364,LEDGER_TRAD,a88e01a2-de71-4a3d-80e7-e0e653c281b9,NaN,NaN,AVVQGFC47,2024-01-31,57.49,Pago del d√≠a,BBVA BANCOMER,01. First_batch,AVVQGFC47_01.First_batch,SPEI DEVUELTO,DEVOLUCION(20): Excede el limite de saldo auto...
363,LEDGER_TRAD,a7c681ca-91dc-4e29-9c5a-e8ac14562c6c,NaN,NaN,ANN93VVCK,2024-01-31,90.56,Pago del d√≠a,BBVA BANCOMER,01. First_batch,ANN93VVCK_01.First_batch,SPEI DEVUELTO,DEVOLUCION(20): Excede el limite de saldo auto...
362,LEDGER_TRAD,a7759bb6-be2a-4bf9-94f6-8bc217e6d1c6,NaN,NaN,A8W7LM7SJ,2024-01-31,671.99,Pago del d√≠a,BBVA BANCOMER,01. First_batch,A8W7LM7SJ_01.First_batch,SPEI DEVUELTO,DEVOLUCION(20): Excede el limite de saldo auto...

In [36]:
error_final.shape

(613, 13)

In [37]:
disp_final.drop(['INDEX'],axis=1,inplace=True)
error_final.drop(['INDEX'],axis=1,inplace=True)

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_7372\1854234940.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disp_final.drop(['INDEX'],axis=1,inplace=True)

# PAGOS NO ENCONTRADOS EN LA DB

In [38]:
payouts_not_found = rs1.merge(disp_2[['INDEX','report_id','type']] ,on='INDEX', how='left')
payouts_not_found['type'].fillna('not_found',inplace=True)
payouts_not_found.head()

,report_id_x,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,...,cep,file_name,Batch_time,Banco_emisor,Banco emisor,INDEX,Date_respuesta,BIN,report_id_y,type
0,AHN3VLNX6,PAID,2024-01-31T19:45:57,324.85,b9fc2374-c741-4f4b-a06d-da3935b1a99b,00bf0fb9-405a-4b41-9ace-14dfe8e0b471,127456013890994028,AZTECA,Omar Polo Ochoa,2024-01-31T00:00,...,"2024-01-31,42644264202401312821502472,40072,40...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AHN3VLNX6_03.Third_batch,2024-01-31,127,AHN3VLNX6,LEDGER_TRAD
1,ASSKDM3KS,PAID,2024-01-31T19:46:08,711.39,b9fc2374-c741-4f4b-a06d-da3935b1a99b,0194010b-f10f-48fd-9b19-5fb77fea13ea,659802020000196080,"Opciones Empresariales del Noreste, S.A. de C....",Alan Orlando Gonzalez Rodriguez,2024-01-31T00:00,...,"2024-01-31,42644264202401312821503249,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,ASSKDM3KS_03.Third_batch,2024-01-31,659,ASSKDM3KS,LEDGER_TRAD
2,ASC8GPZ5Q,PAID,2024-01-31T19:45:52,"1,500.61",b9fc2374-c741-4f4b-a06d-da3935b1a99b,019d425c-787f-4b39-99bd-e6641505ee39,659802020000267294,"Opciones Empresariales del Noreste, S.A. de C....",Jose Guadalupe Herrera Acosta,2024-01-31T00:00,...,"2024-01-31,42644264202401312821502734,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,ASC8GPZ5Q_03.Third_batch,2024-01-31,659,ASC8GPZ5Q,LEDGER_TRAD
3,AMHFXR2F7,PAID,2024-01-31T19:45:57,179.19,b9fc2374-c741-4f4b-a06d-da3935b1a99b,023aeb3b-712b-4472-a8c6-17a42db36c6f,659802020000208334,"Opciones Empresariales del Noreste, S.A. de C....",Alejandro Ponce Estrada,2024-01-31T00:00,...,"2024-01-31,42644264202401312821503435,40072,90...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,AMHFXR2F7_03.Third_batch,2024-01-31,659,AMHFXR2F7,LEDGER_TRAD
4,A9TNVMKB3,PAID,2024-01-31T19:45:48,"1,002.80",b9fc2374-c741-4f4b-a06d-da3935b1a99b,04bc1b25-2e2c-4389-a017-d6a39cc67204,012760001859288342,"BBVA Bancomer, S.A.",Tersesita Rivas,2024-01-31T00:00,...,"2024-01-31,42644264202401312821502874,40072,40...",Respuesta-BNTE-trad-3 2024-01-31.xlsx,03. Third_batch,BANORTE,40072,A9TNVMKB3_03.Third_batch,2024-01-31,012,A9TNVMKB3,LEDGER_TRAD

In [39]:
payouts_not_found.shape

(102262, 24)

In [40]:
payouts_not_found_final = payouts_not_found[(payouts_not_found['type'] == 'not_found')]
payouts_not_found_final.head()

Empty DataFrame
Columns: [report_id_x, status, report_date_local, amount, disbursement_batch_id, merchant_id, CLABE, bank_name, bank_account_owner_name, execution_date, aplication_date, disbursement_tracking_key, error_description, reference_number, cep, file_name, Batch_time, Banco_emisor, Banco emisor, INDEX, Date_respuesta, BIN, report_id_y, type]
Index: []

[0 rows x 24 columns]

In [41]:
payouts_not_found_final.shape

(0, 24)

# ARCHIVOS FINALES

### ARCHIVO DISPERSION

In [42]:
writer = pd.ExcelWriter(excel_name, engine='xlsxwriter', engine_kwargs={'options': {'encoding':'utf-8'}})
disp_final.to_excel(writer, sheet_name='Swap del d√≠a',index=False)
error_final.to_excel(writer, sheet_name='ERROR',index=False)
writer.close()

### ARCHIVO RESPUESTA

In [43]:
rs2.head()

,report_id,status,report_date_local,amount,disbursement_batch_id,merchant_id,CLABE,bank_name,bank_account_owner_name,execution_date,...,Banco_emisor,Banco emisor,INDEX,Date_respuesta,BIN,Clave de la instituci√≥n,Nombre de la instituci√≥n,Comision,LINEA CEP,Metodo de dispersion
0,AHN3VLNX6,PAID,2024-01-31T19:45:57,324.85,b9fc2374-c741-4f4b-a06d-da3935b1a99b,00bf0fb9-405a-4b41-9ace-14dfe8e0b471,127456013890994028,AZTECA,Omar Polo Ochoa,2024-01-31T00:00,...,BANORTE,40072,AHN3VLNX6_03.Third_batch,2024-01-31,127,40127,AZTECA,,"2024-01-31,42644264202401312821502472,40072,40...",BANORTE
1,ASSKDM3KS,PAID,2024-01-31T19:46:08,711.39,b9fc2374-c741-4f4b-a06d-da3935b1a99b,0194010b-f10f-48fd-9b19-5fb77fea13ea,659802020000196080,"Opciones Empresariales del Noreste, S.A. de C....",Alan Orlando Gonzalez Rodriguez,2024-01-31T00:00,...,BANORTE,40072,ASSKDM3KS_03.Third_batch,2024-01-31,659,90659,ASP INTEGRA OPC,,"2024-01-31,42644264202401312821503249,40072,90...",BANORTE
2,ASC8GPZ5Q,PAID,2024-01-31T19:45:52,"1,500.61",b9fc2374-c741-4f4b-a06d-da3935b1a99b,019d425c-787f-4b39-99bd-e6641505ee39,659802020000267294,"Opciones Empresariales del Noreste, S.A. de C....",Jose Guadalupe Herrera Acosta,2024-01-31T00:00,...,BANORTE,40072,ASC8GPZ5Q_03.Third_batch,2024-01-31,659,90659,ASP INTEGRA OPC,,"2024-01-31,42644264202401312821502734,40072,90...",BANORTE
3,AMHFXR2F7,PAID,2024-01-31T19:45:57,179.19,b9fc2374-c741-4f4b-a06d-da3935b1a99b,023aeb3b-712b-4472-a8c6-17a42db36c6f,659802020000208334,"Opciones Empresariales del Noreste, S.A. de C....",Alejandro Ponce Estrada,2024-01-31T00:00,...,BANORTE,40072,AMHFXR2F7_03.Third_batch,2024-01-31,659,90659,ASP INTEGRA OPC,,"2024-01-31,42644264202401312821503435,40072,90...",BANORTE
4,A9TNVMKB3,PAID,2024-01-31T19:45:48,"1,002.80",b9fc2374-c741-4f4b-a06d-da3935b1a99b,04bc1b25-2e2c-4389-a017-d6a39cc67204,012760001859288342,"BBVA Bancomer, S.A.",Tersesita Rivas,2024-01-31T00:00,...,BANORTE,40072,A9TNVMKB3_03.Third_batch,2024-01-31,012,40012,BBVA BANCOMER,,"2024-01-31,42644264202401312821502874,40072,40...",BANORTE

In [44]:
rs_final = rs2[['disbursement_tracking_key','bank_account_owner_name','report_id','CLABE',
                'Nombre de la instituci√≥n','amount','Comision','status','error_description','Date_respuesta','Batch_time',
                'Metodo de dispersion']]
rs_final.rename(columns = {'disbursement_tracking_key':'Rastreo CEP'
                           ,'bank_account_owner_name':'Nombre','CLABE':'Cuenta'
                           ,'Nombre de la instituci√≥n':'Banco','amount':'Importe','status':'Estatus'
                           ,'error_description':'Mensaje'}, inplace=True)
rs_final['Cuenta'] = "'"+rs_final['Cuenta']
rs_final.sort_values(by=['Estatus'], ascending=True, inplace=True)
rs_final.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_7372\1871368444.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rs_final.rename(columns = {'disbursement_tracking_key':'Rastreo CEP'
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_7372\1871368444.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rs_final['Cuenta'] = "'"+rs_final['Cuenta']
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_7372\1871368444.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rs_final.sort_values(by=['Estatus'], ascending=True, inplace=True)

,Rastreo CEP,Nombre,report_id,Cuenta,Banco,Importe,Comision,Estatus,Mensaje,Date_respuesta,Batch_time,Metodo de dispersion
100381,20240131400140HDH0001454314320,Erika Jurez Becerril,ADHZFJKR8,'012180015570999609,BBVA BANCOMER,268.31,,ERROR,DEVOLUCION(20): Excede el limite de saldo auto...,2024-01-31,02. Second_batch,SANTANDER
34150,20240131400140HDH0001455904410,Virginia Jaquelin Garcia Rico,ADBKHB4JB,'012180015027496503,BBVA BANCOMER,319.09,,ERROR,DEVOLUCION(20): Excede el limite de saldo auto...,2024-01-31,01. First_batch,SANTANDER
46730,18D621470BF7CB78,Rosa Isela Gracia Hernandez,AJ65JYCQF,'012180015479397496,BBVA BANCOMER,670.77,,ERROR,/21/CB Return Exceeds authorized account balan...,2024-01-31,01. First_batch,SANTANDER
19832,20240131400140HDH0001455545510,Alexis torres serna,A7WWDXCQM,'002073560171389992,BANAMEX,"6,947.24",,ERROR,DEVOLUCION(06): Cuenta no pertenece al Partici...,2024-01-31,01. First_batch,SANTANDER
83635,20240131400140HDH0001454744730,Jonathan Moreno Garcia,AWHVF3KRW,'012180015862540368,BBVA BANCOMER,75.71,,ERROR,DEVOLUCION(20): Excede el limite de saldo auto...,2024-01-31,01. First_batch,SANTANDER

In [45]:
rs_final.shape

(102262, 12)

In [46]:
rs_final.to_csv(r'G:\.shortcut-targets-by-id\1Oe28Mf9uSidMamjllDen2gkNnC59eSUr\3.-Settlement\Respuestas Swap\2024\01. Enero 2024\Respuesta 2024-01-31.csv',index=False)