In [17]:
import numpy as np
import pandas as pd
import zipfile
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# SFTP

## READING ZIP FILES

### JUNIO

In [ ]:
jun_1=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\01062020\PAYCLIP_ProcessedTrans_01062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_2=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\02062020\PAYCLIP_ProcessedTrans_02062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_3=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\03062020\PAYCLIP_ProcessedTrans_03062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_4=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\04062020\PAYCLIP_ProcessedTrans_04062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_5=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\05062020\PAYCLIP_ProcessedTrans_05062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_6=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\06062020\PAYCLIP_ProcessedTrans_06062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_7=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\07062020\PAYCLIP_ProcessedTrans_07062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_8=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\09062020\PAYCLIP_ProcessedTrans_09062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_9=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\10062020\PAYCLIP_ProcessedTrans_10062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_10=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\11062020\PAYCLIP_ProcessedTrans_11062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_11=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\12062020\PAYCLIP_ProcessedTrans_12062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_12=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\13062020\PAYCLIP_ProcessedTrans_13062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_13=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\14062020\PAYCLIP_ProcessedTrans_14062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_14=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\15062020\PAYCLIP_ProcessedTrans_15062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_15=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\16062020\PAYCLIP_ProcessedTrans_16062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_16=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\17062020\PAYCLIP_ProcessedTrans_17062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_17=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\18062020\PAYCLIP_ProcessedTrans_18062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_18=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\19062020\PAYCLIP_ProcessedTrans_19062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_19=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\20062020\PAYCLIP_ProcessedTrans_20062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_20=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\21062020\PAYCLIP_ProcessedTrans_21062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_21=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\22062020\PAYCLIP_ProcessedTrans_22062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_22=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\23062020\PAYCLIP_ProcessedTrans_23062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_23=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\24062020\PAYCLIP_ProcessedTrans_24062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_24=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\25062020\PAYCLIP_ProcessedTrans_25062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_25=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\26062020\PAYCLIP_ProcessedTrans_26062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_26=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\27062020\PAYCLIP_ProcessedTrans_27062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_27=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\28062020\PAYCLIP_ProcessedTrans_28062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_28=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\29062020\PAYCLIP_ProcessedTrans_29062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jun_29=pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\6. JUNIO\30062020\PAYCLIP_ProcessedTrans_30062020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})

In [ ]:
jun_1['SFTP'] = '20200601'
jun_2['SFTP'] = '20200602'
jun_3['SFTP'] = '20200603'
jun_4['SFTP'] = '20200604'
jun_5['SFTP'] = '20200605'
jun_6['SFTP'] = '20200606'
jun_7['SFTP'] = '20200607'
jun_8['SFTP'] = '20200609'
jun_9['SFTP'] = '20200610'
jun_10['SFTP'] = '20200611'
jun_11['SFTP'] = '20200612'
jun_12['SFTP'] = '20200613'
jun_13['SFTP'] = '20200614'
jun_14['SFTP'] = '20200615'
jun_15['SFTP'] = '20200616'
jun_16['SFTP'] = '20200617'
jun_17['SFTP'] = '20200618'
jun_18['SFTP'] = '20200619'
jun_19['SFTP'] = '20200620'
jun_20['SFTP'] = '20200621'
jun_21['SFTP'] = '20200622'
jun_22['SFTP'] = '20200623'
jun_23['SFTP'] = '20200624'
jun_24['SFTP'] = '20200625'
jun_25['SFTP'] = '20200626'
jun_26['SFTP'] = '20200627'
jun_27['SFTP'] = '20200628'
jun_28['SFTP'] = '20200629'
jun_29['SFTP'] = '20200630'

In [ ]:
sftp_processed_jun = pd.concat([jun_1,jun_2,jun_3,jun_4,jun_5,jun_6,jun_7,jun_8,jun_9,jun_10,jun_11,jun_12,jun_13,jun_14
                                ,jun_15,jun_16,jun_17,jun_18,jun_19,jun_20,jun_21,jun_22,jun_23,jun_24,jun_25,jun_26,jun_27
                                ,jun_28,jun_29])
sftp_processed_jun.drop(['Empty','Empty.2','Empty.3','Empty.5','Empty.6','Empty.7'],axis=1,inplace=True)
sftp_processed_jun.head()

### JULIO

In [19]:
jul_1 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\01072020\PAYCLIP_ProcessedTrans_01072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_2 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\02072020\PAYCLIP_ProcessedTrans_02072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_3 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\03072020\PAYCLIP_ProcessedTrans_03072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_4 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\04072020\PAYCLIP_ProcessedTrans_04072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_5 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\05072020\PAYCLIP_ProcessedTrans_05072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_6 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\06072020\PAYCLIP_ProcessedTrans_06072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_7 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\07072020\PAYCLIP_ProcessedTrans_07072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_8 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\08072020\PAYCLIP_ProcessedTrans_08072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_9 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\09072020\PAYCLIP_ProcessedTrans_09072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_10 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\10072020\PAYCLIP_ProcessedTrans_10072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_11 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\11072020\PAYCLIP_ProcessedTrans_11072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_12 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\12072020\PAYCLIP_ProcessedTrans_12072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_13 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\13072020\PAYCLIP_ProcessedTrans_13072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})
jul_14 =pd.read_csv(r'C:\Users\Cristian.Aparicio\Google Drive\2.-CONCILIACIONES Y POLIZA\SFTP BANORTE\2020 SFTP Banorte\7. JULIO\14072020\PAYCLIP_ProcessedTrans_14072020_V1.csv',names=['Afiliación','Fecha_txn','Fecha_deposito','order_id_db','Empty','Unknown','Empty.2','Empty.3','PAYCLIP','order_id','Tipo','Identificador','Tipo_2','Tarjeta','Monto','Empty.5','Empty.6','Empty.7','Unknown.2','Unknown.3','Mensaje_pago','Banco_pago','Credit_Debit','Brand','Unknown.8','Unknown.9'] ,dtype={'Monto':float,'order_id_db': object,'Afiliación':object,'Tarjeta':object,'order_id_db':object,'Unknown':object,'Unknown.2':object,'Fecha_txn':object,'Fecha_deposito':object})

In [20]:
jul_1['SFTP'] = '20200701'
jul_2['SFTP'] = '20200702'
jul_3['SFTP'] = '20200703'
jul_4['SFTP'] = '20200704'
jul_5['SFTP'] = '20200705'
jul_6['SFTP'] = '20200706'
jul_7['SFTP'] = '20200707'
jul_8['SFTP'] = '20200708'
jul_9['SFTP'] = '20200709'
jul_10['SFTP'] = '20200710'
jul_11['SFTP'] = '20200711'
jul_12['SFTP'] = '20200712'
jul_13['SFTP'] = '20200713'
jul_14['SFTP'] = '20200714'

In [21]:
sftp_processed_jul = pd.concat([jul_1,jul_2,jul_3,jul_4,jul_5,jul_6,jul_7,jul_8,jul_9,jul_10,jul_11,jul_12,jul_13,jul_14])
sftp_processed_jul.drop(['Empty','Empty.2','Empty.3','Empty.5','Empty.6','Empty.7'],axis=1,inplace=True)
sftp_processed_jul.head()

,Afiliación,Fecha_txn,Fecha_deposito,order_id_db,Unknown,PAYCLIP,order_id,Tipo,Identificador,Tipo_2,...,Monto,Unknown.2,Unknown.3,Mensaje_pago,Banco_pago,Credit_Debit,Brand,Unknown.8,Unknown.9,SFTP
0,08343798,20200630000245,20200630000245,997242320679,136054,PAY_CLIP,991809768963,VTA,C,PRD,...,"50,000.00",00,A,Approved,BANAMEX,DEBITO,MASTERCARD,031133,NaN,20200701
1,08343798,20200630000320,20200630000320,899867675241,136051,PAY_CLIP,691809432292,VTA,R,PRD,...,"2,500.00",00,A,Approved,SANTANDER,DEBITO,MASTERCARD,032055,NaN,20200701
2,08343798,20200630000339,20200630000339,964005612863,136052,PAY_CLIP,991809769536,VTA,X,PRD,...,"86,666.00",05,D,Do not honor,BANCOMER,DEBITO,VISA------,000000,NaN,20200701
3,08343798,20200630000427,20200630000427,698208214833,136051,PAY_CLIP,691809432996,VTA,C,PRD,...,"2,500.00",00,A,Approved,SANTANDER,DEBITO,MASTERCARD,042765,NaN,20200701
4,08343798,20200630000451,20200630000451,442085403207,136043,PAY_CLIP,691809433235,VTA,X,PRD,...,"271,800.00",05,D,Do not honor,SCOTIABANK,CREDITO,VISA,000000,NaN,20200701

# PROCESSED ALL

In [22]:
sftp_processed = pd.concat([sftp_processed_jul])
# sftp.drop(['Empty','Empty.1','Empty.2','Empty.3','Empty.4'],axis=1,inplace=True)
# sftp.rename(columns ={'Ref. Interbancaria':'order_id'}, inplace=True)
sftp_processed.head()

,Afiliación,Fecha_txn,Fecha_deposito,order_id_db,Unknown,PAYCLIP,order_id,Tipo,Identificador,Tipo_2,...,Monto,Unknown.2,Unknown.3,Mensaje_pago,Banco_pago,Credit_Debit,Brand,Unknown.8,Unknown.9,SFTP
0,08343798,20200630000245,20200630000245,997242320679,136054,PAY_CLIP,991809768963,VTA,C,PRD,...,"50,000.00",00,A,Approved,BANAMEX,DEBITO,MASTERCARD,031133,NaN,20200701
1,08343798,20200630000320,20200630000320,899867675241,136051,PAY_CLIP,691809432292,VTA,R,PRD,...,"2,500.00",00,A,Approved,SANTANDER,DEBITO,MASTERCARD,032055,NaN,20200701
2,08343798,20200630000339,20200630000339,964005612863,136052,PAY_CLIP,991809769536,VTA,X,PRD,...,"86,666.00",05,D,Do not honor,BANCOMER,DEBITO,VISA------,000000,NaN,20200701
3,08343798,20200630000427,20200630000427,698208214833,136051,PAY_CLIP,691809432996,VTA,C,PRD,...,"2,500.00",00,A,Approved,SANTANDER,DEBITO,MASTERCARD,042765,NaN,20200701
4,08343798,20200630000451,20200630000451,442085403207,136043,PAY_CLIP,691809433235,VTA,X,PRD,...,"271,800.00",05,D,Do not honor,SCOTIABANK,CREDITO,VISA,000000,NaN,20200701

In [23]:
sftp_processed.shape

(34578, 21)

In [24]:
sftp_processed['Net Amount'] = sftp_processed['Monto']/100
sftp_processed['LAST4'] = sftp_processed['Tarjeta'].str[-4:].astype(str)
sftp_processed['CONCAT'] = sftp_processed['order_id'].astype(str).replace(' ', '',regex=True)+'-'+sftp_processed['Net Amount'].apply(np.floor).astype(str).replace(' ', '',regex=True)+'-'+sftp_processed['LAST4'].astype(str).replace(' ', '',regex=True)
sftp_processed['CONCAT_2'] = sftp_processed['LAST4'].astype(str).replace(' ', '',regex=True)+'-'+sftp_processed['Net Amount'].astype(str).replace(' ', '',regex=True)
sftp_processed['order_id'].fillna('NO EXISTE EN sftp_processed',inplace=True)
sftp_processed.head()

,Afiliación,Fecha_txn,Fecha_deposito,order_id_db,Unknown,PAYCLIP,order_id,Tipo,Identificador,Tipo_2,...,Banco_pago,Credit_Debit,Brand,Unknown.8,Unknown.9,SFTP,Net Amount,LAST4,CONCAT,CONCAT_2
0,08343798,20200630000245,20200630000245,997242320679,136054,PAY_CLIP,991809768963,VTA,C,PRD,...,BANAMEX,DEBITO,MASTERCARD,031133,NaN,20200701,500.00,5993,991809768963-500.0-5993,5993-500.0
1,08343798,20200630000320,20200630000320,899867675241,136051,PAY_CLIP,691809432292,VTA,R,PRD,...,SANTANDER,DEBITO,MASTERCARD,032055,NaN,20200701,25.00,9532,691809432292-25.0-9532,9532-25.0
2,08343798,20200630000339,20200630000339,964005612863,136052,PAY_CLIP,991809769536,VTA,X,PRD,...,BANCOMER,DEBITO,VISA------,000000,NaN,20200701,866.66,2037,991809769536-866.0-2037,2037-866.66
3,08343798,20200630000427,20200630000427,698208214833,136051,PAY_CLIP,691809432996,VTA,C,PRD,...,SANTANDER,DEBITO,MASTERCARD,042765,NaN,20200701,25.00,9532,691809432996-25.0-9532,9532-25.0
4,08343798,20200630000451,20200630000451,442085403207,136043,PAY_CLIP,691809433235,VTA,X,PRD,...,SCOTIABANK,CREDITO,VISA,000000,NaN,20200701,"2,718.00",0430,691809433235-2718.0-0430,0430-2718.0

In [25]:
sftp_processed.shape

(34578, 25)

# CHECKS

In [29]:
ticket_zendesk = pd.read_csv('TICKET 1989716.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
ticket_zendesk.rename(columns ={'order_id': 'order_id_db'},inplace=True) 
ticket_zendesk.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,receipt_no,last4,status_code,order_id_db,msi,clip_reader,status_msg,issuer,brand
0,071131a5-9086-402d-9df2-cb3b7fd038b1,8b933a18-7132-4235-a626-f4f012b50294,2020-07-10,2020-07-10 14:13:33,PAYWORKS-BANORTE,700.00,578975,481516,xqBFphA,5604,6,884446964357,0,Clip Classic,CancelReq,BBVA,VISA

In [30]:
# select columns by name
check_txn_xpay = sftp_processed[sftp_processed.order_id_db == ('884446964357')]
check_txn_xpay

,Afiliación,Fecha_txn,Fecha_deposito,order_id_db,Unknown,PAYCLIP,order_id,Tipo,Identificador,Tipo_2,...,Banco_pago,Credit_Debit,Brand,Unknown.8,Unknown.9,SFTP,Net Amount,LAST4,CONCAT,CONCAT_2
205,08343798,20200710091334,20200710091334,884446964357,136046,PAY_CLIP,993842748159,VTA,C,PRD,...,BANCOMER,DEBITO,VISA------,578975,NaN,20200711,700.00,5604,993842748159-700.0-5604,5604-700.0

# MATCH

In [31]:
match = check_txn_xpay.merge(ticket_zendesk[['order_id_db','merchant_id','transaction_id', 'status_code', 'status_msg']],on='order_id_db',how='left')
match['transaction_id'].fillna('NO MATCH',inplace=True)
match['status_code'].fillna('NO MATCH',inplace=True)
match['status_msg'].fillna('NO MATCH',inplace=True)
match.head()

,Afiliación,Fecha_txn,Fecha_deposito,order_id_db,Unknown,PAYCLIP,order_id,Tipo,Identificador,Tipo_2,...,Unknown.9,SFTP,Net Amount,LAST4,CONCAT,CONCAT_2,merchant_id,transaction_id,status_code,status_msg
0,08343798,20200710091334,20200710091334,884446964357,136046,PAY_CLIP,993842748159,VTA,C,PRD,...,NaN,20200711,700.00,5604,993842748159-700.0-5604,5604-700.0,071131a5-9086-402d-9df2-cb3b7fd038b1,8b933a18-7132-4235-a626-f4f012b50294,6,CancelReq

In [32]:
match.to_csv('TICKET 1989716 (PAYWORKS).csv',index=False)