In [1]:
import pandas as pd
import numpy as np

In [2]:
sql1 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\01-03 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql2 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\04-06 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql3 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\07-08 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql4 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\09-10 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql5 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\11-12 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql6 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\13-14 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql7 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\15-16 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql8 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\17-18 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql9 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\19-20 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql10 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\21-22 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql11 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\23-24 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql12 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\25-26 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql13 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\27-28 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql14 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\29-31 jan.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})

In [3]:
sql_m1 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\DISTINCT-1 JAN.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sql_m2 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\TXN BY DAY\DISTINCT-2 JAN.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})

In [4]:
sql = pd.concat([sql1,sql2,sql3,sql4,sql5,sql6,sql7,sql8,sql9,sql10,sql11,sql12,sql13,sql14,sql_m1,sql_m2])
sql['CONCAT'] = sql['order_id'].astype(str).replace(' ', '',regex=True)+'-'+sql['amount'].apply(np.floor).astype(str).replace(' ', '',regex=True)+'-'+sql['last4'].astype(str).replace(' ', '',regex=True)

In [5]:
sql.shape

(3414406, 14)

In [6]:
sql['psp'].unique()

array(['PROSA', 'AMEX', 'OPENPAY'], dtype=object)

# STATUS 1

In [7]:
sql_status_1 = sql[(sql['psp'] == 'PROSA') & (sql['status_code'] == 1)]
sql_status_1 .sort_values(by=('created_at'), ascending=True, inplace=True)
sql_status_1 .head()

C:\Users\CristianAparicio\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT
0,2501fd8c-1eef-495a-971a-6b8fd2bcef89,5c416482-bdb7-4efd-ab8f-8d0e9a729305,2020-01-01,2020-01-01 06:00:03,PROSA,203.0,152886,416916,9742,1,224635954827,0,Clip Plus,224635954827-203.0-9742
1,9604b67f-553e-43e3-8f8a-4e79e867943a,fd33ae12-6c55-45a6-be6d-bacbf00032f2,2020-01-01,2020-01-01 06:00:12,PROSA,685.0,125985,415231,0570,1,417310875943,0,Clip Plus,417310875943-685.0-0570
3,2654d890-5430-4e67-bda7-75f44cc29a56,435b659d-3617-4c81-9417-8d6293d3d4d8,2020-01-01,2020-01-01 06:00:22,PROSA,910.0,126154,477213,5940,1,972232969097,0,Clip Plus,972232969097-910.0-5940
4,914a4631-0bc9-49d4-a47a-96e65e065479,ac77da62-578f-49e2-bf02-bf5527680d28,2020-01-01,2020-01-01 06:00:25,PROSA,345.0,126195,415231,1375,1,297757767881,0,Clip Plus,297757767881-345.0-1375
5,68acbe5c-68b9-4d1b-91ee-6785f42e1a3e,11f7c3d4-3d5d-456c-87bb-9314e081a98e,2020-01-01,2020-01-01 06:00:32,PROSA,80.0,126320,415231,6173,1,612317407269,0,Clip Pro,612317407269-80.0-6173

In [8]:
sql_status_1.shape

(3007865, 14)

In [9]:
#ENERO
df1 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_01012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df1['SFTP'] = '20200101'
df2 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_03012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df2['SFTP'] = '20200103'
df3 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_04012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df3['SFTP'] = '20200104'
df4 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_07012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df4['SFTP'] = '20200107'
df5 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_08012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df5['SFTP'] = '20200108'
df6 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_09012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df6['SFTP'] = '20200109'
df7 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_10012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df7['SFTP'] = '20200110'
df8 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_11012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df8['SFTP'] = '20200111'
df9 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_14012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df9['SFTP'] = '20200114'
df10 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_15012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df10['SFTP'] = '20200115'
df11 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_16012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df11['SFTP'] = '20200116'
df12 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_17012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df12['SFTP'] = '20200117'
df13 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_18012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df13['SFTP'] = '20200118'
df14 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_21012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df14['SFTP'] = '20200121'
df15 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_22012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df15['SFTP'] = '20200122'
df16 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_23012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df16['SFTP'] = '20200123'
df17 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_24012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df17['SFTP'] = '20200124'
df18 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_25012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df18['SFTP'] = '20200125'
df19 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_28012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df19['SFTP'] = '20200128'
df20 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_29012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df20['SFTP'] = '20200129'
df21 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_30012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df21['SFTP'] = '20200130'
df22 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\1. ENERO\SFTP Y QUERIES\PAYCLIP_Settlement_31012020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df22['SFTP'] = '20200131'
# FEBRERO
df23 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\2. FEBRERO\SFTP Y QUERIES\PAYCLIP_Settlement_01022020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df23['SFTP'] = '20200201'
df24 = pd.read_csv(r'C:\Users\CristianAparicio\Documents\Documents\SFTP\2020\2. FEBRERO\SFTP Y QUERIES\PAYCLIP_Settlement_05022020_V1.csv',names=["Tipo de Columna","Afiliación","Referencia","Tarjeta","Monto depositado","Comisiones","Fecha txn","Importe Bruto","Tipo Moneda","Tipo txn","Iva","Iva por pago diferido","Iva pagado por cashback","Iva cobrado por cashback","Comisión pagada por cashback","Comisión cobrada por cashback","Comisión por pago diferido","Monto del Cashback","Núm Pagos","Diferimiento Inicial","Tipo de Plan","Código de Autorización","Empty","ECI","Ref. Interbancaria","Empty.1","Empty.2","Empty.3","Empty.4","Ref. de Payworks","Customer_ref1","Customer_ref2","Customer_ref3","Núm de Control"],dtype={'Importe Bruto':float,'Ref. Interbancaria': object,'Afiliación':object,'Referencia':object,'Tarjeta':object,'Núm Pagos':object,'Diferimiento Inicial':object,'Tipo de Plan':object,'Código de Autorización':object,'ECI':object})
df24['SFTP'] = '20200205'

In [10]:
sftp = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,
                 df22,df23,df24])
sftp.drop(['Empty','Empty.1','Empty.2','Empty.3','Empty.4'],axis=1,inplace=True)
sftp.rename(columns ={'Ref. Interbancaria':'order_id'}, inplace=True)
sftp.head()

,Tipo de Columna,Afiliación,Referencia,Tarjeta,Monto depositado,Comisiones,Fecha txn,Importe Bruto,Tipo Moneda,Tipo txn,...,Tipo de Plan,Código de Autorización,ECI,order_id,Ref. de Payworks,Customer_ref1,Customer_ref2,Customer_ref3,Núm de Control,SFTP
0,H,MXN,7704673312,-143786629,0,99681,3112191,20191231.0,NaN,BANORTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20200101
1,D,07668673,7668673,4152311356,20683,-273,20191229,21000.0,MXN,SETTLED,...,00,299677,74518999364001776686736,105454232159,D,N,PP36811902004238,-273.0,-44.0,20200101
2,D,07668673,7668673,5512387959,29548,-390,20191229,30000.0,MXN,SETTLED,...,00,084975,75445509364010876686738,749436511936,D,N,YZBzNQ2PLDjwO52h,-390.0,-62.0,20200101
3,D,07668673,7668673,4060950201,25882,-533,20191229,26500.0,MXN,SETTLED,...,00,03796C,74518999364000476686731,304345457448,C,I,ZDfdQ8xxTSYNqQjH,-533.0,-85.0,20200101
4,D,07668673,7668673,4037075621,28867,-546,20191229,29500.0,MXN,SETTLED,...,00,856519,74518999364000376686732,304310877731,C,N,bKYXDlzTz0KXrctA,-546.0,-87.0,20200101

In [11]:
sftp.shape

(3481980, 30)

In [12]:
sftp_fecha_deposito = sftp[(sftp['Tipo txn'] == 'BANORTE')]
sftp_fecha_deposito = sftp_fecha_deposito[['SFTP', 'Importe Bruto']]
sftp_fecha_deposito.rename(columns ={'Importe Bruto': 'Fecha_deposito'},inplace=True)                                                
sftp_fecha_deposito.head()

       SFTP  Fecha_deposito
0  20200101      20191231.0
0  20200103      20200102.0
0  20200104      20200103.0
0  20200107      20200106.0
0  20200108      20200107.0

In [13]:
sftp = sftp[(sftp['Tipo txn'] == 'SETTLED')]
sftp = sftp.merge(sftp_fecha_deposito[['SFTP', 'Fecha_deposito']],on='SFTP',how='left')

In [14]:
sftp['Fecha txn'] = pd.to_datetime(sftp['Fecha txn'], format='%Y%m%d').dt.date
sftp['SFTP'] = pd.to_datetime(sftp['SFTP'], format='%Y%m%d').dt.date
sftp['Fecha_deposito'] = pd.to_datetime(sftp['Fecha_deposito'], format='%Y%m%d').dt.date

In [15]:
sftp['Net Amount'] = sftp['Importe Bruto']/100
sftp['LAST4'] = sftp['Tarjeta'].str[-4:].astype(str)
sftp['CONCAT'] = sftp['order_id'].astype(str).replace(' ', '',regex=True)+'-'+sftp['Net Amount'].apply(np.floor).astype(str).replace(' ', '',regex=True)+'-'+sftp['LAST4'].astype(str).replace(' ', '',regex=True)
sftp['order_id'].fillna('NO EXISTE EN SFTP',inplace=True)
sftp.head()

,Tipo de Columna,Afiliación,Referencia,Tarjeta,Monto depositado,Comisiones,Fecha txn,Importe Bruto,Tipo Moneda,Tipo txn,...,Ref. de Payworks,Customer_ref1,Customer_ref2,Customer_ref3,Núm de Control,SFTP,Fecha_deposito,Net Amount,LAST4,CONCAT
0,D,07668673,7668673,4152311356,20683,-273,2019-12-29,21000.0,MXN,SETTLED,...,D,N,PP36811902004238,-273.0,-44.0,2020-01-01,2019-12-31,210.0,1356,105454232159-210.0-1356
1,D,07668673,7668673,5512387959,29548,-390,2019-12-29,30000.0,MXN,SETTLED,...,D,N,YZBzNQ2PLDjwO52h,-390.0,-62.0,2020-01-01,2019-12-31,300.0,7959,749436511936-300.0-7959
2,D,07668673,7668673,4060950201,25882,-533,2019-12-29,26500.0,MXN,SETTLED,...,C,I,ZDfdQ8xxTSYNqQjH,-533.0,-85.0,2020-01-01,2019-12-31,265.0,0201,304345457448-265.0-0201
3,D,07668673,7668673,4037075621,28867,-546,2019-12-29,29500.0,MXN,SETTLED,...,C,N,bKYXDlzTz0KXrctA,-546.0,-87.0,2020-01-01,2019-12-31,295.0,5621,304310877731-295.0-5621
4,D,07668673,7668673,4910894022,59587,-787,2019-12-29,60500.0,MXN,SETTLED,...,D,N,bKYXFoyd4nXebleM,-787.0,-126.0,2020-01-01,2019-12-31,605.0,4022,292557901865-605.0-4022

In [16]:
sftp.shape

(3480557, 34)

In [17]:
data_status_1 = sql_status_1.merge(sftp[['CONCAT','SFTP', 'Fecha txn', 'Fecha_deposito']],on='CONCAT',how='left')
data_status_1['SFTP'].fillna('NO ENCONTRADO EN SFTP',inplace=True)
data_status_1['Fecha txn'].fillna('NO ENCONTRADO EN SFTP',inplace=True)
data_status_1['Fecha_deposito'].fillna('NO ENCONTRADO EN SFTP',inplace=True)
data_status_1.drop_duplicates(subset ="CONCAT", keep = 'last', inplace = True) 
data_status_1.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT,SFTP,Fecha txn,Fecha_deposito
0,2501fd8c-1eef-495a-971a-6b8fd2bcef89,5c416482-bdb7-4efd-ab8f-8d0e9a729305,2020-01-01,2020-01-01 06:00:03,PROSA,203.0,152886,416916,9742,1,224635954827,0,Clip Plus,224635954827-203.0-9742,2020-01-03,2020-01-01,2020-01-02
1,9604b67f-553e-43e3-8f8a-4e79e867943a,fd33ae12-6c55-45a6-be6d-bacbf00032f2,2020-01-01,2020-01-01 06:00:12,PROSA,685.0,125985,415231,0570,1,417310875943,0,Clip Plus,417310875943-685.0-0570,2020-01-03,2020-01-01,2020-01-02
2,2654d890-5430-4e67-bda7-75f44cc29a56,435b659d-3617-4c81-9417-8d6293d3d4d8,2020-01-01,2020-01-01 06:00:22,PROSA,910.0,126154,477213,5940,1,972232969097,0,Clip Plus,972232969097-910.0-5940,2020-01-03,2020-01-01,2020-01-02
3,914a4631-0bc9-49d4-a47a-96e65e065479,ac77da62-578f-49e2-bf02-bf5527680d28,2020-01-01,2020-01-01 06:00:25,PROSA,345.0,126195,415231,1375,1,297757767881,0,Clip Plus,297757767881-345.0-1375,2020-01-03,2020-01-01,2020-01-02
4,68acbe5c-68b9-4d1b-91ee-6785f42e1a3e,11f7c3d4-3d5d-456c-87bb-9314e081a98e,2020-01-01,2020-01-01 06:00:32,PROSA,80.0,126320,415231,6173,1,612317407269,0,Clip Pro,612317407269-80.0-6173,2020-01-03,2020-01-01,2020-01-02

In [18]:
data_status_1.shape

(3007865, 17)

In [19]:
duplicates_status_1 = data_status_1[data_status_1.duplicated(['CONCAT'] , keep=False)]
duplicates_status_1.head()

Empty DataFrame
Columns: [merchant_id, transaction_id, date, created_at, psp, amount, clave_autorizacion, bin, last4, status_code, order_id, msi, clip_reader, CONCAT, SFTP, Fecha txn, Fecha_deposito]
Index: []

In [20]:
duplicates_status_1.shape

(0, 17)

In [21]:
results_status_1 = data_status_1[(data_status_1['Fecha txn'] != 'NO ENCONTRADO EN SFTP')]
results_status_1.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT,SFTP,Fecha txn,Fecha_deposito
0,2501fd8c-1eef-495a-971a-6b8fd2bcef89,5c416482-bdb7-4efd-ab8f-8d0e9a729305,2020-01-01,2020-01-01 06:00:03,PROSA,203.0,152886,416916,9742,1,224635954827,0,Clip Plus,224635954827-203.0-9742,2020-01-03,2020-01-01,2020-01-02
1,9604b67f-553e-43e3-8f8a-4e79e867943a,fd33ae12-6c55-45a6-be6d-bacbf00032f2,2020-01-01,2020-01-01 06:00:12,PROSA,685.0,125985,415231,0570,1,417310875943,0,Clip Plus,417310875943-685.0-0570,2020-01-03,2020-01-01,2020-01-02
2,2654d890-5430-4e67-bda7-75f44cc29a56,435b659d-3617-4c81-9417-8d6293d3d4d8,2020-01-01,2020-01-01 06:00:22,PROSA,910.0,126154,477213,5940,1,972232969097,0,Clip Plus,972232969097-910.0-5940,2020-01-03,2020-01-01,2020-01-02
3,914a4631-0bc9-49d4-a47a-96e65e065479,ac77da62-578f-49e2-bf02-bf5527680d28,2020-01-01,2020-01-01 06:00:25,PROSA,345.0,126195,415231,1375,1,297757767881,0,Clip Plus,297757767881-345.0-1375,2020-01-03,2020-01-01,2020-01-02
4,68acbe5c-68b9-4d1b-91ee-6785f42e1a3e,11f7c3d4-3d5d-456c-87bb-9314e081a98e,2020-01-01,2020-01-01 06:00:32,PROSA,80.0,126320,415231,6173,1,612317407269,0,Clip Pro,612317407269-80.0-6173,2020-01-03,2020-01-01,2020-01-02

In [22]:
results_status_1.shape

(3007652, 17)

In [23]:
NA_status_1 = data_status_1[(data_status_1['Fecha txn'] == 'NO ENCONTRADO EN SFTP')]
NA_status_1.to_csv("NO ENCONTRADO CON ORDER_ID ENERO.csv")
NA_status_1.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT,SFTP,Fecha txn,Fecha_deposito
2662,4477c02f-5489-4c3a-bf26-45c8c60b4dbf,8552bbc1-3ce1-4c4f-a0d7-d01f69996cfb,2020-01-01,2020-01-01 08:42:13,PROSA,450.0,I5B4Q7,487512,2107,1,789960784969,0,Clip Plus,789960784969-450.0-2107,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
33727,5c1ff463-f52f-4da9-af13-6e63903b1d83,50493050-c955-4680-bf71-72b260c3f09b,2020-01-02,2020-01-02 13:53:25,PROSA,50.0,005887,520212,3628,1,679323539128,0,Clip Plus,679323539128-50.0-3628,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
36586,8262f950-bd62-4c5e-b384-ef0317680087,022dc65f-1cfd-49ad-b41c-5229f7a40e87,2020-01-02,2020-01-02 15:42:12,PROSA,530.0,YNJ5K9,487823,4402,1,685411027952,0,Clip Plus,685411027952-530.0-4402,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
67973,5ff69c80-584a-45d1-9e91-93723f088e4f,22377e06-3bc8-43b9-b478-2e76685dcb06,2020-01-02,2020-01-02 21:11:58,PROSA,878.0,YNQAGN,487823,4402,1,111471834804,0,Clip Plus,111471834804-878.0-4402,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
74917,b53cdb46-2030-4fdb-85a2-798db9808a19,5a009cd1-f88e-42d0-8fcd-156e564480cf,2020-01-02,2020-01-02 22:07:39,PROSA,600.0,002491,414718,9117,1,131677703564,0,Clip Plus,131677703564-600.0-9117,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP

In [24]:
NA_status_1.shape

(213, 17)

# INDEX USANDO CLAVE_AUTORIZACION

In [25]:
sinref = pd.read_csv('NO ENCONTRADO CON ORDER_ID ENERO.csv',dtype={'amount':float,'clave_autorizacion': object,'bin':object,'last4':object,'order_id':object})
sinref.drop(['Fecha txn','SFTP','Fecha_deposito','CONCAT','Unnamed: 0'],axis=1,inplace=True)
sinref['CONCAT'] = sinref['clave_autorizacion'].astype(str).replace(' ', '',regex=True)+'-'+sinref['amount'].apply(np.floor).astype(str).replace(' ', '',regex=True)+'-'+sinref['last4'].astype(str).replace(' ', '',regex=True)
sinref.sort_values(by=('created_at'), ascending=True, inplace=True)
sinref.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT
0,4477c02f-5489-4c3a-bf26-45c8c60b4dbf,8552bbc1-3ce1-4c4f-a0d7-d01f69996cfb,2020-01-01,2020-01-01 08:42:13,PROSA,450.0,I5B4Q7,487512,2107,1,789960784969,0,Clip Plus,I5B4Q7-450.0-2107
1,5c1ff463-f52f-4da9-af13-6e63903b1d83,50493050-c955-4680-bf71-72b260c3f09b,2020-01-02,2020-01-02 13:53:25,PROSA,50.0,005887,520212,3628,1,679323539128,0,Clip Plus,005887-50.0-3628
2,8262f950-bd62-4c5e-b384-ef0317680087,022dc65f-1cfd-49ad-b41c-5229f7a40e87,2020-01-02,2020-01-02 15:42:12,PROSA,530.0,YNJ5K9,487823,4402,1,685411027952,0,Clip Plus,YNJ5K9-530.0-4402
3,5ff69c80-584a-45d1-9e91-93723f088e4f,22377e06-3bc8-43b9-b478-2e76685dcb06,2020-01-02,2020-01-02 21:11:58,PROSA,878.0,YNQAGN,487823,4402,1,111471834804,0,Clip Plus,YNQAGN-878.0-4402
4,b53cdb46-2030-4fdb-85a2-798db9808a19,5a009cd1-f88e-42d0-8fcd-156e564480cf,2020-01-02,2020-01-02 22:07:39,PROSA,600.0,002491,414718,9117,1,131677703564,0,Clip Plus,002491-600.0-9117

In [26]:
sinref.shape

(213, 14)

In [27]:
sftp_clave_autorizacion = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17
                                     ,df18,df19,df20,df21,df22,df23,df24])
sftp_clave_autorizacion.drop(['Empty','Empty.1','Empty.2','Empty.3','Empty.4'],axis=1,inplace=True)
sftp_clave_autorizacion.rename(columns ={'Ref. Interbancaria':'order_id'}, inplace=True)

In [28]:
sftp_fecha_deposito_clave_autorizacion = sftp_clave_autorizacion[(sftp_clave_autorizacion['Tipo txn'] == 'BANORTE')]
sftp_fecha_deposito_clave_autorizacion = sftp_fecha_deposito_clave_autorizacion[['SFTP', 'Importe Bruto']]
sftp_fecha_deposito_clave_autorizacion.rename(columns ={'Importe Bruto': 'Fecha_deposito'},inplace=True)
sftp_fecha_deposito_clave_autorizacion.head()

       SFTP  Fecha_deposito
0  20200101      20191231.0
0  20200103      20200102.0
0  20200104      20200103.0
0  20200107      20200106.0
0  20200108      20200107.0

In [29]:
sftp_clave_autorizacion = sftp_clave_autorizacion[(sftp_clave_autorizacion['Tipo txn'] == 'SETTLED')]
sftp_clave_autorizacion = sftp_clave_autorizacion.merge(sftp_fecha_deposito_clave_autorizacion[['SFTP', 'Fecha_deposito']],on='SFTP',how='left')

In [30]:
sftp_clave_autorizacion['Fecha txn'] = pd.to_datetime(sftp_clave_autorizacion['Fecha txn'], format='%Y%m%d').dt.date
sftp_clave_autorizacion['SFTP'] = pd.to_datetime(sftp_clave_autorizacion['SFTP'], format='%Y%m%d').dt.date
sftp_clave_autorizacion['Fecha_deposito'] = pd.to_datetime(sftp_clave_autorizacion['Fecha_deposito'], format='%Y%m%d').dt.date

In [31]:
sftp_clave_autorizacion['Net Amount'] = sftp_clave_autorizacion['Importe Bruto']/100
sftp_clave_autorizacion['last4'] = sftp_clave_autorizacion['Tarjeta'].str[-4:].astype(str)
sftp_clave_autorizacion['CONCAT'] = sftp_clave_autorizacion['Código de Autorización'].astype(str).replace(' ', '',regex=True)+'-'+sftp_clave_autorizacion['Net Amount'].apply(np.floor).astype(str).replace(' ', '',regex=True)+'-'+sftp_clave_autorizacion['last4'].astype(str).replace(' ', '',regex=True)
sftp_clave_autorizacion['order_id'].fillna('NO EXISTE EN SFTP',inplace=True)
sftp_clave_autorizacion.head()

,Tipo de Columna,Afiliación,Referencia,Tarjeta,Monto depositado,Comisiones,Fecha txn,Importe Bruto,Tipo Moneda,Tipo txn,...,Ref. de Payworks,Customer_ref1,Customer_ref2,Customer_ref3,Núm de Control,SFTP,Fecha_deposito,Net Amount,last4,CONCAT
0,D,07668673,7668673,4152311356,20683,-273,2019-12-29,21000.0,MXN,SETTLED,...,D,N,PP36811902004238,-273.0,-44.0,2020-01-01,2019-12-31,210.0,1356,299677-210.0-1356
1,D,07668673,7668673,5512387959,29548,-390,2019-12-29,30000.0,MXN,SETTLED,...,D,N,YZBzNQ2PLDjwO52h,-390.0,-62.0,2020-01-01,2019-12-31,300.0,7959,084975-300.0-7959
2,D,07668673,7668673,4060950201,25882,-533,2019-12-29,26500.0,MXN,SETTLED,...,C,I,ZDfdQ8xxTSYNqQjH,-533.0,-85.0,2020-01-01,2019-12-31,265.0,0201,03796C-265.0-0201
3,D,07668673,7668673,4037075621,28867,-546,2019-12-29,29500.0,MXN,SETTLED,...,C,N,bKYXDlzTz0KXrctA,-546.0,-87.0,2020-01-01,2019-12-31,295.0,5621,856519-295.0-5621
4,D,07668673,7668673,4910894022,59587,-787,2019-12-29,60500.0,MXN,SETTLED,...,D,N,bKYXFoyd4nXebleM,-787.0,-126.0,2020-01-01,2019-12-31,605.0,4022,067983-605.0-4022

In [32]:
sftp_clave_autorizacion.shape

(3480557, 34)

In [33]:
results2 = sinref.merge(sftp_clave_autorizacion[['CONCAT','SFTP', 'Fecha txn', 'Fecha_deposito']],on='CONCAT',how='left')
results2['Fecha txn'].fillna('NO ENCONTRADO EN SFTP',inplace=True)
results2['Fecha_deposito'].fillna('NO ENCONTRADO EN SFTP',inplace=True)
results2.drop_duplicates(subset ="CONCAT", keep = 'last', inplace = True)
results2.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT,SFTP,Fecha txn,Fecha_deposito
0,4477c02f-5489-4c3a-bf26-45c8c60b4dbf,8552bbc1-3ce1-4c4f-a0d7-d01f69996cfb,2020-01-01,2020-01-01 08:42:13,PROSA,450.0,I5B4Q7,487512,2107,1,789960784969,0,Clip Plus,I5B4Q7-450.0-2107,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
1,5c1ff463-f52f-4da9-af13-6e63903b1d83,50493050-c955-4680-bf71-72b260c3f09b,2020-01-02,2020-01-02 13:53:25,PROSA,50.0,005887,520212,3628,1,679323539128,0,Clip Plus,005887-50.0-3628,2020-01-04,2020-01-02,2020-01-03
2,8262f950-bd62-4c5e-b384-ef0317680087,022dc65f-1cfd-49ad-b41c-5229f7a40e87,2020-01-02,2020-01-02 15:42:12,PROSA,530.0,YNJ5K9,487823,4402,1,685411027952,0,Clip Plus,YNJ5K9-530.0-4402,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
3,5ff69c80-584a-45d1-9e91-93723f088e4f,22377e06-3bc8-43b9-b478-2e76685dcb06,2020-01-02,2020-01-02 21:11:58,PROSA,878.0,YNQAGN,487823,4402,1,111471834804,0,Clip Plus,YNQAGN-878.0-4402,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
4,b53cdb46-2030-4fdb-85a2-798db9808a19,5a009cd1-f88e-42d0-8fcd-156e564480cf,2020-01-02,2020-01-02 22:07:39,PROSA,600.0,002491,414718,9117,1,131677703564,0,Clip Plus,002491-600.0-9117,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP

In [34]:
results2.shape

(213, 17)

In [35]:
results2_status_1 = results2[(results2['Fecha txn'] != 'NO ENCONTRADO EN SFTP')]
results2_status_1.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT,SFTP,Fecha txn,Fecha_deposito
1,5c1ff463-f52f-4da9-af13-6e63903b1d83,50493050-c955-4680-bf71-72b260c3f09b,2020-01-02,2020-01-02 13:53:25,PROSA,50.0,005887,520212,3628,1,679323539128,0,Clip Plus,005887-50.0-3628,2020-01-04,2020-01-02,2020-01-03
5,8810a530-2999-435b-9f5d-8ab1b6d0461f,2cd9fcfb-d6b6-46c8-b54f-819c844b1711,2020-01-03,2020-01-03 21:15:34,PROSA,380.0,061543,480061,3925,1,096897788045,0,Clip Plus,061543-380.0-3925,2020-01-07,2020-01-03,2020-01-06
6,7f138a36-4f74-4ab7-9cd1-c70f88d6d8bf,ce627400-3dd4-4499-b853-f49b500aa39f,2020-01-03,2020-01-04 01:08:11,PROSA,575.0,130876,481581,0966,1,090279445867,0,Clip Plus,130876-575.0-0966,2020-01-07,2020-01-03,2020-01-06
7,2c2bd1bd-3021-4b20-8085-186f7541db50,18747dc0-5f3a-4765-bc84-a8b631f313d9,2020-01-03,2020-01-04 02:31:20,PROSA,600.0,162693,534860,3487,1,098352436365,0,Clip Plus,162693-600.0-3487,2020-01-07,2020-01-03,2020-01-06
9,488fd749-45e0-4946-8c4f-f19179321a48,5f48d89e-1074-4647-aed0-346b02db06b9,2020-01-03,2020-01-04 03:50:17,PROSA,700.0,164691,481582,5751,1,391391854562,0,Clip Plus,164691-700.0-5751,2020-01-07,2020-01-03,2020-01-06

In [36]:
results2_status_1.shape

(66, 17)

In [37]:
NA2 = results2[(results2['Fecha txn'] == 'NO ENCONTRADO EN SFTP')]
NA2.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT,SFTP,Fecha txn,Fecha_deposito
0,4477c02f-5489-4c3a-bf26-45c8c60b4dbf,8552bbc1-3ce1-4c4f-a0d7-d01f69996cfb,2020-01-01,2020-01-01 08:42:13,PROSA,450.0,I5B4Q7,487512,2107,1,789960784969,0,Clip Plus,I5B4Q7-450.0-2107,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
2,8262f950-bd62-4c5e-b384-ef0317680087,022dc65f-1cfd-49ad-b41c-5229f7a40e87,2020-01-02,2020-01-02 15:42:12,PROSA,530.0,YNJ5K9,487823,4402,1,685411027952,0,Clip Plus,YNJ5K9-530.0-4402,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
3,5ff69c80-584a-45d1-9e91-93723f088e4f,22377e06-3bc8-43b9-b478-2e76685dcb06,2020-01-02,2020-01-02 21:11:58,PROSA,878.0,YNQAGN,487823,4402,1,111471834804,0,Clip Plus,YNQAGN-878.0-4402,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
4,b53cdb46-2030-4fdb-85a2-798db9808a19,5a009cd1-f88e-42d0-8fcd-156e564480cf,2020-01-02,2020-01-02 22:07:39,PROSA,600.0,002491,414718,9117,1,131677703564,0,Clip Plus,002491-600.0-9117,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP
8,14fbecdd-3b8e-4505-bb85-999d1b75c9dc,8c967d6b-1e1c-47a5-ac4d-0f7d3ee1ea2f,2020-01-03,2020-01-04 03:05:49,PROSA,471.0,R7R1J1,487512,6122,1,624888130832,0,Clip Plus,R7R1J1-471.0-6122,NaN,NO ENCONTRADO EN SFTP,NO ENCONTRADO EN SFTP

In [38]:
NA2.shape

(147, 17)

In [39]:
duplicates = results2[results2.duplicated(['CONCAT'] , keep=False)]
duplicates.to_csv("duplictes.csv")
duplicates.head()

Empty DataFrame
Columns: [merchant_id, transaction_id, date, created_at, psp, amount, clave_autorizacion, bin, last4, status_code, order_id, msi, clip_reader, CONCAT, SFTP, Fecha txn, Fecha_deposito]
Index: []

In [40]:
duplicates.shape

(0, 17)

# CREATE EXCEL

In [41]:
file_excel = pd.concat([results_status_1,results2_status_1])
file_excel.head()

,merchant_id,transaction_id,date,created_at,psp,amount,clave_autorizacion,bin,last4,status_code,order_id,msi,clip_reader,CONCAT,SFTP,Fecha txn,Fecha_deposito
0,2501fd8c-1eef-495a-971a-6b8fd2bcef89,5c416482-bdb7-4efd-ab8f-8d0e9a729305,2020-01-01,2020-01-01 06:00:03,PROSA,203.0,152886,416916,9742,1,224635954827,0,Clip Plus,224635954827-203.0-9742,2020-01-03,2020-01-01,2020-01-02
1,9604b67f-553e-43e3-8f8a-4e79e867943a,fd33ae12-6c55-45a6-be6d-bacbf00032f2,2020-01-01,2020-01-01 06:00:12,PROSA,685.0,125985,415231,0570,1,417310875943,0,Clip Plus,417310875943-685.0-0570,2020-01-03,2020-01-01,2020-01-02
2,2654d890-5430-4e67-bda7-75f44cc29a56,435b659d-3617-4c81-9417-8d6293d3d4d8,2020-01-01,2020-01-01 06:00:22,PROSA,910.0,126154,477213,5940,1,972232969097,0,Clip Plus,972232969097-910.0-5940,2020-01-03,2020-01-01,2020-01-02
3,914a4631-0bc9-49d4-a47a-96e65e065479,ac77da62-578f-49e2-bf02-bf5527680d28,2020-01-01,2020-01-01 06:00:25,PROSA,345.0,126195,415231,1375,1,297757767881,0,Clip Plus,297757767881-345.0-1375,2020-01-03,2020-01-01,2020-01-02
4,68acbe5c-68b9-4d1b-91ee-6785f42e1a3e,11f7c3d4-3d5d-456c-87bb-9314e081a98e,2020-01-01,2020-01-01 06:00:32,PROSA,80.0,126320,415231,6173,1,612317407269,0,Clip Pro,612317407269-80.0-6173,2020-01-03,2020-01-01,2020-01-02

In [42]:
file_excel.shape

(3007718, 17)

In [43]:
r1 = file_excel[(file_excel['date'] == '2020-01-01')]
r2 = file_excel[(file_excel['date'] == '2020-01-02')]
r3 = file_excel[(file_excel['date'] == '2020-01-03')]
r4 = file_excel[(file_excel['date'] == '2020-01-04')]
r5 = file_excel[(file_excel['date'] == '2020-01-05')]
r6 = file_excel[(file_excel['date'] == '2020-01-06')]
r7 = file_excel[(file_excel['date'] == '2020-01-07')]
r8 = file_excel[(file_excel['date'] == '2020-01-08')]
r9 = file_excel[(file_excel['date'] == '2020-01-09')]
r10 = file_excel[(file_excel['date'] == '2020-01-10')]
r11 = file_excel[(file_excel['date'] == '2020-01-11')]
r12 = file_excel[(file_excel['date'] == '2020-01-12')]
r13 = file_excel[(file_excel['date'] == '2020-01-13')]
r14 = file_excel[(file_excel['date'] == '2020-01-14')]
r15 = file_excel[(file_excel['date'] == '2020-01-15')]
r16 = file_excel[(file_excel['date'] == '2020-01-16')]
r17 = file_excel[(file_excel['date'] == '2020-01-17')]
r18 = file_excel[(file_excel['date'] == '2020-01-18')]
r19 = file_excel[(file_excel['date'] == '2020-01-19')]
r20 = file_excel[(file_excel['date'] == '2020-01-20')]
r21 = file_excel[(file_excel['date'] == '2020-01-21')]
r22 = file_excel[(file_excel['date'] == '2020-01-22')]
r23 = file_excel[(file_excel['date'] == '2020-01-23')]
r24 = file_excel[(file_excel['date'] == '2020-01-24')]
r25 = file_excel[(file_excel['date'] == '2020-01-25')]
r26 = file_excel[(file_excel['date'] == '2020-01-26')]
r27 = file_excel[(file_excel['date'] == '2020-01-27')]
r28 = file_excel[(file_excel['date'] == '2020-01-28')]
r29 = file_excel[(file_excel['date'] == '2020-01-29')]
r30 = file_excel[(file_excel['date'] == '2020-01-30')]
r31 = file_excel[(file_excel['date'] == '2020-01-31')]

In [44]:
writer = pd.ExcelWriter('CONCILIACION-CLIP JANUARY 01-16 2020.xlsx', engine='xlsxwriter', options={'encoding':'utf-8'})
r1.to_excel(writer, sheet_name='20200101', index=False)
r2.to_excel(writer, sheet_name='20200102', index=False)
r3.to_excel(writer, sheet_name='20200103', index=False)
r4.to_excel(writer, sheet_name='20200104', index=False)
r5.to_excel(writer, sheet_name='20200105', index=False)
r6.to_excel(writer, sheet_name='20200106', index=False)
r7.to_excel(writer, sheet_name='20200107', index=False)
r8.to_excel(writer, sheet_name='20200108', index=False)
r9.to_excel(writer, sheet_name='20200109', index=False)
r10.to_excel(writer, sheet_name='20200110', index=False)
r11.to_excel(writer, sheet_name='20200111', index=False)
r12.to_excel(writer, sheet_name='20200112', index=False)
r13.to_excel(writer, sheet_name='20200113', index=False)
r14.to_excel(writer, sheet_name='20200114', index=False)
r15.to_excel(writer, sheet_name='20200115', index=False)
r16.to_excel(writer, sheet_name='20200116', index=False)
# r17.to_excel(writer, sheet_name='20200117', index=False)
# r18.to_excel(writer, sheet_name='20200118', index=False)
# r19.to_excel(writer, sheet_name='20200119', index=False)
# r20.to_excel(writer, sheet_name='20200120', index=False)
# r21.to_excel(writer, sheet_name='20200121', index=False)
# r22.to_excel(writer, sheet_name='20200122', index=False)
# r23.to_excel(writer, sheet_name='20200123', index=False)
# r24.to_excel(writer, sheet_name='20200124', index=False)
# r25.to_excel(writer, sheet_name='20200125', index=False)
# r26.to_excel(writer, sheet_name='20200126', index=False)
# r27.to_excel(writer, sheet_name='20200127', index=False)
# r28.to_excel(writer, sheet_name='20200128', index=False)
# r29.to_excel(writer, sheet_name='20200129', index=False)
# r30.to_excel(writer, sheet_name='20200130', index=False)
# r31.to_excel(writer, sheet_name='20200131', index=False)
# NA2.to_excel(writer, sheet_name='MISSING JANUARY', index=False)
writer.save()

In [45]:
writer = pd.ExcelWriter('CONCILIACION-CLIP JANUARY 17-31 2020.xlsx', engine='xlsxwriter', options={'encoding':'utf-8'})
# r1.to_excel(writer, sheet_name='20200101', index=False)
# r2.to_excel(writer, sheet_name='20200102', index=False)
# r3.to_excel(writer, sheet_name='20200103', index=False)
# r4.to_excel(writer, sheet_name='20200104', index=False)
# r5.to_excel(writer, sheet_name='20200105', index=False)
# r6.to_excel(writer, sheet_name='20200106', index=False)
# r7.to_excel(writer, sheet_name='20200107', index=False)
# r8.to_excel(writer, sheet_name='20200108', index=False)
# r9.to_excel(writer, sheet_name='20200109', index=False)
# r10.to_excel(writer, sheet_name='20200110', index=False)
# r11.to_excel(writer, sheet_name='20200111', index=False)
# r12.to_excel(writer, sheet_name='20200112', index=False)
# r13.to_excel(writer, sheet_name='20200113', index=False)
# r14.to_excel(writer, sheet_name='20200114', index=False)
# r15.to_excel(writer, sheet_name='20200115', index=False)
# r16.to_excel(writer, sheet_name='20200116', index=False)
r17.to_excel(writer, sheet_name='20200117', index=False)
r18.to_excel(writer, sheet_name='20200118', index=False)
r19.to_excel(writer, sheet_name='20200119', index=False)
r20.to_excel(writer, sheet_name='20200120', index=False)
r21.to_excel(writer, sheet_name='20200121', index=False)
r22.to_excel(writer, sheet_name='20200122', index=False)
r23.to_excel(writer, sheet_name='20200123', index=False)
r24.to_excel(writer, sheet_name='20200124', index=False)
r25.to_excel(writer, sheet_name='20200125', index=False)
r26.to_excel(writer, sheet_name='20200126', index=False)
r27.to_excel(writer, sheet_name='20200127', index=False)
r28.to_excel(writer, sheet_name='20200128', index=False)
r29.to_excel(writer, sheet_name='20200129', index=False)
r30.to_excel(writer, sheet_name='20200130', index=False)
r31.to_excel(writer, sheet_name='20200131', index=False)
NA2.to_excel(writer, sheet_name='MISSING JANUARY', index=False)
writer.save()

# INDIVIDUAL CHECKS

In [46]:
# sftp.query('order_id == "217754088050"').to_csv(r"C:\Users\CristianAparicio\Documents\Documents\TRACKING TXN\txn faefb7e2-8e05-4d18-bac6-0d574e5ba376.csv")

# VALUES CONCILIATION

### TOTAL OPERACIONES BANORTE ALL STATUS EN 1 CLIP

op_status_1 = pd.pivot_table(file_excel,index=['date'],columns=['status_code'],values=['amount'],fill_value=0,aggfunc=[len,np.sum])
op_status_1.reset_index(inplace=True)
op_status_1.to_csv(r'C:\Users\Cristian.Aparicio\Documents\SFTP\SEPTIEMBRE\CONCILIACION\operaciones_clip_status_1_septiembre.csv',index=False)
op_status_1.head()

# INDIVIDUAL CHECKS

In [47]:
# sql.query('order_id == "199054359537"')