In [1]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook
import glob
import os
import datetime
pd.options.display.float_format = '{:,.2f}'.format
datetime.timedelta(days=1)
datetime.timedelta(1)

datetime.timedelta(days=1)

# SETTLEMENT

In [2]:
start_date = '2019-10-01'
final_date = '2019-10-31'

In [3]:
allfiles_settled = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\POLIZAS\2019\10. OCTUBRE\DATA\TPV*.csv', recursive=False)
allfiles_settled

['C:\\Users\\Cristian.Aparicio\\Documents\\POLIZAS\\2019\\10. OCTUBRE\\DATA\\TPV MERCHANT OCTUBRE 2019.csv']

In [7]:
settled = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in allfiles_settled])
settled.columns = settled.columns.str.strip().str.lower()
#settled['Date_file'] = settled["file_name"].str[-14:-4]
#settled['Date_file']= pd.to_datetime(settled['Date_file'])
settled['report_date_local']= pd.to_datetime(settled['report_date_local'])

In [8]:
settled.reset_index(inplace=True)
settled.drop(['index'],axis=1,inplace=True)
settled.head()

,report_date_local,merchant_id,no_pagos,total_transactions,total_fees_charged,total_taxes,applied_fees_benefits,applied_taxes_benefits,fee_direct_deposit,taxes_direct_deposit,total_adjustments,total_adjustments_fees_charged,total_adjustments_taxes,cobranza,total_released,total_retained,total_due,file_name
0,2019-10-01,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,"2,500.00",90.00,14.40,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"2,395.60",TPV MERCHANT OCTUBRE 2019.csv
1,2019-10-02,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,500.00,18.00,2.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,479.12,TPV MERCHANT OCTUBRE 2019.csv
2,2019-10-08,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,950.00,34.20,5.47,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,910.33,TPV MERCHANT OCTUBRE 2019.csv
3,2019-10-14,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,"1,500.00",54.00,8.64,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"1,437.36",TPV MERCHANT OCTUBRE 2019.csv
4,2019-10-22,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,500.00,18.00,2.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,479.12,TPV MERCHANT OCTUBRE 2019.csv

In [9]:
settled.shape

(814091, 18)

### CURRENT MONTH

In [10]:
settled_current_month = settled[(settled['report_date_local'] >= start_date) & (settled['report_date_local'] <= final_date)]
settled_current_month.head()

,report_date_local,merchant_id,no_pagos,total_transactions,total_fees_charged,total_taxes,applied_fees_benefits,applied_taxes_benefits,fee_direct_deposit,taxes_direct_deposit,total_adjustments,total_adjustments_fees_charged,total_adjustments_taxes,cobranza,total_released,total_retained,total_due,file_name
0,2019-10-01,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,"2,500.00",90.00,14.40,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"2,395.60",TPV MERCHANT OCTUBRE 2019.csv
1,2019-10-02,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,500.00,18.00,2.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,479.12,TPV MERCHANT OCTUBRE 2019.csv
2,2019-10-08,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,950.00,34.20,5.47,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,910.33,TPV MERCHANT OCTUBRE 2019.csv
3,2019-10-14,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,"1,500.00",54.00,8.64,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"1,437.36",TPV MERCHANT OCTUBRE 2019.csv
4,2019-10-22,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,500.00,18.00,2.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,479.12,TPV MERCHANT OCTUBRE 2019.csv

In [11]:
settled_current_month.shape

(814091, 18)

In [12]:
settled_current_month.dtypes

report_date_local                 datetime64[ns]
merchant_id                               object
no_pagos                                   int64
total_transactions                       float64
total_fees_charged                       float64
total_taxes                              float64
applied_fees_benefits                    float64
applied_taxes_benefits                   float64
fee_direct_deposit                       float64
taxes_direct_deposit                     float64
total_adjustments                        float64
total_adjustments_fees_charged           float64
total_adjustments_taxes                  float64
cobranza                                 float64
total_released                           float64
total_retained                           float64
total_due                                float64
file_name                                 object
dtype: object

In [ ]:
# def next_date(settled_current_month):
#     if settled_current_month['updated_time'] >= '20:00:00':
#         return settled_current_month['report_date_local'] + datetime.timedelta(days=1)
#     else:
#         return settled_current_month['report_date_local']
    
# settled_current_month['poliza_date'] = settled_current_month.apply(next_date, axis=1)

In [ ]:
# settled_current_month.head()

In [ ]:
# settled_current_month.shape

In [ ]:
# settled_current_month['poliza_date'].unique()

### CANCELACIONES

In [13]:
settled_current_month.loc[(settled_current_month['total_released'] > 0)
                          & (settled_current_month['total_adjustments'] < 0),'canc_1'] = settled_current_month['total_adjustments']
settled_current_month['canc_1'].fillna(0,inplace=True)

In [14]:
settled_current_month.loc[(settled_current_month['total_released'] > 0)
                          & (settled_current_month['total_adjustments'] < 0),'canc_2'] = settled_current_month['total_released']
settled_current_month['canc_2'].fillna(0,inplace=True)

In [15]:
settled_current_month['cancelaciones'] = (-settled_current_month['canc_1']) - (settled_current_month['canc_2'])
settled_current_month.head()

,report_date_local,merchant_id,no_pagos,total_transactions,total_fees_charged,total_taxes,applied_fees_benefits,applied_taxes_benefits,fee_direct_deposit,taxes_direct_deposit,...,total_adjustments_fees_charged,total_adjustments_taxes,cobranza,total_released,total_retained,total_due,file_name,canc_1,canc_2,cancelaciones
0,2019-10-01,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,"2,500.00",90.00,14.40,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,"2,395.60",TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00
1,2019-10-02,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,500.00,18.00,2.88,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,479.12,TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00
2,2019-10-08,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,950.00,34.20,5.47,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,910.33,TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00
3,2019-10-14,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,"1,500.00",54.00,8.64,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,"1,437.36",TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00
4,2019-10-22,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,500.00,18.00,2.88,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,479.12,TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00

In [16]:
settled_current_month.shape

(814091, 21)

In [20]:
settled_current_month.columns

Index(['report_date_local', 'merchant_id', 'no_pagos', 'total_transactions',
       'total_fees_charged', 'total_taxes', 'applied_fees_benefits',
       'applied_taxes_benefits', 'fee_direct_deposit', 'taxes_direct_deposit',
       'total_adjustments', 'total_adjustments_fees_charged',
       'total_adjustments_taxes', 'cobranza', 'total_released',
       'total_retained', 'total_due', 'file_name', 'canc_1', 'canc_2',
       'cancelaciones'],
      dtype='object')

### TOTAL DUE CALCULADO

In [21]:
settled_current_month['total_due_calculado'] = (settled_current_month['total_transactions']
                                                - settled_current_month['total_fees_charged']
                                                - settled_current_month['total_taxes']
                                                + settled_current_month['applied_fees_benefits']
                                                + settled_current_month['applied_taxes_benefits']
                                                + settled_current_month['fee_direct_deposit']
                                                + settled_current_month['taxes_direct_deposit']
                                                - (-settled_current_month['total_adjustments'])
                                                + (-settled_current_month['total_adjustments_fees_charged'])
                                                + (-settled_current_month['total_adjustments_taxes'])
                                                - settled_current_month['cobranza']
                                                + settled_current_month['total_released']
                                                - settled_current_month['total_retained'])
settled_current_month['diferencias'] = settled_current_month['total_due_calculado'] - settled_current_month['total_due']
settled_current_month.head()

,report_date_local,merchant_id,no_pagos,total_transactions,total_fees_charged,total_taxes,applied_fees_benefits,applied_taxes_benefits,fee_direct_deposit,taxes_direct_deposit,...,cobranza,total_released,total_retained,total_due,file_name,canc_1,canc_2,cancelaciones,total_due_calculado,diferencias
0,2019-10-01,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,"2,500.00",90.00,14.40,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,"2,395.60",TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00,"2,395.60",0.00
1,2019-10-02,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,500.00,18.00,2.88,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,479.12,TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00,479.12,0.00
2,2019-10-08,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,950.00,34.20,5.47,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,910.33,TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00,910.33,-0.00
3,2019-10-14,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,"1,500.00",54.00,8.64,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,"1,437.36",TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00,"1,437.36",0.00
4,2019-10-22,0000001a-e7e3-4fcc-9093-27cf0733fa93,1,500.00,18.00,2.88,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,479.12,TPV MERCHANT OCTUBRE 2019.csv,0.00,0.00,-0.00,479.12,0.00

In [22]:
settled_current_month.shape

(814091, 23)

### CONCILIACION TPV

In [23]:
conc_1 = settled_current_month.groupby(['report_date_local']).agg({'total_transactions':sum,'total_fees_charged':sum
                                                                    ,'total_taxes':sum,'applied_fees_benefits':sum
                                                                    ,'applied_taxes_benefits':sum,'fee_direct_deposit':sum
                                                                    ,'taxes_direct_deposit':sum,'total_adjustments':sum
                                                                    ,'total_adjustments_fees_charged':sum
                                                                    ,'total_adjustments_taxes':sum 
                                                                    ,'cobranza':sum,'total_released':sum
                                                                    ,'total_retained':sum,'cancelaciones':sum
                                                                    ,'total_due_calculado':sum,'total_due':sum
                                                                    ,'diferencias':sum}).reset_index()
conc_1['total_adjustments'] = conc_1['total_adjustments']*-1 
conc_1['total_adjustments_fees_charged'] = conc_1['total_adjustments_fees_charged']*-1
conc_1['total_adjustments_taxes'] = conc_1['total_adjustments_taxes']*-1 
conc_1.head()

,report_date_local,total_transactions,total_fees_charged,total_taxes,applied_fees_benefits,applied_taxes_benefits,fee_direct_deposit,taxes_direct_deposit,total_adjustments,total_adjustments_fees_charged,total_adjustments_taxes,cobranza,total_released,total_retained,cancelaciones,total_due_calculado,total_due,diferencias
0,2019-10-01,"96,054,841.09","4,339,007.54","694,248.19","3,961.27",633.94,661.13,105.87,"19,139.41",77.65,12.42,"60,144.89","1,199,032.21","2,122,610.71",90.07,"90,024,174.84","90,024,174.84",0.00
1,2019-10-02,"61,456,053.06","2,792,189.89","446,756.17","2,543.87",407.19,668.86,107.14,"118,391.39","3,770.78",603.33,"18,618.62","2,205,879.06","1,728,076.07","4,374.11","58,566,001.15","58,566,001.15",-0.00
2,2019-10-03,"63,614,074.32","2,963,944.28","474,236.98","2,375.88",380.25,733.50,117.50,"99,194.82","3,008.48",481.36,"22,149.25","2,357,050.16","2,253,113.70","3,489.84","60,165,582.42","60,165,582.42",-0.00
3,2019-10-04,"66,026,899.42","3,043,134.88","486,906.84","2,387.92",382.27,788.71,126.29,"182,636.34","8,034.74","1,285.56","45,654.36","1,318,170.20","1,742,636.65","9,320.30","61,857,106.04","61,857,106.04",-0.00
4,2019-10-07,"155,157,541.79","6,943,344.45","1,110,948.29","6,928.45","1,108.87","2,366.07",378.93,"102,045.82","3,169.95",507.20,"52,163.60","2,063,321.30","3,050,562.45","3,677.15","145,976,257.95","145,976,257.95",0.00

In [24]:
conc_1.shape

(23, 18)

In [27]:
conc_3 = settled_current_month.groupby(['report_date_local']).agg({'total_transactions':sum,'total_fees_charged':sum
                                                                    ,'total_taxes':sum,'applied_fees_benefits':sum
                                                                    ,'applied_taxes_benefits':sum,'fee_direct_deposit':sum
                                                                    ,'taxes_direct_deposit':sum,'total_adjustments':sum     
                                                                    ,'total_adjustments_fees_charged':sum
                                                                    ,'total_adjustments_taxes':sum 
                                                                    ,'cobranza':sum,'total_released':sum
                                                                    ,'total_retained':sum,'cancelaciones':sum
                                                                    ,'total_due_calculado':sum,'total_due':sum
                                                                    ,'diferencias':sum}).reset_index()
conc_3['total_adjustments'] = conc_3['total_adjustments']*-1 
conc_3['total_adjustments_fees_charged'] = conc_3['total_adjustments_fees_charged']*-1
conc_3['total_adjustments_taxes'] = conc_3['total_adjustments_taxes']*-1 
conc_3.head()

,report_date_local,total_transactions,total_fees_charged,total_taxes,applied_fees_benefits,applied_taxes_benefits,fee_direct_deposit,taxes_direct_deposit,total_adjustments,total_adjustments_fees_charged,total_adjustments_taxes,cobranza,total_released,total_retained,cancelaciones,total_due_calculado,total_due,diferencias
0,2019-10-01,"96,054,841.09","4,339,007.54","694,248.19","3,961.27",633.94,661.13,105.87,"19,139.41",77.65,12.42,"60,144.89","1,199,032.21","2,122,610.71",90.07,"90,024,174.84","90,024,174.84",0.00
1,2019-10-02,"61,456,053.06","2,792,189.89","446,756.17","2,543.87",407.19,668.86,107.14,"118,391.39","3,770.78",603.33,"18,618.62","2,205,879.06","1,728,076.07","4,374.11","58,566,001.15","58,566,001.15",-0.00
2,2019-10-03,"63,614,074.32","2,963,944.28","474,236.98","2,375.88",380.25,733.50,117.50,"99,194.82","3,008.48",481.36,"22,149.25","2,357,050.16","2,253,113.70","3,489.84","60,165,582.42","60,165,582.42",-0.00
3,2019-10-04,"66,026,899.42","3,043,134.88","486,906.84","2,387.92",382.27,788.71,126.29,"182,636.34","8,034.74","1,285.56","45,654.36","1,318,170.20","1,742,636.65","9,320.30","61,857,106.04","61,857,106.04",-0.00
4,2019-10-07,"155,157,541.79","6,943,344.45","1,110,948.29","6,928.45","1,108.87","2,366.07",378.93,"102,045.82","3,169.95",507.20,"52,163.60","2,063,321.30","3,050,562.45","3,677.15","145,976,257.95","145,976,257.95",0.00

In [28]:
conc_3.shape

(23, 18)

# EXCEL FINAL

In [31]:
writer = pd.ExcelWriter('FASE I. DATA OCTUBRE 2019.xlsx',
                        engine='xlsxwriter',
                        engine_kwargs={'options': {'encoding':'utf-8'}})
conc_1.to_excel(writer, sheet_name='MONTOS REPORT_DATE',index=False)
writer.close()