In [1]:
import pandas as pd
import numpy as np
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format
import gc

In [2]:
start_date_fact = '2023-09-01'
final_date_fact = '2023-09-30'

# RUTAS

### EMAIL

In [3]:
email_files = glob.glob(r'G:\My Drive\RESPALDO-PC\DATA EMAILS\*.tsv', recursive=False)
email_files

['G:\\My Drive\\RESPALDO-PC\\DATA EMAILS\\MERCHANT_INFO.tsv']

### MUESTRA AUDITORES

In [4]:
muestra_audit_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\AUDITORIA EXTERNA\Requerimiento 229\Muestra*.xlsx', recursive=False)
muestra_audit_files

['C:\\Users\\Cristian.Aparicio\\Documents\\AUDITORIA EXTERNA\\Requerimiento 229\\Muestra_auditores_diciembre_2023.xlsx']

### AP JOURNAL

In [5]:
ap_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\AUDITORIA EXTERNA\Requerimiento 229\0. QUERIES\AUDITORIA_AP*.tsv', recursive=False)
ap_files

['C:\\Users\\Cristian.Aparicio\\Documents\\AUDITORIA EXTERNA\\Requerimiento 229\\0. QUERIES\\AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv']

### SETTLEMENT MASTER LOG

In [6]:
sml_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\AUDITORIA EXTERNA\Requerimiento 229\0. QUERIES\AUDITORIA_SETT*.tsv', recursive=False)
sml_files

['C:\\Users\\Cristian.Aparicio\\Documents\\AUDITORIA EXTERNA\\Requerimiento 229\\0. QUERIES\\AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 2023 DP.tsv']

In [7]:
# use_cols_sml = ['MVNT_ID','PSP_AMOUNT','GROSS_AMOUNT','FEES','TAXES','NET_AMOUNT','MDR','MSI','NUMBER_MSI','RECEIPT_NO',
#                 'STATUS_CODE','DCC_AMOUNT','DCC_RATE','DCC_STATUS','PYMT_PRG']

### AP JOURNAL - CANCELACIONES

In [8]:
ap_files_canc = glob.glob(r'G:\My Drive\RESPALDO-PC\DYNAMO\2023\12. DICIEMBRE\AP JOURNAL\FACTURACION\AP-JOURNAL-CANCEL*.tsv', recursive=False)
ap_files_canc

['G:\\My Drive\\RESPALDO-PC\\DYNAMO\\2023\\12. DICIEMBRE\\AP JOURNAL\\FACTURACION\\AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv']

# DATA EMAILS

In [9]:
email = pd.concat([pd.read_csv(f,sep='\t').assign(file_name=os.path.basename(f)) for f in email_files])
email.columns = email.columns.str.strip().str.lower()
email['email'] = email['email'].str.lower()
email['merchant_name'].fillna('NULL',inplace=True)
email.sort_values(by=(['merchant_id','updated_at']), ascending=[True,False], inplace=True)
email.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\1850252706.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  email = pd.concat([pd.read_csv(f,sep='\t').assign(file_name=os.path.basename(f)) for f in email_files])

,id,merchant_id,email,merchant_name,state,role,updated_at,file_name
771804,3c2a15f2-b165-45a8-9b93-76d876fca089,0000001a-e7e3-4fcc-9093-27cf0733fa93,korysalomon@gmail.com,EL MUNDO DE LOS LENTES,SUSPENDED,ADMIN,2020-11-12,MERCHANT_INFO.tsv
356800,67080a7a-20e1-4143-9edf-2a13bfb6feff,0000099a-c4d5-48dc-990b-8f06dbee9af8,rcasahonda81@gmail.com,BAGOURMETTE SUBLIMERIAS,ACTIVATED,ADMIN,2019-06-30,MERCHANT_INFO.tsv
1014402,e15155f9-b2be-4628-a68d-0045e33d3423,00000cad-bc81-43fe-ba48-7449b30d5c37,libnay21@gmail.com,FERRETERAS CRISTO REY,ACTIVATED,ADMIN,2021-08-05,MERCHANT_INFO.tsv
1165303,537bc0b4-d0f0-476f-9b86-4cfe44040bf5,00001269-1bce-4cc1-ba64-fb8b7fe4db16,ceballoshumberto93@gmail.com,ROYAL PRESTIGE CEBMA,ACTIVATED,ADMIN,2021-12-16,MERCHANT_INFO.tsv
224182,7ec397a0-532d-4239-ad5b-5618867e3622,000012b6-a453-4285-9f7f-70a7bf46a4fb,myrna.espinosa@bachoco.net,BACHOCO,SUSPENDED,ADMIN,2018-09-18,MERCHANT_INFO.tsv

In [10]:
email.shape

(2394602, 8)

In [11]:
duplicates_email = email[email.duplicated(['merchant_id'] , keep=False)]
duplicates_email.head()

,id,merchant_id,email,merchant_name,state,role,updated_at,file_name
2286437,76988280-87bf-4922-bb07-a32b150e92cb,08c6cd82-668f-4394-9749-5a2a718d4630,teamtaack@gmail.com,TEAMTAACK@GMAIL.COM,VALIDATED,ADMIN,NaN,MERCHANT_INFO.tsv
2286438,3b7d576f-d314-42a1-a401-350dee496741,08c6cd82-668f-4394-9749-5a2a718d4630,teamtaack@gmail.com,TEAMTAACK@GMAIL.COM,VALIDATED,ADMIN,NaN,MERCHANT_INFO.tsv
2363027,748184d5-77d6-4275-984b-b56b05bde583,1bf92d87-6f48-46df-a6ed-c8fb0b0bdbc0,diazderyan@gmail.com,DIAZDERYAN@GMAIL.COM,VALIDATED,ADMIN,NaN,MERCHANT_INFO.tsv
2363028,b9e46ccc-4665-45af-88f8-0a350fe36d58,1bf92d87-6f48-46df-a6ed-c8fb0b0bdbc0,diazderyan@gmail.com,DIAZDERYAN@GMAIL.COM,VALIDATED,ADMIN,NaN,MERCHANT_INFO.tsv
2256336,7aea8ccd-0abf-4c3a-bfab-2e8e15cae044,209ea42c-8b20-4a5e-978c-7c6ecc9a9487,ivanreyeshernandez2@gmail.com,IVANREYESHERNANDEZ2@GMAIL.COM,VALIDATED,ADMIN,NaN,MERCHANT_INFO.tsv

In [12]:
duplicates_email.shape

(25, 8)

In [13]:
email.drop_duplicates(subset='merchant_id', keep='first', inplace=True)

In [14]:
email.shape

(2394589, 8)

# DATA SETTLEMENT MASTER LOG

In [15]:
sml = pd.concat([pd.read_csv(f,sep='\t',dtype={'ORDER_ID':object,'BIN':object,'LAST4':object,'AFFILIATION':object,
                                              'CLAVE_AUTORIZACION':object,'RECEIPT_NO':object,
                                              'DEVICE_ID':object}).assign(file_name=os.path.basename(f)) for f in sml_files])
sml.columns = sml.columns.str.strip().str.lower()
sml.replace('""','', regex=True, inplace=True)
sml['eff_dt'] =  pd.to_datetime(sml['eff_dt'])
sml['date_transaction'] =  pd.to_datetime(sml['date_transaction'])
sml['created_at_cdmx'] =  pd.to_datetime(sml['created_at_cdmx'])
sml['updated_at_cdmx'] =  pd.to_datetime(sml['updated_at_cdmx'])
sml.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,updated_at_cdmx,receipt_no,issuer,device_id,dcc_amount,dcc_rate,dcc_status,cc_nb_currency_code,nu_markup,file_name
0,06d59aac-88bd-594d-93d5-72d1954b948b,8815a060-c601-453e-b15b-e8ddaf0e5813,b4294744-c2c6-4cf1-acd6-970ac80a9ffc,b4294744-c2c6-4cf1-acd6-970ac80a9ffc,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-19T16:39:41Z,2023-09-20,33.00,33.00,...,2023-09-19,lHMXD3T,BBVA,N500W546761,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...
1,dcadce84-6c45-57cb-8204-1f823ed7b620,e3e6193f-17a1-44cc-8d46-ea6fbee3a03d,a470356d-7016-475b-b147-03da15b0ff8d,a470356d-7016-475b-b147-03da15b0ff8d,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-15T08:20:26Z,2023-09-16,59.00,59.00,...,2023-09-15,Kzj18Rr,SODEXO,N500W551725,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...
2,dea9ace0-2333-5033-a0c6-14656e1229c9,88ab347c-5edc-4ccd-9226-ee349852c097,aa1856d8-2d1f-48c0-a3eb-77602c38bbd8,aa1856d8-2d1f-48c0-a3eb-77602c38bbd8,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-25T22:05:11Z,2023-09-26,123.00,123.00,...,2023-09-25,aqOKxAA,SANTANDER PR,A368C7610409E41F00093291DF,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...
3,ffa2b068-1979-5476-a6cf-293ccd2e2e4c,28d62ec2-a419-4110-8218-a12b033e2240,18558a8c-655c-4d40-a5a2-3585e2405f9b,18558a8c-655c-4d40-a5a2-3585e2405f9b,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-27T22:04:30Z,2023-09-28,"1,635.00","1,635.00",...,2023-09-27,LTNVrbM,BBVA,N500W4Z9661,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...
4,b9ff3de4-2179-5205-ab3d-5390141cf72d,831b7b85-a90b-4eda-98ab-d5e71e9da287,99642f27-adf9-4526-b8bd-21085e53ded4,99642f27-adf9-4526-b8bd-21085e53ded4,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-12T18:03:41Z,2023-09-13,"2,691.00","2,691.00",...,2023-09-12,LhQj9Cb,HSBC PR,N500W4Z9397,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...

In [16]:
sml.shape

(1503295, 37)

In [17]:
sml.dtypes

record_uuid                    object
merchant_id                    object
transaction_id                 object
mvnt_id                        object
mvnt_type                      object
pymt_prg                       object
created_at                     object
eff_dt                 datetime64[ns]
psp_amount                    float64
gross_amount                  float64
fees                          float64
taxes                         float64
net_amount                    float64
mdr                           float64
msi                           float64
date_transaction       datetime64[ns]
order_id                       object
created_at_cdmx        datetime64[ns]
bin                            object
last4                          object
affiliation                    object
clave_autorizacion             object
number_msi                    float64
status_code                     int64
brand                          object
psp                            object
payment_sub_type               object
updated_at_cdmx        datetime64[ns]
receipt_no                     object
issuer                         object
device_id                      object
dcc_amount                    float64
dcc_rate                      float64
dcc_status                     object
cc_nb_currency_code            object
nu_markup                     float64
file_name                      object
dtype: object

In [18]:
sml_final = sml

In [19]:
sml_final.shape

(1503295, 37)

In [20]:
sml_final['msi'].unique()

array([0.    , 0.075 , 0.0685, 0.045 , 0.1195, 0.099 , 0.0385, 0.0405,
       0.223 , 0.177 ])

In [21]:
sml_final['mdr'].unique()

array([0.036 , 0.031 , 0.025 , 0.032 , 0.03  , 0.026 , 0.028 , 0.029 ,
       0.033 , 0.0265, 0.022 , 0.024 , 0.0295, 0.    , 0.034 , 0.027 ,
       0.0303, 0.023 , 0.0335, 0.035 ])

In [22]:
duplicates_sml_final = sml_final[sml_final.duplicated(['mvnt_id'] , keep=False)]
duplicates_sml_final.head()

Empty DataFrame
Columns: [record_uuid, merchant_id, transaction_id, mvnt_id, mvnt_type, pymt_prg, created_at, eff_dt, psp_amount, gross_amount, fees, taxes, net_amount, mdr, msi, date_transaction, order_id, created_at_cdmx, bin, last4, affiliation, clave_autorizacion, number_msi, status_code, brand, psp, payment_sub_type, updated_at_cdmx, receipt_no, issuer, device_id, dcc_amount, dcc_rate, dcc_status, cc_nb_currency_code, nu_markup, file_name]
Index: []

[0 rows x 37 columns]

In [23]:
duplicates_sml_final.shape

(0, 37)

In [24]:
sml_final.drop_duplicates(subset='mvnt_id', keep='last', inplace=True) 
sml_final.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,updated_at_cdmx,receipt_no,issuer,device_id,dcc_amount,dcc_rate,dcc_status,cc_nb_currency_code,nu_markup,file_name
0,06d59aac-88bd-594d-93d5-72d1954b948b,8815a060-c601-453e-b15b-e8ddaf0e5813,b4294744-c2c6-4cf1-acd6-970ac80a9ffc,b4294744-c2c6-4cf1-acd6-970ac80a9ffc,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-19T16:39:41Z,2023-09-20,33.00,33.00,...,2023-09-19,lHMXD3T,BBVA,N500W546761,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...
1,dcadce84-6c45-57cb-8204-1f823ed7b620,e3e6193f-17a1-44cc-8d46-ea6fbee3a03d,a470356d-7016-475b-b147-03da15b0ff8d,a470356d-7016-475b-b147-03da15b0ff8d,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-15T08:20:26Z,2023-09-16,59.00,59.00,...,2023-09-15,Kzj18Rr,SODEXO,N500W551725,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...
2,dea9ace0-2333-5033-a0c6-14656e1229c9,88ab347c-5edc-4ccd-9226-ee349852c097,aa1856d8-2d1f-48c0-a3eb-77602c38bbd8,aa1856d8-2d1f-48c0-a3eb-77602c38bbd8,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-25T22:05:11Z,2023-09-26,123.00,123.00,...,2023-09-25,aqOKxAA,SANTANDER PR,A368C7610409E41F00093291DF,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...
3,ffa2b068-1979-5476-a6cf-293ccd2e2e4c,28d62ec2-a419-4110-8218-a12b033e2240,18558a8c-655c-4d40-a5a2-3585e2405f9b,18558a8c-655c-4d40-a5a2-3585e2405f9b,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-27T22:04:30Z,2023-09-28,"1,635.00","1,635.00",...,2023-09-27,LTNVrbM,BBVA,N500W4Z9661,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...
4,b9ff3de4-2179-5205-ab3d-5390141cf72d,831b7b85-a90b-4eda-98ab-d5e71e9da287,99642f27-adf9-4526-b8bd-21085e53ded4,99642f27-adf9-4526-b8bd-21085e53ded4,STL_PCS_RQ,REGULAR_PAYMENT,2023-09-12T18:03:41Z,2023-09-13,"2,691.00","2,691.00",...,2023-09-12,LhQj9Cb,HSBC PR,N500W4Z9397,NaN,NaN,NaN,NaN,NaN,AUDITORIA_SETTLEMENT_MASTER_LOG SEPTIEMBRE 202...

In [25]:
sml_final.shape

(1503295, 37)

In [26]:
sml_final.columns

Index(['record_uuid', 'merchant_id', 'transaction_id', 'mvnt_id', 'mvnt_type',
       'pymt_prg', 'created_at', 'eff_dt', 'psp_amount', 'gross_amount',
       'fees', 'taxes', 'net_amount', 'mdr', 'msi', 'date_transaction',
       'order_id', 'created_at_cdmx', 'bin', 'last4', 'affiliation',
       'clave_autorizacion', 'number_msi', 'status_code', 'brand', 'psp',
       'payment_sub_type', 'updated_at_cdmx', 'receipt_no', 'issuer',
       'device_id', 'dcc_amount', 'dcc_rate', 'dcc_status',
       'cc_nb_currency_code', 'nu_markup', 'file_name'],
      dtype='object')

# DATA AP JOURNAL (PREVIO EMAIL)

In [27]:
ap_init = pd.concat([pd.read_csv(f, sep='\t').assign(file_name=os.path.basename(f)) for f in ap_files])
ap_init.columns = ap_init.columns.str.strip().str.lower()
ap_init.replace('""','', regex=True, inplace=True)
ap_init['eff_dt'] =  pd.to_datetime(ap_init['eff_dt']).dt.tz_localize(None)
ap_init['eff_dt_date'] =  pd.to_datetime(ap_init['eff_dt']).dt.date
ap_init['eff_dt_date'] =  pd.to_datetime(ap_init['eff_dt_date'])
ap_init['eff_dt_time'] =  pd.to_datetime(ap_init['eff_dt']).dt.time
# ap_init['movement_day'] = pd.to_datetime(ap_init['movement_day']).dt.tz_localize(None)
ap_init['created_at'] = pd.to_datetime(ap_init['created_at']).dt.tz_localize(None)
ap_init['created_at_date'] =  pd.to_datetime(ap_init['created_at']).dt.date
ap_init['created_at_date'] =  pd.to_datetime(ap_init['created_at_date'])
ap_init['payment_date_local'] = pd.to_datetime(ap_init['payment_date_local']).dt.tz_localize(None)
ap_init['payment_date_local'] =  pd.to_datetime(ap_init['payment_date_local']).dt.date
ap_init['payment_date_local'] =  pd.to_datetime(ap_init['payment_date_local'])
ap_init['report_date_local'] = pd.to_datetime(ap_init['report_date_local']).dt.tz_localize(None)
ap_init['report_date_local'] =  pd.to_datetime(ap_init['report_date_local']).dt.date
ap_init['report_date_local'] =  pd.to_datetime(ap_init['report_date_local'])
# ap_init['request_effective_date'] = pd.to_datetime(ap_init['request_effective_date']).dt.tz_localize(None)
# ap_init['slot_date'] = pd.to_datetime(ap_init['slot_date']).dt.tz_localize(None)
# ap_init['identifier'] = ap_init['source_type'].str[:1].astype(str)
# ap_init['INDEX'] = (ap_init['eff_dt_date'].astype(str).replace(' ', '',regex=True)+'-'+
#                ap_init['identifier'].astype(str).replace(' ', '',regex=True)+'-'+
#                ap_init['eff_dt_time'].astype(str).replace(' ', '',regex=True))
ap_init.sort_values(by=(['merchant_id','eff_dt']), ascending=[True,False], inplace=True)

In [28]:
ap_init.reset_index(inplace=True)

In [29]:
ap_init.loc[ap_init['source_type'] == 'DISB', 'report_id'] = ap_init['type_request']
ap_init['report_id'] = ap_init['report_id'].groupby(ap_init['merchant_id']).ffill()
ap_init['report_date_local_final'] = ap_init['report_date_local'].groupby(ap_init['merchant_id']).ffill()
ap_init['payment_date_local_final'] = ap_init['payment_date_local'].groupby(ap_init['merchant_id']).ffill()
ap_init['status_final'] = ap_init['status'].groupby(ap_init['merchant_id']).ffill()
ap_init.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,...,payment_date_local,status,file_name,eff_dt_date,eff_dt_time,created_at_date,report_id,report_date_local_final,payment_date_local_final,status_final
0,1413425,0001c1e5-0d42-439e-8082-cbea9d09b094,"-1,437.36",MXN,AN6WV5K49,15cf8f9e-c8c9-3184-bf1d-0b2f0995b32a,DISB_RQ,DISB,2023-09-14 07:21:03,2023-09-14 07:21:08,...,2023-09-14,PAID,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-14,07:21:08,2023-09-14,AN6WV5K49,2023-09-14,2023-09-14,PAID
1,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,NaT,NaN,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-14,05:00:00,2023-09-13,AN6WV5K49,2023-09-14,2023-09-14,PAID
2,989104,0001c1e5-0d42-439e-8082-cbea9d09b094,"-1,916.48",MXN,AJCF7HC37,97a26baa-deca-3205-8727-5a9fa1e5cb62,DISB_RQ,DISB,2023-09-11 07:18:55,2023-09-11 07:19:00,...,2023-09-11,PAID,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-11,07:19:00,2023-09-11,AJCF7HC37,2023-09-11,2023-09-11,PAID
3,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,NaT,NaN,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-11,00:30:00,2023-09-10,AJCF7HC37,2023-09-11,2023-09-11,PAID
4,161,0001c1e5-0d42-439e-8082-cbea9d09b094,"-2,874.72",MXN,A6PTNFRR4,b88a226b-cfec-3537-b090-b9fd256f6c80,DISB_RQ,DISB,2023-09-05 07:22:32,2023-09-05 07:22:37,...,2023-09-05,PAID,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-05,07:22:37,2023-09-05,A6PTNFRR4,2023-09-05,2023-09-05,PAID

In [30]:
ap_init.shape

(1729709, 24)

In [31]:
ap_init.dtypes

index                                int64
merchant_id                         object
amount                             float64
currency                            object
type_request                        object
mvnt_id                             object
movement_type                       object
source_type                         object
created_at                  datetime64[ns]
eff_dt                      datetime64[ns]
movement_day                        object
request_effective_date              object
slot_date                           object
report_date_local           datetime64[ns]
payment_date_local          datetime64[ns]
status                              object
file_name                           object
eff_dt_date                 datetime64[ns]
eff_dt_time                         object
created_at_date             datetime64[ns]
report_id                           object
report_date_local_final     datetime64[ns]
payment_date_local_final    datetime64[ns]
status_final                        object
dtype: object

In [32]:
sorted(list(ap_init['source_type'].unique()))

['BILL_PYMNT',
 'CAAL',
 'DISB',
 'FEE_REFUNDS',
 'LOAN',
 'PYMT',
 'REFUNDS',
 'RISK',
 'SETT',
 'TAXES',
 'TOPUPS']

In [33]:
ap_bill_pymnt = ap_init[(ap_init['source_type'] == 'BILL_PYMNT')]
ap_caal = ap_init[(ap_init['source_type'] == 'CAAL')]
ap_data = ap_init[(ap_init['source_type'] == 'DATA')]
ap_dig_acc = ap_init[(ap_init['source_type'] == 'DIG_ACC')]
ap_disb = ap_init[(ap_init['source_type'] == 'DISB')]
ap_fee_refunds = ap_init[(ap_init['source_type'] == 'FEE_REFUNDS')]
ap_loan = ap_init[(ap_init['source_type'] == 'LOAN')]
ap_promo = ap_init[(ap_init['source_type'] == 'PROMO')]
ap_pymt = ap_init[(ap_init['source_type'] == 'PYMT')]
ap_refunds = ap_init[(ap_init['source_type'] == 'REFUNDS')]
ap_risk = ap_init[(ap_init['source_type'] == 'RISK')]
ap_preview = ap_init[(ap_init['source_type'] == 'SETT')]
ap_sett_adptr = ap_init[(ap_init['source_type'] == 'SETT_ADPTR')]
ap_taxes = ap_init[(ap_init['source_type'] == 'TAXES')]
ap_topups = ap_init[(ap_init['source_type'] == 'TOPUPS')]

In [34]:
ap_preview.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,...,payment_date_local,status,file_name,eff_dt_date,eff_dt_time,created_at_date,report_id,report_date_local_final,payment_date_local_final,status_final
1,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,NaT,NaN,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-14,05:00:00,2023-09-13,AN6WV5K49,2023-09-14,2023-09-14,PAID
3,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,NaT,NaN,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-11,00:30:00,2023-09-10,AJCF7HC37,2023-09-11,2023-09-11,PAID
5,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,NaT,NaN,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-05,06:00:00,2023-09-04,A6PTNFRR4,2023-09-05,2023-09-05,PAID
7,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,NaT,NaN,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-13,04:30:00,2023-09-12,AFJG48G2D,2023-09-13,2023-09-13,PAID
9,180524,000d3438-2c68-41c7-9141-99d91b7c0190,"47,912.00",MXN,settlement processor regular payment request,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,REGULAR_PYMT_RQ,SETT,2023-09-26 23:48:15,2023-09-27 06:00:00,...,NaT,NaN,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-27,06:00:00,2023-09-26,AZWSXBJVP,2023-09-27,2023-09-27,PAID

In [35]:
ap_preview.shape

(1503295, 24)

In [36]:
ap_preview.dtypes

index                                int64
merchant_id                         object
amount                             float64
currency                            object
type_request                        object
mvnt_id                             object
movement_type                       object
source_type                         object
created_at                  datetime64[ns]
eff_dt                      datetime64[ns]
movement_day                        object
request_effective_date              object
slot_date                           object
report_date_local           datetime64[ns]
payment_date_local          datetime64[ns]
status                              object
file_name                           object
eff_dt_date                 datetime64[ns]
eff_dt_time                         object
created_at_date             datetime64[ns]
report_id                           object
report_date_local_final     datetime64[ns]
payment_date_local_final    datetime64[ns]
status_final                        object
dtype: object

In [37]:
ap_preview['report_id'].unique()

array(['AN6WV5K49', 'AJCF7HC37', 'A6PTNFRR4', ..., 'ADL9ND7Q7',
       'APD6SGLW4', 'AF662YKXC'], dtype=object)

# DATA AP JOURNAL CANCELACIONES (PREVIO EMAIL)

In [38]:
ap_preview_canc = pd.concat([pd.read_csv(f, sep='\t').assign(file_name=os.path.basename(f)) for f in ap_files_canc])
ap_preview_canc.columns = ap_preview_canc.columns.str.strip().str.lower()
ap_preview_canc.replace('""','', regex=True, inplace=True)
ap_preview_canc['eff_dt'] =  pd.to_datetime(ap_preview_canc['eff_dt']).dt.tz_localize(None)
ap_preview_canc['eff_dt_date'] =  pd.to_datetime(ap_preview_canc['eff_dt']).dt.date
ap_preview_canc['eff_dt_time'] =  pd.to_datetime(ap_preview_canc['eff_dt']).dt.time
ap_preview_canc['eff_dt_date'] =  pd.to_datetime(ap_preview_canc['eff_dt_date']).dt.tz_localize(None)
ap_preview_canc['movement_day'] = pd.to_datetime(ap_preview_canc['movement_day']).dt.tz_localize(None)
ap_preview_canc['created_at'] = pd.to_datetime(ap_preview_canc['created_at']).dt.tz_localize(None)
ap_preview_canc['request_effective_date'] = pd.to_datetime(ap_preview_canc['request_effective_date']).dt.tz_localize(None)
ap_preview_canc['slot_date'] = pd.to_datetime(ap_preview_canc['slot_date']).dt.tz_localize(None)
# ap_preview_canc['identifier'] = ap_preview_canc['source_type'].str[:1].astype(str)
# ap_preview_canc['INDEX'] = (ap_preview_canc['eff_dt_date'].astype(str).replace(' ', '',regex=True)+'-'+
#                ap_preview_canc['identifier'].astype(str).replace(' ', '',regex=True)+'-'+
#                ap_preview_canc['eff_dt_time'].astype(str).replace(' ', '',regex=True))
ap_preview_canc.sort_values(by=(['merchant_id','eff_dt']), ascending=[True,False], inplace=True)
ap_preview_canc.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time
1,0000b65a-c2a2-4993-8f4c-05e5b7cbd7c0,-787.68,MXN,cancel request,f6b65fd2-d168-4ecd-b433-97b78808adbb,CANCEL_RQ,PYMT,2023-11-09 14:03:50,2023-11-10 03:30:00,2023-11-09 14:03:50,2023-11-10 03:30:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-11-10,03:30:00
0,0000b65a-c2a2-4993-8f4c-05e5b7cbd7c0,-941.28,MXN,cancel request,d739f381-95ed-4f9e-bf7f-691b44004c11,CANCEL_RQ,PYMT,2023-10-19 14:06:46,2023-10-20 03:30:00,2023-10-19 14:06:46,2023-10-20 03:30:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-10-20,03:30:00
6,0000bc20-a726-4fe6-b784-1eb97c287ad5,-94.87,MXN,cancel request,62e7e6f0-aa27-45be-894f-545f4f1b0ab6,CANCEL_RQ,PYMT,2023-08-22 01:36:22,2023-08-22 01:36:27,2023-08-22 01:36:22,2023-08-23 00:00:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-08-22,01:36:27
5,0000bc20-a726-4fe6-b784-1eb97c287ad5,-86.24,MXN,cancel request,6d5ac39e-d9b4-4027-9334-d160e4f41ede,CANCEL_RQ,PYMT,2023-08-06 20:10:36,2023-08-06 20:10:41,2023-08-06 20:10:36,2023-08-07 05:00:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-08-06,20:10:41
4,0000bc20-a726-4fe6-b784-1eb97c287ad5,-60.37,MXN,cancel request,c4edffd4-fe43-4e42-af35-7da22df1ced4,CANCEL_RQ,PYMT,2023-06-22 22:14:53,2023-06-22 22:14:58,2023-06-22 22:14:53,2023-06-23 05:30:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-06-22,22:14:58

In [39]:
ap_preview_canc.shape

(233225, 15)

In [40]:
ap_preview_canc.dtypes

merchant_id                       object
amount                           float64
currency                          object
type_request                      object
mvnt_id                           object
movement_type                     object
source_type                       object
created_at                datetime64[ns]
eff_dt                    datetime64[ns]
movement_day              datetime64[ns]
request_effective_date    datetime64[ns]
slot_date                 datetime64[ns]
file_name                         object
eff_dt_date               datetime64[ns]
eff_dt_time                       object
dtype: object

In [41]:
ap_preview_canc['source_type'].unique()

array(['PYMT', 'RISK'], dtype=object)

# UNION AP JOURNAL CON MAIL

In [42]:
ap = ap_preview.merge(email[['merchant_id','email','merchant_name']],on='merchant_id',how='left')
ap.shape

(1503295, 26)

In [43]:
duplicates_ap = ap[ap.duplicated(['mvnt_id'] , keep=False)]
duplicates_ap.head()

Empty DataFrame
Columns: [index, merchant_id, amount, currency, type_request, mvnt_id, movement_type, source_type, created_at, eff_dt, movement_day, request_effective_date, slot_date, report_date_local, payment_date_local, status, file_name, eff_dt_date, eff_dt_time, created_at_date, report_id, report_date_local_final, payment_date_local_final, status_final, email, merchant_name]
Index: []

[0 rows x 26 columns]

In [44]:
duplicates_ap.shape

(0, 26)

In [45]:
ap.drop_duplicates(subset='mvnt_id', keep='last', inplace=True) 
ap.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,...,file_name,eff_dt_date,eff_dt_time,created_at_date,report_id,report_date_local_final,payment_date_local_final,status_final,email,merchant_name
0,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-14,05:00:00,2023-09-13,AN6WV5K49,2023-09-14,2023-09-14,PAID,gutierrezileyan61@gmail.com,NAIL ART BY NAYELI ALFARO
1,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-11,00:30:00,2023-09-10,AJCF7HC37,2023-09-11,2023-09-11,PAID,gutierrezileyan61@gmail.com,NAIL ART BY NAYELI ALFARO
2,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-05,06:00:00,2023-09-04,A6PTNFRR4,2023-09-05,2023-09-05,PAID,gutierrezileyan61@gmail.com,NAIL ART BY NAYELI ALFARO
3,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-13,04:30:00,2023-09-12,AFJG48G2D,2023-09-13,2023-09-13,PAID,adriana.gosa00@gmail.com,PQ JOYERIA
4,180524,000d3438-2c68-41c7-9141-99d91b7c0190,"47,912.00",MXN,settlement processor regular payment request,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,REGULAR_PYMT_RQ,SETT,2023-09-26 23:48:15,2023-09-27 06:00:00,...,AUDITORIA_AP_JOURNAL SEPTIEMBRE 2023 DP.tsv,2023-09-27,06:00:00,2023-09-26,AZWSXBJVP,2023-09-27,2023-09-27,PAID,jl-munguia@hotmail.com,GIRASOL CLOTHING

In [46]:
ap.shape

(1503295, 26)

# UNION AP JOURNAL CANCELACIONES CON MAIL

In [47]:
ap_canc = ap_preview_canc.merge(email[['merchant_id','email','merchant_name']],on='merchant_id',how='left')
ap_canc.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time,email,merchant_name
0,0000b65a-c2a2-4993-8f4c-05e5b7cbd7c0,-787.68,MXN,cancel request,f6b65fd2-d168-4ecd-b433-97b78808adbb,CANCEL_RQ,PYMT,2023-11-09 14:03:50,2023-11-10 03:30:00,2023-11-09 14:03:50,2023-11-10 03:30:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-11-10,03:30:00,ruvalcabapeleteros@hotmail.com,RUVALCABA PELETEROS S.A. DE C.V.
1,0000b65a-c2a2-4993-8f4c-05e5b7cbd7c0,-941.28,MXN,cancel request,d739f381-95ed-4f9e-bf7f-691b44004c11,CANCEL_RQ,PYMT,2023-10-19 14:06:46,2023-10-20 03:30:00,2023-10-19 14:06:46,2023-10-20 03:30:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-10-20,03:30:00,ruvalcabapeleteros@hotmail.com,RUVALCABA PELETEROS S.A. DE C.V.
2,0000bc20-a726-4fe6-b784-1eb97c287ad5,-94.87,MXN,cancel request,62e7e6f0-aa27-45be-894f-545f4f1b0ab6,CANCEL_RQ,PYMT,2023-08-22 01:36:22,2023-08-22 01:36:27,2023-08-22 01:36:22,2023-08-23 00:00:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-08-22,01:36:27,eberardoburgos6@gmail.com,DOGOS EL WERO
3,0000bc20-a726-4fe6-b784-1eb97c287ad5,-86.24,MXN,cancel request,6d5ac39e-d9b4-4027-9334-d160e4f41ede,CANCEL_RQ,PYMT,2023-08-06 20:10:36,2023-08-06 20:10:41,2023-08-06 20:10:36,2023-08-07 05:00:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-08-06,20:10:41,eberardoburgos6@gmail.com,DOGOS EL WERO
4,0000bc20-a726-4fe6-b784-1eb97c287ad5,-60.37,MXN,cancel request,c4edffd4-fe43-4e42-af35-7da22df1ced4,CANCEL_RQ,PYMT,2023-06-22 22:14:53,2023-06-22 22:14:58,2023-06-22 22:14:53,2023-06-23 05:30:00,1969-12-31 18:00:00,AP-JOURNAL-CANCEL DICIEMBRE 2023.tsv,2023-06-22,22:14:58,eberardoburgos6@gmail.com,DOGOS EL WERO

In [48]:
ap_canc.shape

(233225, 17)

In [49]:
duplicates_ap_canc = ap_canc[ap_canc.duplicated(['mvnt_id'] , keep=False)]
duplicates_ap_canc.head()

Empty DataFrame
Columns: [merchant_id, amount, currency, type_request, mvnt_id, movement_type, source_type, created_at, eff_dt, movement_day, request_effective_date, slot_date, file_name, eff_dt_date, eff_dt_time, email, merchant_name]
Index: []

In [50]:
duplicates_ap_canc.shape

(0, 17)

# CRUCE_1: AP JOURNAL VS SETTLEMENT MASTER LOG

In [51]:
cruce_1 = ap.merge(sml_final[['mvnt_id','transaction_id','mvnt_type','pymt_prg','created_at','psp_amount','gross_amount',
                              'fees','taxes','net_amount','mdr','msi','date_transaction','order_id','created_at_cdmx','bin','last4',
                              'affiliation','clave_autorizacion','number_msi','status_code','brand','psp','payment_sub_type',
                              'updated_at_cdmx','receipt_no','issuer','device_id','dcc_amount','dcc_rate','dcc_status',
                              'cc_nb_currency_code','nu_markup']],on='mvnt_id',
                               how='left')
cruce_1.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,payment_sub_type,updated_at_cdmx,receipt_no,issuer,device_id,dcc_amount,dcc_rate,dcc_status,cc_nb_currency_code,nu_markup
0,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,EMV_PIN,2023-09-13,ux5soI4,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
1,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,EMV_PIN,2023-09-10,ri3mNOx,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
2,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,EMV_PIN,2023-09-04,N7Kpx0I,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
3,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,ECOMMERCE,2023-09-12,e9W4423,AMEX,80010001,NaN,NaN,NaN,NaN,NaN
4,180524,000d3438-2c68-41c7-9141-99d91b7c0190,"47,912.00",MXN,settlement processor regular payment request,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,REGULAR_PYMT_RQ,SETT,2023-09-26 23:48:15,2023-09-27 06:00:00,...,EMV_PIN,2023-09-26,KGqKPN5,BBVA,5331534C480001010049002907E3091B,NaN,NaN,NaN,NaN,NaN

In [52]:
cruce_1.shape

(1503295, 58)

In [53]:
cruce_1_email_null = cruce_1[(cruce_1['email'].isnull())]
cruce_1_email_null.head()

Empty DataFrame
Columns: [index, merchant_id, amount, currency, type_request, mvnt_id, movement_type, source_type, created_at_x, eff_dt, movement_day, request_effective_date, slot_date, report_date_local, payment_date_local, status, file_name, eff_dt_date, eff_dt_time, created_at_date, report_id, report_date_local_final, payment_date_local_final, status_final, email, merchant_name, transaction_id, mvnt_type, pymt_prg, created_at_y, psp_amount, gross_amount, fees, taxes, net_amount, mdr, msi, date_transaction, order_id, created_at_cdmx, bin, last4, affiliation, clave_autorizacion, number_msi, status_code, brand, psp, payment_sub_type, updated_at_cdmx, receipt_no, issuer, device_id, dcc_amount, dcc_rate, dcc_status, cc_nb_currency_code, nu_markup]
Index: []

[0 rows x 58 columns]

In [54]:
cruce_1_email_null.shape

(0, 58)

# CRUCE_1_CANCELACIONES: AP JOURNAL CANCELACIONES VS SETTLEMENT MASTER LOG

In [55]:
cruce_1_canc = ap_canc.merge(sml_final[['mvnt_id','transaction_id','mvnt_type','pymt_prg','created_at','psp_amount','gross_amount',
                              'fees','taxes','net_amount','mdr','msi','date_transaction','order_id','created_at_cdmx','bin','last4',
                              'affiliation','clave_autorizacion','number_msi','status_code','brand','psp','payment_sub_type',
                              'updated_at_cdmx','receipt_no','issuer','device_id','dcc_amount','dcc_rate','dcc_status',
                              'cc_nb_currency_code','nu_markup']],
                             on='mvnt_id',how='left')
cruce_1_canc.rename(columns={'psp_amount':'psp_amount_pymt','gross_amount':'gross_amount_pymt','fees':'fees_pymt',
                             'taxes':'taxes_pymt','net_amount':'net_amount_pymt'},inplace=True)
cruce_1_canc.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,movement_day,...,payment_sub_type,updated_at_cdmx,receipt_no,issuer,device_id,dcc_amount,dcc_rate,dcc_status,cc_nb_currency_code,nu_markup
0,0000b65a-c2a2-4993-8f4c-05e5b7cbd7c0,-787.68,MXN,cancel request,f6b65fd2-d168-4ecd-b433-97b78808adbb,CANCEL_RQ,PYMT,2023-11-09 14:03:50,2023-11-10 03:30:00,2023-11-09 14:03:50,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000b65a-c2a2-4993-8f4c-05e5b7cbd7c0,-941.28,MXN,cancel request,d739f381-95ed-4f9e-bf7f-691b44004c11,CANCEL_RQ,PYMT,2023-10-19 14:06:46,2023-10-20 03:30:00,2023-10-19 14:06:46,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0000bc20-a726-4fe6-b784-1eb97c287ad5,-94.87,MXN,cancel request,62e7e6f0-aa27-45be-894f-545f4f1b0ab6,CANCEL_RQ,PYMT,2023-08-22 01:36:22,2023-08-22 01:36:27,2023-08-22 01:36:22,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0000bc20-a726-4fe6-b784-1eb97c287ad5,-86.24,MXN,cancel request,6d5ac39e-d9b4-4027-9334-d160e4f41ede,CANCEL_RQ,PYMT,2023-08-06 20:10:36,2023-08-06 20:10:41,2023-08-06 20:10:36,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0000bc20-a726-4fe6-b784-1eb97c287ad5,-60.37,MXN,cancel request,c4edffd4-fe43-4e42-af35-7da22df1ced4,CANCEL_RQ,PYMT,2023-06-22 22:14:53,2023-06-22 22:14:58,2023-06-22 22:14:53,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
cruce_1_canc.shape

(233225, 49)

In [57]:
cruce_1_canc_email_null = cruce_1_canc[(cruce_1_canc['email'].isnull())]
cruce_1_canc_email_null.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,movement_day,...,payment_sub_type,updated_at_cdmx,receipt_no,issuer,device_id,dcc_amount,dcc_rate,dcc_status,cc_nb_currency_code,nu_markup
151050,a29137b2-414d-428f-8f4a-c4596e48aaf5,-0.60,MXN,NaN,117a1615-c365-4d27-9bef-45c72e506cd3,CANCEL_RQ,PYMT,2022-04-28 16:57:17,2021-12-15 13:51:52,2021-10-15 14:51:52,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
cruce_1_canc_email_null.shape

(1, 49)

# PERIODO FACTURACION

In [59]:
ap_sett = cruce_1[(cruce_1['eff_dt_date'] >= start_date_fact) & (cruce_1['eff_dt_date'] <= final_date_fact)]
ap_sett.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,payment_sub_type,updated_at_cdmx,receipt_no,issuer,device_id,dcc_amount,dcc_rate,dcc_status,cc_nb_currency_code,nu_markup
0,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,EMV_PIN,2023-09-13,ux5soI4,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
1,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,EMV_PIN,2023-09-10,ri3mNOx,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
2,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,EMV_PIN,2023-09-04,N7Kpx0I,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
3,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,ECOMMERCE,2023-09-12,e9W4423,AMEX,80010001,NaN,NaN,NaN,NaN,NaN
4,180524,000d3438-2c68-41c7-9141-99d91b7c0190,"47,912.00",MXN,settlement processor regular payment request,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,REGULAR_PYMT_RQ,SETT,2023-09-26 23:48:15,2023-09-27 06:00:00,...,EMV_PIN,2023-09-26,KGqKPN5,BBVA,5331534C480001010049002907E3091B,NaN,NaN,NaN,NaN,NaN

In [60]:
ap_sett.shape

(1503295, 58)

In [61]:
sorted(ap_sett['eff_dt_date'].unique())

[Timestamp('2023-09-01 00:00:00'),
 Timestamp('2023-09-02 00:00:00'),
 Timestamp('2023-09-03 00:00:00'),
 Timestamp('2023-09-04 00:00:00'),
 Timestamp('2023-09-05 00:00:00'),
 Timestamp('2023-09-06 00:00:00'),
 Timestamp('2023-09-07 00:00:00'),
 Timestamp('2023-09-08 00:00:00'),
 Timestamp('2023-09-09 00:00:00'),
 Timestamp('2023-09-10 00:00:00'),
 Timestamp('2023-09-11 00:00:00'),
 Timestamp('2023-09-12 00:00:00'),
 Timestamp('2023-09-13 00:00:00'),
 Timestamp('2023-09-14 00:00:00'),
 Timestamp('2023-09-15 00:00:00'),
 Timestamp('2023-09-16 00:00:00'),
 Timestamp('2023-09-17 00:00:00'),
 Timestamp('2023-09-18 00:00:00'),
 Timestamp('2023-09-19 00:00:00'),
 Timestamp('2023-09-20 00:00:00'),
 Timestamp('2023-09-21 00:00:00'),
 Timestamp('2023-09-22 00:00:00'),
 Timestamp('2023-09-23 00:00:00'),
 Timestamp('2023-09-24 00:00:00'),
 Timestamp('2023-09-25 00:00:00'),
 Timestamp('2023-09-26 00:00:00'),
 Timestamp('2023-09-27 00:00:00'),
 Timestamp('2023-09-28 00:00:00'),
 Timestamp('2023-09-29 00:00:00'),
 Timestamp('2023-09-30 00:00:00')]

# TPV NOT FOUND IN SETTLEMENT MASTER LOG

### AP SETTLEMENT

In [62]:
ap_sett['movement_type'].unique()

array(['DEFERRED_REGULAR_PYMNT_RQ', 'REGULAR_PYMT_RQ', 'FAST_PYMT_RQ',
       'DEFERRED_FAST_PYMNT_RQ'], dtype=object)

In [63]:
ap_sett_not_found = ap_sett[(ap_sett['gross_amount'].isnull())]
ap_sett_not_found.drop(['gross_amount','fees','taxes','net_amount'],axis=1,inplace=True)
ap_sett_not_found.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\3254993514.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ap_sett_not_found.drop(['gross_amount','fees','taxes','net_amount'],axis=1,inplace=True)

Empty DataFrame
Columns: [index, merchant_id, amount, currency, type_request, mvnt_id, movement_type, source_type, created_at_x, eff_dt, movement_day, request_effective_date, slot_date, report_date_local, payment_date_local, status, file_name, eff_dt_date, eff_dt_time, created_at_date, report_id, report_date_local_final, payment_date_local_final, status_final, email, merchant_name, transaction_id, mvnt_type, pymt_prg, created_at_y, psp_amount, mdr, msi, date_transaction, order_id, created_at_cdmx, bin, last4, affiliation, clave_autorizacion, number_msi, status_code, brand, psp, payment_sub_type, updated_at_cdmx, receipt_no, issuer, device_id, dcc_amount, dcc_rate, dcc_status, cc_nb_currency_code, nu_markup]
Index: []

[0 rows x 54 columns]

In [64]:
ap_sett_not_found.shape

(0, 54)

# UNION TPV FINAL

### AP SETTLEMENT

In [65]:
ap_sett_found = ap_sett[(ap_sett['gross_amount'].notnull())]
ap_sett_found.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,payment_sub_type,updated_at_cdmx,receipt_no,issuer,device_id,dcc_amount,dcc_rate,dcc_status,cc_nb_currency_code,nu_markup
0,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,EMV_PIN,2023-09-13,ux5soI4,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
1,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,EMV_PIN,2023-09-10,ri3mNOx,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
2,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,EMV_PIN,2023-09-04,N7Kpx0I,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
3,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,ECOMMERCE,2023-09-12,e9W4423,AMEX,80010001,NaN,NaN,NaN,NaN,NaN
4,180524,000d3438-2c68-41c7-9141-99d91b7c0190,"47,912.00",MXN,settlement processor regular payment request,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,REGULAR_PYMT_RQ,SETT,2023-09-26 23:48:15,2023-09-27 06:00:00,...,EMV_PIN,2023-09-26,KGqKPN5,BBVA,5331534C480001010049002907E3091B,NaN,NaN,NaN,NaN,NaN

In [66]:
ap_sett_found.shape

(1503295, 58)

In [67]:
ap_sett_final_1 = pd.concat([ap_sett_found])
ap_sett_final_1.rename(columns={'psp_amount':'psp_amount_sett','gross_amount':'gross_amount_sett','fees':'fees_sett',
                                'taxes':'taxes_sett','net_amount':'net_amount_sett'},inplace=True)
ap_sett_final_1.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,payment_sub_type,updated_at_cdmx,receipt_no,issuer,device_id,dcc_amount,dcc_rate,dcc_status,cc_nb_currency_code,nu_markup
0,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,EMV_PIN,2023-09-13,ux5soI4,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
1,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,EMV_PIN,2023-09-10,ri3mNOx,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
2,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,EMV_PIN,2023-09-04,N7Kpx0I,BBVA,5333594A52000105002F003407E40511,NaN,NaN,NaN,NaN,NaN
3,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,ECOMMERCE,2023-09-12,e9W4423,AMEX,80010001,NaN,NaN,NaN,NaN,NaN
4,180524,000d3438-2c68-41c7-9141-99d91b7c0190,"47,912.00",MXN,settlement processor regular payment request,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,REGULAR_PYMT_RQ,SETT,2023-09-26 23:48:15,2023-09-27 06:00:00,...,EMV_PIN,2023-09-26,KGqKPN5,BBVA,5331534C480001010049002907E3091B,NaN,NaN,NaN,NaN,NaN

In [68]:
ap_sett_final_1.shape

(1503295, 58)

# VALIDACIONES (DEBEN ESTAR EN 0)

In [69]:
ap_sett_final_1_found = ap_sett_final_1[(ap_sett_final_1['gross_amount_sett'].isnull())]
ap_sett_final_1_found.head()

Empty DataFrame
Columns: [index, merchant_id, amount, currency, type_request, mvnt_id, movement_type, source_type, created_at_x, eff_dt, movement_day, request_effective_date, slot_date, report_date_local, payment_date_local, status, file_name, eff_dt_date, eff_dt_time, created_at_date, report_id, report_date_local_final, payment_date_local_final, status_final, email, merchant_name, transaction_id, mvnt_type, pymt_prg, created_at_y, psp_amount_sett, gross_amount_sett, fees_sett, taxes_sett, net_amount_sett, mdr, msi, date_transaction, order_id, created_at_cdmx, bin, last4, affiliation, clave_autorizacion, number_msi, status_code, brand, psp, payment_sub_type, updated_at_cdmx, receipt_no, issuer, device_id, dcc_amount, dcc_rate, dcc_status, cc_nb_currency_code, nu_markup]
Index: []

[0 rows x 58 columns]

In [70]:
ap_sett_final_1_found.shape

(0, 58)

In [71]:
# ap_pymt_final_1_found = ap_pymt_final_1[(ap_pymt_final_1['gross_amount_pymt'].isnull())]
# ap_pymt_final_1_found.head()

In [72]:
# ap_pymt_final_1_found.shape

# RESTAR CANCELACIONES DE AP SETTLEMENT

In [73]:
ap_sett_final = ap_sett_final_1.merge(cruce_1_canc[['mvnt_id','psp_amount_pymt','gross_amount_pymt','fees_pymt','taxes_pymt',
                                                             'net_amount_pymt']],on='mvnt_id',how='left')
ap_sett_final.fillna(0,inplace=True)
ap_sett_final['psp_amount'] = ap_sett_final['psp_amount_sett'] - ap_sett_final['psp_amount_pymt'] 
ap_sett_final['gross_amount'] = ap_sett_final['gross_amount_sett'] - ap_sett_final['gross_amount_pymt'] 
ap_sett_final['fees'] = ap_sett_final['fees_sett'] - ap_sett_final['fees_pymt'] 
ap_sett_final['taxes'] = ap_sett_final['taxes_sett'] - ap_sett_final['taxes_pymt'] 
ap_sett_final['net_amount'] = ap_sett_final['net_amount_sett'] - ap_sett_final['net_amount_pymt']
ap_sett_final.loc[ap_sett_final['pymt_prg'] == 'DIGITAL_ACCOUNT', 'movement_type_sml'] = ap_sett_final['pymt_prg']
ap_sett_final.loc[ap_sett_final['dcc_status'] == 'Tarjeta con DCC', 'movement_type_sml'] = ap_sett_final['dcc_status']
ap_sett_final['movement_type_sml'].fillna(0, inplace=True)
ap_sett_final.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\3865887811.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  ap_sett_final.fillna(0,inplace=True)

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,gross_amount_pymt,fees_pymt,taxes_pymt,net_amount_pymt,psp_amount,gross_amount,fees,taxes,net_amount,movement_type_sml
0,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,0.00,0.00,0.00,0.00,"1,683.45","1,500.00",54.00,8.64,"1,437.36",0
1,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,0.00,0.00,0.00,0.00,"2,244.60","2,000.00",72.00,11.52,"1,916.48",0
2,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,0.00,0.00,0.00,0.00,"3,234.90","3,000.00",108.00,17.28,"2,874.72",0
3,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,0.00,0.00,0.00,0.00,"1,895.22","1,757.60",63.27,10.12,"1,684.21",0
4,180524,000d3438-2c68-41c7-9141-99d91b7c0190,"47,912.00",MXN,settlement processor regular payment request,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,REGULAR_PYMT_RQ,SETT,2023-09-26 23:48:15,2023-09-27 06:00:00,...,0.00,0.00,0.00,0.00,"50,000.00","50,000.00","1,800.00",288.00,"47,912.00",0

In [74]:
ap_sett_final.shape

(1503295, 69)

In [75]:
ap_sett_final['movement_type'].unique()

array(['DEFERRED_REGULAR_PYMNT_RQ', 'REGULAR_PYMT_RQ', 'FAST_PYMT_RQ',
       'DEFERRED_FAST_PYMNT_RQ'], dtype=object)

In [76]:
ap_sett_final['pymt_prg'].unique()

array(['REGULAR_PAYMENT', 'FAST_PAYMENT'], dtype=object)

In [77]:
ap_sett_final['dcc_status'].unique()

array([0, 'Tarjeta con DCC'], dtype=object)

In [78]:
ap_sett_final['movement_type_sml'].unique()

array([0, 'Tarjeta con DCC'], dtype=object)

In [79]:
ap_sett_final.columns

Index(['index', 'merchant_id', 'amount', 'currency', 'type_request', 'mvnt_id',
       'movement_type', 'source_type', 'created_at_x', 'eff_dt',
       'movement_day', 'request_effective_date', 'slot_date',
       'report_date_local', 'payment_date_local', 'status', 'file_name',
       'eff_dt_date', 'eff_dt_time', 'created_at_date', 'report_id',
       'report_date_local_final', 'payment_date_local_final', 'status_final',
       'email', 'merchant_name', 'transaction_id', 'mvnt_type', 'pymt_prg',
       'created_at_y', 'psp_amount_sett', 'gross_amount_sett', 'fees_sett',
       'taxes_sett', 'net_amount_sett', 'mdr', 'msi', 'date_transaction',
       'order_id', 'created_at_cdmx', 'bin', 'last4', 'affiliation',
       'clave_autorizacion', 'number_msi', 'status_code', 'brand', 'psp',
       'payment_sub_type', 'updated_at_cdmx', 'receipt_no', 'issuer',
       'device_id', 'dcc_amount', 'dcc_rate', 'dcc_status',
       'cc_nb_currency_code', 'nu_markup', 'psp_amount_pymt',
       'gross_amount_pymt', 'fees_pymt', 'taxes_pymt', 'net_amount_pymt',
       'psp_amount', 'gross_amount', 'fees', 'taxes', 'net_amount',
       'movement_type_sml'],
      dtype='object')

# IDENTIFICACION DE PAGOS DCC

In [80]:
ap_sett_dcc = ap_sett_final[(ap_sett_final['dcc_status'] == 'Tarjeta con DCC')]
ap_sett_dcc.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,gross_amount_pymt,fees_pymt,taxes_pymt,net_amount_pymt,psp_amount,gross_amount,fees,taxes,net_amount,movement_type_sml
82,180583,00309c2c-53d1-4e77-9ee4-86aec3110649,134.15,MXN,settlement processor regular payment request,05a9402a-4fc4-45cf-8986-58786735841b,REGULAR_PYMT_RQ,SETT,2023-09-12 13:43:13,2023-09-13 03:30:00,...,0.00,0.00,0.00,0.00,140.00,140.00,5.04,0.81,134.15,Tarjeta con DCC
349,181222,00776a5d-ce34-4e34-9ede-fabe44d97163,316.22,MXN,settlement processor regular payment request,11899296-f5e8-4f14-9bfb-00ff36d3e9f2,REGULAR_PYMT_RQ,SETT,2023-09-19 13:13:11,2023-09-20 03:30:00,...,0.00,0.00,0.00,0.00,330.00,330.00,11.88,1.90,316.22,Tarjeta con DCC
370,181198,00776a5d-ce34-4e34-9ede-fabe44d97163,672.21,MXN,settlement processor regular payment request,cd9ddb68-522c-41d5-933a-1d60375e27bb,REGULAR_PYMT_RQ,SETT,2023-09-15 10:54:29,2023-09-16 03:00:00,...,0.00,0.00,0.00,0.00,701.50,701.50,25.25,4.04,672.21,Tarjeta con DCC
833,183002,00aec522-d30b-4c5b-b5d8-20f46855c966,286.52,MXN,settlement processor regular payment request,5dbd222c-f35d-4516-ac2e-9cb5c678336a,REGULAR_PYMT_RQ,SETT,2023-09-29 20:41:09,2023-09-30 05:30:00,...,0.00,0.00,0.00,0.00,299.00,299.00,10.76,1.72,286.52,Tarjeta con DCC
988,182723,00aec522-d30b-4c5b-b5d8-20f46855c966,392.88,MXN,settlement processor regular payment request,f1b1ff0b-c033-4fb4-8e31-301f942db609,REGULAR_PYMT_RQ,SETT,2023-09-17 11:43:41,2023-09-18 03:00:00,...,0.00,0.00,0.00,0.00,410.00,410.00,14.76,2.36,392.88,Tarjeta con DCC

In [81]:
ap_sett_dcc.shape

(28061, 69)

In [82]:
ap_sett_dcc['movement_type'].unique()

array(['REGULAR_PYMT_RQ', 'FAST_PYMT_RQ'], dtype=object)

# ONLY REGULAR - FAST PAYMENTS

In [83]:
ap_sett_final_regular_fp = ap_sett_final
ap_sett_final_regular_fp.loc[ap_sett_final_regular_fp['movement_type'] == 'DEFERRED_REGULAR_PYMNT_RQ', 'gross_amount_dp'] = ap_sett_final_regular_fp['gross_amount']
ap_sett_final_regular_fp.loc[ap_sett_final_regular_fp['movement_type'] == 'DEFERRED_REGULAR_PYMNT_RQ', 'gross_amount'] = 0
ap_sett_final_regular_fp.loc[ap_sett_final_regular_fp['movement_type'] == 'DEFERRED_FAST_PYMNT_RQ', 'gross_amount_dp'] = ap_sett_final_regular_fp['gross_amount']
ap_sett_final_regular_fp.loc[ap_sett_final_regular_fp['movement_type'] == 'DEFERRED_FAST_PYMNT_RQ', 'gross_amount'] = 0
ap_sett_final_regular_fp.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,fees_pymt,taxes_pymt,net_amount_pymt,psp_amount,gross_amount,fees,taxes,net_amount,movement_type_sml,gross_amount_dp
0,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,0.00,0.00,0.00,"1,683.45",0.00,54.00,8.64,"1,437.36",0,"1,500.00"
1,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,0.00,0.00,0.00,"2,244.60",0.00,72.00,11.52,"1,916.48",0,"2,000.00"
2,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,0.00,0.00,0.00,"3,234.90",0.00,108.00,17.28,"2,874.72",0,"3,000.00"
3,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,0.00,0.00,0.00,"1,895.22",0.00,63.27,10.12,"1,684.21",0,"1,757.60"
4,180524,000d3438-2c68-41c7-9141-99d91b7c0190,"47,912.00",MXN,settlement processor regular payment request,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,REGULAR_PYMT_RQ,SETT,2023-09-26 23:48:15,2023-09-27 06:00:00,...,0.00,0.00,0.00,"50,000.00","50,000.00","1,800.00",288.00,"47,912.00",0,NaN

In [84]:
ap_sett_final_regular_fp.shape

(1503295, 70)

In [85]:
ap_sett_final_regular_fp['movement_type'].unique()

array(['DEFERRED_REGULAR_PYMNT_RQ', 'REGULAR_PYMT_RQ', 'FAST_PYMT_RQ',
       'DEFERRED_FAST_PYMNT_RQ'], dtype=object)

In [86]:
ap_sett_final_cancelaciones = ap_sett_final_regular_fp[(ap_sett_final_regular_fp['gross_amount_pymt'] != 0)]
ap_sett_final_cancelaciones.head()

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,fees_pymt,taxes_pymt,net_amount_pymt,psp_amount,gross_amount,fees,taxes,net_amount,movement_type_sml,gross_amount_dp
58,180556,003026b2-09d3-48cf-b611-9ada08487e20,"3,832.96",MXN,settlement processor regular payment request,be2243fd-5976-46ac-a4ae-a3f18bc6e763,REGULAR_PYMT_RQ,SETT,2023-08-31 18:53:04,2023-09-01 05:00:00,...,144.00,23.04,"3,832.96",0.00,0.00,0.00,0.00,0.00,0,NaN
128,91954,00431769-1dd9-4694-8640-69999e703bba,862.42,MXN,deferred regular payment request,ff97f2a6-43a0-496d-be2b-abc95ac798f5,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-09 08:48:45,2023-09-10 02:30:00,...,32.40,5.18,862.42,0.00,0.00,0.00,0.00,0.00,0,0.00
2182,184296,00dd6372-01d8-4909-9faf-bbf68acd4717,137.99,MXN,settlement processor regular payment request,b5bfe0f0-8ebb-41e6-83fb-bb09b6cf71fe,REGULAR_PYMT_RQ,SETT,2023-09-08 15:03:26,2023-09-09 04:00:00,...,5.18,0.83,137.99,0.00,0.00,0.00,0.00,0.00,0,NaN
3487,195348,013f87df-460a-48c4-87d9-5bec982f383e,229.98,MXN,settlement processor regular payment request,1da9d34c-6155-4d58-9e51-1574114b5bcf,REGULAR_PYMT_RQ,SETT,2023-09-27 17:24:33,2023-09-28 04:30:00,...,8.64,1.38,229.98,0.00,0.00,0.00,0.00,0.00,0,NaN
3975,194407,013f87df-460a-48c4-87d9-5bec982f383e,9.58,MXN,settlement processor regular payment request,6d9b685e-935b-44c7-a57e-584fb88f729b,REGULAR_PYMT_RQ,SETT,2023-09-06 11:16:47,2023-09-07 03:00:00,...,0.36,0.06,9.58,0.00,0.00,0.00,0.00,0.00,0,NaN

In [87]:
ap_sett_final_cancelaciones.shape

(2246, 70)

# DATA AUDITORIA REGULAR - FAST PAYMENTS

In [88]:
auditoria_previo_1 = ap_sett_final_regular_fp[['movement_type','email','date_transaction','merchant_id','transaction_id','mvnt_id','order_id',
                                               'created_at_cdmx','gross_amount','fees','taxes','net_amount','bin','last4','affiliation',
                                               'clave_autorizacion','number_msi','status_code','brand','psp','payment_sub_type',
                                               'updated_at_cdmx','receipt_no','issuer','device_id','report_date_local_final',
                                               'payment_date_local_final','report_id','status_final']]
auditoria_previo_1.head()

,movement_type,email,date_transaction,merchant_id,transaction_id,mvnt_id,order_id,created_at_cdmx,gross_amount,fees,...,psp,payment_sub_type,updated_at_cdmx,receipt_no,issuer,device_id,report_date_local_final,payment_date_local_final,report_id,status_final
0,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-13,0001c1e5-0d42-439e-8082-cbea9d09b094,6b5ee517-baab-4cd4-b59d-4c0dbf706098,6b5ee517-baab-4cd4-b59d-4c0dbf706098,321875816224,2023-09-13,0.00,54.00,...,PROSA,EMV_PIN,2023-09-13,ux5soI4,BBVA,5333594A52000105002F003407E40511,2023-09-14 00:00:00,2023-09-14 00:00:00,AN6WV5K49,PAID
1,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-10,0001c1e5-0d42-439e-8082-cbea9d09b094,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,761022586552,2023-09-10,0.00,72.00,...,PROSA,EMV_PIN,2023-09-10,ri3mNOx,BBVA,5333594A52000105002F003407E40511,2023-09-11 00:00:00,2023-09-11 00:00:00,AJCF7HC37,PAID
2,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-04,0001c1e5-0d42-439e-8082-cbea9d09b094,9d3fcf25-4114-49ab-98a5-d0616a5051bf,9d3fcf25-4114-49ab-98a5-d0616a5051bf,339912311718,2023-09-04,0.00,108.00,...,PROSA,EMV_PIN,2023-09-04,N7Kpx0I,BBVA,5333594A52000105002F003407E40511,2023-09-05 00:00:00,2023-09-05 00:00:00,A6PTNFRR4,PAID
3,DEFERRED_REGULAR_PYMNT_RQ,adriana.gosa00@gmail.com,2023-09-12,000a3072-b2a8-498e-8955-0e14a7559f89,56bc70e3-f524-4424-a4af-dd886df23a2c,56bc70e3-f524-4424-a4af-dd886df23a2c,omR3IjLPMcl4,2023-09-12,0.00,63.27,...,AMEX,ECOMMERCE,2023-09-12,e9W4423,AMEX,80010001,2023-09-13 00:00:00,2023-09-13 00:00:00,AFJG48G2D,PAID
4,REGULAR_PYMT_RQ,jl-munguia@hotmail.com,2023-09-26,000d3438-2c68-41c7-9141-99d91b7c0190,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,102406379449,2023-09-26,"50,000.00","1,800.00",...,PAYWORKS-BANORTE-CP,EMV_PIN,2023-09-26,KGqKPN5,BBVA,5331534C480001010049002907E3091B,2023-09-27 00:00:00,2023-09-27 00:00:00,AZWSXBJVP,PAID

In [89]:
auditoria_previo_1.shape

(1503295, 29)

# DEFERRED PAYMENTS

In [90]:
ap_sett_final_deferred = ap_sett_final[((ap_sett_final['movement_type'] == 'DEFERRED_REGULAR_PYMNT_RQ') |
                                        (ap_sett_final['movement_type'] == 'DEFERRED_FAST_PYMNT_RQ'))]
ap_sett_final_deferred['ingreso_deferred'] = ap_sett_final_deferred['psp_amount'] - ap_sett_final_deferred['gross_amount_dp']
ap_sett_final_deferred['fees_deferred'] = ap_sett_final_deferred['ingreso_deferred'] / 1.1600
ap_sett_final_deferred['taxes_deferred'] = ap_sett_final_deferred['fees_deferred']  * 0.1600
ap_sett_final_deferred.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\789703575.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ap_sett_final_deferred['ingreso_deferred'] = ap_sett_final_deferred['psp_amount'] - ap_sett_final_deferred['gross_amount_dp']
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\789703575.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ap_sett_final_deferred['fees_deferred'] = ap_sett_final_deferred['ingreso_deferred'] / 1.1600
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\789703575.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ap_sett_final_deferred['taxes_deferred'] = ap_sett_final_deferred['fees_deferred']  * 0.1600

,index,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at_x,eff_dt,...,psp_amount,gross_amount,fees,taxes,net_amount,movement_type_sml,gross_amount_dp,ingreso_deferred,fees_deferred,taxes_deferred
0,91944,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,437.36",MXN,deferred regular payment request,6b5ee517-baab-4cd4-b59d-4c0dbf706098,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-13 18:47:03,2023-09-14 05:00:00,...,"1,683.45",0.00,54.00,8.64,"1,437.36",0,"1,500.00",183.45,158.15,25.30
1,91943,0001c1e5-0d42-439e-8082-cbea9d09b094,"1,916.48",MXN,deferred regular payment request,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-10 00:47:04,2023-09-11 00:30:00,...,"2,244.60",0.00,72.00,11.52,"1,916.48",0,"2,000.00",244.60,210.86,33.74
2,91942,0001c1e5-0d42-439e-8082-cbea9d09b094,"2,874.72",MXN,deferred regular payment request,9d3fcf25-4114-49ab-98a5-d0616a5051bf,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-04 23:05:41,2023-09-05 06:00:00,...,"3,234.90",0.00,108.00,17.28,"2,874.72",0,"3,000.00",234.90,202.50,32.40
3,91945,000a3072-b2a8-498e-8955-0e14a7559f89,"1,684.21",MXN,deferred regular payment request,56bc70e3-f524-4424-a4af-dd886df23a2c,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-12 16:07:10,2023-09-13 04:30:00,...,"1,895.22",0.00,63.27,10.12,"1,684.21",0,"1,757.60",137.62,118.64,18.98
5,91946,000d3438-2c68-41c7-9141-99d91b7c0190,"4,791.20",MXN,deferred regular payment request,37d26e53-73ed-4426-ab55-40b6cba9349e,DEFERRED_REGULAR_PYMNT_RQ,SETT,2023-09-06 16:58:45,2023-09-07 04:30:00,...,"5,611.50",0.00,180.00,28.80,"4,791.20",0,"5,000.00",611.50,527.16,84.34

In [91]:
ap_sett_final_deferred.shape

(17907, 73)

# FILE AUDITORIA INCLUYENDO DEFERRED PAYMENTS

In [92]:
auditoria_previo_2 = auditoria_previo_1.merge(ap_sett_final_deferred[['mvnt_id','psp_amount','gross_amount_dp','ingreso_deferred',
                                                                   'fees_deferred','taxes_deferred']],on='mvnt_id',how='left')
auditoria_previo_2.fillna(0,inplace=True)
auditoria_previo_2.head()

,movement_type,email,date_transaction,merchant_id,transaction_id,mvnt_id,order_id,created_at_cdmx,gross_amount,fees,...,device_id,report_date_local_final,payment_date_local_final,report_id,status_final,psp_amount,gross_amount_dp,ingreso_deferred,fees_deferred,taxes_deferred
0,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-13,0001c1e5-0d42-439e-8082-cbea9d09b094,6b5ee517-baab-4cd4-b59d-4c0dbf706098,6b5ee517-baab-4cd4-b59d-4c0dbf706098,321875816224,2023-09-13,0.00,54.00,...,5333594A52000105002F003407E40511,2023-09-14 00:00:00,2023-09-14 00:00:00,AN6WV5K49,PAID,"1,683.45","1,500.00",183.45,158.15,25.30
1,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-10,0001c1e5-0d42-439e-8082-cbea9d09b094,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,761022586552,2023-09-10,0.00,72.00,...,5333594A52000105002F003407E40511,2023-09-11 00:00:00,2023-09-11 00:00:00,AJCF7HC37,PAID,"2,244.60","2,000.00",244.60,210.86,33.74
2,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-04,0001c1e5-0d42-439e-8082-cbea9d09b094,9d3fcf25-4114-49ab-98a5-d0616a5051bf,9d3fcf25-4114-49ab-98a5-d0616a5051bf,339912311718,2023-09-04,0.00,108.00,...,5333594A52000105002F003407E40511,2023-09-05 00:00:00,2023-09-05 00:00:00,A6PTNFRR4,PAID,"3,234.90","3,000.00",234.90,202.50,32.40
3,DEFERRED_REGULAR_PYMNT_RQ,adriana.gosa00@gmail.com,2023-09-12,000a3072-b2a8-498e-8955-0e14a7559f89,56bc70e3-f524-4424-a4af-dd886df23a2c,56bc70e3-f524-4424-a4af-dd886df23a2c,omR3IjLPMcl4,2023-09-12,0.00,63.27,...,80010001,2023-09-13 00:00:00,2023-09-13 00:00:00,AFJG48G2D,PAID,"1,895.22","1,757.60",137.62,118.64,18.98
4,REGULAR_PYMT_RQ,jl-munguia@hotmail.com,2023-09-26,000d3438-2c68-41c7-9141-99d91b7c0190,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,102406379449,2023-09-26,"50,000.00","1,800.00",...,5331534C480001010049002907E3091B,2023-09-27 00:00:00,2023-09-27 00:00:00,AZWSXBJVP,PAID,0.00,0.00,0.00,0.00,0.00

In [93]:
auditoria_previo_2.shape

(1503295, 34)

# MUESTRA AUDITORIA

In [94]:
muestra_audit = pd.concat([pd.read_excel(f,sheet_name='Data_facturacion_dp').assign(file_name=os.path.basename(f)) for f in muestra_audit_files])
muestra_audit.head()

,mes_facturacion,numero_partida,tipo_facturacion,merchant_id,user_email,Total due (payment),total_transactions,Txns fees,TopUps fees_2,Fees ingreso bill payments,Fees bonificación bill payments,Fees bonificación cashback,Loans fees,Net fees,Global taxes,gross_amount_dp,fees_deferred,taxes_deferred,status_me,file_name
0,Septiembre,79,Nominativa,0001c1e5-0d42-439e-8082-cbea9d09b094,gutierrezileyan61@gmail.com,"6,228.56",0.00,234.00,0.00,0.00,0.00,0.00,0,234.00,37.44,"6,500.00",571.51,91.44,ACTIVATED,Muestra_auditores_diciembre_2023.xlsx
1,Septiembre,79,Nominativa,000a3072-b2a8-498e-8955-0e14a7559f89,adriana.gosa00@gmail.com,"1,684.21",0.00,63.27,0.00,0.00,0.00,0.00,0,63.27,10.12,"1,757.60",118.64,18.98,ACTIVATED,Muestra_auditores_diciembre_2023.xlsx
2,Septiembre,79,Nominativa,000d3438-2c68-41c7-9141-99d91b7c0190,jl-munguia@hotmail.com,"67,364.27","65,300.00","2,530.80",0.00,0.00,0.00,0.00,0,"2,530.80",404.93,"5,000.00",527.16,84.34,ACTIVATED,Muestra_auditores_diciembre_2023.xlsx
3,Septiembre,79,Nominativa,0011477c-6dab-42c5-a8f8-f9da73399841,patyinteracciones@hotmail.com,"17,947.84","18,230.00",674.28,0.00,0.00,0.00,0.00,0,674.28,107.88,500.00,33.75,5.40,ACTIVATED,Muestra_auditores_diciembre_2023.xlsx
4,Septiembre,79,Nominativa,003026b2-09d3-48cf-b611-9ada08487e20,adrianasr24@yahoo.com.mx,"86,564.11","90,000.00","6,410.25",0.00,0.00,0.00,0.00,0,"6,410.25","1,025.64","4,000.00",734.14,117.46,ACTIVATED,Muestra_auditores_diciembre_2023.xlsx

In [95]:
muestra_audit.shape

(12749, 20)

# CRUCE ARCHIVO AUDITORIA PREVIO VS. MUESTRA AUDITORES

In [96]:
auditoria_previo_3 = auditoria_previo_2.merge(muestra_audit[['merchant_id','mes_facturacion','numero_partida','tipo_facturacion',
                                                             'status_me']],on='merchant_id',how='left')
auditoria_previo_3.fillna(0,inplace=True)
auditoria_previo_3['no_txn'] = ''
auditoria_previo_3['deposit_date'] = ''
auditoria_previo_3.head()

,movement_type,email,date_transaction,merchant_id,transaction_id,mvnt_id,order_id,created_at_cdmx,gross_amount,fees,...,gross_amount_dp,ingreso_deferred,fees_deferred,taxes_deferred,mes_facturacion,numero_partida,tipo_facturacion,status_me,no_txn,deposit_date
0,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-13,0001c1e5-0d42-439e-8082-cbea9d09b094,6b5ee517-baab-4cd4-b59d-4c0dbf706098,6b5ee517-baab-4cd4-b59d-4c0dbf706098,321875816224,2023-09-13,0.00,54.00,...,"1,500.00",183.45,158.15,25.30,Septiembre,79,Nominativa,ACTIVATED,,
1,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-10,0001c1e5-0d42-439e-8082-cbea9d09b094,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,761022586552,2023-09-10,0.00,72.00,...,"2,000.00",244.60,210.86,33.74,Septiembre,79,Nominativa,ACTIVATED,,
2,DEFERRED_REGULAR_PYMNT_RQ,gutierrezileyan61@gmail.com,2023-09-04,0001c1e5-0d42-439e-8082-cbea9d09b094,9d3fcf25-4114-49ab-98a5-d0616a5051bf,9d3fcf25-4114-49ab-98a5-d0616a5051bf,339912311718,2023-09-04,0.00,108.00,...,"3,000.00",234.90,202.50,32.40,Septiembre,79,Nominativa,ACTIVATED,,
3,DEFERRED_REGULAR_PYMNT_RQ,adriana.gosa00@gmail.com,2023-09-12,000a3072-b2a8-498e-8955-0e14a7559f89,56bc70e3-f524-4424-a4af-dd886df23a2c,56bc70e3-f524-4424-a4af-dd886df23a2c,omR3IjLPMcl4,2023-09-12,0.00,63.27,...,"1,757.60",137.62,118.64,18.98,Septiembre,79,Nominativa,ACTIVATED,,
4,REGULAR_PYMT_RQ,jl-munguia@hotmail.com,2023-09-26,000d3438-2c68-41c7-9141-99d91b7c0190,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,e4a6b04e-94ef-4e26-be2d-69bf5ff962b0,102406379449,2023-09-26,"50,000.00","1,800.00",...,0.00,0.00,0.00,0.00,Septiembre,79,Nominativa,ACTIVATED,,

In [97]:
auditoria_previo_3.shape

(1503295, 40)

In [98]:
auditoria_previo_3.columns

Index(['movement_type', 'email', 'date_transaction', 'merchant_id',
       'transaction_id', 'mvnt_id', 'order_id', 'created_at_cdmx',
       'gross_amount', 'fees', 'taxes', 'net_amount', 'bin', 'last4',
       'affiliation', 'clave_autorizacion', 'number_msi', 'status_code',
       'brand', 'psp', 'payment_sub_type', 'updated_at_cdmx', 'receipt_no',
       'issuer', 'device_id', 'report_date_local_final',
       'payment_date_local_final', 'report_id', 'status_final', 'psp_amount',
       'gross_amount_dp', 'ingreso_deferred', 'fees_deferred',
       'taxes_deferred', 'mes_facturacion', 'numero_partida',
       'tipo_facturacion', 'status_me', 'no_txn', 'deposit_date'],
      dtype='object')

# ARCHIVO AUDITORIA FINAL

In [99]:
auditoria_final = auditoria_previo_3[['mes_facturacion','numero_partida','tipo_facturacion','email','no_txn','date_transaction',
                                      'merchant_id','transaction_id','order_id','created_at_cdmx','gross_amount','fees','taxes',
                                      'psp_amount','gross_amount_dp','ingreso_deferred','fees_deferred','taxes_deferred','net_amount',
                                      'bin','last4','affiliation','clave_autorizacion','number_msi', 'status_code','brand','psp',
                                      'payment_sub_type','updated_at_cdmx','receipt_no','issuer','device_id','deposit_date',
                                      'report_date_local_final','payment_date_local_final','report_id','status_final','status_me']]
auditoria_final['report_date_local_final'].fillna('1990-01-01',inplace=True)
auditoria_final['report_date_local_final'] =  pd.to_datetime(auditoria_final['report_date_local_final'])
auditoria_final.sort_values(by=(['merchant_id','report_date_local_final']), ascending=[True,True], inplace=True)
auditoria_final.reset_index(drop=True,inplace=True)
auditoria_final.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\3872190654.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auditoria_final['report_date_local_final'].fillna('1990-01-01',inplace=True)
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\3872190654.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auditoria_final['report_date_local_final'] =  pd.to_datetime(auditoria_final['report_date_local_final'])
C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_15056\3872190654.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auditoria_final.sort_values(by=(['merchant_id','report_date_local_final']), ascending=[True,True], inplace=True)

,mes_facturacion,numero_partida,tipo_facturacion,email,no_txn,date_transaction,merchant_id,transaction_id,order_id,created_at_cdmx,...,updated_at_cdmx,receipt_no,issuer,device_id,deposit_date,report_date_local_final,payment_date_local_final,report_id,status_final,status_me
0,Septiembre,79,Nominativa,gutierrezileyan61@gmail.com,,2023-09-04,0001c1e5-0d42-439e-8082-cbea9d09b094,9d3fcf25-4114-49ab-98a5-d0616a5051bf,339912311718,2023-09-04,...,2023-09-04,N7Kpx0I,BBVA,5333594A52000105002F003407E40511,,2023-09-05,2023-09-05 00:00:00,A6PTNFRR4,PAID,ACTIVATED
1,Septiembre,79,Nominativa,gutierrezileyan61@gmail.com,,2023-09-10,0001c1e5-0d42-439e-8082-cbea9d09b094,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,761022586552,2023-09-10,...,2023-09-10,ri3mNOx,BBVA,5333594A52000105002F003407E40511,,2023-09-11,2023-09-11 00:00:00,AJCF7HC37,PAID,ACTIVATED
2,Septiembre,79,Nominativa,gutierrezileyan61@gmail.com,,2023-09-13,0001c1e5-0d42-439e-8082-cbea9d09b094,6b5ee517-baab-4cd4-b59d-4c0dbf706098,321875816224,2023-09-13,...,2023-09-13,ux5soI4,BBVA,5333594A52000105002F003407E40511,,2023-09-14,2023-09-14 00:00:00,AN6WV5K49,PAID,ACTIVATED
3,Septiembre,79,Nominativa,adriana.gosa00@gmail.com,,2023-09-12,000a3072-b2a8-498e-8955-0e14a7559f89,56bc70e3-f524-4424-a4af-dd886df23a2c,omR3IjLPMcl4,2023-09-12,...,2023-09-12,e9W4423,AMEX,80010001,,2023-09-13,2023-09-13 00:00:00,AFJG48G2D,PAID,ACTIVATED
4,Septiembre,79,Nominativa,jl-munguia@hotmail.com,,2023-09-06,000d3438-2c68-41c7-9141-99d91b7c0190,37d26e53-73ed-4426-ab55-40b6cba9349e,568759836851,2023-09-06,...,2023-09-06,fKU9nNR,CITIBANAMEX,5331534C480001010049002907E3091B,,2023-09-07,2023-09-07 00:00:00,A3NB3DS4M,PAID,ACTIVATED

In [100]:
auditoria_final.shape

(1503295, 38)

In [101]:
auditoria_final['numero_partida'].unique()

array([79], dtype=int64)

# SEPARACION POR PARTIDA

In [102]:
grouped = auditoria_final.groupby(auditoria_final.numero_partida)

In [103]:
group_79 = grouped.get_group(79)
# group_72 = grouped.get_group(72)
# group_73 = grouped.get_group(73)
# group_74 = grouped.get_group(74)
# group_75 = grouped.get_group(75)
# group_76 = grouped.get_group(76)
# group_77 = grouped.get_group(77)
# group_78 = grouped.get_group(78)
# group_80 = grouped.get_group(80)
# group_81 = grouped.get_group(81)
# group_54 = grouped.get_group(54)

In [104]:
group_79_1 = group_79.iloc[:800000]
group_79_2 = group_79.iloc[800000:]

In [109]:
group_79_1.head()

,mes_facturacion,numero_partida,tipo_facturacion,email,no_txn,date_transaction,merchant_id,transaction_id,order_id,created_at_cdmx,...,updated_at_cdmx,receipt_no,issuer,device_id,deposit_date,report_date_local_final,payment_date_local_final,report_id,status_final,status_me
0,Septiembre,79,Nominativa,gutierrezileyan61@gmail.com,,2023-09-04,0001c1e5-0d42-439e-8082-cbea9d09b094,9d3fcf25-4114-49ab-98a5-d0616a5051bf,339912311718,2023-09-04,...,2023-09-04,N7Kpx0I,BBVA,5333594A52000105002F003407E40511,,2023-09-05,2023-09-05 00:00:00,A6PTNFRR4,PAID,ACTIVATED
1,Septiembre,79,Nominativa,gutierrezileyan61@gmail.com,,2023-09-10,0001c1e5-0d42-439e-8082-cbea9d09b094,3c93122c-b6a2-4775-8bfb-3f06c6a43dfb,761022586552,2023-09-10,...,2023-09-10,ri3mNOx,BBVA,5333594A52000105002F003407E40511,,2023-09-11,2023-09-11 00:00:00,AJCF7HC37,PAID,ACTIVATED
2,Septiembre,79,Nominativa,gutierrezileyan61@gmail.com,,2023-09-13,0001c1e5-0d42-439e-8082-cbea9d09b094,6b5ee517-baab-4cd4-b59d-4c0dbf706098,321875816224,2023-09-13,...,2023-09-13,ux5soI4,BBVA,5333594A52000105002F003407E40511,,2023-09-14,2023-09-14 00:00:00,AN6WV5K49,PAID,ACTIVATED
3,Septiembre,79,Nominativa,adriana.gosa00@gmail.com,,2023-09-12,000a3072-b2a8-498e-8955-0e14a7559f89,56bc70e3-f524-4424-a4af-dd886df23a2c,omR3IjLPMcl4,2023-09-12,...,2023-09-12,e9W4423,AMEX,80010001,,2023-09-13,2023-09-13 00:00:00,AFJG48G2D,PAID,ACTIVATED
4,Septiembre,79,Nominativa,jl-munguia@hotmail.com,,2023-09-06,000d3438-2c68-41c7-9141-99d91b7c0190,37d26e53-73ed-4426-ab55-40b6cba9349e,568759836851,2023-09-06,...,2023-09-06,fKU9nNR,CITIBANAMEX,5331534C480001010049002907E3091B,,2023-09-07,2023-09-07 00:00:00,A3NB3DS4M,PAID,ACTIVATED

In [110]:
group_79_1.shape

(800000, 38)

In [111]:
group_79_2.head()

,mes_facturacion,numero_partida,tipo_facturacion,email,no_txn,date_transaction,merchant_id,transaction_id,order_id,created_at_cdmx,...,updated_at_cdmx,receipt_no,issuer,device_id,deposit_date,report_date_local_final,payment_date_local_final,report_id,status_final,status_me
800000,Septiembre,79,Nominativa,buwaysnavojoa2@gmail.com,,2023-09-27,8b259367-05b7-4275-9941-0185f4895c01,d137ad0d-2153-44a9-addf-5d25b5784871,373653374681,2023-09-27,...,2023-09-27,yAvCgDl,BBVA,P5211229002128,,2023-09-28,2023-09-28 00:00:00,AYZNP9C8S,PAID,ACTIVATED
800001,Septiembre,79,Nominativa,buwaysnavojoa2@gmail.com,,2023-09-27,8b259367-05b7-4275-9941-0185f4895c01,383e4045-60e0-4b2c-972a-6c8cd70adcd8,302032586642,2023-09-27,...,2023-09-27,2KMqEMo,CITIBANAMEX,P5211229002128,,2023-09-28,2023-09-28 00:00:00,AYZNP9C8S,PAID,ACTIVATED
800002,Septiembre,79,Nominativa,buwaysnavojoa2@gmail.com,,2023-09-27,8b259367-05b7-4275-9941-0185f4895c01,3e79b3e5-194c-4fd9-8478-b84fd2355183,468107241921,2023-09-27,...,2023-09-27,AoKHpyH,BANCOPPEL,P5211229002128,,2023-09-28,2023-09-28 00:00:00,AYZNP9C8S,PAID,ACTIVATED
800003,Septiembre,79,Nominativa,buwaysnavojoa2@gmail.com,,2023-09-27,8b259367-05b7-4275-9941-0185f4895c01,5ef9b559-d4aa-48d2-b24a-af92d1a00d32,463292867170,2023-09-27,...,2023-09-27,8iP2X67,BBVA,P5211229002128,,2023-09-28,2023-09-28 00:00:00,AYZNP9C8S,PAID,ACTIVATED
800004,Septiembre,79,Nominativa,buwaysnavojoa2@gmail.com,,2023-09-27,8b259367-05b7-4275-9941-0185f4895c01,e0643ffa-8149-4013-8399-9c14a23db4d9,625776000676,2023-09-27,...,2023-09-27,jUE9dUr,CITIBANAMEX,P5211229002128,,2023-09-28,2023-09-28 00:00:00,AYZNP9C8S,PAID,ACTIVATED

In [112]:
group_79_2.shape

(703295, 38)

In [113]:
writer = pd.ExcelWriter('Partida 79.xlsx',
                        engine='xlsxwriter',
                        engine_kwargs={'options': {'encoding':'utf-8'}})
group_79_1.to_excel(writer, sheet_name='Detalle_1',index=False)
group_79_2.to_excel(writer, sheet_name='Detalle_2',index=False)
writer.close()
# group_78.to_excel('Partida 78.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_72.to_excel('Partida 72.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_73.to_excel('Partida 73.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_74.to_excel('Partida 74.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_75.to_excel('Partida 75.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_76.to_excel('Partida 76.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_77.to_excel('Partida 77.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_78.to_excel('Partida 78.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_80.to_excel('Partida 80.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_81.to_excel('Partida 81.xlsx',sheet_name='Data facturación by transaction',index=False)
# group_54.to_excel('Partida 54.xlsx',sheet_name='Data facturación by transaction',index=False)

In [114]:
writer = pd.ExcelWriter('Data_auditoria_septiembre_2023_dp.xlsx',
                        engine='xlsxwriter',
                        engine_kwargs={'options': {'encoding':'utf-8'}})
group_79_1.to_excel(writer, sheet_name='Detalle_1',index=False)
group_79_2.to_excel(writer, sheet_name='Detalle_2',index=False)
writer.close()