In [13]:
import pandas as pd
import numpy as np
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# RUTAS

### SETTLEMENT MASTER LOG

In [14]:
sml_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\COMISIONISTAS\2023\11. NOVIEMBRE\NOT FOUND\SML*.csv', recursive=False)
sml_files

['C:\\Users\\Cristian.Aparicio\\Documents\\COMISIONISTAS\\2023\\11. NOVIEMBRE\\NOT FOUND\\SML_COMISIONISTAS NOVIEMBRE 2023.csv']

### AP JOURNAL

In [15]:
ap_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\COMISIONISTAS\2023\11. NOVIEMBRE\NOT FOUND\AP*.csv', recursive=False)
ap_files

['C:\\Users\\Cristian.Aparicio\\Documents\\COMISIONISTAS\\2023\\11. NOVIEMBRE\\NOT FOUND\\AP_JOURNAL_COMISIONISTAS NOVIEMBRE 2023.csv']

# DATA SETTLEMENT MASTER LOG

In [16]:
sml = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in sml_files])
sml.columns = sml.columns.str.strip().str.lower()
sml.replace('""','', regex=True, inplace=True)
sml['created_at'] = pd.to_datetime(sml['created_at']).dt.tz_localize(None)
sml['created_at_date'] =  pd.to_datetime(sml['created_at']).dt.date
sml['created_at_date'] =  pd.to_datetime(sml['created_at_date'])
sml['eff_dt'] = pd.to_datetime(sml['eff_dt']).dt.tz_localize(None)
sml['eff_dt_date'] =  pd.to_datetime(sml['eff_dt']).dt.date
sml['eff_dt_date'] =  pd.to_datetime(sml['eff_dt_date'])
sml.rename(columns={'ref_id':'transaction_id'},inplace=True)
#sml['PK'] = sml['PK'].replace('M#','',inplace=True)
sml.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,6eb4c96e-acda-545e-8458-d9be5f740335,3ee0c85f-4617-4736-90a1-927a41e0deec,0fe18c09-de9c-4a42-8ae2-c4811b8a28ce,0fe18c09-de9c-4a42-8ae2-c4811b8a28ce,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-01 09:23:48,2023-12-02 02:00:00,"5,796.00","5,796.00",...,0.00,0.00,0.00,1,Paid,6CvANPL,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-01,2023-12-02
1,43bea2d6-589c-56be-afc9-69e487fd67b3,3ee0c85f-4617-4736-90a1-927a41e0deec,ee0c8181-8ed6-42a4-bb45-74659bc4ddb8,ee0c8181-8ed6-42a4-bb45-74659bc4ddb8,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-06 22:15:06,2023-12-07 05:30:00,237.00,237.00,...,0.00,0.00,0.00,1,Paid,nv7UqJ2,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-06,2023-12-07
2,9c1bf27b-4c0f-50ff-a65e-c28e44e14d9e,3ee0c85f-4617-4736-90a1-927a41e0deec,ced72d9f-8d08-4fef-8f5d-1618450c5c97,ced72d9f-8d08-4fef-8f5d-1618450c5c97,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-04 18:43:31,2023-12-05 04:30:00,144.00,144.00,...,0.00,0.00,0.00,1,Paid,5AEaTFx,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-04,2023-12-05
3,9afe46e0-ac39-549b-b9a4-b5c168fcdaec,3ee0c85f-4617-4736-90a1-927a41e0deec,5709354e-b40d-412d-b170-7a617240b4d6,5709354e-b40d-412d-b170-7a617240b4d6,STL_PCS_RQ,REGULAR_PAYMENT,2023-11-30 10:37:48,2023-12-01 02:30:00,869.00,869.00,...,0.00,0.00,0.00,1,Paid,MhB0G5q,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-11-30,2023-12-01
4,6ea175a9-b618-5dae-8652-4c0009a0f2f4,3ee0c85f-4617-4736-90a1-927a41e0deec,90fe2b5c-37f0-4b6a-aa1d-3ed1528e3ca3,90fe2b5c-37f0-4b6a-aa1d-3ed1528e3ca3,STL_PCS_RQ,REGULAR_PAYMENT,2023-11-28 11:14:16,2023-11-29 02:30:00,"1,449.00","1,449.00",...,0.00,0.00,0.00,1,Paid,18W1uHk,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-11-28,2023-11-29

In [17]:
sml.shape

(423, 23)

In [18]:
sml.dtypes

record_uuid                object
merchant_id                object
transaction_id             object
mvnt_id                    object
mvnt_type                  object
pymt_prg                   object
created_at         datetime64[ns]
eff_dt             datetime64[ns]
psp_amount                float64
gross_amount              float64
fees                      float64
taxes                     float64
net_amount                float64
mdr                       float64
msi                       float64
number_msi                float64
status_code                 int64
status_msg                 object
receipt_no                 object
type                       object
file_name                  object
created_at_date    datetime64[ns]
eff_dt_date        datetime64[ns]
dtype: object

In [19]:
sml_final = sml[(sml['mvnt_type'] == 'STL_PCS_RQ')]
sml_final.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,6eb4c96e-acda-545e-8458-d9be5f740335,3ee0c85f-4617-4736-90a1-927a41e0deec,0fe18c09-de9c-4a42-8ae2-c4811b8a28ce,0fe18c09-de9c-4a42-8ae2-c4811b8a28ce,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-01 09:23:48,2023-12-02 02:00:00,"5,796.00","5,796.00",...,0.00,0.00,0.00,1,Paid,6CvANPL,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-01,2023-12-02
1,43bea2d6-589c-56be-afc9-69e487fd67b3,3ee0c85f-4617-4736-90a1-927a41e0deec,ee0c8181-8ed6-42a4-bb45-74659bc4ddb8,ee0c8181-8ed6-42a4-bb45-74659bc4ddb8,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-06 22:15:06,2023-12-07 05:30:00,237.00,237.00,...,0.00,0.00,0.00,1,Paid,nv7UqJ2,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-06,2023-12-07
2,9c1bf27b-4c0f-50ff-a65e-c28e44e14d9e,3ee0c85f-4617-4736-90a1-927a41e0deec,ced72d9f-8d08-4fef-8f5d-1618450c5c97,ced72d9f-8d08-4fef-8f5d-1618450c5c97,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-04 18:43:31,2023-12-05 04:30:00,144.00,144.00,...,0.00,0.00,0.00,1,Paid,5AEaTFx,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-04,2023-12-05
3,9afe46e0-ac39-549b-b9a4-b5c168fcdaec,3ee0c85f-4617-4736-90a1-927a41e0deec,5709354e-b40d-412d-b170-7a617240b4d6,5709354e-b40d-412d-b170-7a617240b4d6,STL_PCS_RQ,REGULAR_PAYMENT,2023-11-30 10:37:48,2023-12-01 02:30:00,869.00,869.00,...,0.00,0.00,0.00,1,Paid,MhB0G5q,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-11-30,2023-12-01
4,6ea175a9-b618-5dae-8652-4c0009a0f2f4,3ee0c85f-4617-4736-90a1-927a41e0deec,90fe2b5c-37f0-4b6a-aa1d-3ed1528e3ca3,90fe2b5c-37f0-4b6a-aa1d-3ed1528e3ca3,STL_PCS_RQ,REGULAR_PAYMENT,2023-11-28 11:14:16,2023-11-29 02:30:00,"1,449.00","1,449.00",...,0.00,0.00,0.00,1,Paid,18W1uHk,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-11-28,2023-11-29

In [20]:
sml_final.shape

(423, 23)

# DATA AP JOURNAL

In [21]:
ap = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in ap_files])
ap.columns = ap.columns.str.strip().str.lower()
ap.replace('""','', regex=True, inplace=True)
ap['eff_dt'] =  pd.to_datetime(ap['eff_dt']).dt.tz_localize(None)
ap['eff_dt_date'] =  pd.to_datetime(ap['eff_dt']).dt.date
ap['eff_dt_date'] =  pd.to_datetime(ap['eff_dt_date'])
ap['eff_dt_time'] =  pd.to_datetime(ap['eff_dt']).dt.time
ap['movement_day'] = pd.to_datetime(ap['movement_day']).dt.tz_localize(None)
ap['created_at'] = pd.to_datetime(ap['created_at']).dt.tz_localize(None)
ap['created_at_date'] =  pd.to_datetime(ap['created_at']).dt.date
ap['created_at_date'] =  pd.to_datetime(ap['created_at_date'])
ap['request_effective_date'] = pd.to_datetime(ap['request_effective_date']).dt.tz_localize(None)
ap['slot_date'] = pd.to_datetime(ap['slot_date']).dt.tz_localize(None)
ap['identifier'] = ap['source_type'].str[:1].astype(str)
ap['INDEX'] = (ap['eff_dt_date'].astype(str).replace(' ', '',regex=True)+'-'+
               ap['identifier'].astype(str).replace(' ', '',regex=True)+'-'+
               ap['eff_dt_time'].astype(str).replace(' ', '',regex=True))
ap.sort_values(by=(['merchant_id','eff_dt']), ascending=[True,False], inplace=True)

In [22]:
ap.loc[ap['source_type'] == 'DISB', 'report_id'] = ap['type_request']
ap['report_id'] = ap['report_id'].groupby(ap['merchant_id']).ffill()
ap.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time,created_at_date,identifier,INDEX,report_id
98,3567dbde-bd56-4ac3-9ea3-bc46ad9c2c23,"-1,599.00",MXN,A63RRKYHD,5d18cf73-6ab5-3a5e-9cf0-8e3a62b31016,DISB_RQ,DISB,2023-12-09 07:24:23,2023-12-09 07:24:28,2023-12-09 07:24:17,2023-12-09 07:05:17,1969-12-31 18:00:00,AP_JOURNAL_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-09,07:24:28,2023-12-09,D,2023-12-09-D-07:24:28,A63RRKYHD
97,3567dbde-bd56-4ac3-9ea3-bc46ad9c2c23,"1,599.00",MXN,settlement processor regular payment request,4ae562bb-14e7-45a6-abda-b425a612b4f4,REGULAR_PYMT_RQ,SETT,2023-12-08 17:32:00,2023-12-09 04:30:00,2023-12-08 17:32:00,2023-12-09 04:00:00,2023-12-09 04:30:00,AP_JOURNAL_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-09,04:30:00,2023-12-08,S,2023-12-09-S-04:30:00,A63RRKYHD
96,3567dbde-bd56-4ac3-9ea3-bc46ad9c2c23,"-2,799.00",MXN,AHDSXTX24,9a399c3d-fded-3050-8792-e1c341443100,DISB_RQ,DISB,2023-12-08 07:22:57,2023-12-08 07:23:02,2023-12-08 07:22:56,2023-12-08 07:05:16,1969-12-31 18:00:00,AP_JOURNAL_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-08,07:23:02,2023-12-08,D,2023-12-08-D-07:23:02,AHDSXTX24
94,3567dbde-bd56-4ac3-9ea3-bc46ad9c2c23,"1,199.00",MXN,settlement processor regular payment request,f5ed7a56-78fa-4bb3-9fdd-7bd7b397a4d4,REGULAR_PYMT_RQ,SETT,2023-12-07 11:38:23,2023-12-08 03:00:00,2023-12-07 11:38:23,2023-12-08 02:30:00,2023-12-08 03:00:00,AP_JOURNAL_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-08,03:00:00,2023-12-07,S,2023-12-08-S-03:00:00,AHDSXTX24
95,3567dbde-bd56-4ac3-9ea3-bc46ad9c2c23,"1,600.00",MXN,settlement processor regular payment request,b88b2535-f1d8-45c8-99dc-2d290c81fb17,REGULAR_PYMT_RQ,SETT,2023-12-07 11:57:35,2023-12-08 03:00:00,2023-12-07 11:57:35,2023-12-08 02:30:00,2023-12-08 03:00:00,AP_JOURNAL_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-08,03:00:00,2023-12-07,S,2023-12-08-S-03:00:00,AHDSXTX24

In [23]:
ap.shape

(595, 19)

In [24]:
ap.dtypes

merchant_id                       object
amount                           float64
currency                          object
type_request                      object
mvnt_id                           object
movement_type                     object
source_type                       object
created_at                datetime64[ns]
eff_dt                    datetime64[ns]
movement_day              datetime64[ns]
request_effective_date    datetime64[ns]
slot_date                 datetime64[ns]
file_name                         object
eff_dt_date               datetime64[ns]
eff_dt_time                       object
created_at_date           datetime64[ns]
identifier                        object
INDEX                             object
report_id                         object
dtype: object

In [25]:
sorted(list(ap['source_type'].unique()))

['BILL_PYMNT', 'DISB', 'PROMO', 'PYMT', 'REFUNDS', 'RISK', 'SETT', 'TOPUPS']

In [26]:
ap['report_id'].unique()

array(['A63RRKYHD', 'AHDSXTX24', 'AP832GYJP', 'AR7NYFM9X', 'AXN9L9XCY',
       'AZHKX4453', 'AR25Q73M4', 'A7ZXR6D6R', 'A9WS3ZWD7', 'ACGS4MKK2',
       'AZVBHWPMZ', 'AGN6K97CW', 'AHLH5QNYV', 'AXLH7MSBW', 'AXQD72K93',
       'AZWJQPCCR', 'ALDNX4LTY', 'A2VBPNYL4', 'AQ7T93LH2', 'AGQBDSTRP',
       'A8WJF2GHC', 'A7324L8WB', 'AVTX6PQLK', 'AKNKZNPKX', 'ANJSY88XD',
       'A2HG59S84', 'A49Q5B2SS', 'AD9T7WYV5', 'ABTK4Q6HR', 'A57YFQW98',
       'AV6B7LP9X', 'AN7RLGDVW', 'APK9YGHN9', 'A8R24SPYG', 'A3S3ZGYVQ',
       'ADKBJBX6L', 'APGGNM7DM', 'ABH7QDWY3', 'AYQBQTJ5V', 'ABRZTJZRZ',
       'AX3BTG3QD', 'AQV7TX437', 'AQC7S7VFF', 'A3NJ7QXDF', 'AYG7396ZZ',
       'AZL3LP2DX', 'ALRHMG9DY', 'AGGJ2M8L5', 'ADCVR4QQK', 'AC59KK8V8',
       'AXS4MXG48', 'AMGSMRDGS', 'AK3VD9Q5F', 'AMDSRV9NG', 'A52478CV8',
       'A7G2RHHM8', 'AMMDLVML8', 'ATVJ656F8', 'AD3PL4DSC', 'A373SCYTR',
       'AS59DRJ3M', 'AX7NKNK8T', 'AD7YN9RV6', 'ADSJFJST9', 'A29WWZV74',
       'AP7T6QTTS', 'AF7NZSLRQ', 'AWCPQ87T9', 'APPLFDZVC', 'AB4PPZLBL',
       'ARYG2ML2D', 'AMLKX5827', 'AXKZQ6DKS', 'A87J3JCKC', 'ABJVMKF28',
       'ATSNMGHVR', 'AH6KVDCBJ', 'AKQGMBHHG', 'A985ZF62H', 'AKMVZ7BJ8',
       'APHRB56SB', 'AL58C937X', 'A2QVN4L28', 'AVYVKCC2N', 'AMKYDZTBC',
       'ASDSF8KLF', 'A7KB87663', 'A85KHR2JL', 'A8D2LPMCM', 'APWCQC6CL',
       'AFYB97WDT', 'ATH2VGXXH', 'ASW6SNSMB', 'A6VFYRTXQ', 'A38W8ZTQM',
       'ARD9DPZG9', 'A8SLCPX8K', 'AQ94JBB27', 'A547L379Z', 'AXBW34Y75',
       'AQQBV4LXZ', 'A7CB7M597', 'ANG3B5P8N', 'AZFBPRQGN', 'ATQ6Y5GW2',
       'A9BXR495T', 'AP2STVM8T', 'AGS7F457D', 'AC3YW2Z38', 'AF48CC933',
       'AG3BZ5XWF', 'AQFX7Q7KB', 'ATMCRXM7C', 'APSWPL9VT', 'AHPTSYCXB',
       'A5S9F4H87', 'ANJ86M24L', 'AW5N7Y4M4', 'AYWPND6FS', 'A9RQS3WCN',
       'A2L5LRPP7', 'ALLN4NF7K', 'A926LWDGX', 'AHZN24TGM', 'A7QPRRT65',
       'AKC27N4RD', 'AYJQXP9CP', 'AR9JFTLSR', 'A92JJCBHC', 'A7M7SPHCZ'],
      dtype=object)

In [27]:
ap_disb = ap[(ap['source_type'] == 'DISB')]
ap_pymt = ap[(ap['source_type'] == 'PYMT')]
ap_sett = ap[(ap['source_type'] == 'SETT')]
ap_topups = ap[(ap['source_type'] == 'TOPUPS')]
ap_risk = ap[(ap['source_type'] == 'RISK')]
# ap_loan = ap[(ap['source_type'] == 'LOAN')]

# CRUCE: IDENTIFICACION DE REPORT_ID

In [28]:
cruce_1 = sml_final.merge(ap[['mvnt_id','report_id','movement_type']],on='mvnt_id',how='left')
cruce_1.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date,report_id,movement_type
0,6eb4c96e-acda-545e-8458-d9be5f740335,3ee0c85f-4617-4736-90a1-927a41e0deec,0fe18c09-de9c-4a42-8ae2-c4811b8a28ce,0fe18c09-de9c-4a42-8ae2-c4811b8a28ce,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-01 09:23:48,2023-12-02 02:00:00,"5,796.00","5,796.00",...,0.00,1,Paid,6CvANPL,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-01,2023-12-02,AX3BTG3QD,REGULAR_PYMT_RQ
1,43bea2d6-589c-56be-afc9-69e487fd67b3,3ee0c85f-4617-4736-90a1-927a41e0deec,ee0c8181-8ed6-42a4-bb45-74659bc4ddb8,ee0c8181-8ed6-42a4-bb45-74659bc4ddb8,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-06 22:15:06,2023-12-07 05:30:00,237.00,237.00,...,0.00,1,Paid,nv7UqJ2,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-06,2023-12-07,APGGNM7DM,REGULAR_PYMT_RQ
2,9c1bf27b-4c0f-50ff-a65e-c28e44e14d9e,3ee0c85f-4617-4736-90a1-927a41e0deec,ced72d9f-8d08-4fef-8f5d-1618450c5c97,ced72d9f-8d08-4fef-8f5d-1618450c5c97,STL_PCS_RQ,REGULAR_PAYMENT,2023-12-04 18:43:31,2023-12-05 04:30:00,144.00,144.00,...,0.00,1,Paid,5AEaTFx,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-12-04,2023-12-05,AYQBQTJ5V,REGULAR_PYMT_RQ
3,9afe46e0-ac39-549b-b9a4-b5c168fcdaec,3ee0c85f-4617-4736-90a1-927a41e0deec,5709354e-b40d-412d-b170-7a617240b4d6,5709354e-b40d-412d-b170-7a617240b4d6,STL_PCS_RQ,REGULAR_PAYMENT,2023-11-30 10:37:48,2023-12-01 02:30:00,869.00,869.00,...,0.00,1,Paid,MhB0G5q,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-11-30,2023-12-01,AQV7TX437,REGULAR_PYMT_RQ
4,6ea175a9-b618-5dae-8652-4c0009a0f2f4,3ee0c85f-4617-4736-90a1-927a41e0deec,90fe2b5c-37f0-4b6a-aa1d-3ed1528e3ca3,90fe2b5c-37f0-4b6a-aa1d-3ed1528e3ca3,STL_PCS_RQ,REGULAR_PAYMENT,2023-11-28 11:14:16,2023-11-29 02:30:00,"1,449.00","1,449.00",...,0.00,1,Paid,18W1uHk,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-11-28,2023-11-29,A3NJ7QXDF,REGULAR_PYMT_RQ

In [29]:
cruce_1.shape

(424, 25)

In [30]:
cruce_1_not_found = cruce_1[(cruce_1['movement_type'].isnull())]
cruce_1_not_found.head()

Empty DataFrame
Columns: [record_uuid, merchant_id, transaction_id, mvnt_id, mvnt_type, pymt_prg, created_at, eff_dt, psp_amount, gross_amount, fees, taxes, net_amount, mdr, msi, number_msi, status_code, status_msg, receipt_no, type, file_name, created_at_date, eff_dt_date, report_id, movement_type]
Index: []

[0 rows x 25 columns]

In [31]:
cruce_1_not_found.shape

(0, 25)

In [32]:
cruce_1_final = cruce_1[['merchant_id','transaction_id','report_id','receipt_no','gross_amount','fees','taxes',
                        'net_amount','eff_dt_date','created_at','created_at_date','status_code','status_msg']]
cruce_1_final.head()

,merchant_id,transaction_id,report_id,receipt_no,gross_amount,fees,taxes,net_amount,eff_dt_date,created_at,created_at_date,status_code,status_msg
0,3ee0c85f-4617-4736-90a1-927a41e0deec,0fe18c09-de9c-4a42-8ae2-c4811b8a28ce,AX3BTG3QD,6CvANPL,"5,796.00",0.00,0.00,"5,796.00",2023-12-02,2023-12-01 09:23:48,2023-12-01,1,Paid
1,3ee0c85f-4617-4736-90a1-927a41e0deec,ee0c8181-8ed6-42a4-bb45-74659bc4ddb8,APGGNM7DM,nv7UqJ2,237.00,0.00,0.00,237.00,2023-12-07,2023-12-06 22:15:06,2023-12-06,1,Paid
2,3ee0c85f-4617-4736-90a1-927a41e0deec,ced72d9f-8d08-4fef-8f5d-1618450c5c97,AYQBQTJ5V,5AEaTFx,144.00,0.00,0.00,144.00,2023-12-05,2023-12-04 18:43:31,2023-12-04,1,Paid
3,3ee0c85f-4617-4736-90a1-927a41e0deec,5709354e-b40d-412d-b170-7a617240b4d6,AQV7TX437,MhB0G5q,869.00,0.00,0.00,869.00,2023-12-01,2023-11-30 10:37:48,2023-11-30,1,Paid
4,3ee0c85f-4617-4736-90a1-927a41e0deec,90fe2b5c-37f0-4b6a-aa1d-3ed1528e3ca3,A3NJ7QXDF,18W1uHk,"1,449.00",0.00,0.00,"1,449.00",2023-11-29,2023-11-28 11:14:16,2023-11-28,1,Paid

In [33]:
cruce_1_final.shape

(424, 13)

In [34]:
cruce_1_dup = cruce_1[cruce_1.duplicated(['mvnt_id'] , keep=False)]
cruce_1_dup.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date,report_id,movement_type
239,ef334a04-11c2-592b-9154-38d34ff6001a,3ee0c85f-4617-4736-90a1-927a41e0deec,f0aba16c-63d2-4524-b7b5-ec64bb74655a,f0aba16c-63d2-4524-b7b5-ec64bb74655a,STL_PCS_RQ,REGULAR_PAYMENT,2023-11-17 17:00:44,2023-11-18 04:00:00,"3,124.00","3,124.00",...,0.00,3,Cancelled. Merchant initiated.,6DZBubi,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-11-17,2023-11-18,AMDSRV9NG,REGULAR_PYMT_RQ
240,ef334a04-11c2-592b-9154-38d34ff6001a,3ee0c85f-4617-4736-90a1-927a41e0deec,f0aba16c-63d2-4524-b7b5-ec64bb74655a,f0aba16c-63d2-4524-b7b5-ec64bb74655a,STL_PCS_RQ,REGULAR_PAYMENT,2023-11-17 17:00:44,2023-11-18 04:00:00,"3,124.00","3,124.00",...,0.00,3,Cancelled. Merchant initiated.,6DZBubi,PAYMENT,SML_COMISIONISTAS NOVIEMBRE 2023.csv,2023-11-17,2023-11-18,AMDSRV9NG,CANCEL_RQ

In [35]:
cruce_1_dup.shape

(2, 25)

In [37]:
check_txn = cruce_1_final[(cruce_1_final['receipt_no'].isin(['r0fHvZ0',
                                                             'pyv48qz']))]
check_txn.head()

,merchant_id,transaction_id,report_id,receipt_no,gross_amount,fees,taxes,net_amount,eff_dt_date,created_at,created_at_date,status_code,status_msg
10,3567dbde-bd56-4ac3-9ea3-bc46ad9c2c23,7ac53dc8-11da-460c-a377-efc983c10d9d,A7324L8WB,r0fHvZ0,"1,999.00",0.00,0.00,"1,999.00",2023-10-25,2023-10-24 10:58:37,2023-10-24,1,Paid
93,3ee0c85f-4617-4736-90a1-927a41e0deec,73e99d16-8b74-4f84-a5d0-d6af150a447b,AQV7TX437,pyv48qz,"13,034.56",586.56,93.85,"12,354.15",2023-12-01,2023-11-30 00:10:56,2023-11-30,1,Paid

In [38]:
check_txn.shape

(2, 13)

In [40]:
check_txn.to_excel('0. DATA COMISIONISTAS-MISSING NOVIEMBRE 2023.xlsx',index=False)