In [1]:
import pandas as pd
import numpy as np
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
start_date_fact = '2024-01-01'
final_date_fact = '2024-01-31'

# RUTAS

### SETTLEMENT MASTER LOG

In [3]:
sml_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\MONTO NO FACTURADO\2024\01. ENERO\LEDGER\*.csv', recursive=False)
sml_files

['C:\\Users\\Cristian.Aparicio\\Documents\\MONTO NO FACTURADO\\2024\\01. ENERO\\LEDGER\\SML MONTO NO FACTURADO ENERO 2024.csv']

### AP JOURNAL

In [4]:
ap_files = glob.glob(r'G:\My Drive\RESPALDO-PC\DYNAMO\2024\01. ENERO\AP JOURNAL\*.tsv', recursive=False)
ap_files

['G:\\My Drive\\RESPALDO-PC\\DYNAMO\\2024\\01. ENERO\\AP JOURNAL\\AP-JOURNAL_DATE ENERO 2024.tsv',
 'G:\\My Drive\\RESPALDO-PC\\DYNAMO\\2024\\01. ENERO\\AP JOURNAL\\AP-JOURNAL_DATE FEBRERO 2024.tsv']

# DATA SETTLEMENT MASTER LOG

In [5]:
sml = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in sml_files])
sml.columns = sml.columns.str.strip().str.lower()
sml.replace('""','', regex=True, inplace=True)
sml['created_at'] = pd.to_datetime(sml['created_at']).dt.tz_localize(None)
sml['created_at_date'] =  pd.to_datetime(sml['created_at']).dt.date
sml['created_at_date'] =  pd.to_datetime(sml['created_at_date'])
sml['eff_dt'] = pd.to_datetime(sml['eff_dt']).dt.tz_localize(None)
sml['eff_dt_date'] =  pd.to_datetime(sml['eff_dt']).dt.date
sml['eff_dt_date'] =  pd.to_datetime(sml['eff_dt_date'])
sml.rename(columns={'ref_id':'transaction_id'},inplace=True)
#sml['PK'] = sml['PK'].replace('M#','',inplace=True)
sml.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,9c3c7bcc-9b5d-5f62-b9ee-deed4a2409e9,51503fff-9f23-4913-898b-3f1cc5a61d24,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:12:00,2024-02-01 05:30:00,"1,568.00","1,568.00",...,0.04,0.00,0.00,1,Paid,uV7iU6G,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
1,57b8ffe6-dd0b-5964-90ec-c016beb0c706,f17144bb-40f1-49d9-9d00-4c41180a7cac,32fd9623-b69b-499f-96d7-28ed55e31193,32fd9623-b69b-499f-96d7-28ed55e31193,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:24:30,2024-02-01 05:30:00,"1,000.00","1,000.00",...,0.04,0.00,0.00,1,Paid,jJyU6ak,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
2,b1265364-a563-5e0b-b920-7ad49bd23a20,259a0282-b016-49ed-b1f3-bd0c6639e00c,7156f1fb-2eea-4956-b9da-16b33bbd567b,7156f1fb-2eea-4956-b9da-16b33bbd567b,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:53:33,2024-02-01 05:30:00,290.00,290.00,...,0.04,0.00,0.00,1,Paid,69tgkTl,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
3,85e52ecd-6c0b-5857-aebd-b1776aec201b,8261d5da-dd20-45a1-8471-e1a7d9b991eb,fe2fc574-e23f-40e6-afda-07f3e730852d,fe2fc574-e23f-40e6-afda-07f3e730852d,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:34:18,2024-02-01 05:30:00,735.00,735.00,...,0.04,0.00,0.00,1,Paid,9k7qHW2,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
4,b220134d-8e71-5fb4-bd4c-a77de0f2276d,687a1551-6937-4a6a-aac4-487bf3999cca,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:58:56,2024-02-01 05:30:00,19.00,19.00,...,0.04,0.00,0.00,1,Paid,coBcBI3,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01

In [6]:
sml.shape

(544777, 23)

In [7]:
sml.dtypes

record_uuid                object
merchant_id                object
transaction_id             object
mvnt_id                    object
mvnt_type                  object
pymt_prg                   object
created_at         datetime64[ns]
eff_dt             datetime64[ns]
psp_amount                float64
gross_amount              float64
fees                      float64
taxes                     float64
net_amount                float64
mdr                       float64
msi                       float64
number_msi                float64
status_code                 int64
status_msg                 object
receipt_no                 object
type                       object
file_name                  object
created_at_date    datetime64[ns]
eff_dt_date        datetime64[ns]
dtype: object

In [8]:
sml_final = sml[(sml['mvnt_type'] == 'STL_PCS_RQ')]
sml_final.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,9c3c7bcc-9b5d-5f62-b9ee-deed4a2409e9,51503fff-9f23-4913-898b-3f1cc5a61d24,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:12:00,2024-02-01 05:30:00,"1,568.00","1,568.00",...,0.04,0.00,0.00,1,Paid,uV7iU6G,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
1,57b8ffe6-dd0b-5964-90ec-c016beb0c706,f17144bb-40f1-49d9-9d00-4c41180a7cac,32fd9623-b69b-499f-96d7-28ed55e31193,32fd9623-b69b-499f-96d7-28ed55e31193,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:24:30,2024-02-01 05:30:00,"1,000.00","1,000.00",...,0.04,0.00,0.00,1,Paid,jJyU6ak,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
2,b1265364-a563-5e0b-b920-7ad49bd23a20,259a0282-b016-49ed-b1f3-bd0c6639e00c,7156f1fb-2eea-4956-b9da-16b33bbd567b,7156f1fb-2eea-4956-b9da-16b33bbd567b,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:53:33,2024-02-01 05:30:00,290.00,290.00,...,0.04,0.00,0.00,1,Paid,69tgkTl,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
3,85e52ecd-6c0b-5857-aebd-b1776aec201b,8261d5da-dd20-45a1-8471-e1a7d9b991eb,fe2fc574-e23f-40e6-afda-07f3e730852d,fe2fc574-e23f-40e6-afda-07f3e730852d,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:34:18,2024-02-01 05:30:00,735.00,735.00,...,0.04,0.00,0.00,1,Paid,9k7qHW2,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
4,b220134d-8e71-5fb4-bd4c-a77de0f2276d,687a1551-6937-4a6a-aac4-487bf3999cca,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:58:56,2024-02-01 05:30:00,19.00,19.00,...,0.04,0.00,0.00,1,Paid,coBcBI3,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01

In [9]:
sml_final.shape

(544777, 23)

In [10]:
sml_mnf = sml_final[(sml_final['created_at_date'] <= '2024-01-31') & (sml_final['eff_dt_date'] >= '2024-02-01')]
sml_mnf.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,9c3c7bcc-9b5d-5f62-b9ee-deed4a2409e9,51503fff-9f23-4913-898b-3f1cc5a61d24,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:12:00,2024-02-01 05:30:00,"1,568.00","1,568.00",...,0.04,0.00,0.00,1,Paid,uV7iU6G,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
1,57b8ffe6-dd0b-5964-90ec-c016beb0c706,f17144bb-40f1-49d9-9d00-4c41180a7cac,32fd9623-b69b-499f-96d7-28ed55e31193,32fd9623-b69b-499f-96d7-28ed55e31193,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:24:30,2024-02-01 05:30:00,"1,000.00","1,000.00",...,0.04,0.00,0.00,1,Paid,jJyU6ak,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
2,b1265364-a563-5e0b-b920-7ad49bd23a20,259a0282-b016-49ed-b1f3-bd0c6639e00c,7156f1fb-2eea-4956-b9da-16b33bbd567b,7156f1fb-2eea-4956-b9da-16b33bbd567b,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:53:33,2024-02-01 05:30:00,290.00,290.00,...,0.04,0.00,0.00,1,Paid,69tgkTl,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
3,85e52ecd-6c0b-5857-aebd-b1776aec201b,8261d5da-dd20-45a1-8471-e1a7d9b991eb,fe2fc574-e23f-40e6-afda-07f3e730852d,fe2fc574-e23f-40e6-afda-07f3e730852d,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:34:18,2024-02-01 05:30:00,735.00,735.00,...,0.04,0.00,0.00,1,Paid,9k7qHW2,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01
4,b220134d-8e71-5fb4-bd4c-a77de0f2276d,687a1551-6937-4a6a-aac4-487bf3999cca,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:58:56,2024-02-01 05:30:00,19.00,19.00,...,0.04,0.00,0.00,1,Paid,coBcBI3,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01

In [11]:
sml_mnf.shape

(544777, 23)

In [12]:
sml_mnf_me_id = sml_mnf.groupby(['merchant_id']).agg({'mvnt_id':'count','gross_amount':sum,'fees':sum,'taxes':sum,
                                                     'net_amount':sum}).reset_index()
sml_mnf_me_id['index'] = (sml_mnf_me_id['merchant_id'].astype(str).replace(' ', '',regex=True)+'-'+
                          sml_mnf_me_id['net_amount'].astype(str).replace(' ', '',regex=True))
sml_mnf_me_id.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_16248\3102954548.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sml_mnf_me_id = sml_mnf.groupby(['merchant_id']).agg({'mvnt_id':'count','gross_amount':sum,'fees':sum,'taxes':sum,

,merchant_id,mvnt_id,gross_amount,fees,taxes,net_amount,index
0,000096e6-5d2f-47e9-a924-4b413eca6a43,1,299.00,10.76,1.72,286.52,000096e6-5d2f-47e9-a924-4b413eca6a43-286.52
1,0000b65a-c2a2-4993-8f4c-05e5b7cbd7c0,1,690.75,24.87,3.98,661.90,0000b65a-c2a2-4993-8f4c-05e5b7cbd7c0-661.9
2,0000bc20-a726-4fe6-b784-1eb97c287ad5,3,687.00,24.74,3.96,658.30,0000bc20-a726-4fe6-b784-1eb97c287ad5-658.3
3,0000d1ea-bfb8-45bf-aae7-a0f7ae11db1e,1,"4,500.00",162.00,25.92,"4,312.08",0000d1ea-bfb8-45bf-aae7-a0f7ae11db1e-4312.08
4,00016126-0052-402d-ba8a-95e5e1a1c673,1,"1,760.00",63.36,10.14,"1,686.50",00016126-0052-402d-ba8a-95e5e1a1c673-1686.5

In [13]:
sml_mnf_me_id.shape

(103527, 7)

In [14]:
sml_mnf.to_excel('Transacciones_no_facturadas_diciembre_2023.xlsx',index=False)

# DATA AP JOURNAL

In [15]:
ap = pd.concat([pd.read_csv(f, sep='\t').assign(file_name=os.path.basename(f)) for f in ap_files])
ap.columns = ap.columns.str.strip().str.lower()
ap.replace('""','', regex=True, inplace=True)
ap['eff_dt'] =  pd.to_datetime(ap['eff_dt']).dt.tz_localize(None)
ap['eff_dt_date'] =  pd.to_datetime(ap['eff_dt']).dt.date
ap['eff_dt_date'] =  pd.to_datetime(ap['eff_dt_date'])
ap['eff_dt_time'] =  pd.to_datetime(ap['eff_dt']).dt.time
ap['movement_day'] = pd.to_datetime(ap['movement_day']).dt.tz_localize(None)
ap['created_at'] = pd.to_datetime(ap['created_at']).dt.tz_localize(None)
ap['created_at_date'] =  pd.to_datetime(ap['created_at']).dt.date
ap['created_at_date'] =  pd.to_datetime(ap['created_at_date'])
ap['request_effective_date'] = pd.to_datetime(ap['request_effective_date']).dt.tz_localize(None)
ap['slot_date'] = pd.to_datetime(ap['slot_date']).dt.tz_localize(None)
ap['identifier'] = ap['source_type'].str[:1].astype(str)
# ap['INDEX'] = (ap['eff_dt_date'].astype(str).replace(' ', '',regex=True)+'-'+
#                ap['identifier'].astype(str).replace(' ', '',regex=True)+'-'+
#                ap['eff_dt_time'].astype(str).replace(' ', '',regex=True))
ap.sort_values(by=(['merchant_id','eff_dt']), ascending=[True,False], inplace=True)
ap.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time,created_at_date,identifier
3,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"-2,874.72",MXN,ARXK7Z9XP,2e17444e-5555-3a8b-99e1-22608168b7fc,DISB_RQ,DISB,2024-01-30 06:29:01,2024-01-30 06:29:06,2024-01-30 06:28:49,2024-01-30 06:06:33,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-30,06:29:06,2024-01-30,D
2,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"2,874.72",MXN,settlement processor regular payment request,54d62474-2e31-42ef-b11a-32abca59c3b6,REGULAR_PYMT_RQ,SETT,2024-01-29 21:09:35,2024-01-30 05:30:00,2024-01-29 21:09:35,2024-01-30 05:00:00,2024-01-30 05:30:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-30,05:30:00,2024-01-29,S
1,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"-2,874.72",MXN,ALH6V3JL8,b86a1190-e950-32e2-a35e-f2a73f39c970,DISB_RQ,DISB,2024-01-02 07:13:11,2024-01-02 07:13:16,2024-01-02 07:13:09,2024-01-02 07:05:30,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-02,07:13:16,2024-01-02,D
0,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"2,874.72",MXN,settlement processor regular payment request,98e7c45d-0f1b-4ea9-a211-773b1a746a85,REGULAR_PYMT_RQ,SETT,2024-01-01 03:59:17,2024-01-02 01:00:00,2024-01-01 03:59:17,2024-01-02 00:30:00,2024-01-02 01:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-02,01:00:00,2024-01-01,S
7,00007725-3116-48dc-9b82-4145699dc290,-958.24,MXN,A6WHZXNT9,cfd169e5-2933-3d1b-88d4-f744a17138cb,DISB_RQ,DISB,2024-01-23 06:26:46,2024-01-23 06:26:51,2024-01-23 06:26:27,2024-01-23 06:06:30,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-23,06:26:51,2024-01-23,D

In [16]:
ap.shape

(21785615, 17)

In [17]:
ap.dtypes

merchant_id                       object
amount                           float64
currency                          object
type_request                      object
mvnt_id                           object
movement_type                     object
source_type                       object
created_at                datetime64[ns]
eff_dt                    datetime64[ns]
movement_day              datetime64[ns]
request_effective_date    datetime64[ns]
slot_date                 datetime64[ns]
file_name                         object
eff_dt_date               datetime64[ns]
eff_dt_time                       object
created_at_date           datetime64[ns]
identifier                        object
dtype: object

In [18]:
sorted(list(ap['source_type'].unique()))

['BILL_PYMNT',
 'CAAL',
 'DATA',
 'DIG_ACC',
 'DISB',
 'FEE_REFUNDS',
 'LOAN',
 'PROMO',
 'PYMT',
 'REFUNDS',
 'RISK',
 'SETT',
 'TAXES',
 'TOPUPS']

In [19]:
ap_bill_pymnt = ap[(ap['source_type'] == 'BILL_PYMNT')]
ap_caal = ap[(ap['source_type'] == 'CAAL')]
ap_data = ap[(ap['source_type'] == 'DATA')]
ap_dig_acc = ap[(ap['source_type'] == 'DIG_ACC')]
ap_disb = ap[(ap['source_type'] == 'DISB')]
ap_fee_refunds = ap[(ap['source_type'] == 'FEE_REFUNDS')]
ap_loan = ap[(ap['source_type'] == 'LOAN')]
ap_promo = ap[(ap['source_type'] == 'PROMO')]
ap_pymt = ap[(ap['source_type'] == 'PYMT')]
ap_refunds = ap[(ap['source_type'] == 'REFUNDS')]
ap_risk = ap[(ap['source_type'] == 'RISK')]
ap_sett = ap[(ap['source_type'] == 'SETT')]
ap_sett_adptr = ap[(ap['source_type'] == 'SETT_ADPTR')]
ap_taxes = ap[(ap['source_type'] == 'TAXES')]
ap_topups = ap[(ap['source_type'] == 'TOPUPS')]

In [20]:
ap_mnf = ap[(ap['eff_dt_date'] >= '2023-01-01')].reset_index(drop=True)
ap_mnf.loc[ap_mnf['source_type'] == 'DISB', 'report_id'] = ap_mnf['type_request']
ap_mnf['report_id'] = ap_mnf['report_id'].groupby(ap_mnf['merchant_id']).ffill()
ap_mnf.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time,created_at_date,identifier,report_id
0,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"-2,874.72",MXN,ARXK7Z9XP,2e17444e-5555-3a8b-99e1-22608168b7fc,DISB_RQ,DISB,2024-01-30 06:29:01,2024-01-30 06:29:06,2024-01-30 06:28:49,2024-01-30 06:06:33,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-30,06:29:06,2024-01-30,D,ARXK7Z9XP
1,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"2,874.72",MXN,settlement processor regular payment request,54d62474-2e31-42ef-b11a-32abca59c3b6,REGULAR_PYMT_RQ,SETT,2024-01-29 21:09:35,2024-01-30 05:30:00,2024-01-29 21:09:35,2024-01-30 05:00:00,2024-01-30 05:30:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-30,05:30:00,2024-01-29,S,ARXK7Z9XP
2,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"-2,874.72",MXN,ALH6V3JL8,b86a1190-e950-32e2-a35e-f2a73f39c970,DISB_RQ,DISB,2024-01-02 07:13:11,2024-01-02 07:13:16,2024-01-02 07:13:09,2024-01-02 07:05:30,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-02,07:13:16,2024-01-02,D,ALH6V3JL8
3,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"2,874.72",MXN,settlement processor regular payment request,98e7c45d-0f1b-4ea9-a211-773b1a746a85,REGULAR_PYMT_RQ,SETT,2024-01-01 03:59:17,2024-01-02 01:00:00,2024-01-01 03:59:17,2024-01-02 00:30:00,2024-01-02 01:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-02,01:00:00,2024-01-01,S,ALH6V3JL8
4,00007725-3116-48dc-9b82-4145699dc290,-958.24,MXN,A6WHZXNT9,cfd169e5-2933-3d1b-88d4-f744a17138cb,DISB_RQ,DISB,2024-01-23 06:26:46,2024-01-23 06:26:51,2024-01-23 06:26:27,2024-01-23 06:06:30,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-23,06:26:51,2024-01-23,D,A6WHZXNT9

In [21]:
ap_mnf.shape

(21785615, 18)

In [27]:
ap_mnf_sett = ap_mnf[(ap_mnf['source_type'] == 'SETT')]
ap_mnf_sett.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time,created_at_date,identifier,report_id
1,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"2,874.72",MXN,settlement processor regular payment request,54d62474-2e31-42ef-b11a-32abca59c3b6,REGULAR_PYMT_RQ,SETT,2024-01-29 21:09:35,2024-01-30 05:30:00,2024-01-29 21:09:35,2024-01-30 05:00:00,2024-01-30 05:30:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-30,05:30:00,2024-01-29,S,ARXK7Z9XP
3,0000275f-d46b-4a9c-a227-42d6f7ce63bd,"2,874.72",MXN,settlement processor regular payment request,98e7c45d-0f1b-4ea9-a211-773b1a746a85,REGULAR_PYMT_RQ,SETT,2024-01-01 03:59:17,2024-01-02 01:00:00,2024-01-01 03:59:17,2024-01-02 00:30:00,2024-01-02 01:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-02,01:00:00,2024-01-01,S,ALH6V3JL8
5,00007725-3116-48dc-9b82-4145699dc290,958.24,MXN,settlement processor regular payment request,b87ada5c-b33d-4c76-b3be-58255c264a38,REGULAR_PYMT_RQ,SETT,2024-01-22 12:09:45,2024-01-23 03:30:00,2024-01-22 12:09:45,2024-01-23 03:00:00,2024-01-23 03:30:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-23,03:30:00,2024-01-22,S,A6WHZXNT9
7,00007725-3116-48dc-9b82-4145699dc290,958.24,MXN,settlement processor regular payment request,f9429f46-4936-4b74-840d-8cfeaeeaf0ad,REGULAR_PYMT_RQ,SETT,2024-01-20 12:29:55,2024-01-21 03:30:00,2024-01-20 12:29:55,2024-01-21 03:00:00,2024-01-21 03:30:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-21,03:30:00,2024-01-20,S,ACN2XQ5PN
9,00008e01-812f-487e-8f34-a80bcb0ae3e3,"19,294.12",MXN,settlement processor regular payment request,b076821b-f2fa-4bd6-8752-e6c12cd19816,REGULAR_PYMT_RQ,SETT,2024-01-16 12:43:04,2024-01-17 03:30:00,2024-01-16 12:43:04,2024-01-17 03:00:00,2024-01-17 03:30:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-17,03:30:00,2024-01-16,S,A2RVSXTZY

In [28]:
ap_mnf_sett.shape

(16994623, 18)

In [29]:
ap_mnf_canc = ap_mnf[(ap_mnf['movement_type'] == 'CANCEL_RQ')]
ap_mnf_canc.head()

,merchant_id,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time,created_at_date,identifier,report_id
16,00008e01-812f-487e-8f34-a80bcb0ae3e3,"-47,912.00",MXN,cancel request,89642c1b-ee74-48a9-a7f4-39f9a6e54aec,CANCEL_RQ,PYMT,2024-01-14 19:15:43,2024-01-15 04:30:00,2024-01-14 19:15:43,2024-01-15 04:30:00,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-15,04:30:00,2024-01-14,P,AJY6HGG8N
1784,000cd34d-55cf-4955-814c-97788df1ab9b,"-6,190.23",MXN,cancel request,c4293d6c-d0d9-4613-b72b-e1835e7d11bc,CANCEL_RQ,PYMT,2024-01-25 13:22:56,2024-01-26 03:00:00,2024-01-25 13:22:56,2024-01-26 03:00:00,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-26,03:00:00,2024-01-25,P,ARMR2HS47
1785,000cd34d-55cf-4955-814c-97788df1ab9b,"-6,190.23",MXN,cancel request,fea82120-39e8-4cf8-b349-d5766117c3f0,CANCEL_RQ,PYMT,2024-01-25 13:23:27,2024-01-26 03:00:00,2024-01-25 13:23:27,2024-01-26 03:00:00,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-26,03:00:00,2024-01-25,P,ARMR2HS47
1786,000cd34d-55cf-4955-814c-97788df1ab9b,"-6,190.23",MXN,cancel request,7191c444-72a2-4c50-a560-65291a6a8390,CANCEL_RQ,PYMT,2024-01-25 13:24:11,2024-01-26 03:00:00,2024-01-25 13:24:11,2024-01-26 03:00:00,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-26,03:00:00,2024-01-25,P,ARMR2HS47
2509,000e8d30-1145-40ef-a265-d347f27e4d87,"-3,353.84",MXN,cancel request,48317244-91a0-48de-8c90-374b6fa6c6d1,CANCEL_RQ,PYMT,2024-01-14 17:19:54,2024-01-15 04:00:00,2024-01-14 17:19:54,2024-01-15 04:00:00,1969-12-31 18:00:00,AP-JOURNAL_DATE ENERO 2024.tsv,2024-01-15,04:00:00,2024-01-14,P,A5HY6TXYW

In [30]:
ap_mnf_canc.shape

(25968, 18)

In [31]:
ap_mnf_canc['source_type'].unique()

array(['PYMT', 'RISK'], dtype=object)

## CRUCE 1: SML VS AP JOURNAL - TRANSACCIONES

In [43]:
cruce_1 = sml_mnf.merge(ap_mnf_sett[['mvnt_id','report_id','eff_dt_date','eff_dt_time','movement_type']],on='mvnt_id',how='left')
cruce_1['report_id'].fillna('not_found',inplace=True)
cruce_1.rename(columns={'psp_amount':'psp_amount_sett','gross_amount':'gross_amount_sett','fees':'fees_sett',
                                'taxes':'taxes_sett','net_amount':'net_amount_sett'},inplace=True)
cruce_1.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount_sett,gross_amount_sett,...,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date_x,report_id,eff_dt_date_y,eff_dt_time,movement_type
0,9c3c7bcc-9b5d-5f62-b9ee-deed4a2409e9,51503fff-9f23-4913-898b-3f1cc5a61d24,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:12:00,2024-02-01 05:30:00,"1,568.00","1,568.00",...,Paid,uV7iU6G,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,ASJQ6WXLY,2024-02-01,06:00:00,REGULAR_PYMT_RQ
1,57b8ffe6-dd0b-5964-90ec-c016beb0c706,f17144bb-40f1-49d9-9d00-4c41180a7cac,32fd9623-b69b-499f-96d7-28ed55e31193,32fd9623-b69b-499f-96d7-28ed55e31193,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:24:30,2024-02-01 05:30:00,"1,000.00","1,000.00",...,Paid,jJyU6ak,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,AZ4HJWJ2S,2024-02-01,06:00:00,REGULAR_PYMT_RQ
2,b1265364-a563-5e0b-b920-7ad49bd23a20,259a0282-b016-49ed-b1f3-bd0c6639e00c,7156f1fb-2eea-4956-b9da-16b33bbd567b,7156f1fb-2eea-4956-b9da-16b33bbd567b,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:53:33,2024-02-01 05:30:00,290.00,290.00,...,Paid,69tgkTl,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,AD927H8H6,2024-02-01,06:00:00,REGULAR_PYMT_RQ
3,85e52ecd-6c0b-5857-aebd-b1776aec201b,8261d5da-dd20-45a1-8471-e1a7d9b991eb,fe2fc574-e23f-40e6-afda-07f3e730852d,fe2fc574-e23f-40e6-afda-07f3e730852d,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:34:18,2024-02-01 05:30:00,735.00,735.00,...,Paid,9k7qHW2,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,AX5X64QLM,2024-02-01,06:00:00,REGULAR_PYMT_RQ
4,b220134d-8e71-5fb4-bd4c-a77de0f2276d,687a1551-6937-4a6a-aac4-487bf3999cca,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:58:56,2024-02-01 05:30:00,19.00,19.00,...,Paid,coBcBI3,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,APYSDYMVD,2024-02-01,06:00:00,REGULAR_PYMT_RQ

In [44]:
cruce_1.shape

(544777, 27)

In [45]:
cruce_1['movement_type'].unique()

array(['REGULAR_PYMT_RQ', 'FAST_PYMT_RQ', 'DEFERRED_REGULAR_PYMNT_RQ'],
      dtype=object)

## CRUCE 2: SML VS AP JOURNAL - CANCELACIONES

In [48]:
cruce_2 = sml_mnf.merge(ap_mnf_canc[['mvnt_id','report_id','eff_dt_date','eff_dt_time','movement_type']],on='mvnt_id',how='left')
cruce_2['report_id'].fillna('not_found',inplace=True)
cruce_2['movement_type'].fillna('not_found',inplace=True)
cruce_2.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date_x,report_id,eff_dt_date_y,eff_dt_time,movement_type
0,9c3c7bcc-9b5d-5f62-b9ee-deed4a2409e9,51503fff-9f23-4913-898b-3f1cc5a61d24,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:12:00,2024-02-01 05:30:00,"1,568.00","1,568.00",...,Paid,uV7iU6G,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,NaT,NaN,not_found
1,57b8ffe6-dd0b-5964-90ec-c016beb0c706,f17144bb-40f1-49d9-9d00-4c41180a7cac,32fd9623-b69b-499f-96d7-28ed55e31193,32fd9623-b69b-499f-96d7-28ed55e31193,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:24:30,2024-02-01 05:30:00,"1,000.00","1,000.00",...,Paid,jJyU6ak,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,NaT,NaN,not_found
2,b1265364-a563-5e0b-b920-7ad49bd23a20,259a0282-b016-49ed-b1f3-bd0c6639e00c,7156f1fb-2eea-4956-b9da-16b33bbd567b,7156f1fb-2eea-4956-b9da-16b33bbd567b,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:53:33,2024-02-01 05:30:00,290.00,290.00,...,Paid,69tgkTl,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,NaT,NaN,not_found
3,85e52ecd-6c0b-5857-aebd-b1776aec201b,8261d5da-dd20-45a1-8471-e1a7d9b991eb,fe2fc574-e23f-40e6-afda-07f3e730852d,fe2fc574-e23f-40e6-afda-07f3e730852d,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:34:18,2024-02-01 05:30:00,735.00,735.00,...,Paid,9k7qHW2,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,NaT,NaN,not_found
4,b220134d-8e71-5fb4-bd4c-a77de0f2276d,687a1551-6937-4a6a-aac4-487bf3999cca,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:58:56,2024-02-01 05:30:00,19.00,19.00,...,Paid,coBcBI3,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,NaT,NaN,not_found

In [49]:
cruce_2.shape

(544777, 27)

In [50]:
cruce_2['movement_type'].unique()

array(['not_found', 'CANCEL_RQ'], dtype=object)

In [51]:
cruce_2_canc = cruce_2[(cruce_2['movement_type'] == 'CANCEL_RQ')]
cruce_2_canc.rename(columns={'psp_amount':'psp_amount_pymt','gross_amount':'gross_amount_pymt','fees':'fees_pymt',
                             'taxes':'taxes_pymt','net_amount':'net_amount_pymt'},inplace=True)
cruce_2_canc.head()

C:\Users\Cristian.Aparicio\AppData\Local\Temp\ipykernel_16248\2353346342.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cruce_2_canc.rename(columns={'psp_amount':'psp_amount_pymt','gross_amount':'gross_amount_pymt','fees':'fees_pymt',

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount_pymt,gross_amount_pymt,...,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date_x,report_id,eff_dt_date_y,eff_dt_time,movement_type
1188,bcd22e16-8fab-55e2-9e52-4984edb72597,7be4c4df-32f6-4aef-b76b-721557b4d3ed,643fa910-ba8c-457d-be98-2b246abebc55,643fa910-ba8c-457d-be98-2b246abebc55,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 22:34:28,2024-02-01 05:30:00,125.00,125.00,...,Cancelled,liRBcIr,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,ANBQ44RLN,2024-02-01,05:30:00,CANCEL_RQ
3871,73e10cfc-b468-5d9f-a4ba-6449dc581428,147383e4-1cb7-485a-b372-902be43bdef3,76e5eb2c-2a05-4bbe-a3c0-cf3d3aa612f2,76e5eb2c-2a05-4bbe-a3c0-cf3d3aa612f2,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 21:24:06,2024-02-01 05:00:00,"6,300.00","6,300.00",...,Cancelled,RvGvkkU,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,2024-02-01,05:00:00,CANCEL_RQ
5314,758ff34d-29d8-56d9-8435-85283db7bf39,7128dfcf-577a-4ee2-bd63-30f539f78633,4d5777fb-4844-49f8-91df-7104e3cbc146,4d5777fb-4844-49f8-91df-7104e3cbc146,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 21:47:49,2024-02-01 05:00:00,116.00,116.00,...,Cancelled. Cardholder initiated.,suxb8ik,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,A53CG6ZYZ,2024-02-01,05:00:00,CANCEL_RQ
6656,6d67b9f6-34cc-5a67-874e-ef72815f5b16,f5cff2a3-ea12-43e5-82f9-1440b59a03d7,1bbf53c4-ddcf-4a1d-82b8-45838b1a167c,1bbf53c4-ddcf-4a1d-82b8-45838b1a167c,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 21:48:57,2024-02-01 05:00:00,803.00,803.00,...,Cancelled,iGPuPXb,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,ABHLQ8D8C,2024-02-01,05:00:00,CANCEL_RQ
8471,0f9e41e9-0a08-5bf7-9691-115fc6c783de,b12f0fe6-1462-4a81-8dca-ea6e31627964,cd9cadfe-ccdb-46b6-a39b-a08c8d6790fc,cd9cadfe-ccdb-46b6-a39b-a08c8d6790fc,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 21:14:48,2024-02-01 05:00:00,324.00,324.00,...,Cancelled. Cardholder initiated.,63Kw9X9,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,ATBCC2TB3,2024-02-01,05:00:00,CANCEL_RQ

In [52]:
cruce_2_canc.shape

(792, 27)

## CRUCE FINAL: RESTAR CANCELACIONES DE TRANSACCIONES

In [53]:
cruce_3 = cruce_1.merge(cruce_2_canc[['mvnt_id','psp_amount_pymt','gross_amount_pymt','fees_pymt','taxes_pymt',
                                                             'net_amount_pymt']],on='mvnt_id',how='left')
cruce_3.fillna(0,inplace=True)
cruce_3['psp_amount'] = cruce_3['psp_amount_sett'] - cruce_3['psp_amount_pymt'] 
cruce_3['gross_amount'] = cruce_3['gross_amount_sett'] - cruce_3['gross_amount_pymt'] 
cruce_3['fees'] = cruce_3['fees_sett'] - cruce_3['fees_pymt'] 
cruce_3['taxes'] = cruce_3['taxes_sett'] - cruce_3['taxes_pymt'] 
cruce_3['net_amount'] = cruce_3['net_amount_sett'] - cruce_3['net_amount_pymt']
cruce_3.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount_sett,gross_amount_sett,...,psp_amount_pymt,gross_amount_pymt,fees_pymt,taxes_pymt,net_amount_pymt,psp_amount,gross_amount,fees,taxes,net_amount
0,9c3c7bcc-9b5d-5f62-b9ee-deed4a2409e9,51503fff-9f23-4913-898b-3f1cc5a61d24,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:12:00,2024-02-01 05:30:00,"1,568.00","1,568.00",...,0.00,0.00,0.00,0.00,0.00,"1,568.00","1,568.00",56.45,9.03,"1,502.52"
1,57b8ffe6-dd0b-5964-90ec-c016beb0c706,f17144bb-40f1-49d9-9d00-4c41180a7cac,32fd9623-b69b-499f-96d7-28ed55e31193,32fd9623-b69b-499f-96d7-28ed55e31193,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:24:30,2024-02-01 05:30:00,"1,000.00","1,000.00",...,0.00,0.00,0.00,0.00,0.00,"1,000.00","1,000.00",36.00,5.76,958.24
2,b1265364-a563-5e0b-b920-7ad49bd23a20,259a0282-b016-49ed-b1f3-bd0c6639e00c,7156f1fb-2eea-4956-b9da-16b33bbd567b,7156f1fb-2eea-4956-b9da-16b33bbd567b,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:53:33,2024-02-01 05:30:00,290.00,290.00,...,0.00,0.00,0.00,0.00,0.00,290.00,290.00,10.44,1.67,277.89
3,85e52ecd-6c0b-5857-aebd-b1776aec201b,8261d5da-dd20-45a1-8471-e1a7d9b991eb,fe2fc574-e23f-40e6-afda-07f3e730852d,fe2fc574-e23f-40e6-afda-07f3e730852d,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:34:18,2024-02-01 05:30:00,735.00,735.00,...,0.00,0.00,0.00,0.00,0.00,735.00,735.00,26.46,4.23,704.31
4,b220134d-8e71-5fb4-bd4c-a77de0f2276d,687a1551-6937-4a6a-aac4-487bf3999cca,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:58:56,2024-02-01 05:30:00,19.00,19.00,...,0.00,0.00,0.00,0.00,0.00,19.00,19.00,0.68,0.11,18.21

In [54]:
cruce_3.shape

(544777, 37)

In [56]:
cruce_3_report_id_found = cruce_3[(cruce_3['report_id'] != 'not_found')]
cruce_3_report_id_found.shape

(544547, 37)

In [57]:
cruce_3_report_id_not_found = cruce_3[(cruce_3['report_id'] == 'not_found')]
cruce_3_report_id_not_found.shape

(230, 37)

In [58]:
writer = pd.ExcelWriter('Monto_no_facturado_ledger_enero_2024.xlsx VF.xlsx',
                        engine='xlsxwriter',
                        engine_kwargs={'options': {'encoding':'utf-8'}})
cruce_3.to_excel(writer, sheet_name='TRANSACCIONES FINAL')
cruce_1.to_excel(writer, sheet_name='TRANSACCIONES REGULARES')
cruce_2_canc.to_excel(writer, sheet_name='CANCELACIONES')
#cruce_not_found_pymt.to_excel(writer, sheet_name='PYMT')
writer.close()

# CRUCE: IDENTIFICACION DE REPORT_ID

In [22]:
cruce_1 = sml_mnf.merge(ap_mnf[['mvnt_id','report_id','eff_dt_date','eff_dt_time','movement_type']],on='mvnt_id',how='left')
cruce_1['report_id'].fillna('not_found',inplace=True)
cruce_1.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date_x,report_id,eff_dt_date_y,eff_dt_time,movement_type
0,9c3c7bcc-9b5d-5f62-b9ee-deed4a2409e9,51503fff-9f23-4913-898b-3f1cc5a61d24,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,88667ebc-5499-4c51-b1c3-fd2633cdf6f4,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:12:00,2024-02-01 05:30:00,"1,568.00","1,568.00",...,Paid,uV7iU6G,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,ASJQ6WXLY,2024-02-01,06:00:00,REGULAR_PYMT_RQ
1,57b8ffe6-dd0b-5964-90ec-c016beb0c706,f17144bb-40f1-49d9-9d00-4c41180a7cac,32fd9623-b69b-499f-96d7-28ed55e31193,32fd9623-b69b-499f-96d7-28ed55e31193,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:24:30,2024-02-01 05:30:00,"1,000.00","1,000.00",...,Paid,jJyU6ak,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,AZ4HJWJ2S,2024-02-01,06:00:00,REGULAR_PYMT_RQ
2,b1265364-a563-5e0b-b920-7ad49bd23a20,259a0282-b016-49ed-b1f3-bd0c6639e00c,7156f1fb-2eea-4956-b9da-16b33bbd567b,7156f1fb-2eea-4956-b9da-16b33bbd567b,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:53:33,2024-02-01 05:30:00,290.00,290.00,...,Paid,69tgkTl,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,AD927H8H6,2024-02-01,06:00:00,REGULAR_PYMT_RQ
3,85e52ecd-6c0b-5857-aebd-b1776aec201b,8261d5da-dd20-45a1-8471-e1a7d9b991eb,fe2fc574-e23f-40e6-afda-07f3e730852d,fe2fc574-e23f-40e6-afda-07f3e730852d,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:34:18,2024-02-01 05:30:00,735.00,735.00,...,Paid,9k7qHW2,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,AX5X64QLM,2024-02-01,06:00:00,REGULAR_PYMT_RQ
4,b220134d-8e71-5fb4-bd4c-a77de0f2276d,687a1551-6937-4a6a-aac4-487bf3999cca,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,7b3ff108-92eb-4d6e-b20b-53f29d02cebf,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 23:58:56,2024-02-01 05:30:00,19.00,19.00,...,Paid,coBcBI3,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,APYSDYMVD,2024-02-01,06:00:00,REGULAR_PYMT_RQ

In [23]:
cruce_1.shape

(545569, 27)

In [24]:
cruce_1_not_found = cruce_1[(cruce_1['report_id'] == 'not_found')]
cruce_1_not_found.head()

,record_uuid,merchant_id,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,gross_amount,...,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date_x,report_id,eff_dt_date_y,eff_dt_time,movement_type
1161,264efbd6-cb7e-5253-948c-aef9663bf218,7101f1ba-c408-432c-ad17-b9b5d3b2ddcd,6e37bad3-9da0-4fc2-b228-32ac21badbb4,6e37bad3-9da0-4fc2-b228-32ac21badbb4,STL_PCS_RQ,DIGITAL_ACCOUNT,2024-01-31 22:11:00,2024-02-01 22:00:00,130.00,130.00,...,Paid,m2z8LvG,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,2024-02-01,22:30:00,REGULAR_PYMT_RQ
3872,73e10cfc-b468-5d9f-a4ba-6449dc581428,147383e4-1cb7-485a-b372-902be43bdef3,76e5eb2c-2a05-4bbe-a3c0-cf3d3aa612f2,76e5eb2c-2a05-4bbe-a3c0-cf3d3aa612f2,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 21:24:06,2024-02-01 05:00:00,"6,300.00","6,300.00",...,Cancelled,RvGvkkU,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,2024-02-01,05:30:00,REGULAR_PYMT_RQ
3873,73e10cfc-b468-5d9f-a4ba-6449dc581428,147383e4-1cb7-485a-b372-902be43bdef3,76e5eb2c-2a05-4bbe-a3c0-cf3d3aa612f2,76e5eb2c-2a05-4bbe-a3c0-cf3d3aa612f2,STL_PCS_RQ,REGULAR_PAYMENT,2024-01-31 21:24:06,2024-02-01 05:00:00,"6,300.00","6,300.00",...,Cancelled,RvGvkkU,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,2024-02-01,05:00:00,CANCEL_RQ
10802,561d71f5-33d4-5d8d-a8b3-851d598b835e,f653b7ac-3210-4245-b4b1-4495c026f6fa,67398071-3bd0-4a84-b8bd-750a7f6e1870,67398071-3bd0-4a84-b8bd-750a7f6e1870,STL_PCS_RQ,DIGITAL_ACCOUNT,2024-01-31 22:17:10,2024-02-01 22:00:00,500.00,500.00,...,Paid,9c9BgKq,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,2024-02-01,22:30:00,REGULAR_PYMT_RQ
12776,6220a6ad-1216-5709-b601-59c379dfa0cf,7609756f-69ee-4545-ad30-d8e2bbb6f71e,7b75c1bf-8cdd-416e-868e-885919ddb1c7,7b75c1bf-8cdd-416e-868e-885919ddb1c7,STL_PCS_RQ,DIGITAL_ACCOUNT,2024-01-31 21:56:59,2024-02-01 21:00:00,17.80,17.80,...,Paid,FV6cqcI,PAYMENT,SML MONTO NO FACTURADO ENERO 2024.csv,2024-01-31,2024-02-01,not_found,2024-02-01,21:30:00,REGULAR_PYMT_RQ

In [25]:
cruce_1_not_found.shape

(332, 27)

In [26]:
cruce_1.to_excel('Monto_no_facturado_ledger_enero_2024.xlsx',index=False)