In [1]:
import pandas as pd
import numpy as np
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# RUTAS

### SETTLEMENT MASTER LOG

In [3]:
sml_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\DETALLE ME\DATA DB\SETTLEMENT*.csv', recursive=False)
sml_files

['C:\\Users\\Cristian.Aparicio\\Documents\\DETALLE ME\\DATA DB\\SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S.A DE C.V.csv']

### AP JOURNAL

In [4]:
ap_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\DETALLE ME\DATA DB\AP*.csv', recursive=False)
ap_files

['C:\\Users\\Cristian.Aparicio\\Documents\\DETALLE ME\\DATA DB\\AP-JOURNAL_MERCHANT_ID COPPEL S.A DE C.V.csv']

# DATA SETTLEMENT MASTER LOG

In [5]:
sml = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in sml_files])
sml.columns = sml.columns.str.strip().str.lower()
sml.replace('""','', regex=True, inplace=True)
sml['created_at'] = pd.to_datetime(sml['created_at']).dt.tz_localize(None)
sml['created_at_date'] =  pd.to_datetime(sml['created_at']).dt.date
sml['created_at_date'] =  pd.to_datetime(sml['created_at_date'])
sml['eff_dt'] = pd.to_datetime(sml['eff_dt']).dt.tz_localize(None)
sml['eff_dt_date'] =  pd.to_datetime(sml['eff_dt']).dt.date
sml['eff_dt_date'] =  pd.to_datetime(sml['eff_dt_date'])
sml.rename(columns={'ref_id':'transaction_id'},inplace=True)
#sml['PK'] = sml['PK'].replace('M#','',inplace=True)
sml.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,461f6516-0cad-510f-8647-a08cb91c03d8,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,50f5c96a-8d20-4302-b97c-96a0090a3dd5,50f5c96a-8d20-4302-b97c-96a0090a3dd5,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-14 09:55:54,2023-06-15 02:00:00,324.00,...,0.02,0.00,0.00,1,Paid,S73SYgh,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-06-14,2023-06-15
1,82a232b4-43d8-544c-b413-d4e859a732a2,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,d5ac34d7-4f1d-47d8-a744-75331c98bb94,d5ac34d7-4f1d-47d8-a744-75331c98bb94,STL_PCS_RQ,REGULAR_PAYMENT,2023-04-19 15:13:37,2023-04-20 03:30:00,10.00,...,0.02,0.00,0.00,1,Paid,1H5v9oi,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-04-19,2023-04-20
2,1479e1f0-f7a8-5569-a3a4-8c5ef29bf8f1,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,91071e74-d7bb-4fa4-b66b-15f5a71daf03,91071e74-d7bb-4fa4-b66b-15f5a71daf03,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-29 13:33:19,2023-05-30 03:00:00,"4,783.00",...,0.02,0.00,0.00,1,Paid,wKD2Ot9,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-05-29,2023-05-30
3,a873bf4c-c930-5e0f-bc57-b3b668b0a99b,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,7c023bf7-bc4c-4a67-a81a-74b27ac894e0,7c023bf7-bc4c-4a67-a81a-74b27ac894e0,STL_PCS_RQ,REGULAR_PAYMENT,2023-07-24 15:24:48,2023-07-25 03:30:00,500.00,...,0.02,0.00,0.00,1,Paid,9aiJtMy,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-07-24,2023-07-25
4,18d1281b-965a-588e-830a-29641801cfa8,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,10d06f88-8700-47b5-adfb-4708f598398a,10d06f88-8700-47b5-adfb-4708f598398a,STL_PCS_RQ,REGULAR_PAYMENT,2023-03-30 16:36:05,2023-03-31 04:00:00,801.00,...,0.02,0.00,0.00,1,Paid,JqQrwmE,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-03-30,2023-03-31

In [6]:
sml.shape

(92972, 24)

In [7]:
sml.dtypes

record_uuid                object
merchant_id                object
merchant_name              object
transaction_id             object
mvnt_id                    object
mvnt_type                  object
pymt_prg                   object
created_at         datetime64[ns]
eff_dt             datetime64[ns]
psp_amount                float64
gross_amount              float64
fees                      float64
taxes                     float64
net_amount                float64
mdr                       float64
msi                       float64
number_msi                float64
status_code                 int64
status_msg                 object
receipt_no                 object
type                       object
file_name                  object
created_at_date    datetime64[ns]
eff_dt_date        datetime64[ns]
dtype: object

In [8]:
sml_final = sml[(sml['mvnt_type'] == 'STL_PCS_RQ')]
sml_final.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,461f6516-0cad-510f-8647-a08cb91c03d8,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,50f5c96a-8d20-4302-b97c-96a0090a3dd5,50f5c96a-8d20-4302-b97c-96a0090a3dd5,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-14 09:55:54,2023-06-15 02:00:00,324.00,...,0.02,0.00,0.00,1,Paid,S73SYgh,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-06-14,2023-06-15
1,82a232b4-43d8-544c-b413-d4e859a732a2,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,d5ac34d7-4f1d-47d8-a744-75331c98bb94,d5ac34d7-4f1d-47d8-a744-75331c98bb94,STL_PCS_RQ,REGULAR_PAYMENT,2023-04-19 15:13:37,2023-04-20 03:30:00,10.00,...,0.02,0.00,0.00,1,Paid,1H5v9oi,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-04-19,2023-04-20
2,1479e1f0-f7a8-5569-a3a4-8c5ef29bf8f1,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,91071e74-d7bb-4fa4-b66b-15f5a71daf03,91071e74-d7bb-4fa4-b66b-15f5a71daf03,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-29 13:33:19,2023-05-30 03:00:00,"4,783.00",...,0.02,0.00,0.00,1,Paid,wKD2Ot9,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-05-29,2023-05-30
3,a873bf4c-c930-5e0f-bc57-b3b668b0a99b,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,7c023bf7-bc4c-4a67-a81a-74b27ac894e0,7c023bf7-bc4c-4a67-a81a-74b27ac894e0,STL_PCS_RQ,REGULAR_PAYMENT,2023-07-24 15:24:48,2023-07-25 03:30:00,500.00,...,0.02,0.00,0.00,1,Paid,9aiJtMy,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-07-24,2023-07-25
4,18d1281b-965a-588e-830a-29641801cfa8,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,10d06f88-8700-47b5-adfb-4708f598398a,10d06f88-8700-47b5-adfb-4708f598398a,STL_PCS_RQ,REGULAR_PAYMENT,2023-03-30 16:36:05,2023-03-31 04:00:00,801.00,...,0.02,0.00,0.00,1,Paid,JqQrwmE,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-03-30,2023-03-31

In [9]:
sml_final.shape

(92972, 24)

# DATA AP JOURNAL

In [10]:
ap = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in ap_files])
ap.columns = ap.columns.str.strip().str.lower()
ap.replace('""','', regex=True, inplace=True)
ap['eff_dt'] =  pd.to_datetime(ap['eff_dt']).dt.tz_localize(None)
ap['eff_dt_date'] =  pd.to_datetime(ap['eff_dt']).dt.date
ap['eff_dt_date'] =  pd.to_datetime(ap['eff_dt_date'])
ap['eff_dt_time'] =  pd.to_datetime(ap['eff_dt']).dt.time
ap['movement_day'] = pd.to_datetime(ap['movement_day']).dt.tz_localize(None)
ap['created_at'] = pd.to_datetime(ap['created_at']).dt.tz_localize(None)
ap['created_at_date'] =  pd.to_datetime(ap['created_at']).dt.date
ap['created_at_date'] =  pd.to_datetime(ap['created_at_date'])
ap['request_effective_date'] = pd.to_datetime(ap['request_effective_date']).dt.tz_localize(None)
ap['slot_date'] = pd.to_datetime(ap['slot_date']).dt.tz_localize(None)
ap['identifier'] = ap['source_type'].str[:1].astype(str)
ap['INDEX'] = (ap['eff_dt_date'].astype(str).replace(' ', '',regex=True)+'-'+
               ap['identifier'].astype(str).replace(' ', '',regex=True)+'-'+
               ap['eff_dt_time'].astype(str).replace(' ', '',regex=True))
ap.sort_values(by=(['merchant_id','eff_dt']), ascending=[True,False], inplace=True)

In [11]:
ap.loc[ap['source_type'] == 'DISB', 'report_id'] = ap['type_request']
ap['report_id'] = ap['report_id'].groupby(ap['merchant_id']).fillna(method='ffill')
ap.head()

,merchant_id,merchant_name,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time,created_at_date,identifier,INDEX,report_id
93283,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,243.33,MXN,settlement processor regular payment request,b9189c7f-b3ae-4d5e-9e88-ded8b6556d57,REGULAR_PYMT_RQ,SETT,2023-07-31 10:00:10,2023-08-01 03:00:00,2023-07-31 10:00:10,2023-08-01 02:30:00,2023-08-01 03:00:00,AP-JOURNAL_MERCHANT_ID COPPEL S.A DE C.V.csv,2023-08-01,03:00:00,2023-07-31,S,2023-08-01-S-03:00:00,NaN
93284,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,"3,685.96",MXN,settlement processor regular payment request,283e50b0-fe9f-46a1-9a67-fb27db038710,REGULAR_PYMT_RQ,SETT,2023-07-31 10:00:30,2023-08-01 03:00:00,2023-07-31 10:00:30,2023-08-01 02:30:00,2023-08-01 03:00:00,AP-JOURNAL_MERCHANT_ID COPPEL S.A DE C.V.csv,2023-08-01,03:00:00,2023-07-31,S,2023-08-01-S-03:00:00,NaN
93285,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,688.14,MXN,settlement processor regular payment request,3c0d1d9b-1afa-42ed-9156-a2a0a336d1ab,REGULAR_PYMT_RQ,SETT,2023-07-31 10:01:00,2023-08-01 03:00:00,2023-07-31 10:01:00,2023-08-01 02:30:00,2023-08-01 03:00:00,AP-JOURNAL_MERCHANT_ID COPPEL S.A DE C.V.csv,2023-08-01,03:00:00,2023-07-31,S,2023-08-01-S-03:00:00,NaN
93286,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,789.37,MXN,settlement processor regular payment request,011750de-ae13-424b-b0e0-1000166cf78d,REGULAR_PYMT_RQ,SETT,2023-07-31 10:01:32,2023-08-01 03:00:00,2023-07-31 10:01:32,2023-08-01 02:30:00,2023-08-01 03:00:00,AP-JOURNAL_MERCHANT_ID COPPEL S.A DE C.V.csv,2023-08-01,03:00:00,2023-07-31,S,2023-08-01-S-03:00:00,NaN
93287,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,698.85,MXN,settlement processor regular payment request,02209b74-dba9-4666-94f0-9f76e4b56fa9,REGULAR_PYMT_RQ,SETT,2023-07-31 10:01:40,2023-08-01 03:00:00,2023-07-31 10:01:40,2023-08-01 02:30:00,2023-08-01 03:00:00,AP-JOURNAL_MERCHANT_ID COPPEL S.A DE C.V.csv,2023-08-01,03:00:00,2023-07-31,S,2023-08-01-S-03:00:00,NaN

In [12]:
ap.shape

(93335, 20)

In [13]:
ap.dtypes

merchant_id                       object
merchant_name                     object
amount                           float64
currency                          object
type_request                      object
mvnt_id                           object
movement_type                     object
source_type                       object
created_at                datetime64[ns]
eff_dt                    datetime64[ns]
movement_day              datetime64[ns]
request_effective_date    datetime64[ns]
slot_date                 datetime64[ns]
file_name                         object
eff_dt_date               datetime64[ns]
eff_dt_time                       object
created_at_date           datetime64[ns]
identifier                        object
INDEX                             object
report_id                         object
dtype: object

In [15]:
ap['report_id'].unique()

array([nan, 'ABR8NVRLP', 'A4J4HCQF9', 'AQMJPZZ9Y', 'ALRGS6SCW',
       'AY7C97RLC', 'AKZRDGFYV', 'ABD3GG9MD', 'A4B7KSY6R', 'APPLNRS5D',
       'AQ592D3WW', 'ALNGHVNZL', 'A88XP888Z', 'ANJC9HPFN', 'AT8CCPQZK',
       'AS438BMDF', 'A59KLGJBG', 'ARNBWQFM7', 'A5X8BDX3K', 'A9BWGB8XK',
       'AWJYHXRCJ', 'AN79427FB', 'A3CWD2H53', 'AYZ6PRF6Y', 'A7P3P87ZF',
       'A3QGV644P', 'AQQXFD522', 'APSPGYCVT', 'AFP2PCVP4', 'AFQS8PX9M',
       'AW8RT5TCP', 'AM2RQVHDS', 'AJNKLCP95', 'A9KPKPSWJ', 'AC655T5HT',
       'AGQ2C8HJ9', 'A5GRSTTGW', 'A6M6J3B6P', 'ADQHG56YX', 'AZQ5WYXM3',
       'A2KVV72LG', 'AM6P5D74Z', 'AN8594BR7', 'AZ7LYZK2T', 'AJ34V9CWT',
       'A2ZG4G85V', 'AQ2Z8B37T', 'ALMPNXL6P', 'A4X7Y7ZBC', 'A2VKWH6PT',
       'A4HWXZN52', 'A8KPCGBWR', 'AG6CZH36L', 'AV4LYLHNL', 'AVHXNT36M',
       'AH2BJ8H62', 'AM6QJFWN4', 'ARKSJF99H', 'APTM5DBDB', 'A27PFX37G',
       'AQMZQY5Q5', 'AFK4FXK4W', 'AGMYQW2T5', 'A8B87NFJL', 'AL7JBTLN8',
       'AF5LZRKFV', 'AH33H77F6', 'AMRB33DT3', 'ADPPGHC3H', 'A47SJRHVW',
       'ATJ8TSVJG', 'AHN5F35GF', 'A9JPTS22L', 'A84MH6PVV', 'AFZKP2QYR',
       'AMCZVRD6M', 'AWFVR5WGT', 'A248GFKLJ', 'A44SXN3JZ', 'A2QR7FWT3',
       'AMP34PX6H', 'AMH6SP3RQ', 'AH8T42CXP', 'ASLZVL6WR', 'AYC37HW74',
       'Recover invalid deposit 2023-04-14', 'ANLNPY98H', 'ARQ638GB4',
       'AT4KG6J7C', 'AX5CJ6SCT', 'AW5C79V8V', 'AQVRF75Y4', 'AW84C39DF',
       'A548ZNRFL', 'ACYYBBD38', 'A3NW3DZ2C', 'A8RX9PB9M', 'AVY7ZNMYB',
       'AHHCQCW8D', 'AV2NVG4JR', 'AYBC77HFG', 'ALDWPHY8Z', 'AWKG9WGPR',
       'A3YSLW3H2', 'A8LXTCDNK', 'A85MP3LD5', 'AG7PS3F2K', 'A34LVWVZZ',
       'A8SMS4ZTS', 'A6NVV54T2', 'AB22DKTYR', 'AWR6RCSKR', 'AX7B6Y67F',
       'A4KH4GDHX', 'ATQ3J7VNH', 'ADLXFCYP8', 'AP6LMPRFX', 'AXFKFNLT2',
       'A2JMJ73VH', 'ATLJJTKCP', 'AFZ84RVTM', 'AWP7BHXY8', 'ARWM6JKJJ',
       'AN35TMYVJ', 'ADX48GD6R', 'AXCDQP8NR', 'AGN852TDZ', 'AXJJ5DWP7',
       'AWLGCBXV4', 'A76KRKGNR', 'AVS6QL7P5', 'A68LPL8SR'], dtype=object)

In [16]:
sorted(ap['source_type'].unique())

['DISB', 'PYMT', 'REFUNDS', 'RISK', 'SETT']

In [27]:
ap.to_excel('0. AP-REPORT_ID COPPEL SA DE CV.xlsx',index=False)

# CRUCE: IDENTIFICACION DE REPORT_ID

In [18]:
cruce_1 = sml_final.merge(ap[['mvnt_id','report_id','movement_type']],on='mvnt_id',how='left')
cruce_1.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date,report_id,movement_type
0,461f6516-0cad-510f-8647-a08cb91c03d8,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,50f5c96a-8d20-4302-b97c-96a0090a3dd5,50f5c96a-8d20-4302-b97c-96a0090a3dd5,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-14 09:55:54,2023-06-15 02:00:00,324.00,...,0.00,1,Paid,S73SYgh,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-06-14,2023-06-15,ALMPNXL6P,REGULAR_PYMT_RQ
1,82a232b4-43d8-544c-b413-d4e859a732a2,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,d5ac34d7-4f1d-47d8-a744-75331c98bb94,d5ac34d7-4f1d-47d8-a744-75331c98bb94,STL_PCS_RQ,REGULAR_PAYMENT,2023-04-19 15:13:37,2023-04-20 03:30:00,10.00,...,0.00,1,Paid,1H5v9oi,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-04-19,2023-04-20,A8LXTCDNK,REGULAR_PYMT_RQ
2,1479e1f0-f7a8-5569-a3a4-8c5ef29bf8f1,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,91071e74-d7bb-4fa4-b66b-15f5a71daf03,91071e74-d7bb-4fa4-b66b-15f5a71daf03,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-29 13:33:19,2023-05-30 03:00:00,"4,783.00",...,0.00,1,Paid,wKD2Ot9,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-05-29,2023-05-30,A8B87NFJL,REGULAR_PYMT_RQ
3,a873bf4c-c930-5e0f-bc57-b3b668b0a99b,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,7c023bf7-bc4c-4a67-a81a-74b27ac894e0,7c023bf7-bc4c-4a67-a81a-74b27ac894e0,STL_PCS_RQ,REGULAR_PAYMENT,2023-07-24 15:24:48,2023-07-25 03:30:00,500.00,...,0.00,1,Paid,9aiJtMy,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-07-24,2023-07-25,ABD3GG9MD,REGULAR_PYMT_RQ
4,18d1281b-965a-588e-830a-29641801cfa8,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,10d06f88-8700-47b5-adfb-4708f598398a,10d06f88-8700-47b5-adfb-4708f598398a,STL_PCS_RQ,REGULAR_PAYMENT,2023-03-30 16:36:05,2023-03-31 04:00:00,801.00,...,0.00,1,Paid,JqQrwmE,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-03-30,2023-03-31,ADX48GD6R,REGULAR_PYMT_RQ

In [19]:
cruce_1.shape

(93161, 26)

In [20]:
cruce_1_not_found = cruce_1[(cruce_1['movement_type'].isnull())]
cruce_1_not_found.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date,report_id,movement_type
59834,1099cc4b-0bb5-5cf4-9b33-043b4a96eb68,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,38d07159-0494-423f-b743-5f70626592cf,38d07159-0494-423f-b743-5f70626592cf,STL_PCS_RQ,REGULAR_PAYMENT,2023-07-14 15:23:31,2023-07-15 03:30:00,"1,000.00",...,0.00,1,Paid,TjG4Ttl,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-07-14,2023-07-15,NaN,NaN
61239,eadd09d6-9e70-569c-b888-f15cd56197b5,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,99c36afb-f1d5-4df6-92d5-774a82ad6b9a,99c36afb-f1d5-4df6-92d5-774a82ad6b9a,STL_PCS_RQ,REGULAR_PAYMENT,2023-07-14 15:23:19,2023-07-15 03:30:00,"19,460.00",...,0.00,1,Paid,AuYKevr,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-07-14,2023-07-15,NaN,NaN
77610,02f39e05-b2d0-5602-8c16-b3beb626b5d2,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,3bee9ccd-7fcd-49cb-8d0b-9b78a6c0b4d7,3bee9ccd-7fcd-49cb-8d0b-9b78a6c0b4d7,STL_PCS_RQ,REGULAR_PAYMENT,2023-07-29 11:24:13,2023-07-30 02:30:00,"1,176.00",...,0.00,1,Paid,G6KELTG,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-07-29,2023-07-30,NaN,NaN

In [21]:
cruce_1_not_found.shape

(3, 26)

In [33]:
cruce_1_final = cruce_1[['merchant_id','merchant_name','transaction_id','report_id','receipt_no','gross_amount','fees','taxes',
                        'net_amount','eff_dt_date','created_at','created_at_date','status_code','status_msg','pymt_prg',
                        'movement_type']]
cruce_1_final.head()

,merchant_id,merchant_name,transaction_id,report_id,receipt_no,gross_amount,fees,taxes,net_amount,eff_dt_date,created_at,created_at_date,status_code,status_msg,pymt_prg,movement_type
0,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,50f5c96a-8d20-4302-b97c-96a0090a3dd5,ALMPNXL6P,S73SYgh,324.00,7.45,1.19,315.36,2023-06-15,2023-06-14 09:55:54,2023-06-14,1,Paid,REGULAR_PAYMENT,REGULAR_PYMT_RQ
1,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,d5ac34d7-4f1d-47d8-a744-75331c98bb94,A8LXTCDNK,1H5v9oi,10.00,0.23,0.04,9.73,2023-04-20,2023-04-19 15:13:37,2023-04-19,1,Paid,REGULAR_PAYMENT,REGULAR_PYMT_RQ
2,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,91071e74-d7bb-4fa4-b66b-15f5a71daf03,A8B87NFJL,wKD2Ot9,"4,783.00",110.01,17.60,"4,655.39",2023-05-30,2023-05-29 13:33:19,2023-05-29,1,Paid,REGULAR_PAYMENT,REGULAR_PYMT_RQ
3,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,7c023bf7-bc4c-4a67-a81a-74b27ac894e0,ABD3GG9MD,9aiJtMy,500.00,11.50,1.84,486.66,2023-07-25,2023-07-24 15:24:48,2023-07-24,1,Paid,REGULAR_PAYMENT,REGULAR_PYMT_RQ
4,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,10d06f88-8700-47b5-adfb-4708f598398a,ADX48GD6R,JqQrwmE,801.00,18.42,2.95,779.63,2023-03-31,2023-03-30 16:36:05,2023-03-30,1,Paid,REGULAR_PAYMENT,REGULAR_PYMT_RQ

In [34]:
cruce_1_final.shape

(93161, 16)

In [35]:
cruce_1_dup = cruce_1[cruce_1.duplicated(['mvnt_id'] , keep=False)]
cruce_1_dup.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date,report_id,movement_type
440,ce357a0f-a38d-5829-8f8f-ad47ecebfc7d,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,637c5ee6-9260-4edb-83e1-9ca5b1b7e822,637c5ee6-9260-4edb-83e1-9ca5b1b7e822,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-08 14:41:12,2023-05-09 03:30:00,145.00,...,0.00,3,Cancelled. Cardholder initiated.,Gq1sfrl,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-05-08,2023-05-09,AYC37HW74,REGULAR_PYMT_RQ
441,ce357a0f-a38d-5829-8f8f-ad47ecebfc7d,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,637c5ee6-9260-4edb-83e1-9ca5b1b7e822,637c5ee6-9260-4edb-83e1-9ca5b1b7e822,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-08 14:41:12,2023-05-09 03:30:00,145.00,...,0.00,3,Cancelled. Cardholder initiated.,Gq1sfrl,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-05-08,2023-05-09,AYC37HW74,CANCEL_RQ
838,5cb058d9-2756-5fcc-8dc4-8cf4785895f6,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,f62e8aca-9d0d-43ed-99c8-f97091f0b078,f62e8aca-9d0d-43ed-99c8-f97091f0b078,STL_PCS_RQ,REGULAR_PAYMENT,2023-03-23 11:24:14,2023-03-24 02:30:00,450.00,...,0.00,3,Cancelled. Merchant initiated.,thR62oN,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-03-23,2023-03-24,A68LPL8SR,REGULAR_PYMT_RQ
839,5cb058d9-2756-5fcc-8dc4-8cf4785895f6,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,f62e8aca-9d0d-43ed-99c8-f97091f0b078,f62e8aca-9d0d-43ed-99c8-f97091f0b078,STL_PCS_RQ,REGULAR_PAYMENT,2023-03-23 11:24:14,2023-03-24 02:30:00,450.00,...,0.00,3,Cancelled. Merchant initiated.,thR62oN,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-03-23,2023-03-24,A68LPL8SR,CANCEL_RQ
966,573d99f6-46ba-5535-9936-53800183243a,c291aa30-f5ae-4b6c-86d4-45c5bef308a3,COPPEL S.A DE C.V,c37661f6-e4d1-4283-b42c-e49d2cd4ef17,c37661f6-e4d1-4283-b42c-e49d2cd4ef17,STL_PCS_RQ,REGULAR_PAYMENT,2023-03-29 11:57:34,2023-03-30 02:30:00,500.00,...,0.00,3,Cancelled. Merchant initiated.,OBHkcS8,PAYMENT,SETTLEMENT_MASTER_LOG_MSI_MERCHAT_ID COPPEL S....,2023-03-29,2023-03-30,AXCDQP8NR,REGULAR_PYMT_RQ

In [36]:
cruce_1_dup.shape

(378, 26)

In [37]:
cruce_1_final.to_excel('0. DATA COPPEL SA DE CV.xlsx',index=False)