In [1]:
import pandas as pd
import numpy as np
import glob
import os
from openpyxl import load_workbook
pd.options.display.float_format = '{:,.2f}'.format

# RUTAS

### SETTLEMENT MASTER LOG

In [2]:
sml_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\COMISIONISTAS\2023\05. MAYO\LEDGER - DB\MISSINGS\SML*.csv', recursive=False)
sml_files

['C:\\Users\\Cristian.Aparicio\\Documents\\COMISIONISTAS\\2023\\05. MAYO\\LEDGER - DB\\MISSINGS\\SML_COMISIONISTAS - MISSINGS MAYO 2023.csv']

### AP JOURNAL

In [3]:
ap_files = glob.glob(r'C:\Users\Cristian.Aparicio\Documents\COMISIONISTAS\2023\05. MAYO\LEDGER - DB\MISSINGS\AP*.csv', recursive=False)
ap_files

['C:\\Users\\Cristian.Aparicio\\Documents\\COMISIONISTAS\\2023\\05. MAYO\\LEDGER - DB\\MISSINGS\\AP_JOURNAL_COMISIONISTAS - MISSINGS MAYO 2023.csv']

# DATA SETTLEMENT MASTER LOG

In [4]:
sml = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in sml_files])
sml.columns = sml.columns.str.strip().str.lower()
sml.replace('""','', regex=True, inplace=True)
sml['created_at'] = pd.to_datetime(sml['created_at']).dt.tz_localize(None)
sml['created_at_date'] =  pd.to_datetime(sml['created_at']).dt.date
sml['created_at_date'] =  pd.to_datetime(sml['created_at_date'])
sml['eff_dt'] = pd.to_datetime(sml['eff_dt']).dt.tz_localize(None)
sml['eff_dt_date'] =  pd.to_datetime(sml['eff_dt']).dt.date
sml['eff_dt_date'] =  pd.to_datetime(sml['eff_dt_date'])
sml.rename(columns={'ref_id':'transaction_id'},inplace=True)
#sml['PK'] = sml['PK'].replace('M#','',inplace=True)
sml.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,0b0f51c4-c7b6-5212-a733-92936fcbdddc,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,80125c7d-9900-492a-8e60-39220244304e,80125c7d-9900-492a-8e60-39220244304e,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-09 10:29:46,2023-06-10 02:30:00,"1,490.00",...,0.00,0.04,3.00,1,Paid,ZMwoj9f,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-09,2023-06-10
1,cc2adc7c-1bda-5879-983d-187a1d409055,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,e1b20367-135d-4473-8b78-b33687a77ad9,e1b20367-135d-4473-8b78-b33687a77ad9,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-31 11:57:32,2023-06-01 02:30:00,"1,049.00",...,0.00,0.00,0.00,1,Paid,X2qTjaX,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-31,2023-06-01
2,57abeb9a-e99a-5f45-8c7e-0f29d4e47aad,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,85abf7cb-42d9-4539-aa13-45e1427e22d3,85abf7cb-42d9-4539-aa13-45e1427e22d3,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-28 15:44:23,2023-05-29 03:30:00,"1,049.00",...,0.00,0.00,0.00,1,Paid,ziW6mcR,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-28,2023-05-29
3,fcff7359-19ce-58d6-b49c-1c30d5628957,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,71e757e9-e54a-46ac-b917-b2b8a2a43a8f,71e757e9-e54a-46ac-b917-b2b8a2a43a8f,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-27 15:10:47,2023-05-28 03:30:00,"1,200.00",...,0.00,0.00,0.00,1,Paid,d3fcS18,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-27,2023-05-28
4,167c24cd-6fbd-5376-b3b0-866bbd97efff,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,2554f200-9b58-4241-83df-3f5a8af02432,2554f200-9b58-4241-83df-3f5a8af02432,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-02 11:08:59,2023-05-03 02:30:00,"7,390.00",...,0.00,0.00,0.00,1,Paid,YRYzjqx,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-02,2023-05-03

In [5]:
sml.shape

(294, 24)

In [6]:
sml.dtypes

record_uuid                object
merchant_id                object
merchant_name              object
transaction_id             object
mvnt_id                    object
mvnt_type                  object
pymt_prg                   object
created_at         datetime64[ns]
eff_dt             datetime64[ns]
psp_amount                float64
gross_amount              float64
fees                      float64
taxes                     float64
net_amount                float64
mdr                       float64
msi                       float64
number_msi                float64
status_code                 int64
status_msg                 object
receipt_no                 object
type                       object
file_name                  object
created_at_date    datetime64[ns]
eff_dt_date        datetime64[ns]
dtype: object

In [7]:
sml_final = sml[(sml['mvnt_type'] == 'STL_PCS_RQ')]
sml_final.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,mdr,msi,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date
0,0b0f51c4-c7b6-5212-a733-92936fcbdddc,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,80125c7d-9900-492a-8e60-39220244304e,80125c7d-9900-492a-8e60-39220244304e,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-09 10:29:46,2023-06-10 02:30:00,"1,490.00",...,0.00,0.04,3.00,1,Paid,ZMwoj9f,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-09,2023-06-10
1,cc2adc7c-1bda-5879-983d-187a1d409055,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,e1b20367-135d-4473-8b78-b33687a77ad9,e1b20367-135d-4473-8b78-b33687a77ad9,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-31 11:57:32,2023-06-01 02:30:00,"1,049.00",...,0.00,0.00,0.00,1,Paid,X2qTjaX,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-31,2023-06-01
2,57abeb9a-e99a-5f45-8c7e-0f29d4e47aad,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,85abf7cb-42d9-4539-aa13-45e1427e22d3,85abf7cb-42d9-4539-aa13-45e1427e22d3,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-28 15:44:23,2023-05-29 03:30:00,"1,049.00",...,0.00,0.00,0.00,1,Paid,ziW6mcR,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-28,2023-05-29
3,fcff7359-19ce-58d6-b49c-1c30d5628957,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,71e757e9-e54a-46ac-b917-b2b8a2a43a8f,71e757e9-e54a-46ac-b917-b2b8a2a43a8f,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-27 15:10:47,2023-05-28 03:30:00,"1,200.00",...,0.00,0.00,0.00,1,Paid,d3fcS18,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-27,2023-05-28
4,167c24cd-6fbd-5376-b3b0-866bbd97efff,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,2554f200-9b58-4241-83df-3f5a8af02432,2554f200-9b58-4241-83df-3f5a8af02432,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-02 11:08:59,2023-05-03 02:30:00,"7,390.00",...,0.00,0.00,0.00,1,Paid,YRYzjqx,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-02,2023-05-03

In [8]:
sml_final.shape

(294, 24)

# DATA AP JOURNAL

In [9]:
ap = pd.concat([pd.read_csv(f).assign(file_name=os.path.basename(f)) for f in ap_files])
ap.columns = ap.columns.str.strip().str.lower()
ap.replace('""','', regex=True, inplace=True)
ap['eff_dt'] =  pd.to_datetime(ap['eff_dt']).dt.tz_localize(None)
ap['eff_dt_date'] =  pd.to_datetime(ap['eff_dt']).dt.date
ap['eff_dt_date'] =  pd.to_datetime(ap['eff_dt_date'])
ap['eff_dt_time'] =  pd.to_datetime(ap['eff_dt']).dt.time
ap['movement_day'] = pd.to_datetime(ap['movement_day']).dt.tz_localize(None)
ap['created_at'] = pd.to_datetime(ap['created_at']).dt.tz_localize(None)
ap['created_at_date'] =  pd.to_datetime(ap['created_at']).dt.date
ap['created_at_date'] =  pd.to_datetime(ap['created_at_date'])
ap['request_effective_date'] = pd.to_datetime(ap['request_effective_date']).dt.tz_localize(None)
ap['slot_date'] = pd.to_datetime(ap['slot_date']).dt.tz_localize(None)
ap['identifier'] = ap['source_type'].str[:1].astype(str)
ap['INDEX'] = (ap['eff_dt_date'].astype(str).replace(' ', '',regex=True)+'-'+
               ap['identifier'].astype(str).replace(' ', '',regex=True)+'-'+
               ap['eff_dt_time'].astype(str).replace(' ', '',regex=True))
ap.sort_values(by=(['merchant_id','eff_dt']), ascending=[True,False], inplace=True)

In [10]:
ap.loc[ap['source_type'] == 'DISB', 'report_id'] = ap['type_request']
ap['report_id'] = ap['report_id'].groupby(ap['merchant_id']).fillna(method='ffill')
ap.head()

,merchant_id,merchant_name,amount,currency,type_request,mvnt_id,movement_type,source_type,created_at,eff_dt,movement_day,request_effective_date,slot_date,file_name,eff_dt_date,eff_dt_time,created_at_date,identifier,INDEX,report_id
324,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,"1,490.00",MXN,settlement processor regular payment request,4343752b-d0a9-4fe9-9bf4-d30e193247cf,REGULAR_PYMT_RQ,SETT,2023-06-12 12:06:20,2023-06-13 03:30:00,2023-06-12 12:06:20,2023-06-13 03:00:00,2023-06-13 03:30:00,AP_JOURNAL_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-13,03:30:00,2023-06-12,S,2023-06-13-S-03:30:00,NaN
325,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,"29,800.00",MXN,settlement processor regular payment request,d5e5cbf0-157c-45b8-bfa8-04513dcab92c,REGULAR_PYMT_RQ,SETT,2023-06-12 12:11:09,2023-06-13 03:30:00,2023-06-12 12:11:09,2023-06-13 03:00:00,2023-06-13 03:30:00,AP_JOURNAL_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-13,03:30:00,2023-06-12,S,2023-06-13-S-03:30:00,NaN
326,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,"4,470.00",MXN,settlement processor regular payment request,746bb8b0-3c12-4aa9-9dcb-3474221cf7a3,REGULAR_PYMT_RQ,SETT,2023-06-12 12:12:57,2023-06-13 03:30:00,2023-06-12 12:12:57,2023-06-13 03:00:00,2023-06-13 03:30:00,AP_JOURNAL_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-13,03:30:00,2023-06-12,S,2023-06-13-S-03:30:00,NaN
327,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,"5,153.18",MXN,settlement processor regular payment request,c5fd934f-5c89-4d30-8ddc-1d1788369c03,REGULAR_PYMT_RQ,SETT,2023-06-12 12:16:59,2023-06-13 03:30:00,2023-06-12 12:16:59,2023-06-13 03:00:00,2023-06-13 03:30:00,AP_JOURNAL_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-13,03:30:00,2023-06-12,S,2023-06-13-S-03:30:00,NaN
319,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,"1,490.00",MXN,settlement processor regular payment request,75c1ad5e-10e3-42c1-8f4a-555af95c615b,REGULAR_PYMT_RQ,SETT,2023-06-12 10:16:47,2023-06-13 03:00:00,2023-06-12 10:16:47,2023-06-13 02:30:00,2023-06-13 03:00:00,AP_JOURNAL_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-13,03:00:00,2023-06-12,S,2023-06-13-S-03:00:00,NaN

In [11]:
ap.shape

(364, 20)

In [12]:
ap.dtypes

merchant_id                       object
merchant_name                     object
amount                           float64
currency                          object
type_request                      object
mvnt_id                           object
movement_type                     object
source_type                       object
created_at                datetime64[ns]
eff_dt                    datetime64[ns]
movement_day              datetime64[ns]
request_effective_date    datetime64[ns]
slot_date                 datetime64[ns]
file_name                         object
eff_dt_date               datetime64[ns]
eff_dt_time                       object
created_at_date           datetime64[ns]
identifier                        object
INDEX                             object
report_id                         object
dtype: object

In [13]:
ap['source_type'].unique()

array(['SETT', 'DISB', 'TOPUPS', 'PYMT'], dtype=object)

In [14]:
ap['report_id'].unique()

array([nan, 'AH32PJFD3', 'A2VJGTZHC', 'A3SXVXP25', 'A7SXX3SGT',
       'A6WZ9NQCM', 'A7T58LJ3P', 'AJWHJR6N6', 'A6JQKGTWD', 'A4PC45HGR',
       'AL4YY7FVQ', 'AKXVFFSSQ', 'AV7MHYFBV', 'ACSNGTGRV', 'ASNV5D584',
       'ABDQNQSN6', 'AJD2XCYV8', 'A9VHDD2PC', 'A3YT3WRZL', 'AMWW95HTY',
       'A2SGF8NMF', 'ANJJCM7YQ', 'AY3HSM5W3', 'A7C9H4YW7', 'AXPZ5R9SZ',
       'AMBN2W6PS', 'AST5R9FK6', 'AQW2CPZTB', 'ABSH9FJDH', 'A9ZQ3QV7M',
       'AQQZV8M9Q', 'AKHRWDLCM', 'A5GT5C3CF', 'A6BK77BM9', 'AQT7TMGGM',
       'ALPVGJ3WL', 'A7VF8P88T', 'ADRZ7L5GY', 'ABY7RMYMM', 'ANN9QJSKH',
       'AWQDMM27T', 'AZNL5BQ2M', 'AWLNML65Z', 'A98XMNGX6', 'ATK75NB33',
       'AQRNR9NQC', 'AF6DRNQ4Q', 'AGJ8WYSQ5', 'A7LRV2TT4', 'A35VMSN2S',
       'ABJKPWG89', 'AFLDNMR5D', 'AGQBWT7SR', 'A4WKLNGB8', 'A245D7DXJ',
       'ABKWK9TDT'], dtype=object)

In [15]:
ap_sett = ap[(ap['source_type'] == 'SETT')]
ap_topups = ap[(ap['source_type'] == 'TOPUPS')]
ap_disb = ap[(ap['source_type'] == 'DISB')]
ap_loan = ap[(ap['source_type'] == 'LOAN')]
ap_pymt = ap[(ap['source_type'] == 'PYMT')]
ap_risk = ap[(ap['source_type'] == 'RISK')]

# CRUCE: IDENTIFICACION DE REPORT_ID

In [16]:
cruce_1 = sml_final.merge(ap[['mvnt_id','report_id','movement_type']],on='mvnt_id',how='left')
cruce_1.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date,report_id,movement_type
0,0b0f51c4-c7b6-5212-a733-92936fcbdddc,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,80125c7d-9900-492a-8e60-39220244304e,80125c7d-9900-492a-8e60-39220244304e,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-09 10:29:46,2023-06-10 02:30:00,"1,490.00",...,3.00,1,Paid,ZMwoj9f,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-09,2023-06-10,A3SXVXP25,REGULAR_PYMT_RQ
1,cc2adc7c-1bda-5879-983d-187a1d409055,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,e1b20367-135d-4473-8b78-b33687a77ad9,e1b20367-135d-4473-8b78-b33687a77ad9,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-31 11:57:32,2023-06-01 02:30:00,"1,049.00",...,0.00,1,Paid,X2qTjaX,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-31,2023-06-01,AV7MHYFBV,REGULAR_PYMT_RQ
2,57abeb9a-e99a-5f45-8c7e-0f29d4e47aad,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,85abf7cb-42d9-4539-aa13-45e1427e22d3,85abf7cb-42d9-4539-aa13-45e1427e22d3,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-28 15:44:23,2023-05-29 03:30:00,"1,049.00",...,0.00,1,Paid,ziW6mcR,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-28,2023-05-29,ABDQNQSN6,REGULAR_PYMT_RQ
3,fcff7359-19ce-58d6-b49c-1c30d5628957,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,71e757e9-e54a-46ac-b917-b2b8a2a43a8f,71e757e9-e54a-46ac-b917-b2b8a2a43a8f,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-27 15:10:47,2023-05-28 03:30:00,"1,200.00",...,0.00,1,Paid,d3fcS18,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-27,2023-05-28,AJD2XCYV8,REGULAR_PYMT_RQ
4,167c24cd-6fbd-5376-b3b0-866bbd97efff,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,2554f200-9b58-4241-83df-3f5a8af02432,2554f200-9b58-4241-83df-3f5a8af02432,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-02 11:08:59,2023-05-03 02:30:00,"7,390.00",...,0.00,1,Paid,YRYzjqx,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-02,2023-05-03,ANN9QJSKH,REGULAR_PYMT_RQ

In [17]:
cruce_1.shape

(296, 26)

In [18]:
cruce_1_not_found = cruce_1[(cruce_1['movement_type'].isnull())]
cruce_1_not_found.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date,report_id,movement_type
20,9741fd0c-4a81-53c3-96b9-4fc1f36794ce,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,a333c4e2-b6c9-4d32-8ade-640bdae94069,a333c4e2-b6c9-4d32-8ade-640bdae94069,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-12 12:32:15,2023-06-13 03:00:00,"2,235.00",...,0.00,1,Paid,mmsUETU,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-12,2023-06-13,NaN,NaN
21,5eecbca0-3a2b-57dc-9481-59799f6f64fe,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,ed5839b3-239b-4a2f-af33-a6df667cbfda,ed5839b3-239b-4a2f-af33-a6df667cbfda,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-12 12:25:47,2023-06-13 03:00:00,"5,885.00",...,3.00,1,Paid,WG4EaUa,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-12,2023-06-13,NaN,NaN
102,2aca743f-88c0-5a05-b82f-8d72632ce34d,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,6c648876-3027-4df6-8d28-208fd67acdeb,6c648876-3027-4df6-8d28-208fd67acdeb,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-12 12:59:10,2023-06-13 03:00:00,"25,390.00",...,0.00,1,Paid,Xq1Dzk3,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-12,2023-06-13,NaN,NaN
117,9d4ecdaf-3331-52ed-9aa2-5daab2df9df1,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,12636aec-13e1-4e24-adb8-42875e2eb341,12636aec-13e1-4e24-adb8-42875e2eb341,STL_PCS_RQ,REGULAR_PAYMENT,2023-06-12 12:35:28,2023-06-13 03:00:00,745.00,...,0.00,1,Paid,uMbq9GD,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-06-12,2023-06-13,NaN,NaN

In [19]:
cruce_1_not_found.shape

(4, 26)

In [20]:
cruce_1_final = cruce_1[['merchant_id','merchant_name','transaction_id','report_id','receipt_no','gross_amount','fees','taxes',
                        'net_amount','eff_dt_date','created_at','created_at_date','status_code','status_msg']]
cruce_1_final.head()

,merchant_id,merchant_name,transaction_id,report_id,receipt_no,gross_amount,fees,taxes,net_amount,eff_dt_date,created_at,created_at_date,status_code,status_msg
0,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,80125c7d-9900-492a-8e60-39220244304e,A3SXVXP25,ZMwoj9f,"1,490.00",67.05,10.73,"1,412.22",2023-06-10,2023-06-09 10:29:46,2023-06-09,1,Paid
1,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,e1b20367-135d-4473-8b78-b33687a77ad9,AV7MHYFBV,X2qTjaX,"1,049.00",0.00,0.00,"1,049.00",2023-06-01,2023-05-31 11:57:32,2023-05-31,1,Paid
2,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,85abf7cb-42d9-4539-aa13-45e1427e22d3,ABDQNQSN6,ziW6mcR,"1,049.00",0.00,0.00,"1,049.00",2023-05-29,2023-05-28 15:44:23,2023-05-28,1,Paid
3,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,71e757e9-e54a-46ac-b917-b2b8a2a43a8f,AJD2XCYV8,d3fcS18,"1,200.00",0.00,0.00,"1,200.00",2023-05-28,2023-05-27 15:10:47,2023-05-27,1,Paid
4,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,2554f200-9b58-4241-83df-3f5a8af02432,ANN9QJSKH,YRYzjqx,"7,390.00",0.00,0.00,"7,390.00",2023-05-03,2023-05-02 11:08:59,2023-05-02,1,Paid

In [21]:
cruce_1_final.shape

(296, 14)

In [22]:
cruce_1_dup = cruce_1[cruce_1.duplicated(['mvnt_id'] , keep=False)]
cruce_1_dup.head()

,record_uuid,merchant_id,merchant_name,transaction_id,mvnt_id,mvnt_type,pymt_prg,created_at,eff_dt,psp_amount,...,number_msi,status_code,status_msg,receipt_no,type,file_name,created_at_date,eff_dt_date,report_id,movement_type
70,5a3dd132-a349-5ef2-bcc8-9e6b681b34ab,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,be6b2ed9-224b-4ded-995d-4e6e714136cc,be6b2ed9-224b-4ded-995d-4e6e714136cc,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-27 12:26:32,2023-05-28 03:00:00,"5,960.00",...,0.00,3,Cancelled. Merchant initiated.,lQ7DUoZ,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-27,2023-05-28,AJD2XCYV8,REGULAR_PYMT_RQ
71,5a3dd132-a349-5ef2-bcc8-9e6b681b34ab,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,be6b2ed9-224b-4ded-995d-4e6e714136cc,be6b2ed9-224b-4ded-995d-4e6e714136cc,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-27 12:26:32,2023-05-28 03:00:00,"5,960.00",...,0.00,3,Cancelled. Merchant initiated.,lQ7DUoZ,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-27,2023-05-28,AJD2XCYV8,CANCEL_RQ
149,6f493d38-9690-5429-9208-a0c743e89c97,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,882cac6f-931d-42ab-9f93-642559741c39,882cac6f-931d-42ab-9f93-642559741c39,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-29 13:46:04,2023-05-30 03:00:00,"1,990.00",...,0.00,3,Cancelled. Merchant initiated.,4HDEAUM,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-29,2023-05-30,ASNV5D584,REGULAR_PYMT_RQ
150,6f493d38-9690-5429-9208-a0c743e89c97,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,882cac6f-931d-42ab-9f93-642559741c39,882cac6f-931d-42ab-9f93-642559741c39,STL_PCS_RQ,REGULAR_PAYMENT,2023-05-29 13:46:04,2023-05-30 03:00:00,"1,990.00",...,0.00,3,Cancelled. Merchant initiated.,4HDEAUM,PAYMENT,SML_COMISIONISTAS - MISSINGS MAYO 2023.csv,2023-05-29,2023-05-30,ASNV5D584,CANCEL_RQ

In [23]:
cruce_1_dup.shape

(4, 26)

In [25]:
check_data_puntual = cruce_1_final[(cruce_1_final['receipt_no'].isin([
'7ZBMiGL',
'VhmHhhm',
'4HDEAUM',
'cL1hVyp',
'WXYkjSf',
'X2qTjaX',
]))]
check_data_puntual.head()

,merchant_id,merchant_name,transaction_id,report_id,receipt_no,gross_amount,fees,taxes,net_amount,eff_dt_date,created_at,created_at_date,status_code,status_msg
1,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,e1b20367-135d-4473-8b78-b33687a77ad9,AV7MHYFBV,X2qTjaX,"1,049.00",0.00,0.00,"1,049.00",2023-06-01,2023-05-31 11:57:32,2023-05-31,1,Paid
127,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,a0fb7a18-eb97-437f-be76-1a05cbf7205e,AV7MHYFBV,cL1hVyp,"4,470.00",201.15,32.18,"4,236.67",2023-06-01,2023-05-31 11:17:24,2023-05-31,1,Paid
130,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,368db60b-c562-4ce3-b145-6907d8078e7f,AV7MHYFBV,VhmHhhm,"1,849.00",0.00,0.00,"1,849.00",2023-06-01,2023-05-31 12:32:17,2023-05-31,1,Paid
132,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,cc037cdd-7d96-4e59-abde-2b9301bfdbb4,AV7MHYFBV,WXYkjSf,"1,849.00",83.21,13.31,"1,752.48",2023-06-01,2023-05-31 11:20:32,2023-05-31,1,Paid
140,3ee0c85f-4617-4736-90a1-927a41e0deec,PAY CLIP S DE RL DE CV,27e6609c-1c43-48c8-9dff-b4dc8c01dc58,AV7MHYFBV,7ZBMiGL,"2,898.00",0.00,0.00,"2,898.00",2023-06-01,2023-05-31 12:04:26,2023-05-31,1,Paid

In [26]:
check_data_puntual.shape

(7, 14)

In [28]:
check_data_puntual.to_excel('0. DATA COMISIONISTAS MAYO - MISSINGS 2023.xlsx',index=False)